import test from 'node:test';import assert from 'node:assert/strict';
import {parseAdaptiveManifest,parseHlsManifest,parseDashManifest,parseAttributeList} from '../src/adaptive-manifest.js';

test('HLS master parses variants and renditions',()=>{const text=`#EXTM3U\n#EXT-X-VERSION:7\n#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aud",NAME="Stereo",DEFAULT=YES,URI="audio.m3u8"\n#EXT-X-STREAM-INF:BANDWIDTH=2400000,AVERAGE-BANDWIDTH=2000000,RESOLUTION=1920x1080,FRAME-RATE=29.97,CODECS="avc1.640028,mp4a.40.2",AUDIO="aud"\nvideo.m3u8`;const manifest=parseHlsManifest(text,{baseUrl:'https://example.test/master.m3u8'});assert.equal(manifest.kind,'master');assert.equal(manifest.variants[0].width,1920);assert.equal(manifest.variants[0].url,'https://example.test/video.m3u8');assert.equal(manifest.renditions[0].default,true);});

test('HLS media parses LL-HLS, ranges, maps, keys and discontinuities',()=>{const text=`#EXTM3U\n#EXT-X-TARGETDURATION:4\n#EXT-X-MEDIA-SEQUENCE:42\n#EXT-X-PART-INF:PART-TARGET=0.5\n#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES,PART-HOLD-BACK=1.5\n#EXT-X-MAP:URI="init.mp4"\n#EXT-X-KEY:METHOD=SAMPLE-AES,URI="key.bin",KEYFORMAT="com.example"\n#EXT-X-PART:DURATION=0.5,URI="p42.0.m4s",INDEPENDENT=YES\n#EXTINF:4.0,one\n#EXT-X-BYTERANGE:100@20\nseg42.m4s\n#EXT-X-DISCONTINUITY\n#EXTINF:4.0,two\nseg43.m4s`;const manifest=parseAdaptiveManifest(text,{baseUrl:'https://cdn.test/live/index.m3u8'});assert.equal(manifest.isLive,true);assert.equal(manifest.mediaSequence,42);assert.equal(manifest.parts[0].independent,true);assert.equal(manifest.segments[0].byteRange.offset,20);assert.equal(manifest.segments[0].key.method,'SAMPLE-AES');assert.equal(manifest.segments[1].discontinuity,true);assert.equal(manifest.serverControl.canBlockReload,true);});

test('attribute list preserves quoted commas',()=>{assert.deepEqual(parseAttributeList('A="x,y",B=2'),{A:'x,y',B:'2'});});

test('DASH SegmentTimeline expands representation templates and protection',()=>{const xml=`<MPD type="static" mediaPresentationDuration="PT6S"><BaseURL>https://cdn.test/</BaseURL><Period duration="PT6S"><AdaptationSet contentType="video" mimeType="video/mp4" codecs="avc1.640028"><ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="kid-1"><cenc:pssh>AAAA</cenc:pssh></ContentProtection><SegmentTemplate timescale="1000" initialization="init-$RepresentationID$.mp4" media="seg-$Number%03d$-$Time$.m4s" startNumber="5"><SegmentTimeline><S t="0" d="2000" r="2"/></SegmentTimeline></SegmentTemplate><Representation id="v1" bandwidth="2000000" width="1280" height="720"/></AdaptationSet></Period></MPD>`;const manifest=parseDashManifest(xml,{baseUrl:'https://origin.test/manifest.mpd'});assert.equal(manifest.variants.length,1);const variant=manifest.variants[0];assert.equal(variant.initialization,'https://cdn.test/init-v1.mp4');assert.equal(variant.segments.length,3);assert.equal(variant.segments[2].url,'https://cdn.test/seg-007-4000.m4s');assert.equal(variant.protection[0].defaultKID,'kid-1');assert.equal(variant.protection[0].pssh,'AAAA');});
test('dynamic DASH duration template projects rolling availability window',()=>{const xml=`<MPD type="dynamic" availabilityStartTime="2026-01-01T00:00:00Z" timeShiftBufferDepth="PT12S" minimumUpdatePeriod="PT2S"><Period><AdaptationSet contentType="video"><SegmentTemplate timescale="1" duration="4" media="s-$Number$.m4s" startNumber="1"/><Representation id="v" bandwidth="1000000"/></AdaptationSet></Period></MPD>`;const manifest=parseDashManifest(xml,{baseUrl:'https://cdn.test/live.mpd',now:Date.parse('2026-01-01T00:00:40Z')});const segments=manifest.variants[0].segments;assert.deepEqual(segments.map(s=>s.sequence),[8,9,10,11]);assert.deepEqual(segments.map(s=>s.start),[28,32,36,40]);});
test('LL-HLS delta update advances listed segment sequence after skipped segments',()=>{const manifest=parseHlsManifest(`#EXTM3U\n#EXT-X-MEDIA-SEQUENCE:100\n#EXT-X-SKIP:SKIPPED-SEGMENTS=3\n#EXTINF:4,\ns103.m4s\n#EXT-X-RENDITION-REPORT:URI="other.m3u8",LAST-MSN=104,LAST-PART=2` ,{baseUrl:'https://cdn.test/live.m3u8'});assert.equal(manifest.skippedSegments,3);assert.equal(manifest.segments[0].sequence,103);assert.equal(manifest.renditionReports[0].lastPart,2);});
test('DASH SegmentList normalizes init/media byte ranges',()=>{const xml=`<MPD type="static" mediaPresentationDuration="PT8S"><Period><AdaptationSet contentType="video"><SegmentList timescale="1" duration="4" startNumber="7"><Initialization sourceURL="all.mp4" range="0-99"/><SegmentURL media="all.mp4" mediaRange="100-199"/><SegmentURL media="all.mp4" mediaRange="200-349"/></SegmentList><Representation id="v" bandwidth="1"/></AdaptationSet></Period></MPD>`;const manifest=parseDashManifest(xml,{baseUrl:'https://cdn.test/x.mpd'}),variant=manifest.variants[0];assert.equal(variant.initialization,'https://cdn.test/all.mp4');assert.deepEqual(variant.initializationRange,{offset:0,length:100,end:100});assert.equal(variant.segments[1].sequence,8);assert.deepEqual(variant.segments[1].byteRange,{offset:200,length:150,end:350});assert.equal(variant.segments[1].start,4);});
test('DASH SegmentBase retains init and sidx index ranges',()=>{const xml=`<MPD type="static"><Period><AdaptationSet contentType="video"><Representation id="v" bandwidth="1"><BaseURL>all.mp4</BaseURL><SegmentBase indexRange="100-199"><Initialization range="0-99"/></SegmentBase></Representation></AdaptationSet></Period></MPD>`;const variant=parseDashManifest(xml,{baseUrl:'https://cdn.test/a.mpd'}).variants[0];assert.equal(variant.segmentBase.url,'https://cdn.test/all.mp4');assert.deepEqual(variant.segmentBase.indexRange,{offset:100,length:100,end:200});assert.deepEqual(variant.initializationRange,{offset:0,length:100,end:100});});
