import test from 'node:test';
import assert from 'node:assert/strict';
import {createCollaborationResolutionDraft,setCollaborationResolutionDecision,collaborationResolutionDraftProgress,finalizeCollaborationResolutionIntent,COLLABORATION_RESOLUTION_INTENT_SCHEMA} from '../src/collaboration-resolution-decisions.js';
const remote={sequence:3,transactionId:'remote-tx',label:'Remote',operationIndex:0,operation:{type:'node.update',scope:'node',id:'n',name:'N',fields:['props:x'],summary:'Update N · props:x'}};
function model({complete=true}={}){return{schema:'media.collaboration-resolution.v1',requestId:'req',status:'conflict',head:{sequence:4,checksum:'head',transactionId:'local-2'},actor:{id:'alice',keyId:'k1'},rows:[{id:'1:0|3:0',local:{sequence:1,transactionId:'local-1',label:'L1',operationIndex:0,operation:{type:'node.update'}},remote,resources:[{local:{scope:'node',id:'n',path:'props:x'},remote:{scope:'node',id:'n',path:'props:x'}}]},{id:'4:0|3:0',local:{sequence:4,transactionId:'local-2',label:'L2',operationIndex:0,operation:{type:'node.update'}},remote,resources:[{local:{scope:'node',id:'n',path:'props:x'},remote:{scope:'node',id:'n',path:'props:x'}}]}],conflictsTruncated:complete?0:2,complete,requiresRefresh:true,requiresResign:true,allowsAutomaticMerge:false};}
test('decision draft groups one remote operation across multiple local conflicts',()=>{const draft=createCollaborationResolutionDraft(model());assert.equal(draft.schema,COLLABORATION_RESOLUTION_INTENT_SCHEMA);assert.equal(draft.groups.length,1);assert.deepEqual(draft.groups[0].rowIds,['1:0|3:0','4:0|3:0']);assert.equal(draft.groups[0].decision,null);assert.deepEqual(collaborationResolutionDraftProgress(draft),{decided:0,total:1,remaining:1,ratio:0,ready:false});});
test('decision updates are immutable and require an allowed explicit choice',()=>{const draft=createCollaborationResolutionDraft(model()),next=setCollaborationResolutionDecision(draft,draft.groups[0].id,'reapply-remote');assert.equal(draft.groups[0].decision,null);assert.equal(next.groups[0].decision,'reapply-remote');assert.equal(collaborationResolutionDraftProgress(next).ready,true);assert.throws(()=>setCollaborationResolutionDecision(draft,draft.groups[0].id,'auto-merge'),/Unsupported resolution choice/);assert.throws(()=>setCollaborationResolutionDecision(draft,'missing','keep-local'),/Unknown resolution group/);});
test('final intent contains only coordinates and choices, not operation payloads',()=>{let draft=createCollaborationResolutionDraft(model());draft=setCollaborationResolutionDecision(draft,draft.groups[0].id,'keep-local');const intent=finalizeCollaborationResolutionIntent(draft),text=JSON.stringify(intent);assert.equal(intent.status,'final');assert.equal(intent.decisions[0].choice,'keep-local');assert.equal(text.includes('props:x'),false);assert.equal(text.includes('"operation":'),false);assert.equal(text.includes('signature'),false);});
test('incomplete or undecided conflict sets cannot finalize',()=>{assert.throws(()=>finalizeCollaborationResolutionIntent(createCollaborationResolutionDraft(model())),/explicit decision/);let partial=createCollaborationResolutionDraft(model({complete:false}));partial=setCollaborationResolutionDecision(partial,partial.groups[0].id,'manual');assert.throws(()=>finalizeCollaborationResolutionIntent(partial),/incomplete conflict set/);});
test('draft fingerprint binds request/head/group coordinates deterministically',()=>{const a=createCollaborationResolutionDraft(model()),b=createCollaborationResolutionDraft(model()),changed=createCollaborationResolutionDraft({...model(),head:{sequence:5,checksum:'other',transactionId:'x'}});assert.equal(a.modelFingerprint,b.modelFingerprint);assert.notEqual(a.modelFingerprint,changed.modelFingerprint);});
