import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac,timingSafeEqual} from 'node:crypto';
import {createGraph} from '../src/graph.js';
import {createOperationLog} from '../src/operation-log.js';
import {createTransaction} from '../src/operations.js';
import {createOperationBatch,signOperationBatch} from '../src/operation-batch.js';
import {createTrustRegistry,enrollTrustActor,enrollTrustKey,hasConsumedTrustNonce} from '../src/trust-registry.js';
import {CollaborationCoordinatorSession} from '../src/collaboration-coordinator.js';
const secret='collab-secret';
function trust(){let r=createTrustRegistry();r=enrollTrustActor(r,{actorId:'alice',now:100});return enrollTrustKey(r,{actorId:'alice',keyId:'k1',purposes:['collaboration'],verification:{ref:'alice'},now:100});}
const verify=async({bytes,signature,key})=>{if(key.verification.ref!=='alice')return false;const e=Buffer.from(createHmac('sha256',secret).update(bytes).digest('hex'),'hex'),a=Buffer.from(String(signature),'hex');return e.length===a.length&&timingSafeEqual(e,a);};
const sign=async({bytes})=>createHmac('sha256',secret).update(bytes).digest('hex');
async function batch(log,transaction,nonce){return signOperationBatch(createOperationBatch(log,[transaction],{actorId:'alice',keyId:'k1',issuedAt:900,nonce}),{sign});}
function coordinator({persist=async()=>{}}={}){const graph=createGraph('Demo'),log=createOperationLog({projectId:graph.projectId});return new CollaborationCoordinatorSession({trustRegistry:trust(),graph,log,verifySignature:verify,now:()=>1000,maxAgeMs:5000,persist});}
function update(graph,patch){return createTransaction('Edit',[{type:'node.update',nodeId:graph.projectId,patch}],{});}
test('current authenticated batch atomically advances graph, log and replay state',async()=>{const writes=[],c=coordinator({persist:async(v)=>writes.push(v)}),before=c.snapshot(),signed=await batch(before.log,update(before.graph,{name:'Remote'}),'n1'),result=await c.submit(signed);assert.equal(result.result.status,'applied');assert.equal(result.graph.nodes[result.graph.projectId].name,'Remote');assert.equal(result.log.entries.length,1);assert.equal(writes.length,1);assert.equal(Object.keys(result.trustRegistry.nonces).length,1);});
test('stale disjoint batch consumes nonce but leaves graph and log unchanged pending re-sign',async()=>{const c=coordinator(),base=c.snapshot(),remote=await batch(base.log,update(base.graph,{name:'Remote'}),'stale'),local=await batch(base.log,update(base.graph,{props:{local:1}}),'local');await c.submit(local);const before=c.snapshot(),result=await c.submit(remote);assert.equal(result.result.status,'rebase-safe');assert.equal(result.graph.nodes[result.graph.projectId].name,before.graph.nodes[before.graph.projectId].name);assert.equal(result.log.entries.length,before.log.entries.length);assert.equal(hasConsumedTrustNonce(result.trustRegistry,{actorId:'alice',keyId:'k1',purpose:'collaboration',nonce:'stale'}),true);});
test('stale overlapping write reports conflict and never mutates graph',async()=>{const c=coordinator(),base=c.snapshot(),remote=await batch(base.log,update(base.graph,{props:{shared:'remote'}}),'conflict'),local=await batch(base.log,update(base.graph,{props:{shared:'local'}}),'local');await c.submit(local);const result=await c.submit(remote);assert.equal(result.result.status,'conflict');assert.equal(result.graph.nodes[result.graph.projectId].props.shared,'local');assert.equal(result.log.entries.length,1);});
test('bad signature invokes neither transition nor atomic persistence',async()=>{let writes=0;const c=coordinator({persist:async()=>{writes++;}}),snap=c.snapshot(),signed=await batch(snap.log,update(snap.graph,{name:'Bad'}),'bad');signed.signature='00'.repeat(32);const result=await c.submit(signed);assert.equal(result.verified,false);assert.equal(c.snapshot().graph.nodes[snap.graph.projectId].name,'Demo');assert.equal(writes,0);});
test('application persistence failure publishes neither batch nor nonce',async()=>{const c=coordinator({persist:async()=>{throw new Error('db abort');}}),snap=c.snapshot(),signed=await batch(snap.log,update(snap.graph,{name:'Nope'}),'abort');await assert.rejects(()=>c.submit(signed),/db abort/);const after=c.snapshot();assert.equal(after.graph.nodes[after.graph.projectId].name,'Demo');assert.equal(after.log.entries.length,0);assert.equal(hasConsumedTrustNonce(after.trustRegistry,{actorId:'alice',keyId:'k1',purpose:'collaboration',nonce:'abort'}),false);});
