import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {createGraph} from '../src/graph.js';
import {createOperationLog} from '../src/operation-log.js';
import {createTransaction} from '../src/operations.js';
import {createOperationBatch,signOperationBatch} from '../src/operation-batch.js';
import {createCollaborationSubmitRequest,encodeCollaborationWireRequest,parseCollaborationWireResponse} from '../src/collaboration-wire.js';
import {CollaborationWebSocketError,CollaborationWebSocketSession} from '../src/collaboration-websocket.js';
async function message(requestId){const graph=createGraph('WS'),log=createOperationLog({projectId:graph.projectId}),tx=createTransaction('Rename',[{type:'node.update',nodeId:graph.projectId,patch:{name:requestId}}]),batch=await signOperationBatch(createOperationBatch(log,[tx],{actorId:'alice',keyId:'k1',issuedAt:1000,nonce:requestId}),{sign:async({bytes})=>createHmac('sha256','ws').update(bytes).digest('hex')}),request=createCollaborationSubmitRequest(batch,{requestId});return{bytes:encodeCollaborationWireRequest(request),batch,log};}
function applied(batch,log){return{verified:true,committed:true,result:{status:'applied',safe:true,requiresResign:false,head:{sequence:1,checksum:batch.entries[0].checksum,transactionId:batch.entries[0].transaction.id}},log:{...log,entries:batch.entries}};}
test('WebSocket session serializes accepted messages per connection',async()=>{const first=await message('one'),second=await message('two'),events=[],sent=[];let release;const gate=new Promise((resolve)=>{release=resolve;}),session=new CollaborationWebSocketSession({send:async(bytes)=>sent.push(parseCollaborationWireResponse(bytes)),submit:async(batch)=>{events.push(`start:${batch.nonce}`);if(batch.nonce==='one')await gate;events.push(`end:${batch.nonce}`);return applied(batch,batch.nonce==='one'?first.log:second.log);}}),a=session.handleMessage(first.bytes),b=session.handleMessage(second.bytes);await new Promise((resolve)=>setImmediate(resolve));assert.deepEqual(events,['start:one']);release();await Promise.all([a,b]);assert.deepEqual(events,['start:one','end:one','start:two','end:two']);assert.deepEqual(sent.map((item)=>item.requestId),['one','two']);});
test('WebSocket session bounds queued work and returns correlated backpressure',async()=>{const first=await message('busy-1'),second=await message('busy-2'),sent=[];let release;const gate=new Promise((resolve)=>{release=resolve;}),session=new CollaborationWebSocketSession({maxPending:1,send:async(bytes)=>sent.push(parseCollaborationWireResponse(bytes)),submit:async(batch)=>{await gate;return applied(batch,first.log);}}),running=session.handleMessage(first.bytes);await new Promise((resolve)=>setImmediate(resolve));const overflow=await session.handleMessage(second.bytes);assert.equal(overflow.statusCode,429);assert.equal(overflow.response.requestId,'busy-2');assert.equal(overflow.response.code,'backpressure');release();await running;assert.equal(sent.length,2);});
test('WebSocket session reuses bounded wire errors for malformed messages',async()=>{const sent=[],session=new CollaborationWebSocketSession({send:async(bytes)=>sent.push(parseCollaborationWireResponse(bytes)),submit:async()=>{throw new Error('must not submit');}}),result=await session.handleMessage('{bad');assert.equal(result.statusCode,400);assert.equal(sent[0].type,'error');});
test('WebSocket session converts unknown service failures to generic errors',async()=>{const item=await message('failure'),sent=[],session=new CollaborationWebSocketSession({send:async(bytes)=>sent.push(parseCollaborationWireResponse(bytes)),submit:async()=>{throw new Error('db password=secret');}}),result=await session.handleMessage(item.bytes);assert.equal(result.statusCode,500);assert.equal(sent[0].code,'internal-error');assert.equal(JSON.stringify(sent[0]).includes('secret'),false);});
test('WebSocket session never retries a failed response send',async()=>{const item=await message('send-failure');let sends=0;const session=new CollaborationWebSocketSession({send:async()=>{sends++;throw new Error('socket closed');},submit:async(batch)=>applied(batch,item.log)});await assert.rejects(()=>session.handleMessage(item.bytes),error=>error instanceof CollaborationWebSocketError&&error.code==='send-failure');assert.equal(sends,1);});
test('closed WebSocket sessions reject new messages without submission',async()=>{const item=await message('closed');let submits=0;const session=new CollaborationWebSocketSession({send:async()=>{},submit:async()=>{submits++;}});session.close();await assert.rejects(()=>session.handleMessage(item.bytes),error=>error.code==='closed');assert.equal(submits,0);});
