import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {createGraph} from '../src/graph.js';
import {appendOperationLog,canonicalOperationLogJson,createOperationLog,operationLogHead} from '../src/operation-log.js';
import {applyTransaction,createTransaction} from '../src/operations.js';
import {createOperationBatch,signOperationBatch} from '../src/operation-batch.js';
import {analyzeOperationBatchRebase} from '../src/operation-conflicts.js';
import {COLLABORATION_RESOLUTION_SCHEMA,createCollaborationConflictModel,describeCollaborationOperation} from '../src/collaboration-resolution.js';

async function fixture(){const baseGraph=createGraph('Demo'),baseLog=createOperationLog({projectId:baseGraph.projectId}),remoteTx=createTransaction('Remote title',[{type:'node.update',nodeId:baseGraph.projectId,patch:{props:{title:'remote'}}}]),remoteBatch=await signOperationBatch(createOperationBatch(baseLog,[remoteTx],{actorId:'alice',keyId:'k1',issuedAt:1000,nonce:'resolve'}),{sign:async({bytes})=>createHmac('sha256','resolve').update(bytes).digest('hex')}),localTx=createTransaction('Local title',[{type:'node.update',nodeId:baseGraph.projectId,patch:{props:{title:'local'}}}]),localLog=appendOperationLog(baseLog,localTx),localGraph=applyTransaction(baseGraph,localTx),analysis=analyzeOperationBatchRebase(localLog,remoteBatch,{graph:localGraph}),conflicts=analysis.conflicts.map(({leftOperation,rightOperation,...conflict})=>conflict),result={type:'batch.result',requestId:'req-resolve',status:'conflict',head:operationLogHead(localLog),verified:true,committed:true,requiresResign:true,safe:false,localEntries:1,remoteEntries:1,conflicts,conflictsTruncated:0};return{baseGraph,localGraph,localLog,remoteBatch,result};}
test('resolution model joins sanitized coordinates to local and remote operation descriptions',async()=>{const {localGraph,localLog,remoteBatch,result}=await fixture(),model=createCollaborationConflictModel(result,{batch:remoteBatch,log:localLog,graph:localGraph});assert.equal(model.schema,COLLABORATION_RESOLUTION_SCHEMA);assert.equal(model.rows.length,1);assert.equal(model.rows[0].local.label,'Local title');assert.equal(model.rows[0].remote.label,'Remote title');assert.deepEqual(model.rows[0].local.operation.fields,['props:title']);assert.deepEqual(model.rows[0].remote.operation.fields,['props:title']);assert.match(model.rows[0].resources[0].local.label,/property title/);assert.equal(model.allowsAutomaticMerge,false);assert.equal(model.complete,true);});
test('resolution model never mutates or rewrites the signed batch/log',async()=>{const {localGraph,localLog,remoteBatch,result}=await fixture(),beforeBatch=canonicalOperationLogJson(remoteBatch),beforeLog=canonicalOperationLogJson(localLog);createCollaborationConflictModel(result,{batch:remoteBatch,log:localLog,graph:localGraph});assert.equal(canonicalOperationLogJson(remoteBatch),beforeBatch);assert.equal(canonicalOperationLogJson(localLog),beforeLog);});
test('resolution model marks truncated server conflict detail as incomplete',async()=>{const {localGraph,localLog,remoteBatch,result}=await fixture(),model=createCollaborationConflictModel({...result,conflictsTruncated:3},{batch:remoteBatch,log:localLog,graph:localGraph});assert.equal(model.complete,false);assert.equal(model.conflictsTruncated,3);});
test('resolution model rejects stale or forged conflict coordinates',async()=>{const {localGraph,localLog,remoteBatch,result}=await fixture(),badTx=structuredClone(result);badTx.conflicts[0].localTransactionId='forged';assert.throws(()=>createCollaborationConflictModel(badTx,{batch:remoteBatch,log:localLog,graph:localGraph}),/does not match sequence/);const badIndex=structuredClone(result);badIndex.conflicts[0].rightOperationIndex=99;assert.throws(()=>createCollaborationConflictModel(badIndex,{batch:remoteBatch,log:localLog,graph:localGraph}),/out of range/);});
test('operation descriptions expose targets/fields but not patch values',()=>{const description=describeCollaborationOperation({type:'node.update',nodeId:'node-1',patch:{name:'secret name',props:{token:'secret value',x:12}}});assert.deepEqual(description.fields,['field:name','props:token','props:x']);assert.equal(JSON.stringify(description).includes('secret value'),false);assert.equal(JSON.stringify(description).includes('secret name'),false);});

test('resolution model de-duplicates repeated sanitized conflict coordinates',async()=>{const {localGraph,localLog,remoteBatch,result}=await fixture(),duplicate={...result,conflicts:[result.conflicts[0],structuredClone(result.conflicts[0])]},model=createCollaborationConflictModel(duplicate,{batch:remoteBatch,log:localLog,graph:localGraph});assert.equal(model.rows.length,1);assert.equal('signature' in model.signedBatch,false);});
