import test from 'node:test';import assert from 'node:assert/strict';
import {parseDashManifestV2,activeDashPeriod,activeDashVariants,nextDashSegments} from '../src/dash-v2.js';
import {resolveDashUtcOffset,dashNow} from '../src/dash-clock.js';
const mpd=`<MPD type="static" mediaPresentationDuration="PT20S"><Period id="p0"><AdaptationSet contentType="video"><SegmentTemplate timescale="1" duration="2" media="p0-$Number$.m4s" initialization="init-$RepresentationID$.mp4"/><Representation id="v" bandwidth="1000000" width="1280" height="720" codecs="avc1.64001f"/></AdaptationSet></Period><Period id="p1" start="PT10S"><AdaptationSet contentType="video"><SegmentTemplate timescale="1" duration="2" media="p1-$Number$.m4s" initialization="init-$RepresentationID$.mp4"/><Representation id="v" bandwidth="1200000" width="1280" height="720" codecs="avc1.64001f"/></AdaptationSet><EventStream schemeIdUri="urn:test" timescale="10"><Event id="e1" presentationTime="5" duration="10">hello</Event></EventStream></Period></MPD>`;
test('DASH period window infers duration from next explicit start',()=>{const m=parseDashManifestV2(mpd,{baseUrl:'https://x.test/master.mpd'});assert.equal(m.periods[0].duration,10);assert.equal(m.periods[1].start,10);assert.equal(m.periods[1].duration,10);});
test('DASH representation IDs are period unique',()=>{const m=parseDashManifestV2(mpd);assert.deepEqual(m.variants.map(v=>v.id),['dash:p0:v','dash:p1:v']);});
test('DASH fixed template does not overlap next period',()=>{const m=parseDashManifestV2(mpd);assert.equal(m.variants[0].segments.at(-1).start,8);assert.equal(m.variants[1].segments[0].start,10);});
test('active period and variants follow presentation time',()=>{const m=parseDashManifestV2(mpd);assert.equal(activeDashPeriod(m,11).id,'p1');assert.equal(activeDashVariants(m,11)[0].id,'dash:p1:v');});
test('next segment IDs remain stable across sequence restart',()=>{const m=parseDashManifestV2(mpd);assert.equal(nextDashSegments(m,{time:11})[0].id,'dash:p1:v:1');});
test('UTCTiming and service description normalize',()=>{const xml=`<MPD type="dynamic" availabilityStartTime="2026-08-15T00:00:00Z"><UTCTiming schemeIdUri="urn:mpeg:dash:utc:direct:2014" value="2026-08-15T00:00:10Z"/><ServiceDescription><Latency target="3000" min="2000" max="5000"/><PlaybackRate min="0.95" max="1.05"/></ServiceDescription><Period><AdaptationSet contentType="video"><Representation id="v"/></AdaptationSet></Period></MPD>`,m=parseDashManifestV2(xml,{now:Date.parse('2026-08-15T00:00:05Z')});assert.equal(m.utcTiming.length,1);assert.equal(m.serviceDescription.latency.target,3000);});
test('EventStream presentation time is period-relative',()=>{const m=parseDashManifestV2(mpd);assert.equal(m.events[0].time,10.5);assert.equal(m.events[0].durationSeconds,1);});
test('direct UTC timing produces clock offset',async()=>{const m={utcTiming:[{schemeIdUri:'urn:mpeg:dash:utc:direct:2014',value:'2026-08-15T00:00:10Z'}]},clock=await resolveDashUtcOffset(m,{now:()=>Date.parse('2026-08-15T00:00:05Z')});assert.equal(clock.offsetMs,5000);assert.equal(dashNow(clock,{now:()=>0}),5000);});
test('HTTP head UTC timing uses Date header',async()=>{const m={utcTiming:[{schemeIdUri:'urn:mpeg:dash:utc:http-head:2014',value:'https://time.test'}]},clock=await resolveDashUtcOffset(m,{now:()=>0,fetchImpl:async()=>({ok:true,headers:{get:()=>new Date(10_000).toUTCString()}})});assert.equal(clock.serverMs,10_000);});

test('DASH template preserves low-latency availability attributes',()=>{const xml=`<MPD type="dynamic" availabilityStartTime="2026-08-15T00:00:00Z"><Period><AdaptationSet contentType="video"><SegmentTemplate timescale="1" duration="2" media="$Number$.m4s" availabilityTimeOffset="1.5" availabilityTimeComplete="false"/><Representation id="v" bandwidth="1"/></AdaptationSet></Period></MPD>`,m=parseDashManifestV2(xml,{now:Date.parse('2026-08-15T00:00:08Z')});assert.equal(m.variants[0].segments[0].availabilityTimeOffset,1.5);assert.equal(m.variants[0].segments[0].availabilityTimeComplete,false);});
