import assert from 'node:assert/strict';
import test from 'node:test';
import { parseIsoBoxes } from '../src/isobmff.js';
import { buildIsoSampleIndex, parseStz2 } from '../src/isobmff-tables.js';
import { demuxIsoBmff, readIsoSample } from '../src/isobmff-demux.js';
import { readEbmlElementHeader } from '../src/ebml.js';
import { demuxWebm, parseWebmBlock, readWebmFrame } from '../src/webm-demux.js';
import { decodeWavPcm, parseWav } from '../src/wav.js';
import { encodeWavPcm } from '../src/wav-encode.js';
import { createPcmBuffer } from '../src/pcm.js';
function concat(...arrays){const out=new Uint8Array(arrays.reduce((sum,a)=>sum+a.length,0));let offset=0;for(const array of arrays){out.set(array,offset);offset+=array.length;}return out;}
function box(type,payload=new Uint8Array()){const out=new Uint8Array(8+payload.length),view=new DataView(out.buffer);view.setUint32(0,out.length,false);for(let i=0;i<4;i++)out[4+i]=type.charCodeAt(i);out.set(payload,8);return out;}
function full(payload){return concat(new Uint8Array(4),payload);}function u32(value){const out=new Uint8Array(4);new DataView(out.buffer).setUint32(0,value,false);return out;}function u16(value){const out=new Uint8Array(2);new DataView(out.buffer).setUint16(0,value,false);return out;}
function makeVideoMp4(){const ftyp=box('ftyp',concat(new TextEncoder().encode('isom'),u32(0),new TextEncoder().encode('isom')));const mvhdPayload=new Uint8Array(20);new DataView(mvhdPayload.buffer).setUint32(12,1000,false);new DataView(mvhdPayload.buffer).setUint32(16,2000,false);const mvhd=box('mvhd',mvhdPayload);const tkhdPayload=new Uint8Array(84);const tkhdView=new DataView(tkhdPayload.buffer);tkhdPayload[3]=1;tkhdView.setUint32(12,1,false);tkhdView.setUint32(76,640*65536,false);tkhdView.setUint32(80,360*65536,false);const tkhd=box('tkhd',tkhdPayload);const mdhdPayload=new Uint8Array(24);const mdhdView=new DataView(mdhdPayload.buffer);mdhdView.setUint32(12,1000,false);mdhdView.setUint32(16,2000,false);mdhdView.setUint16(20,0x15c7,false);const mdhd=box('mdhd',mdhdPayload);const hdlrPayload=new Uint8Array(20);hdlrPayload.set(new TextEncoder().encode('vide'),8);const hdlr=box('hdlr',hdlrPayload);const avcCPayload=new Uint8Array([1,0x64,0,0x28]);const avcC=box('avcC',avcCPayload);const samplePayload=new Uint8Array(78+avcC.length);const sampleView=new DataView(samplePayload.buffer);sampleView.setUint16(6,1,false);sampleView.setUint16(24,640,false);sampleView.setUint16(26,360,false);samplePayload.set(avcC,78);const avc1=box('avc1',samplePayload);const stsd=box('stsd',concat(new Uint8Array(4),u32(1),avc1));const stts=box('stts',concat(new Uint8Array(4),u32(1),u32(2),u32(1000)));const stsc=box('stsc',concat(new Uint8Array(4),u32(1),u32(1),u32(2),u32(1)));const stsz=box('stsz',concat(new Uint8Array(4),u32(0),u32(2),u32(4),u32(5)));const stss=box('stss',concat(new Uint8Array(4),u32(1),u32(1)));const buildMoov=(chunkOffset)=>{const stco=box('stco',concat(new Uint8Array(4),u32(1),u32(chunkOffset)));const stbl=box('stbl',concat(stsd,stts,stsc,stsz,stco,stss));const minf=box('minf',stbl);const mdia=box('mdia',concat(mdhd,hdlr,minf));const trak=box('trak',concat(tkhd,mdia));return box('moov',concat(mvhd,trak));};let moov=buildMoov(0);const mdatOffset=ftyp.length+moov.length+8;moov=buildMoov(mdatOffset);const mdat=box('mdat',new Uint8Array([1,2,3,4,5,6,7,8,9]));return concat(ftyp,moov,mdat);}
test('demuxes a classic non-fragmented MP4 sample table',()=>{const source=makeVideoMp4();const demux=demuxIsoBmff(source);assert.equal(demux.container,'mp4');assert.equal(demux.duration,2);assert.equal(demux.tracks.length,1);assert.equal(demux.tracks[0].codec,'avc1.640028');assert.equal(demux.tracks[0].width,640);assert.equal(demux.chunks.length,2);assert.deepEqual(demux.chunks.map((c)=>c.type),['key','delta']);assert.deepEqual(demux.chunks.map((c)=>c.timestamp),[0,1_000_000]);assert.deepEqual([...readIsoSample(source,demux.chunks[1])],[5,6,7,8,9]);assert.deepEqual(demux.seekPoints,[0]);});
function fullBoxPayload(version,flags,body){const out=new Uint8Array(4+body.length);out[0]=version;out[1]=(flags>>16)&255;out[2]=(flags>>8)&255;out[3]=flags&255;out.set(body,4);return out;}
function makeFragmentedMp4(){const ftyp=box('ftyp',concat(new TextEncoder().encode('isom'),u32(0),new TextEncoder().encode('iso6')));const mvhdPayload=new Uint8Array(20);new DataView(mvhdPayload.buffer).setUint32(12,1000,false);const mvhd=box('mvhd',mvhdPayload);const tkhdPayload=new Uint8Array(84);const tkhdView=new DataView(tkhdPayload.buffer);tkhdPayload[3]=1;tkhdView.setUint32(12,1,false);tkhdView.setUint32(76,1280*65536,false);tkhdView.setUint32(80,720*65536,false);const tkhd=box('tkhd',tkhdPayload);const mdhdPayload=new Uint8Array(24);const mdhdView=new DataView(mdhdPayload.buffer);mdhdView.setUint32(12,1000,false);mdhdView.setUint16(20,0x15c7,false);const mdhd=box('mdhd',mdhdPayload);const hdlrPayload=new Uint8Array(20);hdlrPayload.set(new TextEncoder().encode('vide'),8);const hdlr=box('hdlr',hdlrPayload);const avcC=box('avcC',new Uint8Array([1,0x64,0,0x28]));const samplePayload=new Uint8Array(78+avcC.length);const sampleView=new DataView(samplePayload.buffer);sampleView.setUint16(6,1,false);sampleView.setUint16(24,1280,false);sampleView.setUint16(26,720,false);samplePayload.set(avcC,78);const stsd=box('stsd',concat(new Uint8Array(4),u32(1),box('avc1',samplePayload)));const stbl=box('stbl',stsd);const trak=box('trak',concat(tkhd,box('mdia',concat(mdhd,hdlr,box('minf',stbl)))));const trex=box('trex',fullBoxPayload(0,0,concat(u32(1),u32(1),u32(1000),u32(0),u32(0))));const moov=box('moov',concat(mvhd,trak,box('mvex',trex)));const tfhd=box('tfhd',fullBoxPayload(0,0x020000,u32(1)));const tfdt=box('tfdt',fullBoxPayload(0,0,u32(0)));const makeTrun=(dataOffset)=>box('trun',fullBoxPayload(0,0x000701,concat(u32(2),(()=>{const x=new Uint8Array(4);new DataView(x.buffer).setInt32(0,dataOffset,false);return x;})(),u32(1000),u32(4),u32(0),u32(1000),u32(5),u32(0x00010000))));let moof=box('moof',box('traf',concat(tfhd,tfdt,makeTrun(0))));moof=box('moof',box('traf',concat(tfhd,tfdt,makeTrun(moof.length+8))));return concat(ftyp,moov,moof,box('mdat',new Uint8Array([1,2,3,4,5,6,7,8,9])));}
test('indexes fragmented MP4 moof/trun samples',()=>{const source=makeFragmentedMp4();const demux=demuxIsoBmff(source);assert.equal(demux.metadata.fragmented,true);assert.equal(demux.trackDetails[0].classicReady,false);assert.equal(demux.chunks.length,2);assert.deepEqual(demux.chunks.map((c)=>c.timestamp),[0,1_000_000]);assert.deepEqual(demux.chunks.map((c)=>c.type),['key','delta']);assert.deepEqual([...readIsoSample(source,demux.chunks[1])],[5,6,7,8,9]);assert.equal(demux.duration,2);});
function makeAudioMp4(){const ftyp=box('ftyp',concat(new TextEncoder().encode('M4A '),u32(0),new TextEncoder().encode('isom')));const mvhdPayload=new Uint8Array(20);const mvhdView=new DataView(mvhdPayload.buffer);mvhdView.setUint32(12,1000,false);mvhdView.setUint32(16,1000,false);const mvhd=box('mvhd',mvhdPayload);const tkhdPayload=new Uint8Array(84);tkhdPayload[3]=1;new DataView(tkhdPayload.buffer).setUint32(12,2,false);const tkhd=box('tkhd',tkhdPayload);const mdhdPayload=new Uint8Array(24);const mdhdView=new DataView(mdhdPayload.buffer);mdhdView.setUint32(12,48000,false);mdhdView.setUint32(16,48000,false);mdhdView.setUint16(20,0x15c7,false);const mdhd=box('mdhd',mdhdPayload);const hdlrPayload=new Uint8Array(20);hdlrPayload.set(new TextEncoder().encode('soun'),8);const hdlr=box('hdlr',hdlrPayload);const esDescriptor=new Uint8Array([0x03,0x16,0,1,0,0x04,0x11,0x40,0x15,0,0,0,0,0,0,0,0,0,0,0,0x05,0x02,0x12,0x10]);const esds=box('esds',concat(new Uint8Array(4),esDescriptor));const samplePayload=new Uint8Array(28+esds.length);const sampleView=new DataView(samplePayload.buffer);sampleView.setUint16(6,1,false);sampleView.setUint16(16,2,false);sampleView.setUint16(18,16,false);sampleView.setUint32(24,48000*65536,false);samplePayload.set(esds,28);const mp4a=box('mp4a',samplePayload);const stsd=box('stsd',concat(new Uint8Array(4),u32(1),mp4a));const stts=box('stts',concat(new Uint8Array(4),u32(1),u32(2),u32(24000)));const stsc=box('stsc',concat(new Uint8Array(4),u32(1),u32(1),u32(2),u32(1)));const stsz=box('stsz',concat(new Uint8Array(4),u32(0),u32(2),u32(3),u32(2)));const buildMoov=(chunkOffset)=>{const stco=box('stco',concat(new Uint8Array(4),u32(1),u32(chunkOffset)));const stbl=box('stbl',concat(stsd,stts,stsc,stsz,stco));const minf=box('minf',stbl);const mdia=box('mdia',concat(mdhd,hdlr,minf));return box('moov',concat(mvhd,box('trak',concat(tkhd,mdia))));};let moov=buildMoov(0);const offset=ftyp.length+moov.length+8;moov=buildMoov(offset);return concat(ftyp,moov,box('mdat',new Uint8Array([1,2,3,4,5])));}
test('demuxes MP4 audio sample descriptions and timings',()=>{const source=makeAudioMp4();const demux=demuxIsoBmff(source);assert.equal(demux.tracks[0].type,'audio');assert.equal(demux.tracks[0].codec,'mp4a.40.2');assert.equal(demux.tracks[0].sampleRate,48000);assert.equal(demux.tracks[0].channels,2);assert.deepEqual([...new Uint8Array(demux.tracks[0].description)],[0x12,0x10]);assert.deepEqual(demux.chunks.map((c)=>c.duration),[500_000,500_000]);assert.deepEqual([...readIsoSample(source,demux.chunks[0])],[1,2,3]);});
test('sample index preserves decode and composition timestamps',()=>{const chunks=buildIsoSampleIndex({trackId:'video:1',timescale:1000,stts:[{sampleCount:2,sampleDelta:1000}],ctts:{entries:[{sampleCount:1,sampleOffset:500},{sampleCount:1,sampleOffset:0}]},stsc:[{firstChunk:1,samplesPerChunk:2,sampleDescriptionIndex:1}],stsz:{sampleCount:2,sizes:[4,4]},chunkOffsets:[100],stss:[1]});assert.equal(chunks[0].decodeTimestamp,0);assert.equal(chunks[0].presentationTimestamp,500_000);assert.equal(chunks[1].decodeTimestamp,1_000_000);});
test('parses compact stz2 sample sizes',()=>{const payload=concat(new Uint8Array(4),new Uint8Array([0,0,0,4]),u32(3),new Uint8Array([0x12,0x30]));const wrapped=box('stz2',payload);assert.deepEqual(parseStz2(wrapped,parseIsoBoxes(wrapped)[0]).sizes,[1,2,3]);});
test('ISO parser retains zero-sized box to parent end',()=>{const bytes=box('free',new Uint8Array(4));new DataView(bytes.buffer).setUint32(0,0,false);assert.equal(parseIsoBoxes(bytes)[0].size,bytes.length);});
function idBytes(id){let hex=id.toString(16);if(hex.length%2)hex='0'+hex;return Uint8Array.from(hex.match(/../g).map((pair)=>parseInt(pair,16)));}function vintSize(size){if(size<0x7f)return new Uint8Array([0x80|size]);if(size<0x3fff)return new Uint8Array([0x40|(size>>8),size&255]);throw new Error('test payload too large');}function element(id,payload){return concat(idBytes(id),vintSize(payload.length),payload);}function uintPayload(value){if(value<=0xff)return new Uint8Array([value]);if(value<=0xffff)return new Uint8Array([value>>8,value&255]);if(value<=0xffffff)return new Uint8Array([value>>16,(value>>8)&255,value&255]);return new Uint8Array([(value>>>24)&255,(value>>>16)&255,(value>>>8)&255,value&255]);}function uintElement(id,value){return element(id,uintPayload(value));}function stringElement(id,value){return element(id,new TextEncoder().encode(value));}function float64Element(id,value){const out=new Uint8Array(8);new DataView(out.buffer).setFloat64(0,value,false);return element(id,out);}function simpleBlock(track,timecode,flags,payload){const block=new Uint8Array(4+payload.length);block[0]=0x80|track;new DataView(block.buffer).setInt16(1,timecode,false);block[3]=flags;block.set(payload,4);return element(0xa3,block);}function makeWebm(){const doc=stringElement(0x4282,'webm');const header=element(0x1a45dfa3,doc);const info=element(0x1549a966,concat(uintElement(0x2ad7b1,1_000_000),float64Element(0x4489,2000)));const video=element(0xe0,concat(uintElement(0xb0,320),uintElement(0xba,180)));const entry=element(0xae,concat(uintElement(0xd7,1),uintElement(0x83,1),stringElement(0x86,'V_VP9'),uintElement(0x23e383,1_000_000_000),video));const tracks=element(0x1654ae6b,entry);const cluster=element(0x1f43b675,concat(uintElement(0xe7,0),simpleBlock(1,0,0x80,new Uint8Array([10,11,12])),simpleBlock(1,1000,0,new Uint8Array([20,21]))));return concat(header,element(0x18538067,concat(info,tracks,cluster)));}
test('demuxes WebM tracks and SimpleBlock byte ranges',()=>{const source=makeWebm();const demux=demuxWebm(source);assert.equal(demux.container,'webm');assert.equal(demux.duration,2);assert.equal(demux.tracks[0].codec,'vp09');assert.equal(demux.tracks[0].width,320);assert.equal(demux.chunks.length,2);assert.deepEqual(demux.chunks.map((c)=>c.timestamp),[0,1_000_000]);assert.deepEqual(demux.chunks.map((c)=>c.duration),[1_000_000,1_000_000]);assert.deepEqual([...readWebmFrame(source,demux.chunks[0])],[10,11,12]);});
test('parses fixed-laced WebM blocks into separate frames',()=>{const payload=new Uint8Array([0x81,0,0,0x84,1,1,2,3,4]);const wrapped=element(0xa3,payload);const block=readEbmlElementHeader(wrapped);const frames=parseWebmBlock(wrapped,block,{trackDefaults:new Map([[1,{defaultDurationNs:10_000_000}]])});assert.deepEqual(frames.map((f)=>f.byteLength),[2,2]);assert.deepEqual(frames.map((f)=>f.timestamp),[0,10_000]);});
test('accepts WebM Segment with unknown-size vint',()=>{const source=makeWebm();const header=readEbmlElementHeader(source);const segmentOffset=header.end;const sizeOffset=segmentOffset+4;const mutated=source.slice();mutated[sizeOffset]=0xff;const demux=demuxWebm(mutated);assert.equal(demux.tracks.length,1);assert.equal(demux.chunks.length,2);});
test('parses Xiph and EBML lacing sizes',()=>{const xiphPayload=new Uint8Array([0x81,0,0,0x82,2,2,3,10,11,20,21,22,30]);const xiphWrapped=element(0xa3,xiphPayload);const xiph=parseWebmBlock(xiphWrapped,readEbmlElementHeader(xiphWrapped));assert.deepEqual(xiph.map((f)=>f.byteLength),[2,3,1]);const ebmlPayload=new Uint8Array([0x81,0,0,0x86,2,0x82,0xc0,1,2,3,4,5,6,7,8,9]);const ebmlWrapped=element(0xa3,ebmlPayload);const ebml=parseWebmBlock(ebmlWrapped,readEbmlElementHeader(ebmlWrapped));assert.deepEqual(ebml.map((f)=>f.byteLength),[2,3,4]);});
function approx(actual,expected,tolerance=1e-4){assert.ok(Math.abs(actual-expected)<=tolerance,`${actual} ≉ ${expected}`);}
test('encodes PCM to 16-bit WAV and round-trips samples',()=>{const pcm=createPcmBuffer({channels:2,sampleRate:48000,length:3});pcm.channels[0].set([-1,0,.5]);pcm.channels[1].set([1,-.5,0]);const wav=encodeWavPcm(pcm,{bitDepth:16});const metadata=parseWav(wav);assert.equal(metadata.format.channels,2);assert.equal(metadata.format.bitsPerSample,16);const decoded=decodeWavPcm(wav).pcm;approx(decoded.channels[0][0],-1);approx(decoded.channels[0][2],.5,1/32767);approx(decoded.channels[1][0],1,1/32767);});
test('encodes float32 WAV without quantization',()=>{const pcm=createPcmBuffer({channels:1,sampleRate:8000,length:2});pcm.channels[0].set([.123456,-.654321]);const wav=encodeWavPcm(pcm,{bitDepth:32,float:true});const decoded=decodeWavPcm(wav).pcm;approx(decoded.channels[0][0],.123456,1e-6);approx(decoded.channels[0][1],-.654321,1e-6);});
