import assert from 'node:assert/strict';
import test from 'node:test';
import { KernelTaskLedger, assertKernelMessage, createKernelCancel, createKernelError, createKernelResult, createKernelTask } from '../src/kernel-protocol.js';
import { KernelRuntime } from '../src/kernel-runtime.js';
import { createMuxPlan, createMuxTrack, interleaveMuxSamples, muxByteEstimate, segmentMuxPlan } from '../src/mux.js';
import { createPcmBuffer, dbToLinear, mixPcmInto, normalizePcm, peakPcm, renderPcmMix, resamplePcm, sampleLinear } from '../src/pcm.js';
import { chooseProxyTier, createDerivativeKey, createProxySpec, planDerivativesForSource, planProjectDerivatives, proxyDimensions, thumbnailTimes } from '../src/proxy.js';
import { artifactManifestForJob, claimNextRenderChunk, completeRenderChunk, createRenderJobPlan, failRenderChunk, frameRangeFromManifest, jobHash, recoverInterruptedRenderJob, renderJobProgress } from '../src/render-jobs.js';
import { assertPipelineAcyclic, createProductionPipeline, pipelineProgress, runnablePipelineTasks, skipFailedOptionalTasks, updatePipelineTask } from '../src/pipeline.js';

test('creates and validates versioned kernel tasks', () => { const task=createKernelTask('demux',{assetId:'a'},{id:'x',priority:4});assert.equal(task.protocol,'media.kernel.v1');assert.equal(task.priority,4);assert.doesNotThrow(()=>assertKernelMessage(task));assert.throws(()=>createKernelTask('explode',{}),/Unsupported/); });
test('creates cancel result and error kernel messages', () => { assert.equal(createKernelCancel('x').type,'cancel');assert.equal(createKernelResult('x',{ok:true}).type,'result');assert.equal(createKernelError('x',new Error('bad'),{retryable:true,code:'E_BAD'}).error.code,'E_BAD'); });
test('tracks kernel task lifecycle', () => { const ledger=new KernelTaskLedger();ledger.dispatch(createKernelTask('thumbnail',{}, {id:'thumb'}));ledger.start('thumb');ledger.progress('thumb',.4);ledger.resolve('thumb',{uri:'x'});ledger.dispatch(createKernelTask('waveform',{}, {id:'w'}));ledger.cancel('w');assert.equal(ledger.summary().complete,1);assert.equal(ledger.summary().cancelled,1); });
test('executes kernel handlers with progress and errors', async()=>{const updates=[];const runtime=new KernelRuntime().register('proxy',async(_payload,{progress})=>{progress(.5);return'ok';});const result=await runtime.execute(createKernelTask('proxy',{}, {id:'p'}),{onProgress:(m)=>updates.push(m.progress)});assert.equal(result.type,'result');assert.deepEqual(updates,[.5]);assert.equal((await runtime.execute(createKernelTask('mux',{}, {id:'m'}))).error.code,'NO_HANDLER');});
test('supports cancellation of running kernel handlers',async()=>{const runtime=new KernelRuntime().register('waveform',async(_payload,{signal})=>new Promise((resolve,reject)=>{signal.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError')));setTimeout(()=>resolve('late'),50);}));const promise=runtime.execute(createKernelTask('waveform',{}, {id:'w'}));await new Promise((r)=>setTimeout(r,5));assert.equal(runtime.cancel('w'),true);assert.equal((await promise).error.code,'ABORTED');});

const muxTracks=[createMuxTrack({id:'v',type:'video',codec:'avc1'}),createMuxTrack({id:'a',type:'audio',codec:'aac'})];
test('creates mux tracks and interleaves samples',()=>{assert.equal(muxTracks[0].timescale,1_000_000);const out=interleaveMuxSamples([{trackId:'a',dts:10,trackOrder:1},{trackId:'v',dts:0,trackOrder:0},{trackId:'a',dts:0,trackOrder:1},{trackId:'v',dts:10,trackOrder:0}]);assert.deepEqual(out.map((x)=>x.trackId),['v','a','v','a']);});
test('creates validated mux plan and duration',()=>{const plan=createMuxPlan({container:'mp4',tracks:muxTracks,samples:[{trackId:'v',timestamp:0,duration:1_000_000,type:'key',byteLength:100},{trackId:'a',timestamp:0,duration:500_000,byteLength:20},{trackId:'a',timestamp:500_000,duration:500_000,byteLength:20}]});assert.equal(plan.duration,1);assert.equal(plan.samples.length,3);});
test('segments mux plans on keyframes and estimates bytes',()=>{const samples=[];for(let i=0;i<6;i++)samples.push({trackId:'v',timestamp:i*1_000_000,duration:1_000_000,keyframe:i%2===0,byteLength:100});const plan=createMuxPlan({container:'mp4',tracks:[muxTracks[0]],samples});assert.deepEqual(segmentMuxPlan(plan,{segmentDuration:2}).map((s)=>s.start),[0,2,4]);assert.equal(muxByteEstimate(createMuxPlan({container:'mp4',tracks:[muxTracks[0]],samples:[{trackId:'v',timestamp:0,byteLength:1000}]}),{overheadRatio:.1}),1100);});
test('rejects unknown mux track references',()=>assert.throws(()=>createMuxPlan({container:'mp4',tracks:muxTracks,samples:[{trackId:'x',timestamp:0}]}),/unknown track/));

function mono(values, sampleRate=4) { const buffer=createPcmBuffer({channels:1,sampleRate,length:values.length});buffer.channels[0].set(values);return buffer; }
test('handles PCM gain sampling and resampling',()=>{assert.equal(dbToLinear(0),1);assert.equal(sampleLinear(new Float32Array([0,1]),.5),.5);assert.equal(resamplePcm(mono([0,1,0,-1],4),8).length,8);});
test('mixes PCM with pan and fades',()=>{const source=mono([1,1,1,1],4);const stereo=createPcmBuffer({channels:2,sampleRate:4,length:4});mixPcmInto(stereo,source,{pan:-1});assert.ok(stereo.channels[0][1]>.99);assert.ok(Math.abs(stereo.channels[1][1])<1e-6);const faded=createPcmBuffer({channels:1,sampleRate:4,length:4});mixPcmInto(faded,source,{fadeIn:.5,fadeOut:.5});assert.equal(faded.channels[0][0],0);});
test('normalizes and renders PCM mix plans',()=>{const source=mono([.25,-.5,.1],3);normalizePcm(source,{targetPeak:1});assert.ok(Math.abs(peakPcm(source)-1)<1e-6);const plan={sampleRate:4,startSample:0,sampleCount:4,sources:[{assetId:'a',startSample:0,endSample:4,sourceInSample:0,playbackRate:1,gainDb:0,pan:0,fadeIn:0,fadeOut:0}]};assert.deepEqual([...renderPcmMix(plan,new Map([['a',mono([1,1,1,1],4)]]),{channels:1}).channels[0]],[1,1,1,1]);});

test('creates stable derivative keys and proxy dimensions',()=>{assert.equal(createDerivativeKey({assetId:'a',sourceHash:'h',type:'thumbnail',spec:{width:320,quality:.8}}),createDerivativeKey({assetId:'a',sourceHash:'h',type:'thumbnail',spec:{quality:.8,width:320}}));assert.deepEqual(proxyDimensions({width:3840,height:2160},{maxLongEdge:1280}),{width:1280,height:720,scale:1/3});});
test('chooses tiers specs and thumbnail times',()=>{assert.equal(chooseProxyTier({width:3840,height:2160},{viewportWidth:1000}),'720p');assert.equal(createProxySpec({width:3840,height:2160},{tier:'720p'}).height,720);assert.deepEqual(thumbnailTimes(10,{count:3}),[0,5,10]);});
test('plans source and project derivatives',()=>{assert.deepEqual(planDerivativesForSource({id:'v',hash:'h',mediaKind:'video',duration:10,width:3840,height:2160}).map((x)=>x.type),['thumbnail','proxy-video','waveform']);assert.deepEqual(planProjectDerivatives([{id:'i',mediaKind:'image'},{id:'a',mediaKind:'audio'}]).map((x)=>x.assetId),['i','a']);});

const manifest={signature:'abc123',settings:{fps:30,rangeStart:1,rangeEnd:11,includeAudio:true,width:1920,height:1080},dependencies:[{assetId:'a'}]};
test('partitions deterministic render jobs',()=>{assert.deepEqual(frameRangeFromManifest(manifest),{fps:30,startFrame:30,endFrameExclusive:330,frameCount:300});const job=createRenderJobPlan(manifest,{chunkFrames:64});assert.deepEqual(job.chunks.map((c)=>c.frameCount),[64,64,64,64,44]);assert.equal(jobHash({a:1,b:{x:2,y:3}}),jobHash({b:{y:3,x:2},a:1}));});
test('claims completes and reports render progress',()=>{let job=createRenderJobPlan(manifest,{chunkFrames:200});let claimed=claimNextRenderChunk(job,'w');job=completeRenderChunk(claimed.job,claimed.chunk.id,{uri:'0'});assert.equal(renderJobProgress(job).completedFrames,200);});
test('retries and recovers render chunks',()=>{let job=createRenderJobPlan(manifest,{chunkFrames:300,maxAttempts:2});let claim=claimNextRenderChunk(job,'w');job=failRenderChunk(claim.job,claim.chunk.id,new Error('boom'));assert.equal(job.status,'pending');claim=claimNextRenderChunk(job,'w2');job=failRenderChunk(claim.job,claim.chunk.id,new Error('again'));assert.equal(job.status,'failed');let interrupted=claimNextRenderChunk(createRenderJobPlan(manifest,{chunkFrames:300}),'w').job;assert.equal(recoverInterruptedRenderJob(interrupted).chunks[0].status,'pending');});
test('creates ordered artifact manifest when render complete',()=>{let job=createRenderJobPlan(manifest,{chunkFrames:150});for(let i=0;i<2;i++){const claimed=claimNextRenderChunk(job,`w${i}`);job=completeRenderChunk(claimed.job,claimed.chunk.id,{uri:`${i}`});}assert.deepEqual(artifactManifestForJob(job).chunks.map((c)=>c.artifact.uri),['0','1']);});

const pipelineSources=[{id:'v',mediaKind:'video',width:3840,height:2160,duration:4,hash:'h'}];const pipelineManifest={signature:'sig',settings:{fps:30,rangeStart:0,rangeEnd:4,includeAudio:true,width:1920,height:1080},dependencies:[]};
test('builds acyclic production render DAG',()=>{const plan=createProductionPipeline(pipelineManifest,pipelineSources,{chunkFrames:60});assert.equal(plan.renderJob.chunks.length,2);assert.doesNotThrow(()=>assertPipelineAcyclic(plan));assert.deepEqual(runnablePipelineTasks(plan).map((x)=>x.kind),['verify-source']);});
test('unlocks render work and reports pipeline progress',()=>{let plan=createProductionPipeline(pipelineManifest,pipelineSources,{includeProxies:false});plan=updatePipelineTask(plan,'source:v',{status:'complete'});const kinds=new Set(runnablePipelineTasks(plan).map((x)=>x.kind));assert.ok(kinds.has('render-frames'));assert.ok(kinds.has('render-audio'));assert.ok(pipelineProgress(plan).ratio>0);});
test('skips failed optional derivatives and detects cycles',()=>{let plan=createProductionPipeline(pipelineManifest,pipelineSources,{includeProxies:true});const optional=plan.tasks.find((x)=>x.optional);plan=updatePipelineTask(plan,optional.id,{status:'failed'});assert.equal(skipFailedOptionalTasks(plan).tasks.find((x)=>x.id===optional.id).skipped,true);assert.throws(()=>assertPipelineAcyclic({tasks:[{id:'a',dependsOn:['b']},{id:'b',dependsOn:['a']}]}),/cycle/);});
