import test from 'node:test';
import assert from 'node:assert/strict';
import {appendOperationLog,canonicalOperationLogJson,createOperationLog,operationLogChecksum,operationLogHead,replayOperationLog,truncateOperationLog,validateOperationLog} from '../src/operation-log.js';

const tx=(id,value)=>({id,label:`Add ${value}`,operations:[{type:'add',value}],metadata:{source:'test'}});
test('canonical JSON and checksum ignore object insertion order',()=>{const a={z:1,a:{y:2,x:3}},b={a:{x:3,y:2},z:1};assert.equal(canonicalOperationLogJson(a),canonicalOperationLogJson(b));assert.equal(operationLogChecksum(a),operationLogChecksum(b));});
test('append creates an immutable monotonic checksum chain',()=>{const empty=createOperationLog({projectId:'p',metadata:{name:'Demo'}}),one=appendOperationLog(empty,tx('t1',2)),two=appendOperationLog(one,tx('t2',3));assert.equal(empty.entries.length,0);assert.equal(one.entries[0].sequence,1);assert.equal(two.entries[1].sequence,2);assert.equal(two.entries[1].previousChecksum,two.entries[0].checksum);assert.deepEqual(operationLogHead(two),{sequence:2,checksum:two.entries[1].checksum,transactionId:'t2'});validateOperationLog(two);});
test('tampering is detected before replay',()=>{const log=appendOperationLog(createOperationLog({projectId:'p'}),tx('t1',2)),tampered=structuredClone(log);tampered.entries[0].transaction.operations[0].value=999;assert.throws(()=>validateOperationLog(tampered),/checksum mismatch/);});
test('sequence gaps and broken previous checksums are rejected',()=>{const log=appendOperationLog(appendOperationLog(createOperationLog({projectId:'p'}),tx('t1',1)),tx('t2',2)),gap=structuredClone(log),broken=structuredClone(log);gap.entries[1].sequence=3;broken.entries[1].previousChecksum='bad';assert.throws(()=>validateOperationLog(gap),/sequence gap/);assert.throws(()=>validateOperationLog(broken),/chain mismatch/);});
test('replay applies validated transactions in order',()=>{let log=createOperationLog({projectId:'p'});log=appendOperationLog(log,tx('t1',2));log=appendOperationLog(log,tx('t2',3));const result=replayOperationLog(10,log,(state,transaction)=>state+transaction.operations.reduce((sum,op)=>sum+op.value,0));assert.equal(result,15);});
test('truncate produces a valid recovery prefix that can branch',()=>{let log=createOperationLog({projectId:'p'});log=appendOperationLog(log,tx('t1',1));log=appendOperationLog(log,tx('t2',2));const prefix=truncateOperationLog(log,1),branch=appendOperationLog(prefix,tx('t3',7));assert.equal(branch.entries.length,2);assert.equal(branch.entries[1].sequence,2);assert.equal(branch.entries[1].previousChecksum,branch.entries[0].checksum);validateOperationLog(branch);});
test('non-JSON values are rejected instead of being silently normalized',()=>{const log=createOperationLog({projectId:'p'});assert.throws(()=>appendOperationLog(log,{id:'t',label:'bad',operations:[{value:NaN}],metadata:{}}),/finite numbers/);assert.throws(()=>appendOperationLog(log,{id:'t',label:'bad',operations:[],metadata:{value:undefined}}),/undefined/);});
