import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
import {appendOperationLog,createOperationLog,operationLogHead,validateOperationLog} from '../src/operation-log.js';
import {appendAuthenticatedOperationBatch,createOperationBatch,operationBatchSigningText,replayAuthenticatedOperationBatch,signOperationBatch,verifyOperationBatch} from '../src/operation-batch.js';
const tx=(id,value)=>({id,label:`Add ${value}`,operations:[{type:'add',value}],metadata:{source:'collab'}});
async function hmac(){const key=await webcrypto.subtle.generateKey({name:'HMAC',hash:'SHA-256'},true,['sign','verify']);const encode=(bytes)=>Buffer.from(bytes).toString('base64');return{sign:async({bytes})=>encode(new Uint8Array(await webcrypto.subtle.sign('HMAC',key,bytes))),verifySignature:async({bytes,signature})=>webcrypto.subtle.verify('HMAC',key,Buffer.from(signature,'base64'),bytes)};}
test('operation batch anchors actor identity and exact prior log head',()=>{const log=appendOperationLog(createOperationLog({projectId:'p',baseRevision:3}),tx('base',1)),batch=createOperationBatch(log,[tx('a',2),tx('b',3)],{actorId:'alice',keyId:'alice-main',issuedAt:10,nonce:'n'});assert.deepEqual(batch.previousHead,operationLogHead(log));assert.equal(batch.entries[0].sequence,2);assert.equal(batch.entries[1].previousChecksum,batch.entries[0].checksum);assert.deepEqual(batch.actor,{id:'alice',keyId:'alice-main'});});
test('signed batch verifies and appends without weakening the local checksum chain',async()=>{const auth=await hmac(),log=createOperationLog({projectId:'p'}),signed=await signOperationBatch(createOperationBatch(log,[tx('a',2)],{actorId:'alice',keyId:'k'}),auth),next=await appendAuthenticatedOperationBatch(log,signed,{verifySignature:auth.verifySignature,allowedActorIds:['alice']});assert.equal(next.entries.length,1);validateOperationLog(next);});
test('signature covers transaction bytes even if an attacker recomputes the local checksum',async()=>{const auth=await hmac(),log=createOperationLog({projectId:'p'}),signed=await signOperationBatch(createOperationBatch(log,[tx('a',2)],{actorId:'alice',keyId:'k'}),auth),forged=createOperationBatch(log,[tx('a',999)],{actorId:'alice',keyId:'k'});forged.signature=signed.signature;await assert.rejects(()=>verifyOperationBatch(forged,{verifySignature:auth.verifySignature}),e=>e.code==='ERR_OPERATION_BATCH_SIGNATURE');});
test('invalid signature is rejected before replay calls the transaction applier',async()=>{const auth=await hmac(),log=createOperationLog({projectId:'p'}),signed=await signOperationBatch(createOperationBatch(log,[tx('a',2)],{actorId:'alice',keyId:'k'}),auth);signed.signature=Buffer.from('bad').toString('base64');let calls=0;await assert.rejects(()=>replayAuthenticatedOperationBatch(0,log,signed,(state)=>{calls++;return state;},{verifySignature:auth.verifySignature}),e=>e.code==='ERR_OPERATION_BATCH_SIGNATURE');assert.equal(calls,0);});
test('stale signed batch is rejected before replay when local head has advanced',async()=>{const auth=await hmac(),base=createOperationLog({projectId:'p'}),signed=await signOperationBatch(createOperationBatch(base,[tx('remote',2)],{actorId:'alice',keyId:'k'}),auth),advanced=appendOperationLog(base,tx('local',4));let calls=0;await assert.rejects(()=>replayAuthenticatedOperationBatch(0,advanced,signed,(state)=>{calls++;return state;},{verifySignature:auth.verifySignature}),e=>e.code==='ERR_OPERATION_BATCH_HEAD');assert.equal(calls,0);});
test('actor allowlist and freshness policy fail closed',async()=>{const auth=await hmac(),log=createOperationLog({projectId:'p'}),signed=await signOperationBatch(createOperationBatch(log,[tx('a',1)],{actorId:'alice',keyId:'k',issuedAt:1000}),auth);await assert.rejects(()=>verifyOperationBatch(signed,{verifySignature:auth.verifySignature,allowedActorIds:['bob']}),e=>e.code==='ERR_OPERATION_BATCH_ACTOR');await assert.rejects(()=>verifyOperationBatch(signed,{verifySignature:auth.verifySignature,maxAgeMs:500,now:2000}),e=>e.code==='ERR_OPERATION_BATCH_FRESHNESS');});
test('canonical signing text is stable across caller object insertion order',()=>{const log=createOperationLog({projectId:'p'}),a=createOperationBatch(log,[{id:'x',label:'X',operations:[{type:'set',b:2,a:1}],metadata:{z:3,a:4}}],{actorId:'alice',keyId:'k'}),b=createOperationBatch(log,[{label:'X',id:'x',metadata:{a:4,z:3},operations:[{a:1,b:2,type:'set'}]}],{keyId:'k',actorId:'alice'});assert.equal(operationBatchSigningText(a),operationBatchSigningText(b));});
