import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
import {createRenderJobPlan} from '../src/render-jobs.js';
import {claimAuthenticatedRenderChunk,completeAuthenticatedRenderChunk,createRenderClaimRequest,createRenderCompletionAttestation,signRenderWorkerMessage} from '../src/render-worker-auth.js';
const manifest={signature:'job-sig',settings:{fps:30,rangeStart:0,rangeEnd:1},dependencies:[]};
async function hmac(){const key=await webcrypto.subtle.generateKey({name:'HMAC',hash:'SHA-256'},true,['sign','verify']);return{sign:async({bytes})=>Buffer.from(new Uint8Array(await webcrypto.subtle.sign('HMAC',key,bytes))).toString('base64'),verifySignature:async({bytes,signature})=>webcrypto.subtle.verify('HMAC',key,Buffer.from(signature,'base64'),bytes)};}
test('authenticated claim binds a specific chunk attempt to actor and key',async()=>{const auth=await hmac(),job=createRenderJobPlan(manifest,{chunkFrames:15}),request=await signRenderWorkerMessage(createRenderClaimRequest(job,{actorId:'worker-a',keyId:'key-a',issuedAt:100,nonce:'n1'}),auth),claimed=await claimAuthenticatedRenderChunk(job,request,{verifySignature:auth.verifySignature,now:101});assert.equal(claimed.chunk.id,job.chunks[0].id);assert.equal(claimed.chunk.attempts,1);assert.equal(claimed.chunk.workerId,'worker-a');assert.equal(claimed.chunk.workerKeyId,'key-a');assert.equal(claimed.chunk.claimAttestation.signature,request.signature);});
test('invalid claim signature cannot mutate render state',async()=>{const auth=await hmac(),job=createRenderJobPlan(manifest,{chunkFrames:30}),request=await signRenderWorkerMessage(createRenderClaimRequest(job,{actorId:'worker-a',keyId:'key-a'}),auth);request.signature=Buffer.from('bad').toString('base64');await assert.rejects(()=>claimAuthenticatedRenderChunk(job,request,{verifySignature:auth.verifySignature}),e=>e.code==='ERR_RENDER_WORKER_SIGNATURE');assert.equal(job.chunks[0].status,'pending');assert.equal(job.chunks[0].attempts,0);});
test('claim request is rejected after the eligible chunk state changes',async()=>{const auth=await hmac(),job=createRenderJobPlan(manifest,{chunkFrames:15}),request=await signRenderWorkerMessage(createRenderClaimRequest(job,{actorId:'worker-a',keyId:'key-a'}),auth),first=await claimAuthenticatedRenderChunk(job,request,{verifySignature:auth.verifySignature});await assert.rejects(()=>claimAuthenticatedRenderChunk(first.job,request,{verifySignature:auth.verifySignature}),e=>e.code==='ERR_RENDER_WORKER_STATE');});
test('authenticated completion requires same actor/key and verified artifact digest descriptor',async()=>{const auth=await hmac(),job=createRenderJobPlan(manifest,{chunkFrames:30}),claim=await signRenderWorkerMessage(createRenderClaimRequest(job,{actorId:'worker-a',keyId:'key-a'}),auth),claimed=await claimAuthenticatedRenderChunk(job,claim,{verifySignature:auth.verifySignature}),completion=await signRenderWorkerMessage(createRenderCompletionAttestation(claimed.job,claimed.chunk.id,{key:'seg-0',byteLength:4},{actorId:'worker-a',keyId:'key-a',artifactIntegrity:'sha256-AAAA',nonce:'n2'}),auth);let verified=0;const complete=await completeAuthenticatedRenderChunk(claimed.job,completion,{verifySignature:auth.verifySignature,verifyArtifact:async({artifact,integrity})=>{verified++;assert.equal(artifact.key,'seg-0');assert.equal(integrity,'sha256-AAAA');return true;}});assert.equal(verified,1);assert.equal(complete.status,'complete');assert.equal(complete.chunks[0].artifact.integrity,'sha256-AAAA');assert.equal(complete.chunks[0].artifact.workerAttestation.actor.id,'worker-a');});
test('validly signed completion from a different key cannot take over a claimed chunk',async()=>{const auth=await hmac(),job=createRenderJobPlan(manifest,{chunkFrames:30}),claim=await signRenderWorkerMessage(createRenderClaimRequest(job,{actorId:'worker-a',keyId:'key-a'}),auth),claimed=await claimAuthenticatedRenderChunk(job,claim,{verifySignature:auth.verifySignature}),completion=createRenderCompletionAttestation(claimed.job,claimed.chunk.id,{key:'seg-0'},{actorId:'worker-a',keyId:'key-a',artifactIntegrity:'sha256-AAAA'});completion.actor.keyId='key-b';const signed=await signRenderWorkerMessage(completion,auth);let artifactChecks=0;await assert.rejects(()=>completeAuthenticatedRenderChunk(claimed.job,signed,{verifySignature:auth.verifySignature,verifyArtifact:async()=>{artifactChecks++;return true;}}),e=>e.code==='ERR_RENDER_WORKER_OWNER');assert.equal(artifactChecks,0);});
test('artifact verification fails closed before completion state transition',async()=>{const auth=await hmac(),job=createRenderJobPlan(manifest,{chunkFrames:30}),claim=await signRenderWorkerMessage(createRenderClaimRequest(job,{actorId:'worker-a',keyId:'key-a'}),auth),claimed=await claimAuthenticatedRenderChunk(job,claim,{verifySignature:auth.verifySignature}),completion=await signRenderWorkerMessage(createRenderCompletionAttestation(claimed.job,claimed.chunk.id,{key:'seg-0'},{actorId:'worker-a',keyId:'key-a',artifactIntegrity:'0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'}),auth);await assert.rejects(()=>completeAuthenticatedRenderChunk(claimed.job,completion,{verifySignature:auth.verifySignature,verifyArtifact:async()=>false}),e=>e.code==='ERR_RENDER_ARTIFACT_INTEGRITY');assert.equal(claimed.job.chunks[0].status,'running');});
test('nonce/replay policy runs before claim mutation',async()=>{const auth=await hmac(),job=createRenderJobPlan(manifest,{chunkFrames:30}),request=await signRenderWorkerMessage(createRenderClaimRequest(job,{actorId:'worker-a',keyId:'key-a',nonce:'seen'}),auth);await assert.rejects(()=>claimAuthenticatedRenderChunk(job,request,{verifySignature:auth.verifySignature,verifyNonce:async()=>false}),e=>e.code==='ERR_RENDER_WORKER_REPLAY');assert.equal(job.chunks[0].status,'pending');});
import {releaseRenderChunk,recoverInterruptedRenderJob} from '../src/render-jobs.js';
test('release and interrupted recovery clear authenticated worker ownership metadata',async()=>{const auth=await hmac(),job=createRenderJobPlan(manifest,{chunkFrames:30}),claim=await signRenderWorkerMessage(createRenderClaimRequest(job,{actorId:'worker-a',keyId:'key-a'}),auth),claimed=await claimAuthenticatedRenderChunk(job,claim,{verifySignature:auth.verifySignature}),released=releaseRenderChunk(claimed.job,claimed.chunk.id);assert.equal(released.chunks[0].workerId,null);assert.equal(released.chunks[0].workerKeyId,null);assert.equal(released.chunks[0].claimAttestation,null);const claimedAgain=await claimAuthenticatedRenderChunk(released,await signRenderWorkerMessage(createRenderClaimRequest(released,{actorId:'worker-a',keyId:'key-a'}),auth),{verifySignature:auth.verifySignature}),recovered=recoverInterruptedRenderJob(claimedAgain.job);assert.equal(recovered.chunks[0].workerId,null);assert.equal(recovered.chunks[0].workerKeyId,null);assert.equal(recovered.chunks[0].claimAttestation,null);});
