import test from 'node:test';import assert from 'node:assert/strict';import {planStreamingMp4,writeStreamingMp4} from '../src/isobmff-stream-mux.js';
class Sink{constructor(){this.parts=[];this.bytes=0;}async write(v){const b=v instanceof Uint8Array?v:new Uint8Array(v);this.parts.push(b.slice());this.bytes+=b.length;}async close(){const o=new Uint8Array(this.bytes);let x=0;for(const p of this.parts){o.set(p,x);x+=p.length;}return o;}}
const video={id:'v',type:'video',codec:'avc1.640028',width:16,height:16,config:{description:new Uint8Array([1,100,0,40])}};
const audio={id:'a',type:'audio',codec:'mp4a.40.2',sampleRate:48000,channels:2,config:{description:new Uint8Array([0x12,0x10])}};
function u32(bytes,o){return new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(o,false);}function findBoxes(bytes,type){const marker=new TextEncoder().encode(type),out=[];for(let i=4;i<=bytes.length-marker.length;i++){let ok=true;for(let j=0;j<4;j++)if(bytes[i+j]!==marker[j]){ok=false;break;}if(ok){const offset=i-4,size=u32(bytes,offset);if(size>=8&&offset+size<=bytes.length)out.push({offset,size,dataOffset:offset+8});}}return out;}

test('streaming MP4 interleaves bounded track chunks instead of alternating every packet',()=>{const samples=[];for(let i=0;i<10;i++){samples.push({trackId:'v',dts:i*10_000,timestamp:i*10_000,duration:10_000,type:i===0?'key':'delta',byteLength:2,payload:new Uint8Array([1,i])});samples.push({trackId:'a',dts:i*10_000,timestamp:i*10_000,duration:10_000,type:'key',byteLength:1,payload:new Uint8Array([100+i])});}const layout=planStreamingMp4({tracks:[video,audio],samples},{maxChunkDuration:50_000});assert.deepEqual(layout.chunks.map(c=>[c.trackId,c.sampleCount,c.dts]),[['v',5,0],['a',5,0],['v',5,50_000],['a',5,50_000]]);assert.deepEqual(layout.samples.map(s=>s.trackId),['v','v','v','v','v','a','a','a','a','a','v','v','v','v','v','a','a','a','a','a']);const co64=findBoxes(layout.header,'co64');assert.equal(co64.length,2);const view=new DataView(layout.header.buffer,layout.header.byteOffset,layout.header.byteLength);assert.equal(view.getUint32(co64[0].dataOffset+4,false),2);assert.equal(view.getUint32(co64[1].dataOffset+4,false),2);});

test('streaming MP4 chunk options enforce byte and sample bounds in the final layout',()=>{const samples=Array.from({length:7},(_,i)=>({trackId:'v',dts:i*1000,timestamp:i*1000,duration:1000,type:i?'delta':'key',byteLength:100,payload:new Uint8Array(100)}));const layout=planStreamingMp4({tracks:[video],samples},{maxChunkDuration:100_000,maxChunkBytes:250,maxSamplesPerChunk:4});assert.deepEqual(layout.chunks.map(c=>c.sampleCount),[2,2,2,1]);assert.deepEqual(layout.chunks.map(c=>c.byteLength),[200,200,200,100]);});

test('streaming MP4 writes planned payload order while payloadReader retains original sample identity',async()=>{const samples=[];for(let i=0;i<4;i++){samples.push({trackId:'v',dts:i*10_000,timestamp:i*10_000,duration:10_000,type:i?'delta':'key',byteLength:2,payload:new Uint8Array([1,i])});samples.push({trackId:'a',dts:i*10_000,timestamp:i*10_000,duration:10_000,type:'key',byteLength:1,payload:new Uint8Array([100+i])});}const stripped=samples.map(({payload,...sample})=>sample),sink=new Sink(),seen=[];const result=await writeStreamingMp4({tracks:[video,audio],samples:stripped},sink,{maxChunkDuration:40_000,payloadReader:async(sample)=>{seen.push(sample._index);return samples[sample._index].payload;},close:false});assert.deepEqual(seen,[0,2,4,6,1,3,5,7]);assert.equal(result.bytesWritten,result.byteLength);for(const sample of result.samples){const payload=samples[sample._index].payload;assert.equal(sample.byteLength,payload.byteLength);} });

test('streaming MP4 preserves signed composition offsets after chunk planning',()=>{const layout=planStreamingMp4({tracks:[video],samples:[{trackId:'v',dts:40_000,timestamp:0,duration:33_333,type:'key',byteLength:1,payload:new Uint8Array([1])},{trackId:'v',dts:73_333,timestamp:80_000,duration:33_333,type:'delta',byteLength:1,payload:new Uint8Array([2])}]});const text=new TextDecoder('latin1').decode(layout.header),pos=text.indexOf('ctts');assert.ok(pos>0);assert.equal(layout.header[pos+4],1);const view=new DataView(layout.header.buffer,layout.header.byteOffset,layout.header.byteLength);assert.equal(view.getInt32(pos+16,false),-40_000);});
