import test from 'node:test';import assert from 'node:assert/strict';import{planStreamingMp4,writeStreamingMp4}from'../src/isobmff-stream-mux.js';
class Sink{constructor(){this.parts=[];this.bytes=0;}async write(v){const b=v instanceof Uint8Array?v:new Uint8Array(v);this.parts.push(b.slice());this.bytes+=b.length;}async close(){const o=new Uint8Array(this.bytes);let x=0;for(const p of this.parts){o.set(p,x);x+=p.length;}return o;}}
const video={id:'v',type:'video',codec:'avc1.640028',width:16,height:16,config:{description:new Uint8Array([1,100,0,40])}};
const audio={id:'a',type:'audio',codec:'mp4a.40.2',sampleRate:48000,channels:2,config:{description:new Uint8Array([0x12,0x10])}};
const samples=[{trackId:'v',dts:0,timestamp:0,duration:33333,type:'key',byteLength:4,payload:new Uint8Array([1,2,3,4])},{trackId:'a',dts:0,timestamp:0,duration:21333,type:'key',byteLength:3,payload:new Uint8Array([9,8,7])},{trackId:'v',dts:33333,timestamp:40000,duration:33333,type:'delta',byteLength:2,payload:new Uint8Array([5,6])}];
function typeAt(bytes,o){return String.fromCharCode(...bytes.slice(o+4,o+8));}
function u32(bytes,o){return new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(o,false);}
test('streaming MP4 precomputes fast-start metadata and exact sample offsets',()=>{const layout=planStreamingMp4({tracks:[video,audio],samples});assert.equal(typeAt(layout.header,0),'ftyp');const ftypSize=u32(layout.header,0);assert.equal(typeAt(layout.header,ftypSize),'moov');const moovSize=u32(layout.header,ftypSize),mdat=ftypSize+moovSize;assert.equal(typeAt(layout.header,mdat),'mdat');assert.equal(layout.samples[0].offset,layout.header.length);assert.equal(layout.samples.reduce((n,s)=>n+s.byteLength,0),9);assert.ok(new TextDecoder('latin1').decode(layout.header).includes('co64'));assert.ok(new TextDecoder('latin1').decode(layout.header).includes('ctts'));});
test('streaming MP4 writes each payload directly without collecting the file',async()=>{const stripped=samples.map(({payload,...sample})=>sample),payloads=new Map(samples.map((s,i)=>[`${s.trackId}:${s.sequence??i}`,s.payload])),sink=new Sink(),seen=[];const result=await writeStreamingMp4({tracks:[video,audio],samples:stripped},sink,{payloadReader:async(sample)=>{seen.push(sample._index);return samples[sample._index].payload;}});assert.equal(result.bytesWritten,result.byteLength);assert.equal(seen.length,3);const bytes=await sink.close();for(const sample of result.samples){assert.deepEqual([...bytes.slice(sample.offset,sample.offset+sample.byteLength)],[...samples[sample._index].payload]);}assert.equal(typeAt(bytes,0),'ftyp');});

test('streaming MP4 preserves signed composition offsets for reordered video',()=>{const layout=planStreamingMp4({tracks:[video],samples:[{trackId:'v',dts:40000,timestamp:0,duration:33333,type:'key',byteLength:1,payload:new Uint8Array([1])},{trackId:'v',dts:73333,timestamp:80000,duration:33333,type:'delta',byteLength:1,payload:new Uint8Array([2])}]});const text=new TextDecoder('latin1').decode(layout.header),pos=text.indexOf('ctts');assert.ok(pos>0);const version=layout.header[pos+4];assert.equal(version,1);const view=new DataView(layout.header.buffer,layout.header.byteOffset,layout.header.byteLength),firstOffset=view.getInt32(pos+16,false);assert.equal(firstOffset,-40000);});
import { parseTkhdRotation, parseVideoSampleMetadata } from '../src/isobmff-metadata.js';
function findBox(bytes,type,start=0){const marker=new TextEncoder().encode(type);for(let i=Math.max(4,start);i<=bytes.length-marker.length;i++){let ok=true;for(let j=0;j<marker.length;j++)if(bytes[i+j]!==marker[j]){ok=false;break;}if(ok){const offset=i-4,size=u32(bytes,offset);if(size>=8&&offset+size<=bytes.length)return{type,offset,size,dataOffset:offset+8,dataSize:size-8,end:offset+size};}}return null;}
test('streaming MP4 preserves rotation, aspect, color and HDR presentation metadata',()=>{const enriched={...video,rotation:90,pixelAspectRatio:{hSpacing:4,vSpacing:3},colorSpace:{codes:{primaries:9,transfer:16,matrix:9},fullRange:false},contentLightLevel:{maxCLL:1000,maxFALL:400},masteringDisplay:{primaries:[34000,16000,13250,34500,7500,3000],whitePoint:[15635,16450],maxLuminance:10000000,minLuminance:50}};const layout=planStreamingMp4({tracks:[enriched],samples:[samples[0]]}),tkhd=findBox(layout.header,'tkhd'),nested=['pasp','colr','clli','mdcv'].map((type)=>findBox(layout.header,type));assert.equal(parseTkhdRotation(layout.header,tkhd),90);const metadata=parseVideoSampleMetadata(layout.header,nested);assert.deepEqual(metadata.pixelAspectRatio,{hSpacing:4,vSpacing:3});assert.equal(metadata.colorSpace.codes.primaries,9);assert.equal(metadata.colorSpace.codes.transfer,16);assert.equal(metadata.contentLightLevel.maxCLL,1000);assert.equal(metadata.masteringDisplay.maxLuminance,10000000);});
test('streaming MP4 preserves delayed track start with leading empty edit',()=>{const layout=planStreamingMp4({tracks:[video],samples:[{trackId:'v',dts:1_000_000,timestamp:1_000_000,duration:40_000,type:'key',byteLength:1,payload:new Uint8Array([1])}]}),elst=findBox(layout.header,'elst');assert.ok(elst);const marker=elst.offset+4,view=new DataView(layout.header.buffer,layout.header.byteOffset,layout.header.byteLength);assert.equal(layout.header[marker+4],1);assert.equal(view.getUint32(marker+8,false),2);assert.equal(Number(view.getBigUint64(marker+12,false)),1_000_000);assert.equal(view.getBigInt64(marker+20,false),-1n);assert.equal(Number(view.getBigUint64(marker+32,false)),40_000);});
test('streaming MP4 groups consecutive same-track payloads into fewer chunk offsets',()=>{const layout=planStreamingMp4({tracks:[video],samples:[{trackId:'v',dts:0,timestamp:0,duration:1000,type:'key',byteLength:1,payload:new Uint8Array([1])},{trackId:'v',dts:1000,timestamp:1000,duration:1000,type:'delta',byteLength:1,payload:new Uint8Array([2])},{trackId:'v',dts:2000,timestamp:2000,duration:1000,type:'delta',byteLength:1,payload:new Uint8Array([3])}]}),co=findBox(layout.header,'co64'),sc=findBox(layout.header,'stsc'),view=new DataView(layout.header.buffer,layout.header.byteOffset,layout.header.byteLength);assert.equal(view.getUint32(co.dataOffset+4,false),1);assert.equal(view.getUint32(sc.dataOffset+4,false),1);assert.equal(view.getUint32(sc.dataOffset+12,false),3);});
