import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac,timingSafeEqual} from 'node:crypto';
import {createTrustRegistry,enrollTrustActor,enrollTrustKey,hasConsumedTrustNonce} from '../src/trust-registry.js';
import {TrustedTransitionSession} from '../src/trusted-transition.js';
const secret='atomic-secret';
function registry(){let r=createTrustRegistry();r=enrollTrustActor(r,{actorId:'alice',now:100});return enrollTrustKey(r,{actorId:'alice',keyId:'k1',purposes:['collaboration'],verification:{ref:'alice'},now:100});}
function context(nonce,{bad=false}={}){const statement={schema:'media.operation-batch.v1',actor:{id:'alice',keyId:'k1'},issuedAt:900,nonce},bytes=new TextEncoder().encode(JSON.stringify(statement)),signature=createHmac('sha256',secret).update(bytes).digest('hex');return{statement,actor:statement.actor,bytes,signature:bad?'00'.repeat(32):signature};}
const verify=async({bytes,signature,key})=>{if(key.verification.ref!=='alice')return false;const expected=Buffer.from(createHmac('sha256',secret).update(bytes).digest('hex'),'hex'),actual=Buffer.from(String(signature),'hex');return expected.length===actual.length&&timingSafeEqual(expected,actual);};
const policy={purpose:'collaboration',schema:'media.operation-batch.v1',maxAgeMs:5000};
test('trusted transition persists replay and application state in one callback before publishing',async()=>{const writes=[],session=new TrustedTransitionSession({trustRegistry:registry(),state:{value:1},verifySignature:verify,policy,now:()=>1000,persist:async(value,meta)=>writes.push({value,meta})});const result=await session.process(context('n1'),(state)=>({state:{value:state.value+1},result:{status:'applied'}}));assert.equal(result.result.status,'applied');assert.equal(writes.length,1);assert.equal(writes[0].value.state.value,2);assert.equal(Object.keys(writes[0].value.trustRegistry.nonces).length,1);assert.equal(session.snapshot().state.value,2);});
test('signature failure invokes neither transition nor persistence',async()=>{let transitions=0,writes=0;const session=new TrustedTransitionSession({trustRegistry:registry(),state:{value:1},verifySignature:verify,policy,now:()=>1000,persist:async()=>{writes++;}});const result=await session.process(context('bad',{bad:true}),()=>{transitions++;return{value:2};});assert.equal(result.verified,false);assert.equal(transitions,0);assert.equal(writes,0);assert.equal(session.snapshot().state.value,1);});
test('transition failure does not consume replay state',async()=>{const session=new TrustedTransitionSession({trustRegistry:registry(),state:{value:1},verifySignature:verify,policy,now:()=>1000,persist:async()=>{throw new Error('should not persist');}});await assert.rejects(()=>session.process(context('transition-fail'),()=>{throw new Error('invalid graph');}),/invalid graph/);assert.equal(hasConsumedTrustNonce(session.snapshot().trustRegistry,{actorId:'alice',keyId:'k1',purpose:'collaboration',nonce:'transition-fail'}),false);});
test('atomic persistence failure publishes neither application nor nonce state',async()=>{const session=new TrustedTransitionSession({trustRegistry:registry(),state:{value:1},verifySignature:verify,policy,now:()=>1000,persist:async()=>{throw new Error('transaction aborted');}});await assert.rejects(()=>session.process(context('persist-fail'),(state)=>({value:state.value+1})),/transaction aborted/);const snap=session.snapshot();assert.equal(snap.state.value,1);assert.equal(hasConsumedTrustNonce(snap.trustRegistry,{actorId:'alice',keyId:'k1',purpose:'collaboration',nonce:'persist-fail'}),false);});
test('unchanged conflict state can atomically consume the authenticated request nonce',async()=>{const writes=[],session=new TrustedTransitionSession({trustRegistry:registry(),state:{head:3},verifySignature:verify,policy,now:()=>1000,persist:async(value)=>writes.push(value)});const result=await session.process(context('conflict'),(state)=>({state,result:{status:'conflict'}}));assert.equal(result.result.status,'conflict');assert.equal(result.state.head,3);assert.equal(writes.length,1);assert.equal(Object.keys(result.trustRegistry.nonces).length,1);});
test('duplicate concurrent messages serialize so only one transition runs',async()=>{let release;const gate=new Promise((resolve)=>{release=resolve;}),events=[],session=new TrustedTransitionSession({trustRegistry:registry(),state:{value:0},verifySignature:async(context)=>{await gate;return verify(context);},policy,now:()=>1000,persist:async()=>{}}),ctx=context('race'),first=session.process(ctx,(state)=>{events.push('first');return{value:state.value+1};}),second=session.process(ctx,(state)=>{events.push('second');return{value:state.value+1};});release();assert.equal((await first).state.value,1);await assert.rejects(()=>second,/already been consumed/);assert.deepEqual(events,['first']);});
