import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac,timingSafeEqual} from 'node:crypto';
import {createTrustRegistry,enrollTrustActor,enrollTrustKey,revokeTrustActor,revokeTrustKey,resolveTrustKey,TrustRegistrySession,operationBatchTrustVerifier,renderWorkerTrustVerifier,hasConsumedTrustNonce,prepareTrustedMessageVerification} from '../src/trust-registry.js';

const secrets=new Map([['alice-key','alpha-secret'],['worker-key','worker-secret']]);
const sign=(secret,bytes)=>createHmac('sha256',secret).update(bytes).digest('hex');
const verifySignature=async({bytes,signature,key})=>{const expected=Buffer.from(sign(secrets.get(key.verification.secretRef),bytes),'hex'),actual=Buffer.from(String(signature),'hex');return expected.length===actual.length&&timingSafeEqual(expected,actual);};
function bytesFor(statement){return new TextEncoder().encode(JSON.stringify(statement));}
function ctx(statement,secretRef){const bytes=bytesFor(statement);return{bytes,text:new TextDecoder().decode(bytes),statement,actor:statement.actor,signature:sign(secrets.get(secretRef),bytes)};}
function registry(){let value=createTrustRegistry({metadata:{project:'p'}});value=enrollTrustActor(value,{actorId:'alice',now:100});value=enrollTrustKey(value,{actorId:'alice',keyId:'k1',purposes:['collaboration'],verification:{secretRef:'alice-key'},now:100,notBefore:100,expiresAt:10_000});value=enrollTrustActor(value,{actorId:'worker',now:100});value=enrollTrustKey(value,{actorId:'worker',keyId:'wk1',purposes:['render-worker'],verification:{secretRef:'worker-key'},now:100});return value;}

test('trust registry enrolls scoped keys and never reuses revoked identities',()=>{let value=registry();assert.equal(resolveTrustKey(value,{actorId:'alice',keyId:'k1',purpose:'collaboration',at:500}).key.id,'k1');assert.throws(()=>resolveTrustKey(value,{actorId:'alice',keyId:'k1',purpose:'render-worker',at:500}),/not authorized/);value=revokeTrustKey(value,'alice','k1',{now:600,reason:'rotate'});assert.throws(()=>resolveTrustKey(value,{actorId:'alice',keyId:'k1',purpose:'collaboration',at:600}),/revoked/);assert.throws(()=>enrollTrustKey(value,{actorId:'alice',keyId:'k1',purposes:['collaboration'],verification:{secretRef:'alice-key'}}),/already exists/);value=revokeTrustActor(value,'worker',{now:700});assert.throws(()=>resolveTrustKey(value,{actorId:'worker',keyId:'wk1',purpose:'render-worker',at:700}),/revoked/);});

test('operation batch verifier persists nonce only after signature success',async()=>{const writes=[];const session=new TrustRegistrySession({registry:registry(),persist:async(next,context)=>writes.push({next,context}),verifySignature,now:()=>1000,maxAgeMs:5000});const verify=operationBatchTrustVerifier(session),statement={schema:'media.operation-batch.v1',projectId:'p',actor:{id:'alice',keyId:'k1'},issuedAt:900,nonce:'n1'};const bad=ctx(statement,'alice-key');bad.signature='00'.repeat(32);assert.equal(await verify(bad),false);assert.equal(writes.length,0);assert.equal(hasConsumedTrustNonce(session.snapshot(),{actorId:'alice',keyId:'k1',purpose:'collaboration',nonce:'n1'}),false);assert.equal(await verify(ctx(statement,'alice-key')),true);assert.equal(writes.length,1);assert.equal(writes[0].context.type,'nonce.consume');assert.equal(hasConsumedTrustNonce(session.snapshot(),{actorId:'alice',keyId:'k1',purpose:'collaboration',nonce:'n1'}),true);});

test('replayed nonce is rejected before signature verifier runs again',async()=>{let calls=0;const session=new TrustRegistrySession({registry:registry(),persist:async()=>{},verifySignature:async(context)=>{calls++;return verifySignature(context);},now:()=>1000});const verify=operationBatchTrustVerifier(session),statement={schema:'media.operation-batch.v1',actor:{id:'alice',keyId:'k1'},issuedAt:900,nonce:'same'};assert.equal(await verify(ctx(statement,'alice-key')),true);await assert.rejects(()=>verify(ctx(statement,'alice-key')),/already been consumed/);assert.equal(calls,1);});

test('concurrent duplicate nonces serialize so only one verification succeeds',async()=>{let release;const gate=new Promise((resolve)=>{release=resolve;});let calls=0;const session=new TrustRegistrySession({registry:registry(),persist:async()=>{},verifySignature:async(context)=>{calls++;await gate;return verifySignature(context);},now:()=>1000});const verify=renderWorkerTrustVerifier(session),statement={schema:'media.render-worker.v1',type:'claim',actor:{id:'worker',keyId:'wk1'},issuedAt:950,nonce:'race'},context=ctx(statement,'worker-key'),first=verify(context),second=verify(context);release();assert.equal(await first,true);await assert.rejects(()=>second,/already been consumed/);assert.equal(calls,1);});

test('persistence failure does not advance in-memory replay state',async()=>{const base=registry(),session=new TrustRegistrySession({registry:base,persist:async()=>{throw new Error('disk unavailable');},verifySignature,now:()=>1000}),verify=operationBatchTrustVerifier(session),statement={schema:'media.operation-batch.v1',actor:{id:'alice',keyId:'k1'},issuedAt:900,nonce:'persist-fail'};await assert.rejects(()=>verify(ctx(statement,'alice-key')),/disk unavailable/);assert.equal(hasConsumedTrustNonce(session.snapshot(),{actorId:'alice',keyId:'k1',purpose:'collaboration',nonce:'persist-fail'}),false);});

test('registry session persists enrollment and revocation before publishing state',async()=>{const events=[];const session=new TrustRegistrySession({registry:createTrustRegistry(),persist:async(next,context)=>events.push({revision:next.revision,context}),verifySignature:async()=>true,now:()=>1000});await session.enrollActor({actorId:'a',now:1000});await session.enrollKey({actorId:'a',keyId:'k',purposes:['collaboration','render-worker'],verification:{ref:'public-key'},now:1000});await session.revokeKey('a','k',{now:1100});assert.deepEqual(events.map((event)=>event.context.type),['actor.enroll','key.enroll','key.revoke']);assert.equal(session.snapshot().actors.a.keys.k.status,'revoked');});

test('protocol wrappers enforce domain separation and freshness/key validity',async()=>{const session=new TrustRegistrySession({registry:registry(),persist:async()=>{},verifySignature,now:()=>1000,maxAgeMs:100,maxFutureSkewMs:5}),operationVerify=operationBatchTrustVerifier(session),renderVerify=renderWorkerTrustVerifier(session);await assert.rejects(()=>operationVerify(ctx({schema:'media.render-worker.v1',type:'claim',actor:{id:'alice',keyId:'k1'},issuedAt:950,nonce:'x'},'alice-key')),/schema mismatch/);await assert.rejects(()=>renderVerify(ctx({schema:'media.render-worker.v1',type:'cancel',actor:{id:'worker',keyId:'wk1'},issuedAt:950,nonce:'x'},'worker-key')),/type is not allowed/);await assert.rejects(()=>operationVerify(ctx({schema:'media.operation-batch.v1',actor:{id:'alice',keyId:'k1'},issuedAt:800,nonce:'old'},'alice-key')),/freshness window/);await assert.rejects(()=>operationVerify(ctx({schema:'media.operation-batch.v1',actor:{id:'alice',keyId:'k1'},issuedAt:1006,nonce:'future'},'alice-key')),/freshness window/);});


test('prepared verification returns a next replay registry without persisting or mutating the input',async()=>{const base=registry(),statement={schema:'media.operation-batch.v1',actor:{id:'alice',keyId:'k1'},issuedAt:900,nonce:'atomic-1'},prepared=await prepareTrustedMessageVerification(base,ctx(statement,'alice-key'),{purpose:'collaboration',schema:'media.operation-batch.v1',verifySignature,now:1000,maxAgeMs:5000});assert.equal(prepared.verified,true);assert.equal(base.revision,4);assert.equal(prepared.registry.revision,5);assert.equal(hasConsumedTrustNonce(base,{actorId:'alice',keyId:'k1',purpose:'collaboration',nonce:'atomic-1'}),false);assert.equal(hasConsumedTrustNonce(prepared.registry,{actorId:'alice',keyId:'k1',purpose:'collaboration',nonce:'atomic-1'}),true);assert.equal(prepared.actor.id,'alice');assert.equal(prepared.key.id,'k1');});
