import assert from 'node:assert/strict';
import test from 'node:test';
import { demuxWebm, readWebmFrame } from '../src/webm-demux.js';
import { encodeEbmlSize, encodeEbmlVintValue, muxWebm } from '../src/webm-mux.js';

test('encodes EBML sizes and track-number vints',()=>{assert.deepEqual([...encodeEbmlSize(5)],[0x85]);assert.deepEqual([...encodeEbmlVintValue(1)],[0x81]);assert.equal(encodeEbmlSize(200).length,2);});
test('muxes VP9 samples into a WebM file that the demuxer can read back',()=>{const first=new Uint8Array([1,2,3]).buffer,second=new Uint8Array([4,5]).buffer;const plan={container:'webm',tracks:[{id:'v',type:'video',codec:'vp09',timescale:1_000_000,config:{width:320,height:180}}],samples:[{trackId:'v',timestamp:0,duration:1_000_000,sequence:0,keyframe:true,byteLength:3,payload:first},{trackId:'v',timestamp:1_000_000,duration:1_000_000,sequence:1,keyframe:false,byteLength:2,payload:second}]};const file=muxWebm(plan);const parsed=demuxWebm(file);assert.equal(parsed.tracks[0].codec,'vp09');assert.equal(parsed.tracks[0].width,320);assert.equal(parsed.duration,2);assert.deepEqual(parsed.chunks.map((chunk)=>chunk.type),['key','delta']);assert.deepEqual(parsed.chunks.map((chunk)=>chunk.timestamp),[0,1_000_000]);assert.deepEqual([...readWebmFrame(file,parsed.chunks[0])],[1,2,3]);assert.deepEqual([...readWebmFrame(file,parsed.chunks[1])],[4,5]);});
test('muxes Opus metadata and payload beside video',()=>{const opusPrivate=new Uint8Array([79,112,117,115,72,101,97,100]).buffer;const plan={container:'webm',tracks:[{id:'v',type:'video',codec:'vp09',config:{width:64,height:64}},{id:'a',type:'audio',codec:'opus',config:{sampleRate:48000,channels:2,description:opusPrivate}}],samples:[{trackId:'v',trackOrder:0,timestamp:0,duration:1_000_000,sequence:0,keyframe:true,payload:new Uint8Array([7]).buffer},{trackId:'a',trackOrder:1,timestamp:0,duration:20_000,sequence:0,keyframe:true,payload:new Uint8Array([8,9]).buffer}]};const file=muxWebm(plan);const parsed=demuxWebm(file);const audio=parsed.tracks.find((track)=>track.type==='audio');assert.equal(audio.codec,'opus');assert.equal(audio.sampleRate,48000);assert.equal(audio.channels,2);assert.deepEqual([...new Uint8Array(audio.description)], [...new Uint8Array(opusPrivate)]);assert.equal(parsed.chunks.length,2);});
test('rejects codecs outside the WebM profile',()=>assert.throws(()=>muxWebm({container:'webm',tracks:[{id:'v',type:'video',codec:'avc1.640028',config:{width:16,height:16}}],samples:[]}),/not supported/));
