import assert from 'node:assert/strict';
import test from 'node:test';
import { createGraph } from '../../../packages/core/src/graph.js';
import { applyTransaction } from '../../../packages/core/src/operations.js';
import { createAgentPlan } from '../../../packages/core/src/agent-plan.js';
import { createAgentWorkflow } from '../../../packages/core/src/agent-workflow.js';
import { createPlannerProvider } from '../../../packages/core/src/providers.js';
import { ModelRouter } from '../../../packages/core/src/model-router.js';
import { AgentProposalSession } from '../agent-proposal-session.js';
import { AgentWorkflowSession } from '../agent-workflow-session.js';
import { AgentDelegationSession } from '../agent-delegation-session.js';

function noopProvider(){return createPlannerProvider({id:'noop',plan:async()=>({summary:'noop',operations:[]})});}

test('delegation executes workflow into review without committing generated bytes', async()=>{
  let graph=createGraph('Film');let commits=0;
  const router=new ModelRouter().register({id:'image',operations:['generate-image'],invoke:async()=>({artifact:{name:'Frame.png',mimeType:'image/png'},payload:new Uint8Array([1,2,3])})});
  const proposal=new AgentProposalSession({provider:noopProvider(),getGraph:()=>graph,commit:async()=>{commits++;}});
  const execution=new AgentWorkflowSession({router,getGraph:()=>graph});
  const session=new AgentDelegationSession({proposalSession:proposal,workflowSession:execution});
  const plan=createAgentPlan(graph,{intent:'generate frame',providerId:'mock',operations:[]});
  const workflow=createAgentWorkflow(plan,[{id:'generate',kind:'generate-media',payload:{operation:'generate-image'}}]);
  const state=await session.execute(workflow);
  assert.equal(state.status,'pending');assert.equal(state.workflow.assetWriteCount,1);assert.equal(commits,0);assert.equal(Object.values(graph.nodes).some(n=>n.kind==='asset'),false);
});

test('delegation apply commits reviewed operations and matching generated asset bytes atomically', async()=>{
  let graph=createGraph('Film');let commitOptions;
  const router=new ModelRouter().register({id:'image',operations:['generate-image'],invoke:async()=>({artifact:{name:'Frame.png',mimeType:'image/png'},payload:new Uint8Array([1,2])})});
  const proposal=new AgentProposalSession({provider:noopProvider(),getGraph:()=>graph,commit:async(label,operations,metadata,options)=>{commitOptions=options;graph=applyTransaction(graph,{id:'tx',label,operations,metadata,createdAt:'now'});}});
  const session=new AgentDelegationSession({proposalSession:proposal,workflowSession:new AgentWorkflowSession({router,getGraph:()=>graph})});
  const plan=createAgentPlan(graph,{intent:'generate frame',providerId:'mock',operations:[]});
  const workflow=createAgentWorkflow(plan,[{id:'generate',kind:'generate-media',payload:{operation:'generate-image'}}]);
  await session.execute(workflow);await session.apply();
  const asset=Object.values(graph.nodes).find(n=>n.kind==='asset');assert.ok(asset);assert.deepEqual(commitOptions.persistContext.assetWrites.map(w=>w.assetId),[asset.id]);assert.equal(session.snapshot().status,'idle');
});

test('delegation discard drops pending payloads without graph mutation', async()=>{
  const graph=createGraph('Film');
  const router=new ModelRouter().register({id:'image',operations:['generate-image'],invoke:async()=>({artifact:{name:'Frame.png',mimeType:'image/png'},payload:new Uint8Array([1])})});
  const proposal=new AgentProposalSession({provider:noopProvider(),getGraph:()=>graph,commit:async()=>{throw new Error('must not commit');}});
  const session=new AgentDelegationSession({proposalSession:proposal,workflowSession:new AgentWorkflowSession({router,getGraph:()=>graph})});
  const plan=createAgentPlan(graph,{intent:'generate',providerId:'mock',operations:[]});const workflow=createAgentWorkflow(plan,[{id:'g',kind:'generate-media',payload:{operation:'generate-image'}}]);
  await session.execute(workflow);const dropped=session.discard();assert.equal(dropped.workflow.persistContext.assetWrites.length,1);assert.equal(session.snapshot().status,'idle');assert.equal(Object.values(graph.nodes).some(n=>n.kind==='asset'),false);
});

test('delegation keeps workflow payloads pending when durable apply fails so retry is possible', async()=>{
  const graph=createGraph('Film');let attempts=0;
  const router=new ModelRouter().register({id:'image',operations:['generate-image'],invoke:async()=>({artifact:{name:'Frame.png',mimeType:'image/png'},payload:new Uint8Array([1])})});
  const proposal=new AgentProposalSession({provider:noopProvider(),getGraph:()=>graph,commit:async()=>{attempts++;throw new Error('quota');}});
  const session=new AgentDelegationSession({proposalSession:proposal,workflowSession:new AgentWorkflowSession({router,getGraph:()=>graph})});
  const plan=createAgentPlan(graph,{intent:'generate',providerId:'mock',operations:[]});const workflow=createAgentWorkflow(plan,[{id:'g',kind:'generate-media',payload:{operation:'generate-image'}}]);
  await session.execute(workflow);await assert.rejects(()=>session.apply(),/quota/);assert.equal(attempts,1);assert.equal(session.snapshot().status,'pending');assert.equal(session.snapshot().workflow.assetWriteCount,1);
});
