import test from 'node:test';
import assert from 'node:assert/strict';
import { CmafWebCodecsSession } from '../cmaf-webcodecs-session.js';
class FakeDecoder{constructor({output,error}){this.output=output;this.error=error;this.decodeQueueSize=0;this.decoded=[];this.flushes=0;this.closed=false;}configure(config){this.config=config;}decode(chunk){this.decoded.push(chunk);this.decodeQueueSize++;this.output({timestamp:chunk.timestamp,kind:chunk.kind});}async flush(){this.flushes++;this.decodeQueueSize=0;}close(){this.closed=true;}}
const chunkFactory=async(track,descriptor,bytes)=>({kind:track.type,timestamp:descriptor.presentationTimestamp,duration:descriptor.duration,data:[...bytes]});
const configFactory=async(track)=>({codec:track.codec});
function fixture(){const tracks=[{id:'video:1',type:'video',codec:'avc1.640028'},{id:'audio:2',type:'audio',codec:'mp4a.40.2'}],chunks=[{trackId:'video:1',type:'key',presentationTimestamp:1000,duration:40000,byteLength:2,sequence:0},{trackId:'audio:2',type:'key',presentationTimestamp:1000,duration:20000,byteLength:3,sequence:0}],record={id:'frag:0',tracks,chunks},reads=[];const cmaf={async readChunk(chunk){reads.push(chunk.trackId);return chunk.trackId==='video:1'?Uint8Array.from([1,2]):Uint8Array.from([3,4,5]);}};return{record,cmaf,reads};}
test('persistent CMAF decoder submits indexed video and audio samples immediately',async()=>{const f=fixture(),video=[],audio=[],submitted=[],session=new CmafWebCodecsSession({VideoDecoderCtor:FakeDecoder,AudioDecoderCtor:FakeDecoder,decoderConfigFactory:configFactory,chunkFactory,onVideoFrame:(frame,ctx)=>video.push([frame,ctx.track.id]),onAudioData:(data,ctx)=>audio.push([data,ctx.track.id]),onSubmitted:(p)=>submitted.push(p.track.id)});const result=await session.accept({...f,variant:{id:'v'}});assert.equal(result.submitted,2);assert.deepEqual(f.reads,['video:1','audio:2']);assert.deepEqual(submitted,['video:1','audio:2']);assert.equal(video[0][0].timestamp,1000);assert.equal(audio[0][0].timestamp,1000);assert.deepEqual(session.stats(),{records:1,samples:2,videoSamples:1,audioSamples:1,decoderFlushes:0,variantResets:0,decoders:2,variants:1});});
test('decoder instances persist across fragment records and apply queue backpressure',async()=>{const f=fixture(),session=new CmafWebCodecsSession({maxQueue:1,VideoDecoderCtor:FakeDecoder,AudioDecoderCtor:FakeDecoder,decoderConfigFactory:configFactory,chunkFactory});await session.accept({...f,variant:{id:'v'}});const videoRecord={id:'frag:1',tracks:[f.record.tracks[0]],chunks:[{...f.record.chunks[0],sequence:1,presentationTimestamp:41000}]};await session.accept({record:videoRecord,cmaf:f.cmaf,variant:{id:'v'}});assert.equal(session.stats().decoders,2);assert.equal(session.stats().decoderFlushes,1);});
test('changing CMAF initialization for the same variant closes stale decoders',async()=>{const f=fixture(),session=new CmafWebCodecsSession({VideoDecoderCtor:FakeDecoder,AudioDecoderCtor:FakeDecoder,decoderConfigFactory:configFactory,chunkFactory});await session.accept({...f,variant:{id:'v'}});const states=[...session.decoders.values()].map((s)=>s.decoder);await session.accept({record:f.record,cmaf:{async readChunk(c){return f.cmaf.readChunk(c);}},variant:{id:'v'}});assert.equal(states.every((decoder)=>decoder.closed),true);assert.equal(session.stats().variantResets,1);assert.equal(session.stats().decoders,2);});
test('encrypted samples are rejected before WebCodecs submission',async()=>{const f=fixture();f.record={...f.record,chunks:[{...f.record.chunks[0],encryption:{scheme:'cenc'}}]};const session=new CmafWebCodecsSession({VideoDecoderCtor:FakeDecoder,AudioDecoderCtor:FakeDecoder,decoderConfigFactory:configFactory,chunkFactory});await assert.rejects(()=>session.accept({...f,variant:{id:'v'}}),/must be decrypted/);assert.equal(session.stats().samples,0);});
test('abort prevents additional low-latency sample submission',async()=>{const f=fixture(),controller=new AbortController();controller.abort();const session=new CmafWebCodecsSession({VideoDecoderCtor:FakeDecoder,AudioDecoderCtor:FakeDecoder,decoderConfigFactory:configFactory,chunkFactory});await assert.rejects(()=>session.accept({...f,variant:{id:'v'},signal:controller.signal}),error=>error?.name==='AbortError');});
