import test from 'node:test';
import assert from 'node:assert/strict';
import {createCollaborationResolutionDraft,setCollaborationResolutionDecision} from '../../../packages/core/src/collaboration-resolution-decisions.js';
import {applyCollaborationResolutionDecision,decisionFromCollaborationControl,renderCollaborationResolutionDecisionPanel} from '../collaboration-resolution-view.js';

function model({complete=true}={}){
  const remote={sequence:3,transactionId:'remote-tx',label:'Remote <script>alert(1)</script>',operationIndex:0,operation:{type:'node.update',scope:'node',id:'node-1',name:'Node',fields:['props:title'],summary:'Update <img src=x onerror=boom> · props:title'}};
  return{schema:'media.collaboration-resolution.v1',requestId:'req',status:'conflict',head:{sequence:4,checksum:'head',transactionId:'local'},actor:{id:'alice<&',keyId:'key"1'},rows:[{id:'1:0|3:0',local:{sequence:1,transactionId:'local-1',label:'Local <b>edit</b>',operationIndex:0,operation:{type:'node.update',summary:'Update Local & title'}},remote,resources:[{local:{label:'Node Local · property title'},remote:{label:'Node Remote · property title'}}]}],conflictsTruncated:complete?0:2,complete,requiresRefresh:true,requiresResign:true,allowsAutomaticMerge:false};
}

test('resolution renderer escapes labels and emits only explicit allowed decision controls',()=>{const m=model(),draft=createCollaborationResolutionDraft(m),html=renderCollaborationResolutionDecisionPanel({model:m,draft});assert.equal(html.includes('<script>'),false);assert.equal(html.includes('<img'),false);assert.match(html,/Remote &lt;script&gt;alert\(1\)&lt;\/script&gt;/);assert.match(html,/Local &lt;b&gt;edit&lt;\/b&gt;/);assert.equal((html.match(/data-collaboration-decision=/g)??[]).length,3);for(const choice of ['keep-local','reapply-remote','manual'])assert.match(html,new RegExp(`data-collaboration-decision="${choice}"`));assert.equal(html.includes('auto-merge'),false);});

test('renderer keeps final action disabled until every complete conflict group has a decision',()=>{const m=model(),draft=createCollaborationResolutionDraft(m),before=renderCollaborationResolutionDecisionPanel({model:m,draft});assert.match(before,/data-collaboration-resolution-finalize disabled/);const next=setCollaborationResolutionDecision(draft,draft.groups[0].id,'keep-local'),after=renderCollaborationResolutionDecisionPanel({model:m,draft:next});assert.match(after,/data-collaboration-resolution-finalize >Review resolution intent/);assert.match(after,/data-collaboration-decision="keep-local"[^>]*aria-pressed="true"/);});

test('renderer blocks finalization and displays a warning for truncated conflict detail',()=>{const m=model({complete:false}),draft=createCollaborationResolutionDraft(m),decided=setCollaborationResolutionDecision(draft,draft.groups[0].id,'manual'),html=renderCollaborationResolutionDecisionPanel({model:m,draft:decided});assert.match(html,/Conflict details are incomplete/);assert.match(html,/2 conflicts were omitted/);assert.match(html,/data-collaboration-resolution-finalize disabled/);});

test('decision helpers delegate only validated dataset choices to immutable core state',()=>{const m=model(),draft=createCollaborationResolutionDraft(m),next=applyCollaborationResolutionDecision(draft,{groupId:draft.groups[0].id,choice:'reapply-remote'});assert.equal(draft.groups[0].decision,null);assert.equal(next.groups[0].decision,'reapply-remote');const viaControl=decisionFromCollaborationControl(draft,{dataset:{resolutionGroupId:draft.groups[0].id,collaborationDecision:'manual'}});assert.equal(viaControl.groups[0].decision,'manual');assert.throws(()=>decisionFromCollaborationControl(draft,{dataset:{resolutionGroupId:draft.groups[0].id,collaborationDecision:'merge'}}),/Unsupported resolution choice/);});

test('rendered presentation contains no batch signature or patch value fields',()=>{const m=model();m.signedBatch={signature:'should-never-render'};m.rows[0].remote.operation.secret='patch-secret';const draft=createCollaborationResolutionDraft(m),html=renderCollaborationResolutionDecisionPanel({model:m,draft});assert.equal(html.includes('should-never-render'),false);assert.equal(html.includes('patch-secret'),false);assert.equal(html.includes('signature'),false);});
