import test from 'node:test';
import assert from 'node:assert/strict';
import { KernelCompositionFrameProvider } from '../kernel-frame-provider.js';
import { CompositionPlaybackEngine } from '../composition-playback-engine.js';

test('hybrid provider routes video to kernel and images to fallback',async()=>{const calls=[];const provider=new KernelCompositionFrameProvider({videoEngine:{async frameAt(){calls.push('video');return{frame:'vf'};}},fallbackProvider:{async get(){calls.push('image');return'img';}}});assert.equal(await provider.get({props:{mediaKind:'video'}},1),'vf');assert.equal(await provider.get({props:{mediaKind:'image'}},0),'img');assert.deepEqual(calls,['video','image']);});
function fakeCanvas(){return{width:0,height:0,style:{},dataset:{},getContext(){return{clearRect(){},drawImage(){}};}};}
test('composition playback discards a stale async render after a newer seek',async()=>{const commits=[];let resolveFirst;const renderer=async(canvas,plan)=>{if(plan.time===1)await new Promise((resolve)=>{resolveFirst=resolve;});canvas.width=plan.width;canvas.height=plan.height;commits.push(`render:${plan.time}`);return{errors:[]};};const container={children:[],querySelector(selector){if(selector.includes('canvas[data-composition-playback'))return this.children.find((c)=>selector.includes(c.dataset.compositionPlayback))??null;return null;},querySelectorAll(){return this.children;},appendChild(value){this.children.push(value);}};const engine=new CompositionPlaybackEngine({frameProvider:{get(){},clear(){}},evaluate:(_g,{time})=>({time,width:100,height:100,visual:[{kind:'text',text:'x',style:{fontSize:10},transform:{}}]}),scalePlan:(plan)=>plan,renderer,canvasFactory:fakeCanvas});const first=engine.present({nodes:{}},1,container);const second=engine.present({nodes:{}},2,container);await second;resolveFirst();const stale=await first;assert.equal(stale.stale,true);assert.equal(container.children.length,1);});

test('composition playback prefers GPU only for fully supported plan',async()=>{const calls=[];const canvas={dataset:{},style:{},width:0,height:0,getContext(type){if(type==='2d')return{clearRect(){},drawImage(){}};return null;}};const container={children:[],querySelector(selector){if(selector.includes('canvas[data-composition-playback'))return this.children.find((c)=>selector.includes(c.dataset.compositionPlayback))??null;return null;},querySelectorAll(){return this.children;},appendChild(c){this.children.push(c);}};const gpuRenderer={supports(){return true;},async present(target,plan,{shouldCommit}){calls.push(['gpu',plan.visual.length,shouldCommit()]);return{backend:'webgpu-layers'};}};const engine=new CompositionPlaybackEngine({frameProvider:{},gpuRenderer,evaluate:()=>({width:100,height:100,background:'#000',visual:[{assetId:'a',kind:'clip',transform:{},effects:[],blendMode:'normal'}],audio:[]}),scalePlan:(p)=>p,canvasFactory:()=>canvas,renderer:async()=>{throw new Error('canvas fallback should not run');}});const result=await engine.present({nodes:{a:{id:'a'}}},0,container);assert.equal(result.backend,'webgpu-layers');assert.deepEqual(calls,[['gpu',1,true]]);});
