import test from 'node:test';
import assert from 'node:assert/strict';
import { DashCmafLivePlaybackSession } from '../dash-cmaf-live-playback-session.js';
function media(timestamp,duration=0){return{timestamp,duration,closed:false,close(){this.closed=true;}};}
function harness(schedulerOptions={}){let options;const events=[],decode={async open(){events.push('open');return{opened:true};},async pumpOnce(){events.push('pump');return{pumped:true};},async flush(){events.push('flush');return 2;},stop(){events.push('decode-stop');},clear(){events.push('decode-clear');},snapshot(){return{samples:2};}};const session=new DashCmafLivePlaybackSession({manifestUrl:'https://x/live.mpd',decodeSessionFactory:async(value)=>{options=value;return decode;},schedulerOptions});return{session,events,get options(){return options;}};}
test('decoder video output is buffered and presented against playhead seconds',async()=>{const shown=[],h=harness({videoLateToleranceMicros:100_000,presentVideo:(frame)=>shown.push(frame.timestamp)});await h.session.open();h.options.dashCmafOptions.dashOptions.onVariant({id:'v'});h.options.decoderOptions.onVideoFrame(media(40_000),{variant:{id:'v'},track:{id:'video:1'}});const result=await h.session.present(.05);assert.equal(result.presented.timestamp,40_000);assert.deepEqual(shown,[40_000]);assert.equal(h.session.snapshot().presents,1);});
test('decoder audio output is scheduled inside live lookahead',async()=>{const scheduled=[],h=harness({audioAheadMicros:100_000,scheduleAudio:(data)=>scheduled.push(data.timestamp)});await h.session.open();h.options.dashCmafOptions.dashOptions.onVariant({id:'v'});h.options.decoderOptions.onAudioData(media(80_000,20_000),{variant:{id:'v'},track:{id:'audio:1'}});await h.session.present(.02);assert.deepEqual(scheduled,[80_000]);});
test('variant callback clears old buffered outputs before new presentation',async()=>{const h=harness(),frame=media(0);await h.session.open();h.options.dashCmafOptions.dashOptions.onVariant({id:'a'});h.options.decoderOptions.onVideoFrame(frame,{variant:{id:'a'},track:{id:'video:1'}});h.options.dashCmafOptions.dashOptions.onVariant({id:'b'});assert.equal(frame.closed,true);assert.equal(h.session.snapshot().variantChanges,2);});
test('pump flush and stop delegate through the composed playback session',async()=>{const h=harness();assert.deepEqual(await h.session.open(),{opened:true});assert.deepEqual(await h.session.pumpOnce(),{pumped:true});assert.equal(await h.session.flush(),2);h.session.stop();assert.deepEqual(h.events,['open','pump','flush','decode-stop']);});
