import test from 'node:test';
import assert from 'node:assert/strict';
import { DashCmafSession } from '../dash-cmaf-session.js';
class FakeCmaf{constructor(init){this.init=[...init];this.pushes=[];}async push(bytes,{id}={}){const record={id,bytes:[...bytes],chunks:[{trackId:'video:1',byteLength:bytes.length}]};this.pushes.push(record);return record;}clear(){this.cleared=true;}}
function harness(){let dashOptions;const cmaf=[];const bridge=new DashCmafSession({manifestUrl:'https://x.test/live.mpd',dashSessionFactory:async(options)=>{dashOptions=options;return{async open(){return{opened:true};},async pumpOnce(){return{pumped:true};},stop(){this.stopped=true;},snapshot(){return{ready:true};}};},cmafSessionFactory:async(init)=>{const session=new FakeCmaf(init);cmaf.push(session);return session;}});return{bridge,cmaf,get options(){return dashOptions;}};}
test('init creates a per-variant CMAF session and non-LL media demuxes once',async()=>{const h=harness();assert.deepEqual(await h.bridge.open(),{opened:true});await h.options.onSegment({segment:{id:'init:v',initialization:true},bytes:Uint8Array.from([1,2]),variant:{id:'v'}});await h.options.onSegment({segment:{id:'s1'},bytes:Uint8Array.from([3,4]),variant:{id:'v'}});assert.equal(h.cmaf.length,1);assert.deepEqual(h.cmaf[0].init,[1,2]);assert.deepEqual(h.cmaf[0].pushes.map(x=>x.id),['s1']);assert.equal(h.bridge.snapshot().demuxedUnits,1);});
test('low-latency fragments demux immediately and suppress whole-segment double demux',async()=>{const events=[],h=harness();h.bridge.onCmafFragment=(payload)=>events.push(`fragment:${payload.record.id}`);h.bridge.onDashSegment=(payload)=>events.push(`segment:${payload.segment.id}`);await h.bridge.open();await h.options.onSegment({segment:{id:'init:v',initialization:true},bytes:Uint8Array.from([1]),variant:{id:'v'}});await h.options.onFragment({segment:{id:'s1'},fragment:{id:'s1:0',bytes:Uint8Array.from([2,3])},variant:{id:'v'}});assert.deepEqual(events,['segment:init:v','fragment:s1:0']);await h.options.onSegment({segment:{id:'s1'},bytes:Uint8Array.from([2,3]),variant:{id:'v'}});assert.deepEqual(h.cmaf[0].pushes.map(x=>x.id),['s1:0']);assert.equal(h.bridge.snapshot().fragments,1);assert.equal(h.bridge.snapshot().suppressedWholeSegments,1);assert.deepEqual(events,['segment:init:v','fragment:s1:0','segment:s1']);});
test('variant changes keep independent init/demux sessions',async()=>{const h=harness();await h.bridge.open();for(const id of ['a','b'])await h.options.onSegment({segment:{id:`init:${id}`,initialization:true},bytes:Uint8Array.from([id.charCodeAt(0)]),variant:{id}});await h.options.onFragment({segment:{id:'sa'},fragment:{bytes:Uint8Array.from([1])},variant:{id:'a'}});await h.options.onSegment({segment:{id:'sb'},bytes:Uint8Array.from([2]),variant:{id:'b'}});assert.deepEqual(h.bridge.snapshot().variants,['a','b']);assert.equal(h.cmaf[0].pushes.length,1);assert.equal(h.cmaf[1].pushes.length,1);assert.equal(h.bridge.snapshot().demuxedUnits,2);});
test('media before init is rejected instead of buffering ambiguous bytes',async()=>{const h=harness();await h.bridge.open();await assert.rejects(()=>h.options.onFragment({segment:{id:'s'},fragment:{bytes:new Uint8Array([1])},variant:{id:'v'}}),/before initialization/);await assert.rejects(()=>h.options.onSegment({segment:{id:'s'},bytes:new Uint8Array([1]),variant:{id:'v'}}),/before CMAF initialization/);});
test('new init for a variant clears the replaced CMAF buffer',async()=>{const h=harness();await h.bridge.open();await h.options.onSegment({segment:{id:'init:v:1',initialization:true},bytes:Uint8Array.from([1]),variant:{id:'v'}});const first=h.cmaf[0];await h.options.onSegment({segment:{id:'init:v:2',initialization:true},bytes:Uint8Array.from([2]),variant:{id:'v'}});assert.equal(first.cleared,true);assert.deepEqual(h.cmaf[1].init,[2]);assert.deepEqual(h.bridge.snapshot().variants,['v']);});
