import test from 'node:test';
import assert from 'node:assert/strict';
import { DashCompositionFrameProvider, isDashAdaptiveAsset } from '../dash-composition-frame-provider.js';
function asset(overrides={}){return{id:'a',name:'Live',props:{mediaKind:'video',uri:'https://x/live.mpd',mimeType:'application/dash+xml',...overrides}};}
function harness({snapshot={decode:{bridge:{dash:{presentationNow:10,livePosition:30}}}}}={}){const events=[],base={async get(a,t){events.push(`base:${a.id}:${t}`);return{base:true};},clear(){events.push('base-clear');},clearAsset(id){events.push(`base-clear:${id}`);},stats(){return{ok:true};}},sessions=[];const provider=new DashCompositionFrameProvider({baseProvider:base,maxPumps:2,sessionFactory:async(options)=>{const session={options,current:null,async open(){events.push('open');return{};},snapshot(){return snapshot;},async pumpOnce({playhead}){events.push(`pump:${playhead}`);this.current={timestamp:playhead*1_000_000,closed:false,close(){this.closed=true;}};options.schedulerOptions.presentVideo(this.current,{variant:{id:'v'}},{});return{};},async flush(){events.push('flush');return 1;},async present(time){events.push(`present:${time}`);return{presented:this.current};},stop(){events.push('stop');},clear(){events.push('session-clear');}};sessions.push(session);return session;}});return{provider,base,sessions,events};}
test('DASH asset detection accepts protocol mime and MPD URL only for video',()=>{assert.equal(isDashAdaptiveAsset(asset()),true);assert.equal(isDashAdaptiveAsset(asset({mimeType:'video/mp4',uri:'https://x/live.mpd'})),true);assert.equal(isDashAdaptiveAsset(asset({adaptiveProtocol:'dash',uri:'https://x/video'})),true);assert.equal(isDashAdaptiveAsset({id:'x',props:{mediaKind:'audio',uri:'https://x/live.mpd'}}),false);assert.equal(isDashAdaptiveAsset(asset({mimeType:'video/mp4',uri:'https://x/video.mp4'})),false);});
test('non-DASH visuals delegate unchanged to base composition frame provider',async()=>{const h=harness(),normal=asset({mimeType:'video/mp4',uri:'https://x/video.mp4'}),frame=await h.provider.get(normal,2);assert.deepEqual(frame,{base:true});assert.deepEqual(h.events,['base:a:2']);assert.equal(h.provider.stats().baseRequests,1);});
test('live DASH scrub maps clip source time from initial live edge and flushes decoded frame',async()=>{const h=harness(),frame=await h.provider.forRequest({mode:'scrub'}).get(asset(),2,{signal:{aborted:false}});assert.equal(frame.timestamp,32_000_000);assert.deepEqual(h.events,['open','pump:32','flush','present:32']);assert.equal(h.provider.stats().dashRequests,1);assert.equal(h.provider.stats().frames,1);});
test('static DASH source uses source time directly instead of live-edge origin',async()=>{const h=harness({snapshot:{decode:{bridge:{dash:{presentationNow:null,livePosition:99}}}}});const frame=await h.provider.get(asset(),3);assert.equal(frame.timestamp,3_000_000);assert.ok(h.events.includes('pump:3'));});
test('DASH playback only flushes to bootstrap then reuses streaming decoder output',async()=>{const h=harness(),a=asset(),playback=h.provider.forRequest({mode:'playback'});await playback.get(a,0);await playback.get(a,1);assert.equal(h.sessions.length,1);assert.equal(h.events.filter((event)=>event==='flush').length,1);await h.provider.forRequest({mode:'scrub'}).get(a,2);assert.equal(h.events.filter((event)=>event==='flush').length,2);await h.provider.get({...a,props:{...a.props,hash:'new'}},1);assert.equal(h.sessions.length,2);assert.ok(h.events.includes('stop'));assert.ok(h.events.includes('session-clear'));});
test('clearAsset closes DASH source and also forwards invalidation to base provider',async()=>{const h=harness();await h.provider.get(asset(),0);h.provider.clearAsset('a');await new Promise((resolve)=>queueMicrotask(resolve));assert.ok(h.events.includes('stop'));assert.ok(h.events.includes('session-clear'));assert.ok(h.events.includes('base-clear:a'));assert.equal(h.provider.stats().dashSources,0);});

test('custom adaptive audio callback owns AudioData instead of default close hook',async()=>{let audioOptions,closed=0,custom=0,base={get:async()=>null},provider=new DashCompositionFrameProvider({baseProvider:base,onAudioData:(data)=>{closed++;data.close?.();},sessionOptions:{schedulerOptions:{scheduleAudio:(data)=>{custom++;assert.equal(data.closed,false);}}},sessionFactory:async(options)=>{audioOptions=options;return{open:async()=>{},snapshot:()=>({decode:{bridge:{dash:{presentationNow:null,livePosition:0}}}}),pumpOnce:async()=>{},flush:async()=>{},present:async()=>({presented:{timestamp:0}}),stop(){},clear(){}};}});await provider.get(asset(),0);const data={closed:false,close(){this.closed=true;}};audioOptions.schedulerOptions.scheduleAudio(data,{},{});assert.equal(custom,1);assert.equal(closed,0);assert.equal(data.closed,false);});
