import assert from 'node:assert/strict';
import test from 'node:test';
import { decodeFrameNearTime, generateThumbnailArtifact, generateThumbnailSet, generateVideoProxyArtifact, renderThumbnailFrame, thumbnailDimensions } from '../derivative-engine.js';
const track={id:'v',type:'video',codec:'vp09',width:1920,height:1080};
const chunks=[0,1,2,3].map((second,index)=>({trackId:'v',type:index===0||index===2?'key':'delta',timestamp:second*1_000_000,duration:1_000_000,sequence:index,offset:index,byteLength:1}));
function frame(timestamp,width=1920,height=1080){return{timestamp,displayWidth:width,displayHeight:height,closed:false,close(){this.closed=true;}};}
function canvasFactory(width,height){return{width,height,draws:[],getContext(){return{drawImage:(source,x,y,w,h)=>this.draws.push({source,x,y,w,h})}},async convertToBlob({type}){return new Blob([new Uint8Array([1,2,3])],{type});}};}
test('calculates aspect-preserving thumbnail dimensions',()=>{assert.deepEqual(thumbnailDimensions(frame(0),{width:320}),{width:320,height:180,scale:1/6});assert.deepEqual(thumbnailDimensions(frame(0,100,50),{width:320}),{width:100,height:50,scale:1});});
test('renders a decoded frame to an encoded thumbnail blob',async()=>{const result=await renderThumbnailFrame(frame(0),{width:320,format:'image/png'},{canvasFactory});assert.equal(result.width,320);assert.equal(result.height,180);assert.equal(result.mimeType,'image/png');assert.equal(result.blob.type,'image/png');});
test('decodes from a preceding keyframe and selects nearest output frame',async()=>{const produced=[frame(2_000_000),frame(2_900_000),frame(3_100_000)];let received=[];const decoder=async(_track,windowChunks,_source,{onOutput})=>{received=windowChunks;produced.forEach(onOutput);return{submitted:windowChunks.length};};const result=await decodeFrameNearTime({track,chunks,source:new Uint8Array([1]),time:3,decoder});assert.equal(received[0].timestamp,2_000_000);assert.equal(result.frame.timestamp,2_900_000);assert.equal(produced[0].closed,true);assert.equal(produced[2].closed,true);});
test('generates thumbnail artifact and closes selected frame',async()=>{const selected=frame(1_000_000);const decoder=async(_track,_chunks,_source,{onOutput})=>{onOutput(selected);return{submitted:1};};const result=await generateThumbnailArtifact({track,chunks,source:new Uint8Array([1]),time:1,spec:{width:160},decoder,canvasFactory});assert.equal(result.width,160);assert.equal(result.height,90);assert.equal(result.time,1);assert.equal(selected.closed,true);});
test('generates deterministic ordered thumbnail sets with progress',async()=>{const progress=[];const decoder=async(_track,windowChunks,_source,{onOutput})=>{onOutput(frame(windowChunks[0].timestamp));return{submitted:1};};const result=await generateThumbnailSet({track,chunks,source:new Uint8Array([1]),times:[2,0,2],spec:{width:80},decoder,canvasFactory,onProgress:(ratio)=>progress.push(ratio)});assert.equal(result.length,2);assert.deepEqual(progress,[.5,1]);});
test('transcodes decoded video frames into a muxed WebM proxy artifact',async()=>{const sourceFrames=[frame(0,1920,1080),frame(33333,1920,1080)];const decoder=async(_track,_chunks,_source,{onOutput})=>{sourceFrames.forEach(onOutput);return{submitted:2};};const scaled=[];const frameScaler=async(input,{width,height})=>{const out=frame(input.timestamp,width,height);out.duration=33333;scaled.push(out);return out;};let encoderConfig=null;const encoder=async(frames,config)=>{encoderConfig=config;return{submitted:frames.length,chunks:frames.map((f,index)=>({timestamp:f.timestamp,dts:f.timestamp,duration:33333,type:index?'delta':'key',keyframe:index===0,byteLength:2,payload:new Uint8Array([index,9]).buffer}))};};let muxPlan=null;const muxer=(plan)=>{muxPlan=plan;return new Uint8Array([9,8,7]);};const result=await generateVideoProxyArtifact({track,chunks,source:new Uint8Array([1]),spec:{width:640,height:360,codec:'vp9',framerate:30},decoder,videoEncoder:encoder,frameScaler,muxer});assert.equal(result.byteLength,3);assert.equal(result.width,640);assert.equal(result.height,360);assert.equal(result.videoOnly,true);assert.equal(encoderConfig.codec,'vp09.00.10.08');assert.equal(muxPlan.container,'webm');assert.equal(muxPlan.samples.length,2);assert.ok(sourceFrames.every((f)=>f.closed));assert.ok(scaled.every((f)=>f.closed));});

test('includes Opus audio when proxy audio track/chunks are supplied',async()=>{const videoFrame=frame(0);const audioFrame={timestamp:0,duration:20_000,closed:false,close(){this.closed=true;}};const decoder=async(inputTrack,_chunks,_source,{onOutput})=>{onOutput(inputTrack.type==='video'?videoFrame:audioFrame);return{submitted:1};};const frameScaler=async(input,{width,height})=>{const out=frame(input.timestamp,width,height);out.duration=33333;return out;};const videoEncoder=async()=>({chunks:[{timestamp:0,dts:0,duration:33333,type:'key',keyframe:true,byteLength:1,payload:new Uint8Array([1]).buffer}]});let audioConfig=null;const audioEncoder=async(_frames,config)=>{audioConfig=config;return{chunks:[{timestamp:0,dts:0,duration:20_000,type:'key',byteLength:1,payload:new Uint8Array([2]).buffer}]};};let plan=null;const muxer=(value)=>{plan=value;return new Uint8Array([1,2]);};const result=await generateVideoProxyArtifact({track,chunks:[chunks[0]],source:new Uint8Array([1]),audioTrack:{id:'a',type:'audio',codec:'mp4a.40.2',sampleRate:48000,channels:2},audioChunks:[{trackId:'a',type:'key',timestamp:0,duration:20_000,offset:0,byteLength:1}],spec:{width:640,height:360},decoder,videoEncoder,audioEncoder,frameScaler,muxer});assert.equal(result.audioIncluded,true);assert.equal(result.videoOnly,false);assert.equal(audioConfig.codec,'opus');assert.equal(plan.tracks.length,2);assert.equal(plan.samples.length,2);assert.equal(audioFrame.closed,true);});
test('bounds batch proxy frame retention and asks callers to segment long work',async()=>{const produced=[frame(0),frame(1),frame(2)];const decoder=async(_track,_chunks,_source,{onOutput})=>{produced.forEach(onOutput);return{submitted:3};};await assert.rejects(()=>generateVideoProxyArtifact({track,chunks:[chunks[0]],source:new Uint8Array([1]),spec:{maxDecodedFrames:2,width:640,height:360},decoder,frameScaler:async(f)=>f,videoEncoder:async()=>({chunks:[]}),muxer:()=>new Uint8Array()}),/segment the source/);assert.ok(produced.every((f)=>f.closed));});
