import test from 'node:test';
import assert from 'node:assert/strict';
import { HistoryJournalSession } from '../history-journal-session.js';

const createHistory=(graph)=>({present:graph,past:[],future:[]});
const commitHistory=(history,graph,label)=>({present:graph,past:[...history.past,{graph:history.present,label}],future:[]});
const undoHistory=(history)=>history;
const redoHistory=(history)=>history;
const createTransaction=(label,operations,metadata={})=>({id:`tx:${label}`,label,operations,metadata});
const applyTransaction=(graph,tx)=>({...graph,value:(graph.value??0)+tx.operations.reduce((n,op)=>n+(op.delta??0),0)});
function session(options={}){return new HistoryJournalSession({history:createHistory({projectId:'p',value:0,nodes:{old:{id:'old',kind:'asset',props:{hash:'old'}}}}),applyTransaction,createTransaction,persist:async()=>{},compactThreshold:0,commitHistory,undoHistory,redoHistory,createHistory,...options});}

test('pressure cleanup targets quota delta and retains present plus undo sources',async()=>{const calls=[],s=session({estimateStorage:async()=>({usage:95,quota:100,ratio:.95}),collectAssets:async(options)=>{calls.push(options);return{deletedIds:['stale'],deleteBytes:15};}});const result=await s.commitGraphFactory('Import',(graph)=>({...graph,value:1,nodes:{new:{id:'new',kind:'asset',props:{hash:'new'}}}}),{}, {persistContext:{assetWrites:[{assetId:'new',blob:{}}]}});assert.equal(calls.length,1);assert.equal(calls[0].maxDeleteBytes,15);assert.equal(calls[0].retentionGraph.nodes.new.id,'new');assert.equal(calls[0].retentionGraph.nodes.old.id,'old');assert.equal(result.assetCleanup.deleteBytes,15);assert.equal(s.stats().assetCollections,1);assert.equal(s.stats().assetBytesDeleted,15);});

test('below pressure does not invoke cleanup',async()=>{let called=0,s=session({estimateStorage:async()=>({usage:80,quota:100,ratio:.8}),collectAssets:async()=>{called++;return{};}});const result=await s.edit('edit',[{delta:1}],{}, {persistContext:{assetWrites:[{assetId:'a',blob:{}}]}});assert.equal(called,0);assert.equal(result.assetCleanup,null);});

test('cleanup failure never rolls back a durable edit',async()=>{const s=session({estimateStorage:async()=>{throw new Error('estimate failed');}}),result=await s.edit('edit',[{delta:2}],{}, {persistContext:{assetWrites:[{assetId:'a',blob:{}}]}});assert.equal(result.graph.value,2);assert.match(result.assetCleanup.error.message,/estimate failed/);assert.equal(s.stats().maintenanceFailures,1);});

test('maintenance estimate and cleanup outputs reject getters and coercion without execution',async()=>{let getterCalls=0,coercions=0,collectCalls=0;const estimate={usage:95,quota:100};Object.defineProperty(estimate,'ratio',{enumerable:true,get(){getterCalls+=1;return.95;}});const first=session({estimateStorage:async()=>estimate,collectAssets:async()=>{collectCalls+=1;return{};}}),firstResult=await first.edit('edit',[{delta:1}],{}, {persistContext:{assetWrites:[{assetId:'a',blob:{}}]}});assert.equal(firstResult.graph.value,1);assert.equal(getterCalls,0);assert.equal(collectCalls,0);assert.equal(first.stats().maintenanceFailures,1);const second=session({estimateStorage:async()=>({usage:95,quota:100,ratio:{valueOf(){coercions+=1;return.95;}}}),collectAssets:async()=>{collectCalls+=1;return{};}}),secondResult=await second.edit('edit',[{delta:1}],{}, {persistContext:{assetWrites:[{assetId:'a',blob:{}}]}});assert.equal(secondResult.graph.value,1);assert.equal(coercions,0);assert.equal(collectCalls,0);const cleanup={deleteBytes:10};Object.defineProperty(cleanup,'deletedIds',{enumerable:true,get(){getterCalls+=1;return['stale'];}});const third=session({estimateStorage:async()=>({usage:95,quota:100,ratio:.95}),collectAssets:async()=>{collectCalls+=1;return cleanup;}}),thirdResult=await third.edit('edit',[{delta:1}],{}, {persistContext:{assetWrites:[{assetId:'a',blob:{}}]}});assert.equal(thirdResult.graph.value,1);assert.equal(getterCalls,0);assert.equal(third.stats().maintenanceFailures,1);});

test('maintenance returns a bounded inert deletion summary and strips unrelated collector payloads',async()=>{const deletedIds=Array.from({length:300},(_,index)=>`asset-${index}`),s=session({estimateStorage:async()=>({usage:95,quota:100,ratio:.95}),collectAssets:async()=>({deletedIds,deleteBytes:25,candidates:[{private:'payload'}],retained:['private']})}),result=await s.edit('edit',[{delta:1}],{}, {persistContext:{assetWrites:[{assetId:'a',blob:{}}]}});assert.equal(result.assetCleanup.deletedIds.length,256);assert.equal(result.assetCleanup.deletedCount,300);assert.equal(result.assetCleanup.truncatedDeletedIds,44);assert.equal(result.assetCleanup.deleteBytes,25);assert.equal('candidates'in result.assetCleanup,false);assert.equal('retained'in result.assetCleanup,false);assert.equal(s.stats().assetCollections,1);assert.equal(s.stats().assetBytesDeleted,25);});

test('retention maintenance snapshots only inert asset identity and hash fields',async()=>{let getterCalls=0,seenNode=null;const asset={id:'old',kind:'asset',props:{hash:'old'}};Object.defineProperty(asset,'secret',{enumerable:true,get(){getterCalls+=1;return'private';}});const s=new HistoryJournalSession({history:createHistory({projectId:'p',value:0,nodes:{old:asset}}),applyTransaction,createTransaction,persist:async()=>{},compactThreshold:0,estimateStorage:async()=>({usage:95,quota:100,ratio:.95}),collectAssets:async({retentionGraph})=>{seenNode=retentionGraph.nodes.old;return{deletedIds:[],deleteBytes:0};},commitHistory,undoHistory,redoHistory,createHistory});await s.edit('edit',[{delta:1}],{}, {persistContext:{assetWrites:[{assetId:'a',blob:{}}]}});assert.equal(getterCalls,0);assert.notEqual(seenNode,asset);assert.deepEqual(seenNode,{id:'old',kind:'asset',props:{hash:'old'}});});

test('maintenance error snapshots never execute hostile error fields or coercion',async()=>{let getterCalls=0,coercions=0;const error={toString(){coercions+=1;return'unsafe';}};Object.defineProperty(error,'message',{enumerable:true,get(){getterCalls+=1;return'unsafe';}});const s=session({estimateStorage:async()=>{throw error;}}),result=await s.edit('edit',[{delta:1}],{}, {persistContext:{assetWrites:[{assetId:'a',blob:{}}]}});assert.equal(result.graph.value,1);assert.equal(getterCalls,0);assert.equal(coercions,0);assert.equal(result.assetCleanup.error.message,'Asset maintenance failed');});
