import test from 'node:test';
import assert from 'node:assert/strict';
import {HistoryJournalSession,recoverHistoryJournalSession} from '../history-journal-session.js';
import {appendOperationLog,createOperationLog} from '../../../packages/core/src/operation-log.js';

const createHistory=(graph)=>({present:graph,past:[],future:[]});
const commitHistory=(history,graph,label)=>({present:graph,past:[...history.past,{graph:history.present,label}],future:[]});
const undoHistory=(history)=>{const previous=history.past.at(-1);return previous?{present:previous.graph,past:history.past.slice(0,-1),future:[{graph:history.present,label:previous.label},...history.future]}:history;};
const redoHistory=(history)=>{const next=history.future[0];return next?{present:next.graph,past:[...history.past,{graph:history.present,label:next.label}],future:history.future.slice(1)}:history;};
const createTransaction=(label,operations,metadata={})=>({id:`tx:${label}:${JSON.stringify(metadata)}`,label,operations:structuredClone(operations),metadata:structuredClone(metadata)});
const applyTransaction=(graph,transaction)=>({...graph,value:transaction.operations.reduce((value,operation)=>value+Number(operation.delta??0),Number(graph.value??0))});
function make({graph={projectId:'p',value:0},persist=async()=>{}}={}){return new HistoryJournalSession({history:createHistory(graph),applyTransaction,createTransaction,persist,commitHistory,undoHistory,redoHistory,createHistory});}

test('edit advances snapshot history only after durable journal commit',async()=>{let release,persisted=false;const session=make({persist:()=>new Promise((resolve)=>{release=()=>{persisted=true;resolve();};})}),task=session.edit('Raise',[{delta:2}]);await new Promise((resolve)=>setTimeout(resolve,0));assert.equal(session.snapshot().graph.value,0);assert.equal(session.snapshot().history.past.length,0);release();const result=await task;assert.equal(persisted,true);assert.equal(result.graph.value,2);assert.equal(result.history.past.length,1);assert.equal(result.history.past[0].label,'Raise');assert.equal(session.stats().edits,1);});
test('failed edit persistence leaves history and journal sequence unchanged',async()=>{const session=make({persist:async()=>{throw new Error('quota');}});await assert.rejects(()=>session.edit('Raise',[{delta:2}]),/quota/);assert.equal(session.snapshot().graph.value,0);assert.equal(session.snapshot().history.past.length,0);assert.equal(session.stats().sequence,0);assert.equal(session.stats().failed,1);});
test('undo and redo persist checkpoint entries before switching history',async()=>{const persisted=[],session=make({persist:async(graph,entry)=>persisted.push({value:graph.value,entry})});await session.edit('Raise',[{delta:3}]);const undo=await session.undo();assert.equal(undo.graph.value,0);assert.equal(undo.entry.transaction.metadata.historyAction,'undo');assert.equal(undo.history.future.length,1);const redo=await session.redo();assert.equal(redo.graph.value,3);assert.equal(redo.entry.transaction.metadata.historyAction,'redo');assert.equal(redo.history.past.length,1);assert.deepEqual(persisted.map((item)=>item.value),[3,0,3]);assert.equal(session.stats().sequence,3);});
test('undo and redo no-ops do not append journal entries',async()=>{const session=make();const undo=await session.undo(),redo=await session.redo();assert.equal(undo.noOp,true);assert.equal(redo.noOp,true);assert.equal(session.stats().sequence,0);assert.equal(session.stats().noops,2);});
test('direct graph commit persists a checkpoint while preserving undo history',async()=>{const session=make({graph:{projectId:'p',value:4}}),result=await session.commitGraph('Import media',{projectId:'p',value:9},{source:'import'});assert.equal(result.graph.value,9);assert.equal(result.history.past.length,1);assert.equal(result.history.past[0].label,'Import media');assert.equal(result.entry.transaction.metadata.historyAction,'commit-graph');assert.equal(result.entry.transaction.checkpointGraph.value,9);assert.equal(session.stats().graphCommits,1);const undone=await session.undo();assert.equal(undone.graph.value,4);});
test('graph factory evaluates against latest serialized history',async()=>{const gates=[],session=make({persist:async()=>new Promise((resolve)=>gates.push(resolve))}),first=session.edit('Raise',[{delta:2}]),second=session.commitGraphFactory('Import',(graph)=>({...graph,value:graph.value+5}));await new Promise((resolve)=>setTimeout(resolve,0));gates.shift()();await first;await new Promise((resolve)=>setTimeout(resolve,0));gates.shift()();const result=await second;assert.equal(result.graph.value,7);assert.equal(result.history.past.length,2);});
test('replacement resets snapshot history but remains replayable as checkpoint',async()=>{const session=make({graph:{projectId:'p',value:4}});await session.edit('Raise',[{delta:1}]);const replacement={projectId:'p',value:20},result=await session.replace('Open project',replacement,{source:'import'});assert.equal(result.graph.value,20);assert.equal(result.history.past.length,0);assert.equal(result.entry.transaction.metadata.historyAction,'replace');assert.equal(result.entry.transaction.checkpointGraph.value,20);assert.equal(session.stats().replacements,1);});
test('serialized concurrent edits preserve graph and history order',async()=>{const order=[],gates=[],session=make({persist:async(_graph,entry)=>{order.push(`start:${entry.sequence}`);await new Promise((resolve)=>gates.push(resolve));order.push(`end:${entry.sequence}`);}}),first=session.edit('One',[{delta:1}]),second=session.edit('Two',[{delta:2}]);await new Promise((resolve)=>setTimeout(resolve,0));assert.deepEqual(order,['start:1']);gates.shift()();await first;await new Promise((resolve)=>setTimeout(resolve,0));assert.deepEqual(order,['start:1','end:1','start:2']);gates.shift()();await second;assert.equal(session.snapshot().graph.value,3);assert.deepEqual(session.snapshot().history.past.map((item)=>item.label),['One','Two']);});
test('recovery validates journal then starts a clean restart history at current graph',()=>{const base={projectId:'p',value:0},transaction=createTransaction('Raise',[{delta:5}]),log=appendOperationLog(createOperationLog({projectId:'p'}),transaction),session=recoverHistoryJournalSession({recovery:{baseGraph:base,graph:{projectId:'p',value:5},log},applyTransaction,createTransaction,persist:async()=>{},commitHistory,undoHistory,redoHistory,createHistory});assert.equal(session.snapshot().graph.value,5);assert.equal(session.snapshot().history.past.length,0);assert.equal(session.stats().sequence,1);});
