import assert from 'node:assert/strict';
import test from 'node:test';
import { createKernelTask } from '../../../packages/core/src/kernel-protocol.js';
import { demuxWebm, readWebmFrame } from '../../../packages/core/src/webm-demux.js';
import { decodeWavPcm } from '../../../packages/core/src/wav.js';
import { createDefaultKernelRuntime, inspectContainerPayload } from '../kernel-handlers.js';
import { collectTransferables } from '../kernel-transfer.js';

function makeWav(){const buffer=new ArrayBuffer(46);const view=new DataView(buffer);const text=(o,s)=>[...s].forEach((c,i)=>view.setUint8(o+i,c.charCodeAt(0)));text(0,'RIFF');view.setUint32(4,38,true);text(8,'WAVE');text(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,8000,true);view.setUint32(28,16000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,2,true);view.setInt16(44,16384,true);return buffer;}
test('default kernel demuxes WAV with a normalized track',()=>{const result=inspectContainerPayload({name:'tone.wav',bytes:makeWav()});assert.equal(result.container,'wav');assert.equal(result.tracks[0].sampleRate,8000);});
test('default kernel encodes Float32 PCM to WAV',async()=>{const runtime=createDefaultKernelRuntime();const channel=new Float32Array([0,.5,-.5]);const message=await runtime.execute(createKernelTask('encode-audio',{format:'wav',sampleRate:8000,length:3,channels:[channel.buffer],bitDepth:16},{id:'enc'}));assert.equal(message.type,'result');assert.equal(message.result.mimeType,'audio/wav');const decoded=decodeWavPcm(message.result.bytes).pcm;assert.equal(decoded.length,3);assert.ok(decoded.channels[0][1]>.49);});

test('default kernel can feed demuxed video chunks through WebCodecs adapters',async()=>{const previousDecoder=globalThis.VideoDecoder,previousChunk=globalThis.EncodedVideoChunk;class Chunk{constructor(init){Object.assign(this,init);this.data=new Uint8Array(init.data);}}class Decoder{static async isConfigSupported(config){return{supported:true,config};}constructor({output}){this.output=output;this.decodeQueueSize=0;}configure(){}decode(chunk){this.output({timestamp:chunk.timestamp,bytes:[...chunk.data]});}async flush(){}close(){}}globalThis.VideoDecoder=Decoder;globalThis.EncodedVideoChunk=Chunk;try{const track={id:'video:1',type:'video',codec:'avc1.640028',timescale:1_000_000,duration:1,width:16,height:16,description:null};const bytes=new Uint8Array([0,1,2,3,4]).buffer;const chunks=[{trackId:'video:1',type:'key',timestamp:0,presentationTimestamp:10,duration:33,offset:1,byteLength:3,sequence:0}];const message=await createDefaultKernelRuntime().execute(createKernelTask('decode-video',{track,chunks,bytes},{id:'video'}));assert.equal(message.type,'result');assert.equal(message.result.submitted,1);assert.deepEqual(message.result.frames,[{timestamp:10,bytes:[1,2,3]}]);}finally{globalThis.VideoDecoder=previousDecoder;globalThis.EncodedVideoChunk=previousChunk;}});

test('default kernel encodes video frames through WebCodecs and returns muxable byte records',async()=>{const prevEncoder=globalThis.VideoEncoder;class Encoded{constructor(index,timestamp,key){this.type=key?'key':'delta';this.timestamp=timestamp;this.duration=33;this.data=Uint8Array.from([index,5]);this.byteLength=2;}copyTo(target){target.set(this.data);}}class Encoder{static async isConfigSupported(config){return{supported:true,config};}constructor({output}){this.output=output;this.encodeQueueSize=0;this.i=0;}configure(){}encode(frame,{keyFrame}){this.output(new Encoded(this.i++,frame.timestamp,keyFrame),{});}async flush(){}close(){}}globalThis.VideoEncoder=Encoder;try{const message=await createDefaultKernelRuntime().execute(createKernelTask('encode-video',{trackId:'v',frames:[{timestamp:0},{timestamp:33}],config:{codec:'avc1.640028',width:16,height:16},keyFrameInterval:2},{id:'ve'}));assert.equal(message.type,'result');assert.deepEqual(message.result.chunks.map((c)=>c.type),['key','delta']);assert.deepEqual([...new Uint8Array(message.result.chunks[1].bytes)],[1,5]);}finally{globalThis.VideoEncoder=prevEncoder;}});

test('kernel transfer collector deduplicates nested ArrayBuffers',()=>{const buffer=new ArrayBuffer(8);const view=new Uint8Array(buffer);const transfer=collectTransferables({a:buffer,b:[view,{again:buffer}]},{scope:{}});assert.deepEqual(transfer,[buffer]);});

test('default kernel muxes WebM into a demuxable file',async()=>{const plan={container:'webm',tracks:[{id:'v',type:'video',codec:'vp09.00.10.08',timescale:1_000_000,config:{width:320,height:180}}],samples:[{trackId:'v',timestamp:0,dts:0,duration:1_000_000,keyframe:true,type:'key',sequence:0,byteLength:3,payload:new Uint8Array([7,8,9])}]};const result=await createDefaultKernelRuntime().execute(createKernelTask('mux',{plan},{id:'mux-webm'}));assert.equal(result.type,'result');const parsed=demuxWebm(new Uint8Array(result.result.bytes));assert.equal(parsed.tracks[0].codec,'vp09');assert.deepEqual([...readWebmFrame(new Uint8Array(result.result.bytes),parsed.chunks[0])],[7,8,9]);});
