import test from 'node:test';
import assert from 'node:assert/strict';
import { BrowserLiveVideoPresenter, BrowserLiveAudioScheduler, audioDataToAudioBuffer } from '../live-browser-output.js';
function fakeCanvas(){const calls=[];return{width:0,height:0,calls,getContext(){return{drawImage(...args){calls.push(args);}};}};}
function fakeAudioData(timestamp=120000){return{timestamp,duration:20000,numberOfFrames:2,numberOfChannels:2,sampleRate:100,planes:[[.1,.2],[.3,.4]],closed:false,copyTo(dest,{planeIndex,format}){assert.equal(format,'f32-planar');dest.set(this.planes[planeIndex]);},close(){this.closed=true;}};}
function fakeContext(){const starts=[],sources=[];const context={currentTime:10,state:'running',destination:{},starts,sources,createGain(){return{gain:{value:0},connect(){},disconnect(){}};},createBuffer(channels,frames,sampleRate){const data=Array.from({length:channels},()=>new Float32Array(frames));return{duration:frames/sampleRate,getChannelData(i){return data[i];},data};},createBufferSource(){const source={buffer:null,stopped:false,connect(){},start(...args){starts.push(args);},stop(){this.stopped=true;},addEventListener(){}};sources.push(source);return source;}};return context;}
test('live video presenter draws VideoFrame-compatible objects to Cut-style canvas',async()=>{const canvas=fakeCanvas(),presenter=new BrowserLiveVideoPresenter({canvas}),frame={displayWidth:640,displayHeight:360,timestamp:0};await presenter.present(frame,{},{});assert.equal(canvas.width,640);assert.equal(canvas.height,360);assert.equal(canvas.calls[0][0],frame);assert.equal(presenter.stats().framesPresented,1);});
test('AudioData converts through required f32-planar Web Audio bridge',()=>{const context=fakeContext(),data=fakeAudioData(),buffer=audioDataToAudioBuffer(context,data);assert.ok(Math.abs(buffer.data[0][0]-.1)<1e-6);assert.ok(Math.abs(buffer.data[0][1]-.2)<1e-6);assert.ok(Math.abs(buffer.data[1][0]-.3)<1e-6);assert.ok(Math.abs(buffer.data[1][1]-.4)<1e-6);});
test('live audio scheduler anchors AudioContext time to playhead and closes AudioData after copy',async()=>{const context=fakeContext(),scheduler=new BrowserLiveAudioScheduler({context,maxDriftSeconds:.08}),data=fakeAudioData(120000),result=await scheduler.schedule(data,{}, {playheadMicros:100000,aheadMicros:20000});assert.equal(result.scheduled,true);assert.ok(Math.abs(result.startAt-10.02)<1e-9);assert.deepEqual(context.starts[0],[10.02,0]);assert.equal(data.closed,true);});
test('large playhead drift re-anchors audio clock and late starts skip stale samples',async()=>{const context=fakeContext(),scheduler=new BrowserLiveAudioScheduler({context,maxDriftSeconds:.05});await scheduler.schedule(fakeAudioData(120000),{}, {playheadMicros:100000,aheadMicros:20000});context.currentTime=11;const data=fakeAudioData(220000),result=await scheduler.schedule(data,{}, {playheadMicros:200000,aheadMicros:20000});assert.equal(scheduler.stats().clockCorrections,1);assert.ok(Math.abs(result.startAt-11.02)<1e-9);});

test('slightly late audio starts now with a source offset instead of replaying stale samples',async()=>{const context=fakeContext(),scheduler=new BrowserLiveAudioScheduler({context,maxDriftSeconds:.08}),data=fakeAudioData(90000),result=await scheduler.schedule(data,{}, {playheadMicros:100000,aheadMicros:-10000});assert.equal(result.scheduled,true);assert.equal(result.startAt,10);assert.ok(Math.abs(result.sourceOffset-.01)<1e-9);assert.equal(scheduler.stats().lateStarts,1);assert.equal(data.closed,true);});
test('audio reset stops scheduled sources and clears clock anchor',async()=>{const context=fakeContext(),scheduler=new BrowserLiveAudioScheduler({context});await scheduler.schedule(fakeAudioData(),{}, {playheadMicros:100000,aheadMicros:20000});scheduler.reset();assert.equal(context.sources[0].stopped,true);assert.equal(scheduler.stats().sources,0);assert.equal(scheduler.stats().clockOffset,null);});
