import test from 'node:test';
import assert from 'node:assert/strict';
import { LiveDecodedMediaScheduler } from '../live-decoded-media-scheduler.js';
function media(timestamp,duration=0){return{timestamp,duration,closed:false,close(){this.closed=true;}};}
test('live scheduler presents latest due video and closes superseded frames',async()=>{const shown=[],scheduler=new LiveDecodedMediaScheduler({videoLateToleranceMicros:100_000,presentVideo:(frame)=>shown.push(frame.timestamp)}),a=media(0),b=media(40_000),c=media(80_000);scheduler.activateVariant({id:'v'});scheduler.pushVideo(a,{variant:{id:'v'}});scheduler.pushVideo(b,{variant:{id:'v'}});scheduler.pushVideo(c,{variant:{id:'v'}});await scheduler.advance(50_000);assert.deepEqual(shown,[40_000]);assert.equal(a.closed,true);assert.equal(b.closed,false);assert.equal(c.closed,false);assert.equal(scheduler.stats().videoPresented,1);});
test('audio is scheduled only inside lookahead and late audio is dropped',async()=>{const scheduled=[],scheduler=new LiveDecodedMediaScheduler({audioAheadMicros:100_000,audioLateToleranceMicros:10_000,scheduleAudio:(data)=>scheduled.push(data.timestamp)}),late=media(0,10_000),ready=media(90_000,20_000),future=media(250_000,20_000);scheduler.activateVariant({id:'v'});for(const item of [late,ready,future])scheduler.pushAudio(item,{variant:{id:'v'}});await scheduler.advance(50_000);assert.equal(late.closed,true);assert.deepEqual(scheduled,[90_000]);assert.equal(ready.closed,false);assert.equal(future.closed,false);assert.equal(scheduler.stats().audioBuffered,1);});
test('variant switch closes old buffered media and rejects stale decoder output',()=>{const scheduler=new LiveDecodedMediaScheduler(),oldVideo=media(0),oldAudio=media(0,20_000),stale=media(40_000);scheduler.activateVariant({id:'a'});scheduler.pushVideo(oldVideo,{variant:{id:'a'}});scheduler.pushAudio(oldAudio,{variant:{id:'a'}});scheduler.activateVariant({id:'b'});assert.equal(oldVideo.closed,true);assert.equal(oldAudio.closed,true);assert.equal(scheduler.pushVideo(stale,{variant:{id:'a'}}),false);assert.equal(stale.closed,true);assert.equal(scheduler.stats().activeVariant,'b');assert.equal(scheduler.stats().variantSwitches,1);});
test('capacity bounds close oldest video and audio outputs',()=>{const scheduler=new LiveDecodedMediaScheduler({maxVideoFrames:2,maxAudioFrames:2}),v=[media(0),media(1),media(2)],a=[media(0),media(1),media(2)];scheduler.activateVariant({id:'v'});v.forEach(x=>scheduler.pushVideo(x,{variant:{id:'v'}}));a.forEach(x=>scheduler.pushAudio(x,{variant:{id:'v'}}));assert.equal(v[0].closed,true);assert.equal(a[0].closed,true);assert.equal(scheduler.stats().videoBuffered,2);assert.equal(scheduler.stats().audioBuffered,2);});
test('clear closes retained decoded outputs',()=>{const scheduler=new LiveDecodedMediaScheduler(),v=media(0),a=media(0,1);scheduler.pushVideo(v,{variant:{id:'v'}});scheduler.pushAudio(a,{variant:{id:'v'}});scheduler.clear();assert.equal(v.closed,true);assert.equal(a.closed,true);assert.equal(scheduler.stats().videoBuffered,0);assert.equal(scheduler.stats().audioBuffered,0);});
