import test from 'node:test';
import assert from 'node:assert/strict';
import {ProjectJournalSession,recoverProjectJournalSession} from '../project-journal-session.js';
import {createOperationLog,appendOperationLog} from '../../../packages/core/src/operation-log.js';

const transactionFactory=(label,operations,metadata={})=>({id:`tx:${label}`,label,operations:structuredClone(operations),metadata:structuredClone(metadata)});
const apply=(graph,transaction)=>({...graph,value:transaction.operations.reduce((value,operation)=>value+Number(operation.delta??0),Number(graph.value??0))});
test('commit persists graph and journal entry before advancing session state',async()=>{const persisted=[],session=new ProjectJournalSession({graph:{projectId:'p',value:0},applyTransaction:apply,createTransaction:transactionFactory,persist:async(graph,entry)=>persisted.push({graph:structuredClone(graph),entry:structuredClone(entry)})});const result=await session.commit('one',[{delta:2}],{source:'ui'});assert.equal(result.graph.value,2);assert.equal(result.entry.sequence,1);assert.equal(persisted[0].graph.value,2);assert.equal(session.snapshot().graph.value,2);assert.deepEqual(session.stats(),{commits:1,checkpoints:0,persisted:1,compactions:0,failed:0,sequence:1,projectId:'p'});});
test('failed persistence leaves graph and sequence unchanged',async()=>{let fail=true;const session=new ProjectJournalSession({graph:{projectId:'p',value:0},applyTransaction:apply,createTransaction:transactionFactory,persist:async()=>{if(fail)throw new Error('disk full');}});await assert.rejects(()=>session.commit('bad',[{delta:5}]),/disk full/);assert.equal(session.snapshot().graph.value,0);assert.equal(session.stats().sequence,0);fail=false;const result=await session.commit('good',[{delta:1}]);assert.equal(result.entry.sequence,1);assert.equal(session.snapshot().graph.value,1);assert.equal(session.stats().failed,1);});
test('concurrent commits serialize persistence and sequence order',async()=>{const order=[],gates=[];const persist=async(_graph,entry)=>{order.push(`start:${entry.sequence}`);await new Promise((resolve)=>gates.push(resolve));order.push(`end:${entry.sequence}`);},session=new ProjectJournalSession({graph:{projectId:'p',value:0},applyTransaction:apply,createTransaction:transactionFactory,persist});const first=session.commit('one',[{delta:1}]),second=session.commit('two',[{delta:2}]);await new Promise((resolve)=>setTimeout(resolve,0));assert.deepEqual(order,['start:1']);gates.shift()();await first;await new Promise((resolve)=>setTimeout(resolve,0));assert.deepEqual(order,['start:1','end:1','start:2']);gates.shift()();const result=await second;assert.equal(result.entry.sequence,2);assert.equal(session.snapshot().graph.value,3);});
test('recovery replays base plus journal and rejects checkpoint mismatch',()=>{const base={projectId:'p',value:0},first=transactionFactory('one',[{delta:2}]),second=transactionFactory('two',[{delta:3}]);let log=createOperationLog({projectId:'p'});log=appendOperationLog(log,first);log=appendOperationLog(log,second);const good=recoverProjectJournalSession({recovery:{baseGraph:base,graph:{projectId:'p',value:5},log},applyTransaction:apply,createTransaction:transactionFactory,persist:async()=>{}});assert.equal(good.snapshot().graph.value,5);assert.throws(()=>recoverProjectJournalSession({recovery:{baseGraph:base,graph:{projectId:'p',value:6},log},applyTransaction:apply,createTransaction:transactionFactory,persist:async()=>{}}),/does not match/);});

test('checkpoint entries preserve undo or imported graph transitions for replay',async()=>{const persisted=[],session=new ProjectJournalSession({graph:{projectId:'p',value:1},applyTransaction:apply,createTransaction:transactionFactory,persist:async(graph,entry)=>persisted.push({graph:structuredClone(graph),entry:structuredClone(entry)})});const result=await session.checkpoint('undo',{projectId:'p',value:0},{historyAction:'undo'});assert.equal(result.entry.transaction.metadata.journalMode,'checkpoint');assert.equal(result.entry.transaction.checkpointGraph.value,0);assert.equal(session.stats().checkpoints,1);const recovery={baseGraph:{projectId:'p',value:1},graph:{projectId:'p',value:0},log:result.log},restored=recoverProjectJournalSession({recovery,applyTransaction:apply,createTransaction:transactionFactory,persist:async()=>{}});assert.equal(restored.snapshot().graph.value,0);assert.equal(persisted.length,1);});
test('failed checkpoint persistence leaves current graph intact',async()=>{const session=new ProjectJournalSession({graph:{projectId:'p',value:4},applyTransaction:apply,createTransaction:transactionFactory,persist:async()=>{throw new Error('quota');}});await assert.rejects(()=>session.checkpoint('undo',{projectId:'p',value:2}),/quota/);assert.equal(session.snapshot().graph.value,4);assert.equal(session.stats().sequence,0);});
test('persistence context is snapshotted out-of-band without entering the journal checksum payload',async()=>{const blob={opaque:true},context={assetWrites:[{assetId:'a',blob,metadata:{name:'original'}}]},seen=[];const session=new ProjectJournalSession({graph:{projectId:'p',value:0},applyTransaction:apply,createTransaction:transactionFactory,persist:async(_graph,entry,persistContext)=>seen.push({entry,persistContext})});const pending=session.commit('asset edit',[{delta:1}],{source:'ui'},{persistContext:context});context.assetWrites[0].assetId='mutated';context.assetWrites[0].metadata.name='mutated';const result=await pending;assert.notEqual(seen[0].persistContext,context);assert.equal(seen[0].persistContext.assetWrites[0].assetId,'a');assert.equal(seen[0].persistContext.assetWrites[0].metadata.name,'original');assert.equal(seen[0].persistContext.assetWrites[0].blob,blob);assert.equal(result.persistedAssetWrites,true);assert.equal(result.entry.transaction.metadata.source,'ui');assert.equal('assetWrites' in result.entry.transaction.metadata,false);assert.equal(result.graph.value,1);});

test('persistence context rejects accessors and coercive asset identities before enqueueing persistence',async()=>{let persistCalls=0,getterCalls=0,coercions=0;const session=new ProjectJournalSession({graph:{projectId:'p',value:0},applyTransaction:apply,createTransaction:transactionFactory,persist:async()=>{persistCalls+=1;}});const options={};Object.defineProperty(options,'persistContext',{enumerable:true,get(){getterCalls+=1;return null;}});assert.throws(()=>session.commit('edit',[],{},options),/journal options must contain enumerable data fields only/);assert.equal(getterCalls,0);const write={blob:{}};Object.defineProperty(write,'assetId',{enumerable:true,get(){getterCalls+=1;return'a';}});assert.throws(()=>session.commit('edit',[],{},{persistContext:{assetWrites:[write]}}),/Asset write 0 must contain enumerable data fields only/);assert.equal(getterCalls,0);assert.throws(()=>session.commit('edit',[],{},{persistContext:{assetWrites:[{assetId:{toString(){coercions+=1;return'a';}},blob:{}}]}}),/assetId must be a non-empty string/);assert.equal(coercions,0);assert.equal(persistCalls,0);});

test('journal metadata is snapshotted before queued work and rejects accessors before persistence',async()=>{const gates=[],seen=[],session=new ProjectJournalSession({graph:{projectId:'p',value:0},applyTransaction:apply,createTransaction:transactionFactory,persist:async(_graph,entry)=>{seen.push(entry.transaction.metadata);if(entry.sequence===1)await new Promise((resolve)=>gates.push(resolve));},compact:async({metadata})=>({compacted:true,metadata})});const first=session.commit('one',[{delta:1}]);await new Promise((resolve)=>setTimeout(resolve,0));const metadata={note:'original'},operations=[{delta:1}],second=session.commit('two',operations,metadata);metadata.note='mutated';operations[0].delta=99;gates.shift()();await first;const secondResult=await second;assert.equal(seen[1].note,'original');assert.equal(secondResult.graph.value,2);let getterCalls=0;const forged={};Object.defineProperty(forged,'secret',{enumerable:true,get(){getterCalls+=1;return'unsafe';}});assert.throws(()=>session.checkpoint('checkpoint',{projectId:'p',value:2},forged),/checkpoint metadata must be JSON-safe/);assert.throws(()=>session.compact(forged),/compact metadata must be JSON-safe/);assert.equal(getterCalls,0);});

test('compaction rebases the in-memory journal only after durable compare-and-swap',async()=>{const calls=[],session=new ProjectJournalSession({graph:{projectId:'p',value:0},applyTransaction:apply,createTransaction:transactionFactory,persist:async()=>{},compact:async(request)=>{calls.push(request);return{compacted:true};}});await session.commit('one',[{delta:1}]);await session.commit('two',[{delta:2}]);const before=session.snapshot();assert.equal(before.graph.value,3);assert.equal(before.log.entries.length,2);const compacted=await session.compact({reason:'threshold'});assert.equal(compacted.compacted,true);assert.equal(compacted.previousHead.sequence,2);assert.equal(calls[0].sequence,2);assert.equal(calls[0].checksum,before.log.entries[1].checksum);assert.equal(calls[0].metadata.reason,'threshold');assert.equal(session.snapshot().graph.value,3);assert.equal(session.stats().sequence,0);assert.equal(session.stats().compactions,1);const next=await session.commit('three',[{delta:4}]);assert.equal(next.entry.sequence,1);assert.equal(next.entry.previousChecksum,null);assert.equal(next.graph.value,7);});
test('failed compaction leaves the current journal head intact',async()=>{const session=new ProjectJournalSession({graph:{projectId:'p',value:0},applyTransaction:apply,createTransaction:transactionFactory,persist:async()=>{},compact:async()=>{throw new Error('stale head');}});await session.commit('one',[{delta:1}]);const checksum=session.snapshot().log.entries[0].checksum;await assert.rejects(()=>session.compact(),/stale head/);assert.equal(session.stats().sequence,1);assert.equal(session.snapshot().log.entries[0].checksum,checksum);assert.equal(session.stats().compactions,0);assert.equal(session.stats().failed,1);});
