import assert from 'node:assert/strict';
import test from 'node:test';
import { checkDecoderSupport, checkEncoderSupport, chunkBytes, createWebCodecsChunk, decodeChunkDescriptors, encodeAudioData, encodeVideoFrames, encodedChunkInit, webCodecsCapabilities } from '../webcodecs.js';
import { KernelWorkerPool, PlaybackPrefetchController } from '../kernel-pool.js';
import { WorkerKernelClient } from '../kernel-client.js';
import { createSeekIndex } from '../../../packages/core/src/seek-index.js';

const videoTrack={id:'video:1',type:'video',codec:'avc1.640028',width:640,height:360,timescale:1_000_000,duration:2,description:null};
const source=new Uint8Array([9,8,7,6,5,4]);
const descriptor={trackId:'video:1',type:'key',timestamp:100,duration:33,offset:1,byteLength:3,sequence:0,presentationTimestamp:200};
class FakeChunk{constructor(init){this.type=init.type;this.timestamp=init.timestamp;this.duration=init.duration;this.data=new Uint8Array(init.data);}}
class FakeDecoder{
  static async isConfigSupported(config){return{supported:true,config:{...config,hardwareAcceleration:'no-preference'}};}
  constructor({output,error}){this.output=output;this.error=error;this.decodeQueueSize=0;this.config=null;this.closed=false;}
  configure(config){this.config=config;}
  decode(chunk){this.decodeQueueSize++;this.output({timestamp:chunk.timestamp});this.decodeQueueSize--;}
  async flush(){}
  close(){this.closed=true;}
}
test('WebCodecs adapter exposes capabilities without assuming globals',()=>{assert.deepEqual(webCodecsCapabilities({VideoDecoder:FakeDecoder,EncodedVideoChunk:FakeChunk}),{videoDecoder:true,audioDecoder:false,encodedVideoChunk:true,encodedAudioChunk:false,videoEncoder:false,audioEncoder:false});});
test('reads encoded byte ranges and uses presentation timestamps',()=>{assert.deepEqual([...chunkBytes(source,descriptor)],[8,7,6]);assert.equal(encodedChunkInit(descriptor,source).timestamp,200);const chunk=createWebCodecsChunk(videoTrack,descriptor,source,{VideoChunk:FakeChunk});assert.deepEqual([...chunk.data],[8,7,6]);});
test('checks decoder support and decodes descriptor sequences',async()=>{const support=await checkDecoderSupport(videoTrack,{VideoDecoderCtor:FakeDecoder});assert.equal(support.supported,true);const output=[];const result=await decodeChunkDescriptors(videoTrack,[descriptor,{...descriptor,type:'delta',offset:4,byteLength:2,sequence:1,presentationTimestamp:233}],source,{VideoDecoderCtor:FakeDecoder,VideoChunk:FakeChunk,onOutput:(frame)=>output.push(frame.timestamp)});assert.equal(result.submitted,2);assert.deepEqual(output,[200,233]);});
test('rejects missing WebCodecs decoders cleanly',async()=>{const support=await checkDecoderSupport(videoTrack,{VideoDecoderCtor:null});assert.equal(support.supported,false);await assert.rejects(()=>decodeChunkDescriptors(videoTrack,[descriptor],source,{VideoDecoderCtor:null,VideoChunk:FakeChunk}),/unavailable/);});

class FakeEncodedOutput{constructor({type='delta',timestamp=0,duration=0,data=[]}={}){this.type=type;this.timestamp=timestamp;this.duration=duration;this.data=Uint8Array.from(data);this.byteLength=this.data.length;}copyTo(target){target.set(this.data);}}
class FakeVideoEncoder{static async isConfigSupported(config){return{supported:true,config};}constructor({output}){this.output=output;this.encodeQueueSize=0;this.index=0;}configure(config){this.config=config;}encode(frame,{keyFrame}={}){this.output(new FakeEncodedOutput({type:keyFrame?'key':'delta',timestamp:frame.timestamp,duration:frame.duration,data:[this.index++,7]}),{decoderConfig:{codec:this.config.codec,description:new Uint8Array([1,2]).buffer}});}async flush(){}close(){}}
class FakeAudioEncoder{static async isConfigSupported(config){return{supported:true,config};}constructor({output}){this.output=output;this.encodeQueueSize=0;this.index=0;}configure(config){this.config=config;}encode(frame){this.output(new FakeEncodedOutput({type:'key',timestamp:frame.timestamp,duration:frame.duration,data:[this.index++,9]}),{});}async flush(){}close(){}}
test('WebCodecs encoder adapters copy encoded bytes into mux-ready records',async()=>{assert.equal((await checkEncoderSupport('video',{codec:'avc1'},{VideoEncoderCtor:FakeVideoEncoder})).supported,true);const video=await encodeVideoFrames([{timestamp:0,duration:33},{timestamp:33,duration:33}],{codec:'avc1',width:16,height:16},{trackId:'v',VideoEncoderCtor:FakeVideoEncoder,keyFrameInterval:2});assert.deepEqual(video.chunks.map((c)=>c.type),['key','delta']);assert.deepEqual([...new Uint8Array(video.chunks[1].bytes)],[1,7]);assert.equal(video.chunks[0].decoderConfig.codec,'avc1');const audio=await encodeAudioData([{timestamp:0,duration:20}],{codec:'opus',sampleRate:48000,numberOfChannels:2},{trackId:'a',AudioEncoderCtor:FakeAudioEncoder});assert.equal(audio.chunks[0].trackId,'a');assert.deepEqual([...new Uint8Array(audio.chunks[0].bytes)],[0,9]);});

class FakeWorker{constructor(){this.listeners={message:[],error:[]};this.posts=[];this.terminated=false;}addEventListener(type,handler){this.listeners[type].push(handler);}postMessage(message,transfer=[]){this.posts.push({message,transfer});}emit(type,data){for(const handler of this.listeners[type])handler(type==='message'?{data}:{error:data});}terminate(){this.terminated=true;}}
test('worker client posts the transferable buffer reachable from the actual task payload',async()=>{const worker=new FakeWorker();const client=new WorkerKernelClient({workerFactory:()=>worker});const bytes=new ArrayBuffer(4);const handle=client.run('demux',{bytes},{id:'transfer',transfer:[bytes]});assert.equal(worker.posts[0].message.payload.bytes,bytes);assert.deepEqual(worker.posts[0].transfer,[bytes]);worker.emit('message',{protocol:'media.kernel.v1',type:'result',id:'transfer',result:{ok:true}});assert.deepEqual(await handle.promise,{ok:true});client.close();});
test('worker client rejects pending work on worker failure',async()=>{const worker=new FakeWorker();const client=new WorkerKernelClient({workerFactory:()=>worker});const handle=client.run('demux',{bytes:new ArrayBuffer(1)},{id:'fatal'});worker.emit('error',new Error('worker crashed'));await assert.rejects(handle.promise,/worker crashed/);client.close();});

function controlledClient(order){return{run(kind,payload){order.push(`start:${payload.name}`);let resolve;const promise=new Promise((r)=>{resolve=r;});return{promise,cancel:()=>{resolve(`cancel:${payload.name}`);},resolve};},close(){}};}
test('kernel pool prioritizes queued work after active slots finish',async()=>{const order=[];const client=controlledClient(order);const pool=new KernelWorkerPool({size:1,clientFactory:()=>client});const first=pool.schedule('x',{name:'first'},{priority:0});const low=pool.schedule('x',{name:'low'},{priority:1});const high=pool.schedule('x',{name:'high'},{priority:10});const active=pool.clients[0].busy.underlying;active.resolve('first');assert.equal(await first.promise,'first');await new Promise((r)=>setTimeout(r,0));assert.equal(pool.clients[0].busy.payload.name,'high');pool.clients[0].busy.underlying.resolve('high');assert.equal(await high.promise,'high');await new Promise((r)=>setTimeout(r,0));pool.clients[0].busy.underlying.resolve('low');assert.equal(await low.promise,'low');assert.deepEqual(order,['start:first','start:high','start:low']);pool.close();});
test('kernel pool deduplicates keyed tasks',async()=>{const pool=new KernelWorkerPool({size:1,clientFactory:()=>controlledClient([])});const a=pool.schedule('x',{name:'a'},{key:'same'});const b=pool.schedule('x',{name:'b'},{key:'same'});assert.equal(a,b);pool.clients[0].busy.underlying.resolve('done');assert.equal(await a.promise,'done');pool.close();});
test('kernel pool cancellation rejects running handles promptly',async()=>{const pool=new KernelWorkerPool({size:1,clientFactory:()=>controlledClient([])});const handle=pool.schedule('x',{name:'cancel'});assert.equal(handle.cancel(),true);await assert.rejects(handle.promise,(error)=>error.name==='AbortError');pool.close();});
test('prefetch controller derives keyframe-safe windows',()=>{const chunks=[0,1,2,3].map((s,i)=>({trackId:'video:1',type:i===0||i===2?'key':'delta',timestamp:s*1_000_000,duration:1_000_000,sequence:i}));const index=createSeekIndex(chunks);const scheduled=[];const fakePool={schedule(kind,payload,options){scheduled.push({kind,payload,options});return{promise:Promise.resolve(),cancel(){}};}};const controller=new PlaybackPrefetchController({pool:fakePool,index,trackIds:['video:1'],payloadForWindow:(window)=>({window})});const result=controller.update({time:2.5,direction:1,horizon:2});assert.equal(result.windows[0].start,2);assert.equal(scheduled[0].kind,'decode-video');controller.cancel();});
