import test from 'node:test';
import assert from 'node:assert/strict';
import { mergeAssetRetentionGraph, garbageCollectStoredAssetsWithRetention } from '../storage-maintenance.js';

function request(result){const r={result:undefined,error:null};queueMicrotask(()=>{r.result=result;r.onsuccess?.();});return r;}
function fakeDb({graph,assets}){const rows=new Map(assets.map((row)=>[row.id,{...row}]));const calls=[];return{rows,calls,db:{transaction(names,mode){calls.push({names:[...names],mode});const tx={oncomplete:null,onerror:null,onabort:null,error:null,abort(){this.onabort?.();},objectStore(name){if(name==='workspace')return{get(){return request({key:'current',graph});}};return{getAll(){return request([...rows.values()]);},delete(id){rows.delete(id);}};}};setTimeout(()=>tx.oncomplete?.(),0);return tx;}}};}

test('retention graph unions persisted and history-only asset identities',()=>{const merged=mergeAssetRetentionGraph({projectId:'p',nodes:{a:{id:'a',kind:'asset',props:{hash:'ha'}}}},{nodes:{b:{id:'b',kind:'asset',props:{hash:'hb'}}}});assert.deepEqual(Object.keys(merged.nodes).sort(),['a','b']);});

test('retention graph normalization rejects executable and coercive fields without execution',()=>{let getterCalls=0,coercions=0;const graph={nodes:{}};Object.defineProperty(graph,'projectId',{enumerable:true,get(){getterCalls+=1;return'p';}});assert.throws(()=>mergeAssetRetentionGraph(graph,null),/projectId must be an enumerable data field/);assert.equal(getterCalls,0);assert.throws(()=>mergeAssetRetentionGraph({projectId:{toString(){coercions+=1;return'p';}},nodes:{}},null),/projectId must be a non-empty string/);assert.equal(coercions,0);const node={kind:'asset',props:{hash:'h'}};Object.defineProperty(node,'id',{enumerable:true,get(){getterCalls+=1;return'a';}});assert.throws(()=>mergeAssetRetentionGraph({nodes:{a:node}},null),/node a id must be an enumerable data field/);assert.equal(getterCalls,0);});

test('retention graph output is inert minimal asset data instead of caller-owned nodes',()=>{let getterCalls=0;const node={id:'a',kind:'asset',props:{hash:'ha'},metadata:{private:true}};Object.defineProperty(node,'secret',{enumerable:true,get(){getterCalls+=1;return'private';}});const merged=mergeAssetRetentionGraph({projectId:'p',nodes:{a:node}},null);assert.equal(getterCalls,0);assert.notEqual(merged.nodes.a,node);assert.deepEqual(merged.nodes.a,{id:'a',kind:'asset',props:{hash:'ha'}});assert.equal('metadata'in merged.nodes.a,false);assert.equal('secret'in merged.nodes.a,false);});

test('retention-aware cleanup preserves persisted, undo and fingerprint sources',async()=>{const now=Date.parse('2026-08-15T00:00:00Z'),fake=fakeDb({graph:{projectId:'p',nodes:{current:{id:'current',kind:'asset',props:{hash:'hc'}}}},assets:[{id:'current',hash:'hc',size:1,savedAt:'2020-01-01T00:00:00Z'},{id:'undo',hash:'hu',size:2,savedAt:'2020-01-01T00:00:00Z'},{id:'alias',hash:'hu',size:3,savedAt:'2020-01-01T00:00:00Z'},{id:'old',hash:'old',size:4,savedAt:'2020-01-01T00:00:00Z'}]});const result=await garbageCollectStoredAssetsWithRetention({retentionGraph:{nodes:{undo:{id:'undo',kind:'asset',props:{hash:'hu'}}}},now,olderThanMs:1000,databaseProvider:async()=>fake.db});assert.deepEqual(result.deletedIds,['old']);assert.equal(fake.rows.has('current'),true);assert.equal(fake.rows.has('undo'),true);assert.equal(fake.rows.has('alias'),true);assert.equal(fake.rows.has('old'),false);assert.deepEqual(fake.calls,[{names:['workspace','assets'],mode:'readwrite'}]);});

test('retention cleanup preflights options before database access and snapshots retention state',async()=>{let getterCalls=0,providerCalls=0;const forged={databaseProvider:async()=>{providerCalls+=1;return null;}};Object.defineProperty(forged,'now',{enumerable:true,get(){getterCalls+=1;return 1;}});await assert.rejects(()=>garbageCollectStoredAssetsWithRetention(forged),/options must contain enumerable data fields only/);assert.equal(getterCalls,0);assert.equal(providerCalls,0);let release;const gate=new Promise((resolve)=>{release=resolve;}),fake=fakeDb({graph:{projectId:'p',nodes:{}},assets:[{id:'undo',hash:'original',size:1,savedAt:'2020-01-01T00:00:00Z'}]}),retentionGraph={nodes:{undo:{id:'undo',kind:'asset',props:{hash:'original'}}}},pending=garbageCollectStoredAssetsWithRetention({retentionGraph,now:Date.parse('2026-08-15T00:00:00Z'),olderThanMs:1000,databaseProvider:async()=>{providerCalls+=1;await gate;return fake.db;}});retentionGraph.nodes.undo.id='mutated';retentionGraph.nodes.undo.props.hash='mutated';release();const result=await pending;assert.deepEqual(result.deletedIds,[]);assert.equal(fake.rows.has('undo'),true);assert.equal(providerCalls,1);});

test('retention cleanup rejects stored workspace graph accessors without execution',async()=>{let getterCalls=0;const current={key:'current'};Object.defineProperty(current,'graph',{enumerable:true,get(){getterCalls+=1;return{nodes:{}};}});const db={transaction(){const tx={oncomplete:null,onerror:null,onabort:null,error:null,abort(){this.onabort?.();},objectStore(name){if(name==='workspace')return{get(){return request(current);}};return{getAll(){return request([]);},delete(){}};}};setTimeout(()=>tx.oncomplete?.(),0);return tx;}};await assert.rejects(()=>garbageCollectStoredAssetsWithRetention({databaseProvider:async()=>db}),/Stored workspace graph must be an enumerable data field/);assert.equal(getterCalls,0);});

test('retention cleanup rejects database method accessors without execution',async()=>{let getterCalls=0;const db={};Object.defineProperty(db,'transaction',{enumerable:true,get(){getterCalls+=1;return()=>{};}});await assert.rejects(()=>garbageCollectStoredAssetsWithRetention({databaseProvider:async()=>db}),/transaction must be a data method/);assert.equal(getterCalls,0);});
