function bitrateOf(variant){return Number(variant?.averageBandwidth??variant?.bandwidth??0)||0;}
function pixelsOf(variant){const w=Number(variant?.width??0),h=Number(variant?.height??0);return w>0&&h>0?w*h:0;}
export class ThroughputEstimator{
  constructor({fastHalfLife=3,slowHalfLife=10,initialBps=5_000_000}={}){this.fastHalfLife=Math.max(.1,fastHalfLife);this.slowHalfLife=Math.max(this.fastHalfLife,slowHalfLife);this.fast=initialBps;this.slow=initialBps;this.samples=0;}
  sample(bytes,durationSeconds){const seconds=Math.max(.001,Number(durationSeconds)||0),bps=Math.max(1,Number(bytes)*8/seconds);this.fast=this.#update(this.fast,bps,this.fastHalfLife);this.slow=this.#update(this.slow,bps,this.slowHalfLife);this.samples++;return this.estimate();}
  #update(current,value,halfLife){const alpha=1-Math.pow(.5,1/halfLife);return current+(value-current)*alpha;}
  estimate(){return Math.min(this.fast,this.slow);}
  snapshot(){return{samples:this.samples,fastBps:this.fast,slowBps:this.slow,estimateBps:this.estimate()};}
}
export function selectAdaptiveVariant(variants,{bandwidthBps=Infinity,safetyFactor=.82,maxWidth=Infinity,maxHeight=Infinity,maxPixels=Infinity,preferredType='video',currentId=null,upgradeMargin=1.15}={}){const candidates=(variants??[]).filter((variant)=>!preferredType||variant.type==null||variant.type===preferredType).filter((variant)=>Number(variant.width??0)<=maxWidth&&Number(variant.height??0)<=maxHeight&&(pixelsOf(variant)===0||pixelsOf(variant)<=maxPixels)).sort((a,b)=>bitrateOf(a)-bitrateOf(b)||pixelsOf(a)-pixelsOf(b));if(!candidates.length)return null;const budget=Math.max(1,Number(bandwidthBps)||1)*Math.max(.1,Math.min(1,safetyFactor)),affordable=candidates.filter((variant)=>bitrateOf(variant)<=budget||bitrateOf(variant)===0),chosen=affordable.at(-1)??candidates[0];if(currentId){const current=candidates.find((variant)=>variant.id===currentId);if(current&&bitrateOf(chosen)>bitrateOf(current)&&bandwidthBps<bitrateOf(chosen)*upgradeMargin)return current;}return chosen;}
export function manifestMediaSegments(manifest,{variantId=null,includeParts=true}={}){if(!manifest)return[];if(manifest.protocol==='hls'&&manifest.kind==='media')return [...(manifest.segments??[]),...(includeParts?manifest.parts??[]:[])].sort((a,b)=>a.start-b.start||Number(a.partial)-Number(b.partial));const variant=(manifest.variants??[]).find((item)=>item.id===variantId)??manifest.variants?.[0];return variant?.segments??[];}
export function liveEdge(manifest,{variantId=null}={}){const segments=manifestMediaSegments(manifest,{variantId});return segments.reduce((max,segment)=>Math.max(max,Number(segment.start)+Number(segment.duration)),0);}
export function recommendedLivePosition(manifest,{variantId=null}={}){const edge=liveEdge(manifest,{variantId}),hold=Number(manifest.serverControl?.partHoldBack??manifest.serverControl?.holdBack??manifest.suggestedPresentationDelay??((manifest.targetDuration??2)*3));return Math.max(0,edge-Math.max(0,hold));}
export function nextAdaptiveRequests(manifest,{variantId=null,afterSequence=null,playhead=0,maxRequests=3,includeParts=true}={}){const segments=manifestMediaSegments(manifest,{variantId,includeParts});let filtered=segments.filter((segment)=>afterSequence==null||Number(segment.sequence)>Number(afterSequence)||segment.partial&&Number(segment.sequence)>=Number(afterSequence));if(afterSequence==null)filtered=filtered.filter((segment)=>Number(segment.start)+Number(segment.duration)>Number(playhead));return filtered.slice(0,Math.max(0,maxRequests));}
export function mergeAdaptiveWindow(previous,next,{variantId=null}={}){if(!previous)return next;if(!next)return previous;if(previous.protocol!==next.protocol)return next;if(next.protocol==='hls'&&next.kind==='media'){const key=(segment)=>`${segment.sequence}:${segment.partial?'p':'s'}:${segment.url}`,map=new Map([...(previous.segments??[]),...(previous.parts??[])].map((segment)=>[key(segment),segment]));for(const segment of [...(next.segments??[]),...(next.parts??[])])map.set(key(segment),segment);const all=[...map.values()].sort((a,b)=>a.start-b.start||a.sequence-b.sequence),minSequence=Math.max(0,Number(next.mediaSequence??0));return{...next,segments:all.filter((s)=>!s.partial&&s.sequence>=minSequence),parts:all.filter((s)=>s.partial&&s.sequence>=minSequence)};}return next;}
export class AdaptiveSessionState{
  constructor({variantId=null,initialBandwidthBps=5_000_000}={}){this.variantId=variantId;this.estimator=new ThroughputEstimator({initialBps:initialBandwidthBps});this.bufferedUntil=0;this.lastSequence=null;this.discontinuities=0;this.downloads=0;}
  choose(manifest,options={}){const variant=selectAdaptiveVariant(manifest?.variants??[],{...options,bandwidthBps:options.bandwidthBps??this.estimator.estimate(),currentId:this.variantId});if(variant)this.variantId=variant.id;return variant;}
  recordDownload({bytes,durationSeconds,segment}){this.estimator.sample(bytes,durationSeconds);this.downloads++;if(segment){this.lastSequence=segment.sequence;this.bufferedUntil=Math.max(this.bufferedUntil,Number(segment.start)+Number(segment.duration));if(segment.discontinuity)this.discontinuities++;}return this.snapshot();}
  snapshot(){return{variantId:this.variantId,bandwidth:this.estimator.snapshot(),bufferedUntil:this.bufferedUntil,lastSequence:this.lastSequence,discontinuities:this.discontinuities,downloads:this.downloads};}
}
