import { createCompositeRangeSource } from './composite-range-source.js';
import { demuxFragmentedIsoBmffSource } from './isobmff-fragment-range.js';
function bytesOf(value){if(value instanceof Uint8Array)return value;if(value instanceof ArrayBuffer)return new Uint8Array(value);if(ArrayBuffer.isView(value))return new Uint8Array(value.buffer,value.byteOffset,value.byteLength);throw new Error('CMAF segment must be binary');}
export class CmafSegmentSession{
  constructor(initSegment,{container='mp4',maxSegments=6}={}){this.init=bytesOf(initSegment).slice();this.container=container;this.maxSegments=Math.max(1,Math.round(Number(maxSegments)||6));this.segments=new Map();this.order=[];this.sequence=0;this.evictions=0;this.totalBytes=this.init.byteLength;}
  async push(segment,{id=null,signal}={}){const bytes=bytesOf(segment).slice(),segmentId=String(id??`segment-${this.sequence++}`);if(this.segments.has(segmentId))throw new Error(`CMAF segment already exists: ${segmentId}`);const source=createCompositeRangeSource([this.init,bytes],{id:`cmaf:${segmentId}`}),plan=await demuxFragmentedIsoBmffSource(source,{container:this.container,signal});const initSize=this.init.byteLength,chunks=plan.chunks.map((chunk)=>{const localOffset=Number(chunk.offset)-initSize;if(localOffset<0||localOffset+Number(chunk.byteLength)>bytes.byteLength)throw new Error(`CMAF chunk ${chunk.trackId}:${chunk.sequence} points outside media segment`);return{...chunk,segmentId,segmentOffset:localOffset,offset:localOffset};});const record={id:segmentId,bytes,chunks,tracks:plan.tracks,duration:plan.duration,metadata:plan.metadata,acked:false,createdOrder:this.sequence};this.segments.set(segmentId,record);this.order.push(segmentId);this.totalBytes+=bytes.byteLength;this.#evict();return{...record,bytes:undefined};}
  async readChunk(chunk){const record=this.segments.get(String(chunk.segmentId));if(!record)throw new Error(`CMAF segment is no longer buffered: ${chunk.segmentId}`);const offset=Number(chunk.segmentOffset??chunk.offset),length=Number(chunk.byteLength);if(offset<0||length<0||offset+length>record.bytes.byteLength)throw new Error('CMAF chunk range exceeds buffered segment');return record.bytes.slice(offset,offset+length);}
  acknowledge(segmentId){const record=this.segments.get(String(segmentId));if(!record)return false;record.acked=true;this.#evict(true);return true;}
  #evict(ackedOnly=false){while(this.order.length){const id=this.order[0],record=this.segments.get(id);if(!record){this.order.shift();continue;}const over=this.order.length>this.maxSegments;if(!(record.acked&&(ackedOnly||over))&&!over)break;if(!record.acked&&ackedOnly)break;this.order.shift();this.segments.delete(id);this.totalBytes-=record.bytes.byteLength;this.evictions++;}}
  stats(){return{segments:this.segments.size,maxSegments:this.maxSegments,bytes:this.totalBytes,initBytes:this.init.byteLength,evictions:this.evictions,ids:[...this.order]};}
  clear(){this.segments.clear();this.order=[];this.totalBytes=this.init.byteLength;}
}
