import {canonicalOperationLogJson,operationLogHead} from './operation-log.js';
import {validateOperationBatchStructure} from './operation-batch.js';
import {TrustRegistryError} from './trust-registry.js';

export const COLLABORATION_WIRE_SCHEMA='media.collaboration-wire.v1';
const encoder=new TextEncoder();
const decoder=new TextDecoder('utf-8',{fatal:true});
export class CollaborationWireError extends Error{constructor(message,{code='ERR_COLLABORATION_WIRE',statusCode=400,requestId=null}={}){super(message);this.name='CollaborationWireError';this.code=code;this.statusCode=statusCode;this.requestId=requestId;}}
function clone(value){return JSON.parse(canonicalOperationLogJson(value));}
function token(value,label,{maxLength=128}={}){if(typeof value!=='string'||!value||value.length>maxLength)throw new CollaborationWireError(`${label} is invalid`,{code:'ERR_COLLABORATION_WIRE_FORMAT'});return value;}
function bytesOf(value){if(typeof value==='string')return encoder.encode(value);if(value instanceof Uint8Array)return value;if(value instanceof ArrayBuffer)return new Uint8Array(value);if(ArrayBuffer.isView(value))return new Uint8Array(value.buffer,value.byteOffset,value.byteLength);throw new CollaborationWireError('Collaboration payload must be UTF-8 JSON',{code:'ERR_COLLABORATION_WIRE_FORMAT'});}
function assertTopLevelKeys(value,allowed){for(const key of Object.keys(value))if(!allowed.has(key))throw new CollaborationWireError(`Unsupported collaboration envelope field: ${key}`,{code:'ERR_COLLABORATION_WIRE_FORMAT',requestId:value.requestId??null});}
function errorEnvelope({requestId=null,code,message}){return{schema:COLLABORATION_WIRE_SCHEMA,type:'error',requestId,code,message};}
function encodeBounded(value,maxBytes){const text=canonicalOperationLogJson(value),bytes=encoder.encode(text);if(bytes.byteLength>maxBytes)throw new CollaborationWireError('Collaboration response exceeds byte limit',{code:'ERR_COLLABORATION_WIRE_RESPONSE_TOO_LARGE',statusCode:500,requestId:value.requestId??null});return bytes;}
function sanitizeConflict(conflict){return{localSequence:conflict.localSequence,localTransactionId:conflict.localTransactionId,remoteSequence:conflict.remoteSequence,remoteTransactionId:conflict.remoteTransactionId,leftOperationIndex:conflict.leftOperationIndex,rightOperationIndex:conflict.rightOperationIndex,resources:clone(conflict.resources??[])};}
function resultResponse(request,outcome,{maxConflicts=100}={}){const result=outcome.result??{},conflicts=(result.conflicts??[]).slice(0,Math.max(0,Number(maxConflicts)||0)).map(sanitizeConflict);return{schema:COLLABORATION_WIRE_SCHEMA,type:'batch.result',requestId:request.requestId,status:result.status??'applied',verified:true,committed:Boolean(outcome.committed),requiresResign:Boolean(result.requiresResign),safe:Boolean(result.safe),head:result.head??operationLogHead(outcome.log),localEntries:Number(result.localEntries??0),remoteEntries:Number(result.remoteEntries??request.batch.entries.length),conflicts,conflictsTruncated:Math.max(0,(result.conflicts??[]).length-conflicts.length)};}
export function createCollaborationSubmitRequest(batch,{requestId}={}){validateOperationBatchStructure(batch,{requireSignature:true});return{schema:COLLABORATION_WIRE_SCHEMA,type:'batch.submit',requestId:token(requestId,'Collaboration requestId'),batch:clone(batch)};}
export function encodeCollaborationWireRequest(request,{maxBytes=1024*1024}={}){const parsed=parseCollaborationWireRequest(canonicalOperationLogJson(request),{maxBytes});return encodeBounded(parsed,Math.max(1,Number(maxBytes)||1));}
export function parseCollaborationWireRequest(value,{maxBytes=1024*1024}={}){const bytes=bytesOf(value),limit=Math.max(1,Number(maxBytes)||1);if(bytes.byteLength>limit)throw new CollaborationWireError('Collaboration request exceeds byte limit',{code:'ERR_COLLABORATION_WIRE_TOO_LARGE',statusCode:413});let parsed;try{parsed=JSON.parse(decoder.decode(bytes));}catch(error){throw new CollaborationWireError('Collaboration request must be valid UTF-8 JSON',{code:'ERR_COLLABORATION_WIRE_JSON',statusCode:400});}if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new CollaborationWireError('Collaboration request must be an object',{code:'ERR_COLLABORATION_WIRE_FORMAT'});assertTopLevelKeys(parsed,new Set(['schema','type','requestId','batch']));if(parsed.schema!==COLLABORATION_WIRE_SCHEMA)throw new CollaborationWireError(`Unsupported collaboration wire schema: ${parsed.schema}`,{code:'ERR_COLLABORATION_WIRE_SCHEMA',requestId:parsed.requestId??null});if(parsed.type!=='batch.submit')throw new CollaborationWireError(`Unsupported collaboration request type: ${parsed.type}`,{code:'ERR_COLLABORATION_WIRE_TYPE',requestId:parsed.requestId??null});token(parsed.requestId,'Collaboration requestId');try{validateOperationBatchStructure(parsed.batch,{requireSignature:true});}catch(error){throw new CollaborationWireError('Collaboration batch is malformed',{code:'ERR_COLLABORATION_WIRE_BATCH',statusCode:400,requestId:parsed.requestId});}return{schema:COLLABORATION_WIRE_SCHEMA,type:'batch.submit',requestId:parsed.requestId,batch:clone(parsed.batch)};}
export async function submitCollaborationWirePayload(value,{submit,maxRequestBytes=1024*1024,maxResponseBytes=256*1024,maxConflicts=100}={}){if(typeof submit!=='function')throw new CollaborationWireError('Collaboration wire submit callback is required',{code:'ERR_COLLABORATION_WIRE_CONFIG',statusCode:500});let request;try{request=parseCollaborationWireRequest(value,{maxBytes:maxRequestBytes});const outcome=await submit(request.batch);if(!outcome?.verified){const response=errorEnvelope({requestId:request.requestId,code:'authentication-rejected',message:'Authentication rejected'});return{statusCode:401,body:encodeBounded(response,maxResponseBytes),response};}const response=resultResponse(request,outcome,{maxConflicts});return{statusCode:200,body:encodeBounded(response,maxResponseBytes),response};}catch(error){if(error instanceof CollaborationWireError){const response=errorEnvelope({requestId:error.requestId??request?.requestId??null,code:error.code,message:error.statusCode>=500?'Collaboration service error':error.message});return{statusCode:error.statusCode,body:encodeBounded(response,maxResponseBytes),response};}if(error instanceof TrustRegistryError){const replay=error.code==='ERR_TRUST_REPLAY',response=errorEnvelope({requestId:request?.requestId??null,code:replay?'replay-rejected':'authentication-rejected',message:replay?'Replay rejected':'Authentication rejected'});return{statusCode:replay?409:401,body:encodeBounded(response,maxResponseBytes),response};}throw error;}}
