import {canonicalOperationLogJson} from './operation-log.js';
import {submitCollaborationWirePayload} from './collaboration-wire.js';

export const DEFAULT_COLLABORATION_HTTP_PATH='/api/media/collaboration/v1/batches';
class CollaborationHttpError extends Error{constructor(message,{statusCode=400,code='http-error'}={}){super(message);this.name='CollaborationHttpError';this.statusCode=statusCode;this.code=code;}}
function jsonResponse(statusCode,value,headers={}){return new Response(canonicalOperationLogJson(value),{status:statusCode,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});}
function errorResponse(statusCode,code,message,headers={}){return jsonResponse(statusCode,{schema:'media.collaboration-http.v1',type:'error',code,message},headers);}
async function originPolicy(request,allowedOrigins){const origin=request.headers.get('origin');if(!origin)return{allowed:true,corsOrigin:null};let target;try{target=new URL(request.url).origin;}catch{return{allowed:false,corsOrigin:null};}if(origin===target)return{allowed:true,corsOrigin:null};if(allowedOrigins==null)return{allowed:false,corsOrigin:null};const allowed=typeof allowedOrigins==='function'?await allowedOrigins(origin,request):new Set(allowedOrigins).has(origin);return{allowed:allowed===true,corsOrigin:allowed===true?origin:null};}
function corsHeaders(origin,{preflight=false,allowedHeaders=['content-type','authorization']}={}){if(!origin)return{};const headers={'Access-Control-Allow-Origin':origin,'Vary':'Origin'};if(preflight){headers['Access-Control-Allow-Methods']='POST, OPTIONS';headers['Access-Control-Allow-Headers']=allowedHeaders.join(', ');headers['Access-Control-Max-Age']='600';}return headers;}
function preflightHeadersAllowed(request,allowedHeaders){const raw=request.headers.get('access-control-request-headers');if(!raw)return true;const allowed=new Set(allowedHeaders.map((value)=>String(value).toLowerCase()));return raw.split(',').map((value)=>value.trim().toLowerCase()).filter(Boolean).every((value)=>allowed.has(value));}
async function readBoundedBody(request,maxBytes){const limit=Math.max(1,Number(maxBytes)||1),declared=Number(request.headers.get('content-length'));if(Number.isFinite(declared)&&declared>limit)throw new CollaborationHttpError('Request body exceeds byte limit',{statusCode:413,code:'request-too-large'});if(!request.body)return new Uint8Array();const reader=request.body.getReader(),parts=[];let total=0;try{for(;;){const {done,value}=await reader.read();if(done)break;const bytes=value instanceof Uint8Array?value:new Uint8Array(value);total+=bytes.byteLength;if(total>limit){await reader.cancel('body too large').catch(()=>{});throw new CollaborationHttpError('Request body exceeds byte limit',{statusCode:413,code:'request-too-large'});}parts.push(bytes);}}finally{reader.releaseLock?.();}const out=new Uint8Array(total);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.byteLength;}return out;}
export function createCollaborationHttpHandler({submit,path=DEFAULT_COLLABORATION_HTTP_PATH,maxBodyBytes=1024*1024,maxResponseBytes=256*1024,maxConflicts=100,allowedOrigins=null,allowedRequestHeaders=['content-type','authorization'],authorizeRequest=async()=>true}={}){if(typeof submit!=='function')throw new Error('Collaboration HTTP handler requires submit callback');if(typeof authorizeRequest!=='function')throw new Error('Collaboration HTTP authorizeRequest must be a function');const route=String(path),allowedHeaders=[...new Set(allowedRequestHeaders.map((value)=>String(value).toLowerCase()))];return async function handleCollaborationHttp(request){let cors={};try{if(!(request instanceof Request))throw new CollaborationHttpError('Request object required',{statusCode:400,code:'invalid-request'});const url=new URL(request.url);if(url.pathname!==route)return errorResponse(404,'not-found','Not found');const origin=await originPolicy(request,allowedOrigins);if(!origin.allowed)return errorResponse(403,'origin-rejected','Origin rejected');cors=corsHeaders(origin.corsOrigin);if(request.method==='OPTIONS'){if(!origin.corsOrigin)return errorResponse(405,'method-not-allowed','Method not allowed',{'Allow':'POST'});if(request.headers.get('access-control-request-method')!=='POST'||!preflightHeadersAllowed(request,allowedHeaders))return errorResponse(403,'preflight-rejected','Preflight rejected',cors);return new Response(null,{status:204,headers:{...corsHeaders(origin.corsOrigin,{preflight:true,allowedHeaders}),'Cache-Control':'no-store'}});}if(request.method!=='POST')return errorResponse(405,'method-not-allowed','Method not allowed',{...cors,'Allow':'POST'});const contentType=(request.headers.get('content-type')??'').split(';',1)[0].trim().toLowerCase();if(contentType!=='application/json')return errorResponse(415,'unsupported-media-type','Content-Type must be application/json',cors);const authorized=await authorizeRequest(request);if(authorized!==true)return errorResponse(401,'authorization-rejected','Authorization rejected',cors);const body=await readBoundedBody(request,maxBodyBytes),result=await submitCollaborationWirePayload(body,{submit,maxRequestBytes:maxBodyBytes,maxResponseBytes,maxConflicts});return new Response(result.body,{status:result.statusCode,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...cors}});}catch(error){if(error instanceof CollaborationHttpError)return errorResponse(error.statusCode,error.code,error.message,cors);return errorResponse(500,'internal-error','Collaboration service error',cors);}};}
