export const BLEND_MODES=Object.freeze(['normal','multiply','screen','overlay','add','darken','lighten']);
export const TRANSITION_TYPES=Object.freeze(['crossfade','wipe-left','wipe-right','dip-to-black']);
const blendSet=new Set(BLEND_MODES),transitionSet=new Set(TRANSITION_TYPES);
export function normalizeBlendMode(value='normal'){const mode=String(value||'normal').toLowerCase();if(!blendSet.has(mode))throw new Error(`Unsupported blend mode: ${value}`);return mode;}
export function normalizeMask(mask){if(!mask)return null;const assetId=String(mask.assetId??mask.sourceAssetId??'');if(!assetId)throw new Error('Mask requires assetId');return{assetId,invert:Boolean(mask.invert),opacity:Math.max(0,Math.min(1,Number(mask.opacity??1))),feather:Math.max(0,Number(mask.feather??0)),mode:String(mask.mode??'alpha')};}
export function normalizeTransition(value){if(!value)return null;const type=String(value.type??'crossfade').toLowerCase();if(!transitionSet.has(type))throw new Error(`Unsupported transition type: ${type}`);const duration=Math.max(0,Number(value.duration??0));return{type,duration,easing:String(value.easing??'linear')};}
function eased(t,easing){const x=Math.max(0,Math.min(1,t));if(easing==='ease-in')return x*x;if(easing==='ease-out')return 1-(1-x)*(1-x);if(easing==='ease-in-out')return x<.5?2*x*x:1-((-2*x+2)**2)/2;return x;}
export function transitionAtTime(node,time){const start=Number(node?.props?.start??0),duration=Number(node?.props?.duration??0),end=start+duration,now=Number(time),incoming=normalizeTransition(node?.props?.transitionIn),outgoing=normalizeTransition(node?.props?.transitionOut);if(incoming?.duration>0&&now<start+incoming.duration)return{...incoming,direction:'in',progress:eased((now-start)/incoming.duration,incoming.easing)};if(outgoing?.duration>0&&now>end-outgoing.duration)return{...outgoing,direction:'out',progress:eased((end-now)/outgoing.duration,outgoing.easing)};return null;}
export function compositingState(node,time){return{blendMode:normalizeBlendMode(node?.props?.blendMode??'normal'),mask:normalizeMask(node?.props?.mask),transition:transitionAtTime(node,time)};}
