function number(value,fallback=null){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function resolveUrl(value,base){if(!value)return base??null;try{return base?new URL(value,base).href:String(value);}catch{return String(value);}}
export function parseIsoDurationV2(value){if(value==null)return null;const m=/^P(?:(\d+(?:\.\d+)?)D)?(?:T(?:(\d+(?:\.\d+)?)H)?(?:(\d+(?:\.\d+)?)M)?(?:(\d+(?:\.\d+)?)S)?)?$/.exec(String(value));return m?Number(m[1]??0)*86400+Number(m[2]??0)*3600+Number(m[3]??0)*60+Number(m[4]??0):null;}
function attrs(source=''){const out={};for(const m of source.matchAll(/([\w:.-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g))out[m[1]]=m[2]??m[3]??'';return out;}
function name(value){return String(value).split(':').at(-1);}
export function parseXmlLiteV2(xml){const root={name:'#document',attrs:{},children:[],text:''},stack=[root];for(const token of String(xml??'').replace(/<!--[\s\S]*?-->/g,'').match(/<[^>]+>|[^<]+/g)??[]){if(token.startsWith('<?')||token.startsWith('<!'))continue;if(token.startsWith('</')){if(stack.length>1)stack.pop();continue;}if(token.startsWith('<')){const self=/\/\s*>$/.test(token),m=/^<\s*([^\s/>]+)([\s\S]*?)\/?\s*>$/.exec(token);if(!m)continue;const node={name:name(m[1]),qualifiedName:m[1],attrs:attrs(m[2]),children:[],text:''};stack.at(-1).children.push(node);if(!self)stack.push(node);}else stack.at(-1).text+=token;}return root.children[0]??root;}
const child=(node,n)=>node?.children?.find(v=>v.name===n)??null,children=(node,n)=>node?.children?.filter(v=>v.name===n)??[];
function baseOf(node,parent){const text=child(node,'BaseURL')?.text?.trim();return text?resolveUrl(text,parent):parent;}
function templateOf(node){const t=child(node,'SegmentTemplate');if(!t)return null;return{...t.attrs,timeline:child(t,'SegmentTimeline')};}
function mergeTemplate(...items){let out=null;for(const item of items)if(item)out={...(out??{}),...item,timeline:item.timeline??out?.timeline??null};return out;}
function replaceTemplate(value,vars){return String(value??'').replace(/\$\$/g,'\0').replace(/\$(RepresentationID|Bandwidth|Number|Time)(?:%0(\d+)d)?\$/g,(_,key,width)=>{const v=vars[key]??'';return width?String(v).padStart(Number(width),'0'):String(v);}).replace(/\0/g,'$');}
function periodWindows(periodNodes,mpdDuration){const result=[];let cursor=0;for(let i=0;i<periodNodes.length;i++){const node=periodNodes[i],explicit=parseIsoDurationV2(node.attrs.start),start=explicit??cursor,nextExplicit=parseIsoDurationV2(periodNodes[i+1]?.attrs?.start),declared=parseIsoDurationV2(node.attrs.duration);let duration=declared;if(duration==null&&nextExplicit!=null)duration=Math.max(0,nextExplicit-start);if(duration==null&&i===periodNodes.length-1&&mpdDuration!=null)duration=Math.max(0,mpdDuration-start);result.push({index:i,id:node.attrs.id??`period-${i}`,start,duration,end:duration==null?null:start+duration,node});if(duration!=null)cursor=start+duration;else cursor=start;}return result;}
function timelineEntries(timeline,{timescale,periodDuration,maxSegments}){const out=[];let current=0;for(const s of children(timeline,'S')){const d=number(s.attrs.d,0);if(!(d>0))continue;if(s.attrs.t!=null)current=number(s.attrs.t,current);let repeat=Math.trunc(number(s.attrs.r,0));if(repeat<0)repeat=periodDuration==null?0:Math.max(0,Math.ceil(periodDuration*timescale/d)-1);for(let i=0;i<=repeat&&out.length<maxSegments;i++){out.push({time:current,duration:d});current+=d;}}return out;}
function protection(nodes){return nodes.flatMap(n=>children(n,'ContentProtection')).map(n=>({schemeIdUri:n.attrs.schemeIdUri??null,value:n.attrs.value??null,defaultKID:n.attrs['cenc:default_KID']??n.attrs.default_KID??null,pssh:child(n,'pssh')?.text?.trim()??null}));}
function serviceDescription(root){const s=child(root,'ServiceDescription');if(!s)return null;const latency=child(s,'Latency'),rate=child(s,'PlaybackRate');return{id:s.attrs.id??null,latency:latency?{target:number(latency.attrs.target),min:number(latency.attrs.min),max:number(latency.attrs.max)}:null,playbackRate:rate?{min:number(rate.attrs.min),max:number(rate.attrs.max)}:null};}
function utcTiming(root){return children(root,'UTCTiming').map(n=>({schemeIdUri:n.attrs.schemeIdUri??null,value:n.attrs.value??null}));}
function eventStreams(period,periodStart){return children(period,'EventStream').flatMap(stream=>{const timescale=Math.max(1,number(stream.attrs.timescale,1));return children(stream,'Event').map(event=>({schemeIdUri:stream.attrs.schemeIdUri??null,value:stream.attrs.value??null,id:event.attrs.id??null,presentationTime:number(event.attrs.presentationTime,0),duration:number(event.attrs.duration,0),time:periodStart+number(event.attrs.presentationTime,0)/timescale,durationSeconds:number(event.attrs.duration,0)/timescale,messageData:event.attrs.messageData??event.text?.trim()??''}));});}
function segmentsFromTemplate(template,{period,representationId,bandwidth,baseUrl,maxSegments,isDynamic,presentationNow,timeShiftBufferDepth}){if(!template?.media)return[];const timescale=Math.max(1,number(template.timescale,1)),startNumber=Math.max(0,Math.trunc(number(template.startNumber,1))),pto=number(template.presentationTimeOffset,0),ato=number(template.availabilityTimeOffset,0),complete=String(template.availabilityTimeComplete??'true')!=='false',entries=timelineEntries(template.timeline,{timescale,periodDuration:period.duration,maxSegments}),out=[];
  if(entries.length){entries.forEach((e,i)=>{const sequence=startNumber+i,start=period.start+(e.time-pto)/timescale;out.push({id:`dash:${period.id}:${representationId}:${sequence}`,periodIndex:period.index,sequence,url:resolveUrl(replaceTemplate(template.media,{RepresentationID:representationId,Bandwidth:bandwidth,Number:sequence,Time:e.time}),baseUrl),start,duration:e.duration/timescale,time:e.time,availabilityTimeOffset:ato,availabilityTimeComplete:complete,partial:false});});return out;}
  const units=number(template.duration);if(!(units>0))return out;const duration=units/timescale;let first=0,count=period.duration==null?Math.min(12,maxSegments):Math.min(maxSegments,Math.ceil(period.duration/duration));if(isDynamic&&presentationNow!=null){const localNow=Math.max(0,presentationNow-period.start),windowStart=Math.max(0,localNow-(timeShiftBufferDepth??30));first=Math.max(0,Math.floor(windowStart/duration));const last=Math.max(first,Math.floor(localNow/duration));count=Math.min(maxSegments,last-first+1);}for(let i=0;i<count;i++){const index=first+i,sequence=startNumber+index,time=index*units,start=period.start+(time-pto)/timescale;out.push({id:`dash:${period.id}:${representationId}:${sequence}`,periodIndex:period.index,sequence,url:resolveUrl(replaceTemplate(template.media,{RepresentationID:representationId,Bandwidth:bandwidth,Number:sequence,Time:time}),baseUrl),start,duration,time,availabilityTimeOffset:ato,availabilityTimeComplete:complete,partial:false});}return out;}
export function parseDashManifestV2(xml,{baseUrl=null,now=Date.now(),maxSegments=10000}={}){const root=parseXmlLiteV2(xml);if(root.name!=='MPD')throw new Error('DASH manifest root must be MPD');const isDynamic=String(root.attrs.type??'static').toLowerCase()==='dynamic',duration=parseIsoDurationV2(root.attrs.mediaPresentationDuration),availabilityStartMs=Date.parse(root.attrs.availabilityStartTime??''),presentationNow=isDynamic&&Number.isFinite(availabilityStartMs)?Math.max(0,(Number(now)-availabilityStartMs)/1000):null,timeShiftBufferDepth=parseIsoDurationV2(root.attrs.timeShiftBufferDepth),mpdBase=baseOf(root,baseUrl),periods=periodWindows(children(root,'Period'),duration),variants=[],events=[];
  for(const period of periods){const periodBase=baseOf(period.node,mpdBase),periodTemplate=templateOf(period.node),periodProtection=protection([period.node]);events.push(...eventStreams(period.node,period.start));for(const adaptation of children(period.node,'AdaptationSet')){const adaptBase=baseOf(adaptation,periodBase),adaptTemplate=mergeTemplate(periodTemplate,templateOf(adaptation)),adaptProtection=[...periodProtection,...protection([adaptation])],type=adaptation.attrs.contentType??(String(adaptation.attrs.mimeType??'').split('/')[0]||null);for(const representation of children(adaptation,'Representation')){const repId=representation.attrs.id??`${period.index}-${variants.length}`,bandwidth=number(representation.attrs.bandwidth),repBase=baseOf(representation,adaptBase),template=mergeTemplate(adaptTemplate,templateOf(representation)),segments=segmentsFromTemplate(template,{period,representationId:repId,bandwidth,baseUrl:repBase,maxSegments,isDynamic,presentationNow,timeShiftBufferDepth}),initialization=template?.initialization?resolveUrl(replaceTemplate(template.initialization,{RepresentationID:repId,Bandwidth:bandwidth}),repBase):null;variants.push({id:`dash:p${period.index}:${repId}`,representationId:repId,periodId:period.id,periodIndex:period.index,periodStart:period.start,periodDuration:period.duration,type:representation.attrs.contentType??type,mimeType:representation.attrs.mimeType??adaptation.attrs.mimeType??null,codecs:representation.attrs.codecs??adaptation.attrs.codecs??null,bandwidth,width:number(representation.attrs.width??adaptation.attrs.width),height:number(representation.attrs.height??adaptation.attrs.height),baseUrl:repBase,initialization,segments,protection:[...adaptProtection,...protection([representation])]});}}}
  return{schema:'media.adaptive.v2',protocol:'dash',kind:'mpd',baseUrl:mpdBase,isLive:isDynamic,type:root.attrs.type??'static',duration,availabilityStartTime:root.attrs.availabilityStartTime??null,publishTime:root.attrs.publishTime??null,minimumUpdatePeriod:parseIsoDurationV2(root.attrs.minimumUpdatePeriod),timeShiftBufferDepth,suggestedPresentationDelay:parseIsoDurationV2(root.attrs.suggestedPresentationDelay),minBufferTime:parseIsoDurationV2(root.attrs.minBufferTime),utcTiming:utcTiming(root),serviceDescription:serviceDescription(root),periods:periods.map(({node,...p})=>p),events,variants,presentationNow};}
export function activeDashPeriod(manifest,time){const t=Number(time)||0;return(manifest?.periods??[]).find(p=>t>=p.start&&(p.end==null||t<p.end))??manifest?.periods?.at(-1)??null;}
export function activeDashVariants(manifest,time,{type=null}={}){const period=activeDashPeriod(manifest,time);return(manifest?.variants??[]).filter(v=>v.periodIndex===period?.index&&(!type||v.type==null||v.type===type));}
export function nextDashSegments(manifest,{time=0,afterId=null,maxRequests=3,type='video'}={}){const variants=activeDashVariants(manifest,time,{type});const segments=variants[0]?.segments??[];let start=0;if(afterId){const index=segments.findIndex(s=>s.id===afterId);if(index>=0)start=index+1;}else{const index=segments.findIndex(s=>s.start+s.duration>time);start=Math.max(0,index);}return segments.slice(start,start+Math.max(0,maxRequests));}
