function finite(value,label){const n=Number(value);if(!Number.isFinite(n))throw new Error(`${label} must be finite`);return n;}
function keyOf(assetId,type,index){return `derived-job:${assetId}:${type}:${String(index).padStart(5,'0')}`;}
export function planDerivativeSegments({assetId,type='proxy-video',duration,segmentDuration=8,keyframes=[]}={}){if(!assetId)throw new Error('Derivative segments require assetId');const total=Math.max(0,finite(duration,'duration')),target=Math.max(.25,finite(segmentDuration,'segmentDuration'));const points=[0,...keyframes.map((v)=>Math.max(0,Math.min(total,finite(v,'keyframe')))).filter((v)=>v>0&&v<total),total].sort((a,b)=>a-b);const unique=[...new Set(points)];const boundaries=[0];let cursor=target;while(cursor<total){let chosen=unique.find((v)=>v>=cursor-0.001);if(chosen==null||chosen>=total)chosen=Math.min(total,cursor);if(chosen<=boundaries.at(-1)+.001)chosen=Math.min(total,boundaries.at(-1)+target);boundaries.push(chosen);cursor=chosen+target;}if(boundaries.at(-1)!==total)boundaries.push(total);return boundaries.slice(0,-1).map((start,index)=>({id:keyOf(assetId,type,index),index,start,end:boundaries[index+1],duration:boundaries[index+1]-start,status:'pending',attempts:0,artifact:null,error:null}));}
export function createDerivativeJob({assetId,sourceHash=null,type='proxy-video',spec={},duration=0,keyframes=[],segmentDuration=8,maxAttempts=3}={}){const segments=planDerivativeSegments({assetId,type,duration,segmentDuration,keyframes});return{version:1,id:`derivative:${assetId}:${type}`,assetId,sourceHash,type,spec:structuredClone(spec),duration:Number(duration)||0,maxAttempts:Math.max(1,Math.round(Number(maxAttempts)||3)),status:segments.length?'pending':'complete',segments,createdAt:new Date().toISOString()};}
export function claimDerivativeSegment(job,workerId='local'){const next=job.segments.find((s)=>s.status==='pending'&&s.attempts<job.maxAttempts);if(!next)return{job,segment:null};const copy=structuredClone(job),segment=copy.segments.find((s)=>s.id===next.id);segment.status='running';segment.workerId=workerId;segment.attempts++;copy.status='running';return{job:copy,segment:structuredClone(segment)};}
export function completeDerivativeSegment(job,segmentId,artifact){const copy=structuredClone(job),segment=copy.segments.find((s)=>s.id===segmentId);if(!segment)throw new Error(`Unknown derivative segment ${segmentId}`);segment.status='complete';segment.artifact=structuredClone(artifact);segment.error=null;delete segment.workerId;copy.status=copy.segments.every((s)=>s.status==='complete')?'complete':'pending';return copy;}
export function failDerivativeSegment(job,segmentId,error){const copy=structuredClone(job),segment=copy.segments.find((s)=>s.id===segmentId);if(!segment)throw new Error(`Unknown derivative segment ${segmentId}`);segment.error=String(error?.message??error);delete segment.workerId;segment.status=segment.attempts>=copy.maxAttempts?'failed':'pending';copy.status=copy.segments.some((s)=>s.status==='failed')?'failed':'pending';return copy;}
export function recoverDerivativeJob(job){const copy=structuredClone(job);for(const segment of copy.segments)if(segment.status==='running'){segment.status=segment.attempts>=copy.maxAttempts?'failed':'pending';delete segment.workerId;}copy.status=copy.segments.some((s)=>s.status==='failed')?'failed':copy.segments.every((s)=>s.status==='complete')?'complete':'pending';return copy;}
export function derivativeJobProgress(job){const complete=job.segments.filter((s)=>s.status==='complete').reduce((sum,s)=>sum+s.duration,0);const total=job.segments.reduce((sum,s)=>sum+s.duration,0);return{ratio:total?complete/total:1,completedSegments:job.segments.filter((s)=>s.status==='complete').length,totalSegments:job.segments.length,completedDuration:complete,totalDuration:total,status:job.status};}
export function derivativeArtifactManifest(job){if(job.status!=='complete')throw new Error('Derivative job is not complete');return{version:1,jobId:job.id,assetId:job.assetId,type:job.type,sourceHash:job.sourceHash,spec:structuredClone(job.spec),segments:job.segments.map((s)=>({index:s.index,start:s.start,end:s.end,artifact:structuredClone(s.artifact)}))};}
