const PQ={m1:2610/16384,m2:2523/32,c1:3424/4096,c2:2413/128,c3:2392/128};
export function pqToNits(value){const v=Math.max(0,Math.min(1,Number(value)||0)),p=v**(1/PQ.m2),num=Math.max(p-PQ.c1,0),den=PQ.c2-PQ.c3*p;return 10000*(num/den)**(1/PQ.m1);}
export function nitsToPq(nits){const l=Math.max(0,Number(nits)||0)/10000,p=l**PQ.m1;return ((PQ.c1+PQ.c2*p)/(1+PQ.c3*p))**PQ.m2;}
export function hlgToRelative(value,{systemGamma=1.2}={}){const e=Math.max(0,Math.min(1,Number(value)||0)),a=.17883277,b=1-4*a,c=.5-a*Math.log(4*a),scene=e<=.5?(e*e)/3:(Math.exp((e-c)/a)+b)/12;return scene**Number(systemGamma||1.2);}
export function relativeToHlg(value,{systemGamma=1.2}={}){const scene=Math.max(0,Number(value)||0)**(1/Number(systemGamma||1.2)),a=.17883277,b=1-4*a,c=.5-a*Math.log(4*a);return scene<=1/12?Math.sqrt(3*scene):a*Math.log(12*scene-b)+c;}
function aces(x){const a=2.51,b=.03,c=2.43,d=.59,e=.14;return Math.max(0,Math.min(1,(x*(a*x+b))/(x*(c*x+d)+e)));}
function hable(x){const A=.15,B=.50,C=.10,D=.20,E=.02,F=.30;return ((x*(A*x+C*B)+D*E)/(x*(A*x+B)+D*F))-E/F;}
export function toneMapValue(value,{method='aces',sourcePeakNits=1000,targetPeakNits=100}={}){const normalized=Math.max(0,Number(value)||0)*Math.max(1,Number(sourcePeakNits)||1000)/Math.max(1,Number(targetPeakNits)||100);if(method==='reinhard')return normalized/(1+normalized);if(method==='hable'){const white=hable(Math.max(1,Number(sourcePeakNits)/Number(targetPeakNits)));return Math.max(0,Math.min(1,hable(normalized)/Math.max(1e-6,white)));}if(method==='clip')return Math.min(1,normalized);return aces(normalized);}
export function toneMapRgb(rgb,options={}){return rgb.map((value)=>toneMapValue(value,options));}
export function hdrWorkingPolicy(colorSpace,{workingFormat='rgba16float',toneMap=null}={}){const transfer=String(colorSpace?.transfer??'').toLowerCase(),hdr=['pq','smpte2084','hlg','arib-std-b67'].includes(transfer);if(!hdr)return{supported:true,hdr:false,workingFormat,toneMap:null};if(!String(workingFormat).includes('16float')&&!String(workingFormat).includes('32float'))return{supported:false,hdr:true,reason:'float-working-target-required',workingFormat};if(!toneMap)return{supported:false,hdr:true,reason:'tone-map-policy-required',workingFormat};return{supported:true,hdr:true,workingFormat,toneMap:{method:toneMap.method??'aces',sourcePeakNits:Number(toneMap.sourcePeakNits??1000),targetPeakNits:Number(toneMap.targetPeakNits??100)}};}
