function finite(v,label){const n=Number(v);if(!Number.isFinite(n))throw new Error(`${label} must be finite`);return n;}
const PRE_B=[1.53512485958697,-2.69169618940638,1.19839281085285],PRE_A=[1,-1.69065929318241,0.73248077421585];
const RLB_B=[1,-2,1],RLB_A=[1,-1.99004745483398,0.99007225036621];
function biquad(input,b,a){const out=new Float64Array(input.length);let x1=0,x2=0,y1=0,y2=0;for(let i=0;i<input.length;i++){const x=input[i];const y=b[0]*x+b[1]*x1+b[2]*x2-a[1]*y1-a[2]*y2;out[i]=y;x2=x1;x1=x;y2=y1;y1=y;}return out;}
function resampleChannel(channel,sourceRate,targetRate=48000){if(sourceRate===targetRate)return Float64Array.from(channel);const length=Math.max(1,Math.round(channel.length*targetRate/sourceRate));const out=new Float64Array(length),ratio=sourceRate/targetRate;for(let i=0;i<length;i++){const p=i*ratio,left=Math.floor(p),mix=p-left,a=channel[Math.min(left,channel.length-1)]??0,b=channel[Math.min(left+1,channel.length-1)]??a;out[i]=a+(b-a)*mix;}return out;}
function kWeight(channel,rate){let data=resampleChannel(channel,rate,48000);data=biquad(data,PRE_B,PRE_A);return biquad(data,RLB_B,RLB_A);}
function blockEnergy(channels,start,length,weights){let energy=0;for(let c=0;c<channels.length;c++){const channel=channels[c],weight=weights[c]??1;let sum=0;const end=Math.min(channel.length,start+length);for(let i=start;i<end;i++)sum+=channel[i]*channel[i];const count=Math.max(1,end-start);energy+=weight*(sum/count);}return energy;}
function energyToLufs(energy){return energy>0?-0.691+10*Math.log10(energy):-Infinity;}
function mean(values){return values.length?values.reduce((a,b)=>a+b,0)/values.length:0;}
export function defaultLoudnessChannelWeights(count){const n=Math.max(1,Math.round(Number(count)||1));if(n===6)return[1,1,1,0,1.41,1.41];if(n===8)return[1,1,1,0,1.41,1.41,1.41,1.41];return Array(n).fill(1);}
export function analyzeLoudness(buffer,{channelWeights,blockSeconds=.4,stepSeconds=.1}={}){if(!buffer?.channels?.length)throw new Error('Loudness analysis requires PCM channels');const rate=finite(buffer.sampleRate,'sampleRate');const filtered=buffer.channels.map((channel)=>kWeight(channel,rate));const weights=channelWeights??defaultLoudnessChannelWeights(filtered.length);const block=Math.max(1,Math.round(blockSeconds*48000)),step=Math.max(1,Math.round(stepSeconds*48000));const energies=[];for(let start=0;start+Math.min(block,filtered[0].length)>0&&start<filtered[0].length;start+=step)energies.push(blockEnergy(filtered,start,block,weights));const absolute=energies.filter((e)=>energyToLufs(e)>=-70);const ungated=energyToLufs(mean(absolute));const relativeThreshold=ungated-10;const gated=absolute.filter((e)=>energyToLufs(e)>=relativeThreshold);const integrated=energyToLufs(mean(gated));let samplePeak=0;for(const channel of buffer.channels)for(const sample of channel)samplePeak=Math.max(samplePeak,Math.abs(Number(sample)||0));const truePeak=intersamplePeakEstimate(buffer,4);return{integratedLufs:integrated,ungatedLufs:ungated,relativeThresholdLufs:relativeThreshold,blocks:energies.length,gatedBlocks:gated.length,samplePeak,truePeak,truePeakDbfs:truePeak>0?20*Math.log10(truePeak):-Infinity};}
function sinc(x){if(Math.abs(x)<1e-12)return 1;const v=Math.PI*x;return Math.sin(v)/v;}
function hann(distance,half){return Math.abs(distance)>half?0:.5+.5*Math.cos(Math.PI*distance/half);}
export function intersamplePeakEstimate(buffer,oversample=4,{taps=12}={}){const factor=Math.max(1,Math.round(oversample)),tapCount=Math.max(4,Math.round(taps/2)*2),half=tapCount/2;let peak=0;for(const channel of buffer.channels){for(let i=0;i<channel.length;i++){peak=Math.max(peak,Math.abs(Number(channel[i])||0));for(let phase=1;phase<factor;phase++){const position=i+phase/factor;let sum=0,weight=0;const first=Math.floor(position-half+1),last=Math.floor(position+half);for(let sample=first;sample<=last;sample++){if(sample<0||sample>=channel.length)continue;const distance=position-sample,w=sinc(distance)*hann(distance,half);sum+=(Number(channel[sample])||0)*w;weight+=w;}if(Math.abs(weight)>1e-12)sum/=weight;peak=Math.max(peak,Math.abs(sum));}}}return peak;}
export function loudnessSeries(buffer,{windowSeconds=.4,stepSeconds=.1,channelWeights}={}){if(!buffer?.channels?.length)throw new Error('Loudness series requires PCM channels');const filtered=buffer.channels.map((channel)=>kWeight(channel,finite(buffer.sampleRate,'sampleRate'))),weights=channelWeights??defaultLoudnessChannelWeights(filtered.length),window=Math.max(1,Math.round(windowSeconds*48000)),step=Math.max(1,Math.round(stepSeconds*48000)),values=[];for(let start=0;start<filtered[0].length;start+=step){const length=Math.min(window,filtered[0].length-start);if(length<=0)break;values.push({time:start/48000,lufs:energyToLufs(blockEnergy(filtered,start,length,weights))});}return values;}
export function loudnessGainDb(analysis,{targetLufs=-14,maxGainDb=24,minGainDb=-60}={}){if(!Number.isFinite(analysis?.integratedLufs))return 0;return Math.max(minGainDb,Math.min(maxGainDb,finite(targetLufs,'targetLufs')-analysis.integratedLufs));}
export function normalizeLoudness(buffer,{targetLufs=-14,maxTruePeakDbfs=-1,maxGainDb=24}={}){const analysis=analyzeLoudness(buffer);let gain=loudnessGainDb(analysis,{targetLufs,maxGainDb});if(analysis.truePeak>0){const peakAfterDb=20*Math.log10(analysis.truePeak)+gain;if(peakAfterDb>maxTruePeakDbfs)gain-=peakAfterDb-maxTruePeakDbfs;}const linear=10**(gain/20);for(const channel of buffer.channels)for(let i=0;i<channel.length;i++)channel[i]*=linear;return{buffer,gainDb:gain,before:analysis,after:analyzeLoudness(buffer)};}
