function findStartCodes(data){const starts=[];for(let i=0;i+3<data.length;i++){if(data[i]===0&&data[i+1]===0&&data[i+2]===1){starts.push({offset:i,length:3});i+=2;}else if(i+4<=data.length&&data[i]===0&&data[i+1]===0&&data[i+2]===0&&data[i+3]===1){starts.push({offset:i,length:4});i+=3;}}return starts;}
export function splitAnnexBNalus(bytes){const data=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes),starts=findStartCodes(data),nalus=[];for(let i=0;i<starts.length;i++){const start=starts[i].offset+starts[i].length,end=i+1<starts.length?starts[i+1].offset:data.length;if(end>start)nalus.push(data.slice(start,end));}return nalus;}
class BitReader{constructor(bytes){this.bytes=bytes;this.bit=0;}read(n=1){let v=0;for(let i=0;i<n;i++){const byte=this.bytes[this.bit>>3]??0,vbit=(byte>>(7-(this.bit&7)))&1;v=(v<<1)|vbit;this.bit++;}return v;}ue(){let zeros=0;while(this.read(1)===0&&zeros<32)zeros++;return (2**zeros-1)+this.read(zeros);}se(){const code=this.ue();return code&1?(code+1)/2:-(code/2);}}
function rbsp(nalu){const out=[];for(let i=1;i<nalu.length;i++){if(i+2<nalu.length&&nalu[i]===0&&nalu[i+1]===0&&nalu[i+2]===3){out.push(0,0);i+=2;continue;}out.push(nalu[i]);}return new Uint8Array(out);}
function skipScalingList(br,size){let last=8,next=8;for(let i=0;i<size;i++){if(next!==0){const delta=br.se();next=(last+delta+256)%256;}last=next===0?last:next;}}
export function parseH264Sps(nalu){
  if(!nalu?.length||(nalu[0]&0x1f)!==7)return null;const profileIdc=nalu[1],constraint=nalu[2],levelIdc=nalu[3],br=new BitReader(rbsp(nalu));br.read(8);br.read(8);br.read(8);br.ue();let chromaFormatIdc=1;
  if([100,110,122,244,44,83,86,118,128,138,139,134,135].includes(profileIdc)){chromaFormatIdc=br.ue();if(chromaFormatIdc===3)br.read();br.ue();br.ue();br.read();if(br.read())for(let i=0;i<(chromaFormatIdc!==3?8:12);i++)if(br.read())skipScalingList(br,i<6?16:64);}
  br.ue();const pocType=br.ue();if(pocType===0)br.ue();else if(pocType===1){br.read();br.se();br.se();const n=br.ue();for(let i=0;i<n;i++)br.se();}br.ue();br.read();const picWidthMbsMinus1=br.ue(),picHeightMapUnitsMinus1=br.ue(),frameMbsOnlyFlag=br.read();if(!frameMbsOnlyFlag)br.read();br.read();let cropLeft=0,cropRight=0,cropTop=0,cropBottom=0;if(br.read()){cropLeft=br.ue();cropRight=br.ue();cropTop=br.ue();cropBottom=br.ue();}
  const subWidth=chromaFormatIdc===1||chromaFormatIdc===2?2:1,subHeight=chromaFormatIdc===1?2:1,cropUnitX=chromaFormatIdc===0?1:subWidth,cropUnitY=(chromaFormatIdc===0?1:subHeight)*(2-frameMbsOnlyFlag),width=(picWidthMbsMinus1+1)*16-(cropLeft+cropRight)*cropUnitX,height=(2-frameMbsOnlyFlag)*(picHeightMapUnitsMinus1+1)*16-(cropTop+cropBottom)*cropUnitY;
  return{profileIdc,constraint,levelIdc,width,height,codec:`avc1.${[profileIdc,constraint,levelIdc].map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase()}`};
}
export function inspectAnnexB(bytes,{codec='h264'}={}){const nalus=splitAnnexBNalus(bytes);if(codec==='h264'){const spsNalu=nalus.find(n=>(n[0]&0x1f)===7),sps=spsNalu?parseH264Sps(spsNalu):null,key=nalus.some(n=>(n[0]&0x1f)===5);return{key,sps,codec:sps?.codec??'avc1',nalus};}const key=nalus.some(n=>{const type=(n[0]>>1)&0x3f;return type>=16&&type<=21;});return{key,sps:null,codec:'hvc1',nalus};}
