import {parseTsPackets,TsContinuityTracker} from './mpegts-packet.js';
import {PsiSectionAssembler,parsePatSection,parsePmtSection} from './mpegts-psi.js';
import {PesAssembler,parsePesPacket,TimestampUnwrapper,ticksToMicros} from './mpegts-pes.js';
import {AdtsFrameAssembler} from './mpegts-audio.js';
import {inspectAnnexB} from './mpegts-video.js';
function stateMap(state,key){return state[key]??(state[key]=new Map());}
function unwrapFor(state,pid,kind){const map=stateMap(state,kind);if(!map.has(pid))map.set(pid,new TimestampUnwrapper());return map.get(pid);}
function finalizeDurations(chunks){const byTrack=new Map();for(const c of chunks){const list=byTrack.get(c.trackId)??[];list.push(c);byTrack.set(c.trackId,list);}for(const list of byTrack.values()){list.sort((a,b)=>a.timestamp-b.timestamp);for(let i=0;i<list.length-1;i++)if(!list[i].duration)list[i].duration=Math.max(0,list[i+1].timestamp-list[i].timestamp);}return chunks;}
export function createMpegTsState(){return{pts:new Map(),dts:new Map(),adts:new Map(),program:null,pmtPid:null,lastPcr:null};}
export function resetMpegTsState(state,{timestamps=true,audio=true,program=false}={}){if(timestamps){for(const u of state.pts?.values?.()??[])u.reset();for(const u of state.dts?.values?.()??[])u.reset();}if(audio)for(const a of state.adts?.values?.()??[])a.reset();if(program){state.program=null;state.pmtPid=null;}return state;}
export function demuxMpegTs(bytes,{state=createMpegTsState(),discontinuity=false}={}){
  if(discontinuity)resetMpegTsState(state,{timestamps:true,audio:true});const {packets,trailing,syncOffset}=parseTsPackets(bytes),psi=new PsiSectionAssembler(),pes=new PesAssembler(),continuity=new TsContinuityTracker(),chunks=[],tracks=new Map(),diagnostics={continuityErrors:[],transportErrors:[],scrambled:[],pcr:[],trailing,syncOffset};
  const processPes=(record)=>{const stream=state.program?.streams?.find(s=>s.pid===record.pid);if(!stream)return;if(record.bytes.length<9)return;const parsed=parsePesPacket(record.bytes,{ptsUnwrapper:unwrapFor(state,record.pid,'pts'),dtsUnwrapper:unwrapFor(state,record.pid,'dts')}),timestamp=ticksToMicros(parsed.pts??parsed.dts??0),dts=ticksToMicros(parsed.dts??parsed.pts??0),trackId=`ts:${record.pid}`;
    if(stream.streamType===0x0f){let adts=state.adts.get(record.pid);if(!adts){adts=new AdtsFrameAssembler();state.adts.set(record.pid,adts);}const frames=adts.push(parsed.payload,{timestampMicros:timestamp});for(const frame of frames){tracks.set(trackId,{id:trackId,type:'audio',codec:frame.codec,sampleRate:frame.sampleRate,channels:frame.channels,description:frame.description,pid:record.pid,streamType:stream.streamType});chunks.push({trackId,type:'key',timestamp:frame.timestamp??timestamp,dts:frame.timestamp??dts,duration:frame.duration,sequence:frame.sequence,byteLength:frame.data.length,payload:frame.data});}return;}
    if(stream.kind==='video'){const info=inspectAnnexB(parsed.payload,{codec:stream.streamType===0x24?'h265':'h264'});const previous=tracks.get(trackId)??{};tracks.set(trackId,{id:trackId,type:'video',codec:info.codec,width:info.sps?.width??previous.width??null,height:info.sps?.height??previous.height??null,pid:record.pid,streamType:stream.streamType,format:'annexb'});chunks.push({trackId,type:info.key?'key':'delta',timestamp,dts,duration:0,sequence:chunks.filter(c=>c.trackId===trackId).length,byteLength:parsed.payload.length,payload:parsed.payload.slice()});return;}
    tracks.set(trackId,{id:trackId,type:stream.kind,codec:stream.codec,pid:record.pid,streamType:stream.streamType});chunks.push({trackId,type:'key',timestamp,dts,duration:0,sequence:chunks.filter(c=>c.trackId===trackId).length,byteLength:parsed.payload.length,payload:parsed.payload.slice()});};
  for(const packet of packets){if(packet.transportError)diagnostics.transportErrors.push({pid:packet.pid,offset:packet.offset});if(packet.scramblingControl)diagnostics.scrambled.push({pid:packet.pid,offset:packet.offset,control:packet.scramblingControl});continuity.observe(packet);if(packet.adaptation?.pcr){state.lastPcr=packet.adaptation.pcr;diagnostics.pcr.push({pid:packet.pid,...packet.adaptation.pcr});}if(packet.pid===0||packet.pid===state.pmtPid){for(const section of psi.push(packet)){if(section[0]===0){const pat=parsePatSection(section);state.pmtPid=pat.programs[0]?.pmtPid??state.pmtPid;}else if(section[0]===2)state.program=parsePmtSection(section);}continue;}if(state.program?.streams?.some(s=>s.pid===packet.pid)){if(packet.scramblingControl)continue;for(const record of pes.push(packet))processPes(record);}}
  for(const record of pes.flush())processPes(record);diagnostics.continuityErrors=continuity.errors;
  if(diagnostics.scrambled.length){const error=new Error('MPEG-TS transport-scrambled packets require an external descrambler');error.code='ERR_ENCRYPTED_MEDIA';error.diagnostics=diagnostics;throw error;}
  finalizeDurations(chunks);const duration=chunks.reduce((m,c)=>Math.max(m,(c.timestamp+c.duration)/1e6),0),seekPoints=chunks.filter(c=>c.type==='key'&&tracks.get(c.trackId)?.type==='video').map(c=>c.timestamp/1e6);
  return{schema:'media.mpegts.v1',container:'mpegts',duration,tracks:[...tracks.values()],chunks,seekPoints,program:state.program,diagnostics,state};
}
export class MpegTsSegmentSession{
  constructor({maxSegments=8,state=createMpegTsState()}={}){this.maxSegments=Math.max(1,maxSegments);this.state=state;this.records=new Map();this.order=[];}
  push(bytes,{id=`ts:${Date.now()}`,discontinuity=false}={}){const result=demuxMpegTs(bytes,{state:this.state,discontinuity});const record={id:String(id),result,byteLength:Number(bytes.byteLength??bytes.length??0)};this.records.set(record.id,record);this.order.push(record.id);while(this.order.length>this.maxSegments)this.records.delete(this.order.shift());return record;}
  acknowledge(id){const key=String(id),ok=this.records.delete(key);this.order=this.order.filter(v=>v!==key);return ok;}
  readChunk(chunk){const payload=chunk?.payload;if(payload instanceof Uint8Array)return payload;if(payload instanceof ArrayBuffer)return new Uint8Array(payload);throw new Error('MPEG-TS chunk payload is unavailable');}
  clear(){this.records.clear();this.order.length=0;resetMpegTsState(this.state,{timestamps:true,audio:true,program:true});}
  stats(){return{segments:this.records.size,maxSegments:this.maxSegments,ids:[...this.order],program:this.state.program??null};}
}
