import { automationValueAt } from './audio-automation.js';
function sampleLinear(channel,position){if(!channel?.length)return 0;if(position<=0)return channel[0]??0;if(position>=channel.length-1)return channel[channel.length-1]??0;const left=Math.floor(position),mix=position-left;return channel[left]*(1-mix)+channel[left+1]*mix;}
function dbGain(db){const v=Number(db)||0;return v<=-120?0:10**(v/20);}
function envelope(frame,total,fadeInFrames,fadeOutFrames){let v=1;if(fadeInFrames>0)v=Math.min(v,Math.max(0,Math.min(1,frame/fadeInFrames)));if(fadeOutFrames>0)v=Math.min(v,Math.max(0,Math.min(1,(total-frame)/fadeOutFrames)));return v;}
function sourceFor(sources,id){return sources instanceof Map?sources.get(id):sources?.[id];}
function sourceEndSample(source){return source?.blocks?.length?Number(source.length??0):Number(source?.startSample??0)+Number(source?.length??0);}
function sourceChannelCount(source){return source?.blocks?.[0]?.channels?.length??source?.channels?.length??0;}
function sparseBlockAt(source,position){if(!source?.blocks?.length)return null;let low=0,high=source.blocks.length-1;while(low<=high){const mid=(low+high)>>1,block=source.blocks[mid],start=Number(block.startSample??0),end=start+Number(block.length??0);if(position<start)high=mid-1;else if(position>=end)low=mid+1;else return block;}return null;}
function sourceChannelAt(source,channelIndex,position){if(source?.blocks?.length){const block=sparseBlockAt(source,position);if(!block)return 0;const channel=block.channels[Math.min(channelIndex,block.channels.length-1)];return sampleLinear(channel,position-Number(block.startSample??0));}const base=Number(source?.startSample??0),channel=source?.channels?.[Math.min(channelIndex,Math.max(0,(source?.channels?.length??1)-1))];return sampleLinear(channel,position-base);}
export function renderAutomatedMix(plan,sources,{channels=2,clipAutomation={},masterAutomation={}}={}){const rate=Number(plan.sampleRate),length=Number(plan.sampleCount);const output={sampleRate:rate,length,channels:Array.from({length:channels},()=>new Float32Array(length))};for(const item of plan.sources??[]){const source=sourceFor(sources,item.assetId);if(!source)continue;const start=Math.max(0,item.startSample-plan.startSample),frames=Math.max(0,Math.min(length-start,item.endSample-item.startSample));const auto=clipAutomation[item.clipId]??{};const fadeIn=Math.round(Number(item.fadeIn??0)*rate),fadeOut=Math.round(Number(item.fadeOut??0)*rate);for(let frame=0;frame<frames;frame++){const timelineSample=item.startSample+frame,timelineTime=timelineSample/rate;const sourcePos=(Number(item.sourceInSample??0)+frame*Number(item.playbackRate??1))*(source.sampleRate/rate);if(sourcePos<0||sourcePos>sourceEndSample(source)-1)continue;const gainDb=Number(item.gainDb??0)+(auto.gainDb?.length?automationValueAt(auto.gainDb,timelineTime):0);const pan=Math.max(-1,Math.min(1,Number(item.pan??0)+(auto.pan?.length?automationValueAt(auto.pan,timelineTime):0)));const angle=(pan+1)*Math.PI/4,gain=dbGain(gainDb)*envelope(frame,frames,fadeIn,fadeOut),sourceChannels=sourceChannelCount(source);if(channels===1){let value=0;for(let c=0;c<sourceChannels;c++)value+=sourceChannelAt(source,c,sourcePos);output.channels[0][start+frame]+=value/Math.max(1,sourceChannels)*gain;}else{const left=sourceChannelAt(source,0,sourcePos),right=sourceChannelAt(source,Math.min(1,sourceChannels-1),sourcePos);output.channels[0][start+frame]+=left*gain*Math.cos(angle);output.channels[1][start+frame]+=right*gain*Math.sin(angle);for(let c=2;c<channels;c++)output.channels[c][start+frame]+=sourceChannelAt(source,Math.min(c,sourceChannels-1),sourcePos)*gain;}}}if(masterAutomation.gainDb?.length){for(let frame=0;frame<length;frame++){const time=(plan.startSample+frame)/rate,gain=dbGain(automationValueAt(masterAutomation.gainDb,time));for(const channel of output.channels)channel[frame]*=gain;}}return output;}
export function pcmBlocks(buffer,{blockFrames=1024}={}){const size=Math.max(1,Math.round(Number(blockFrames)||1024));const blocks=[];for(let start=0;start<buffer.length;start+=size){const length=Math.min(size,buffer.length-start);blocks.push({start,length,sampleRate:buffer.sampleRate,channels:buffer.channels.map((channel)=>channel.slice(start,start+length))});}return blocks;}
