function finite(value, label) { const parsed = Number(value); if (!Number.isFinite(parsed)) throw new Error(`${label} must be finite`); return parsed; }
function integer(value, label, min = 0) { const parsed = Math.round(finite(value, label)); if (parsed < min) throw new Error(`${label} must be >= ${min}`); return parsed; }
function stable(value) { if (Array.isArray(value)) return value.map(stable); if (!value || typeof value !== "object") return value; return Object.fromEntries(Object.keys(value).sort().map((key) => [key, stable(value[key])])); }
export function stableJobStringify(value) { return JSON.stringify(stable(value)); }
export function jobHash(value) { let h = 2166136261; for (const char of stableJobStringify(value)) { h ^= char.charCodeAt(0); h = Math.imul(h, 16777619); } return (h >>> 0).toString(16).padStart(8, "0"); }
export function frameRangeFromManifest(manifest) { const settings = manifest?.settings; if (!settings) throw new Error("Render manifest requires settings"); const fps = finite(settings.fps, "fps"); if (fps <= 0) throw new Error("fps must be positive"); const start = finite(settings.rangeStart, "rangeStart"); const end = finite(settings.rangeEnd, "rangeEnd"); if (end < start) throw new Error("rangeEnd must be >= rangeStart"); const startFrame = Math.ceil(start * fps - 1e-9); const endFrameExclusive = Math.ceil(end * fps - 1e-9); return { fps, startFrame, endFrameExclusive, frameCount: Math.max(0, endFrameExclusive - startFrame) }; }
export function createRenderJobPlan(manifest, { chunkFrames = 120, maxAttempts = 3, now = null } = {}) { const { fps, startFrame, endFrameExclusive, frameCount } = frameRangeFromManifest(manifest); const size = integer(chunkFrames, "chunkFrames", 1); const attempts = integer(maxAttempts, "maxAttempts", 1); const signature = String(manifest.signature || jobHash(manifest)); const chunks = []; for (let frame = startFrame, index = 0; frame < endFrameExclusive; frame += size, index += 1) { const frameEnd = Math.min(endFrameExclusive, frame + size); chunks.push({ id: `${signature}:${String(index).padStart(5, "0")}`, index, frameStart: frame, frameEnd, frameCount: frameEnd - frame, timeStart: frame / fps, timeEnd: frameEnd / fps, status: "pending", attempts: 0, maxAttempts: attempts, workerId: null, startedAt: null, completedAt: null, artifact: null, error: null }); } return { version: 1, id: `render:${signature}`, signature, createdAt: now, status: frameCount ? "pending" : "complete", settings: structuredClone(manifest.settings), dependencies: structuredClone(manifest.dependencies ?? []), frameCount, chunks }; }
export function claimNextRenderChunk(job, workerId, { now = null } = {}) { const next = job.chunks.find((chunk) => chunk.status === "pending" || (chunk.status === "failed" && chunk.attempts < chunk.maxAttempts)); if (!next) return { job, chunk: null }; const chunks = job.chunks.map((chunk) => chunk.id === next.id ? { ...chunk, status: "running", attempts: chunk.attempts + 1, workerId: String(workerId || "worker"), startedAt: now, completedAt: null, error: null } : chunk); return { job: refreshRenderJob({ ...job, chunks }), chunk: chunks.find((chunk) => chunk.id === next.id) }; }
export function completeRenderChunk(job, chunkId, artifact, { now = null } = {}) { let found = false; const chunks = job.chunks.map((chunk) => { if (chunk.id !== chunkId) return chunk; found = true; if (chunk.status !== "running") throw new Error(`Chunk ${chunkId} is not running`); return { ...chunk, status: "complete", completedAt: now, artifact: structuredClone(artifact ?? {}), error: null }; }); if (!found) throw new Error(`Unknown render chunk: ${chunkId}`); return refreshRenderJob({ ...job, chunks }); }
export function failRenderChunk(job, chunkId, error, { retry = true, now = null } = {}) { let found = false; const chunks = job.chunks.map((chunk) => { if (chunk.id !== chunkId) return chunk; found = true; if (chunk.status !== "running") throw new Error(`Chunk ${chunkId} is not running`); const canRetry = retry && chunk.attempts < chunk.maxAttempts; return { ...chunk, status: canRetry ? "pending" : "failed", completedAt: now, workerId: null, error: String(error?.message ?? error ?? "Render failed") }; }); if (!found) throw new Error(`Unknown render chunk: ${chunkId}`); return refreshRenderJob({ ...job, chunks }); }
export function releaseRenderChunk(job, chunkId, { reason = 'Interrupted', preserveAttempt = false } = {}) { let found = false; const chunks = job.chunks.map((chunk) => { if (chunk.id !== chunkId) return chunk; found = true; if (chunk.status !== 'running') throw new Error(`Chunk ${chunkId} is not running`); return { ...chunk, status: 'pending', attempts: preserveAttempt ? chunk.attempts : Math.max(0, chunk.attempts - 1), workerId: null, startedAt: null, completedAt: null, error: String(reason) }; }); if (!found) throw new Error(`Unknown render chunk: ${chunkId}`); return refreshRenderJob({ ...job, chunks }); }
export function recoverInterruptedRenderJob(job) { const chunks = job.chunks.map((chunk) => chunk.status === "running" ? { ...chunk, status: chunk.attempts < chunk.maxAttempts ? "pending" : "failed", workerId: null, error: "Interrupted", startedAt: null } : chunk); return refreshRenderJob({ ...job, chunks }); }
export function renderJobProgress(job) { const total = job.chunks.reduce((sum, chunk) => sum + chunk.frameCount, 0); const complete = job.chunks.filter((chunk) => chunk.status === "complete").reduce((sum, chunk) => sum + chunk.frameCount, 0); const running = job.chunks.filter((chunk) => chunk.status === "running").reduce((sum, chunk) => sum + chunk.frameCount, 0); const failed = job.chunks.filter((chunk) => chunk.status === "failed").reduce((sum, chunk) => sum + chunk.frameCount, 0); return { totalFrames: total, completedFrames: complete, runningFrames: running, failedFrames: failed, ratio: total ? complete / total : 1 }; }
export function refreshRenderJob(job) { const chunks = job.chunks ?? []; const terminalFailure = chunks.some((chunk) => chunk.status === "failed" && chunk.attempts >= chunk.maxAttempts); const allComplete = chunks.every((chunk) => chunk.status === "complete"); const anyRunning = chunks.some((chunk) => chunk.status === "running"); const status = allComplete ? "complete" : terminalFailure ? "failed" : anyRunning ? "running" : "pending"; return { ...job, status }; }
export function artifactManifestForJob(job) { if (job.status !== "complete") throw new Error("Render job is not complete"); return { version: 1, jobId: job.id, signature: job.signature, frameCount: job.frameCount, chunks: [...job.chunks].sort((a, b) => a.index - b.index).map((chunk) => ({ id: chunk.id, frameStart: chunk.frameStart, frameEnd: chunk.frameEnd, artifact: structuredClone(chunk.artifact) })) }; }
