import { createEncodedChunkDescriptor } from './media-kernel.js';
import { readRange } from './range-source.js';
import { demuxWebm } from './webm-demux.js';

const IDS={EBML:0x1a45dfa3,SEGMENT:0x18538067,INFO:0x1549a966,TRACKS:0x1654ae6b,CLUSTER:0x1f43b675,TIMECODE:0xe7,SIMPLE_BLOCK:0xa3,BLOCK_GROUP:0xa0,BLOCK:0xa1,REFERENCE_BLOCK:0xfb};
function concat(parts){const out=new Uint8Array(parts.reduce((sum,part)=>sum+part.byteLength,0));let offset=0;for(const part of parts){out.set(part,offset);offset+=part.byteLength;}return out;}
function unknownSegmentHeader(){return new Uint8Array([0x18,0x53,0x80,0x67,0x01,0xff,0xff,0xff,0xff,0xff,0xff,0xff]);}
function vintLength(first,max=8){let mask=0x80,length=1;while(length<=max&&!(first&mask)){mask>>=1;length++;}if(length>max||mask===0)throw new Error('Invalid EBML vint');return{length,mask};}
function unsigned(bytes){let value=0n;for(const byte of bytes)value=(value<<8n)|BigInt(byte);if(value>BigInt(Number.MAX_SAFE_INTEGER))throw new Error('EBML value exceeds safe integer range');return Number(value);}
async function readElementHeader(source,offset,parentEnd=source.size,{signal}={}){if(offset>=parentEnd)return null;const first=await readRange(source,offset,1,{signal}),idInfo=vintLength(first[0],4),idBytes=idInfo.length===1?first:await readRange(source,offset,idInfo.length,{signal}),id=unsigned(idBytes);const sizeFirst=await readRange(source,offset+idInfo.length,1,{signal}),sizeInfo=vintLength(sizeFirst[0],8),sizeBytes=sizeInfo.length===1?sizeFirst:await readRange(source,offset+idInfo.length,sizeInfo.length,{signal});let sizeValue=BigInt(sizeBytes[0]&(sizeInfo.mask-1));for(let i=1;i<sizeBytes.length;i++)sizeValue=(sizeValue<<8n)|BigInt(sizeBytes[i]);const max=(1n<<BigInt(7*sizeInfo.length))-1n,unknown=sizeValue===max,headerSize=idInfo.length+sizeInfo.length,dataOffset=offset+headerSize;const size=unknown?parentEnd-dataOffset:Number(sizeValue);if(size<0||dataOffset+size>parentEnd)throw new Error('EBML element exceeds parent/source bounds');return{id,offset,headerSize,dataOffset,size,end:dataOffset+size,unknownSize:unknown};}
async function readElementBytes(source,element,{signal,maxBytes=8*1024*1024}={}){if(element.size+element.headerSize>maxBytes)throw new Error(`EBML metadata element ${element.id.toString(16)} exceeds ${maxBytes} bytes`);return readRange(source,element.offset,element.headerSize+element.size,{signal});}
function parseBlockHeader(bytes,element,{clusterTimecode,timecodeScale,trackMap,keyframeOverride}={}){let cursor=0;const trackInfo=vintLength(bytes[cursor],8);let trackValue=BigInt(bytes[cursor]&(trackInfo.mask-1));for(let i=1;i<trackInfo.length;i++)trackValue=(trackValue<<8n)|BigInt(bytes[cursor+i]);const trackNumber=Number(trackValue);cursor+=trackInfo.length;if(cursor+3>bytes.length)throw new Error('Truncated WebM block header');const raw=(bytes[cursor]<<8)|bytes[cursor+1],relative=raw&0x8000?raw-0x10000:raw-0;cursor+=2;const flags=bytes[cursor++],lacing=(flags>>1)&3,keyframe=keyframeOverride??Boolean(flags&0x80);let sizes=[];const payloadLength=element.size;if(lacing===0)sizes=[payloadLength-cursor];else{if(cursor>=bytes.length)throw new Error('Truncated WebM lace count');const frameCount=bytes[cursor++]+1;if(lacing===2){const remaining=payloadLength-cursor;if(remaining%frameCount)throw new Error('Invalid fixed WebM lacing');sizes=Array(frameCount).fill(remaining/frameCount);}else if(lacing===1){let used=0;for(let frame=0;frame<frameCount-1;frame++){let size=0;while(true){if(cursor>=bytes.length)throw new Error('WebM Xiph lace header exceeds read limit');const value=bytes[cursor++];size+=value;if(value!==255)break;}sizes.push(size);used+=size;}sizes.push(payloadLength-cursor-used);}else{const readLocalVint=()=>{if(cursor>=bytes.length)throw new Error('WebM EBML lace header exceeds read limit');const info=vintLength(bytes[cursor],8);if(cursor+info.length>bytes.length)throw new Error('Truncated WebM EBML lace');let value=BigInt(bytes[cursor]&(info.mask-1));for(let i=1;i<info.length;i++)value=(value<<8n)|BigInt(bytes[cursor+i]);cursor+=info.length;return{value,length:info.length};};const first=readLocalVint();sizes=[Number(first.value)];let used=sizes[0];for(let frame=1;frame<frameCount-1;frame++){const delta=readLocalVint(),bias=(1n<<BigInt(7*delta.length-1))-1n,next=sizes.at(-1)+Number(delta.value-bias);if(next<0)throw new Error('Negative WebM lace size');sizes.push(next);used+=next;}sizes.push(payloadLength-cursor-used);}}
  if(sizes.some((size)=>size<0)||sizes.reduce((sum,size)=>sum+size,0)!==payloadLength-cursor)throw new Error('Invalid WebM lace payload sizes');const track=trackMap.get(trackNumber);if(!track)return[];const defaultDurationMicros=track.defaultDurationNs?Math.round(track.defaultDurationNs/1000):0,baseMicros=Math.max(0,Math.round((clusterTimecode+relative)*timecodeScale/1000));let absolute=element.dataOffset+cursor;return sizes.map((size,index)=>{const value={trackNumber,trackId:track.id,type:keyframe?'key':'delta',timestamp:baseMicros+index*defaultDurationMicros,duration:defaultDurationMicros,offset:absolute,byteLength:size,flags:{keyframe,lacing}};absolute+=size;return value;});}
async function parseSparseBlock(source,element,options){let headerLimit=Math.min(element.size,64);while(true){const bytes=await readRange(source,element.dataOffset,headerLimit,{signal:options.signal});try{return parseBlockHeader(bytes,element,options);}catch(error){if(!/header exceeds read limit|Truncated WebM lace/.test(String(error?.message))||headerLimit>=Math.min(element.size,64*1024))throw error;headerLimit=Math.min(element.size,Math.min(64*1024,headerLimit*4));}}}
async function scanGroup(source,group,options){let cursor=group.dataOffset,block=null,reference=false;while(cursor<group.end){const child=await readElementHeader(source,cursor,group.end,{signal:options.signal});if(!child)break;if(child.id===IDS.BLOCK)block=child;if(child.id===IDS.REFERENCE_BLOCK)reference=true;cursor=child.end;}return block?parseSparseBlock(source,block,{...options,keyframeOverride:!reference}):[];}
async function scanCluster(source,cluster,{timecodeScale,trackMap,signal}={}){let cursor=cluster.dataOffset,timecode=0;const blocks=[];while(cursor<cluster.end){const child=await readElementHeader(source,cursor,cluster.end,{signal});if(!child)break;if(child.id===IDS.TIMECODE){const data=await readRange(source,child.dataOffset,child.size,{signal});timecode=unsigned(data);}else if(child.id===IDS.SIMPLE_BLOCK)blocks.push(...await parseSparseBlock(source,child,{clusterTimecode:timecode,timecodeScale,trackMap,signal}));else if(child.id===IDS.BLOCK_GROUP)blocks.push(...await scanGroup(source,child,{clusterTimecode:timecode,timecodeScale,trackMap,signal}));cursor=child.end;}return blocks;}
export async function demuxWebmSource(source,{signal,maxMetadataBytes=8*1024*1024}={}){if(!source||typeof source.read!=='function')throw new Error('WebM range demux requires a range source');const root=await readElementHeader(source,0,source.size,{signal});if(root?.id!==IDS.EBML)throw new Error('WebM EBML header not found');const headerBytes=await readElementBytes(source,root,{signal,maxBytes:maxMetadataBytes});let cursor=root.end,segment=null;while(cursor<source.size){const element=await readElementHeader(source,cursor,source.size,{signal});if(!element)break;if(element.id===IDS.SEGMENT){segment=element;break;}cursor=element.end;}if(!segment)throw new Error('WebM Segment not found');let info=null,tracks=null;const clusters=[];cursor=segment.dataOffset;while(cursor<segment.end){const element=await readElementHeader(source,cursor,segment.end,{signal});if(!element)break;if(element.id===IDS.INFO)info=element;else if(element.id===IDS.TRACKS)tracks=element;else if(element.id===IDS.CLUSTER)clusters.push(element);cursor=element.end;}if(!tracks)throw new Error('WebM Tracks element not found');const metadataParts=[headerBytes,unknownSegmentHeader()];if(info)metadataParts.push(await readElementBytes(source,info,{signal,maxBytes:maxMetadataBytes}));metadataParts.push(await readElementBytes(source,tracks,{signal,maxBytes:maxMetadataBytes}));const metadataPlan=demuxWebm(concat(metadataParts));const trackMap=new Map(metadataPlan.trackDetails.map((detail)=>[detail.number,{id:detail.id,defaultDurationNs:detail.defaultDurationNs??0,type:metadataPlan.tracks.find((track)=>track.id===detail.id)?.type}]));const chunks=[];let sequence=new Map();for(const cluster of clusters){for(const frame of await scanCluster(source,cluster,{timecodeScale:metadataPlan.metadata.timecodeScale??1_000_000,trackMap,signal})){const value=sequence.get(frame.trackId)??0;sequence.set(frame.trackId,value+1);chunks.push({...createEncodedChunkDescriptor({trackId:frame.trackId,type:frame.type,timestamp:frame.timestamp,duration:frame.duration,byteLength:frame.byteLength,offset:frame.offset,sequence:value}),presentationTimestamp:frame.timestamp,decodeTimestamp:frame.timestamp,blockFlags:frame.flags});}}
  for(const track of metadataPlan.tracks){const list=chunks.filter((chunk)=>chunk.trackId===track.id).sort((a,b)=>a.timestamp-b.timestamp||a.sequence-b.sequence);for(let i=0;i<list.length;i++)if(!list[i].duration&&list[i+1])list[i].duration=Math.max(0,list[i+1].timestamp-list[i].timestamp);}
  const seekPoints=[...new Set(chunks.filter((chunk)=>chunk.type==='key'&&metadataPlan.tracks.find((track)=>track.id===chunk.trackId)?.type==='video').map((chunk)=>chunk.timestamp/1_000_000))].sort((a,b)=>a-b);const duration=metadataPlan.duration||Math.max(0,...chunks.map((chunk)=>(chunk.timestamp+chunk.duration)/1_000_000));return{...metadataPlan,duration,seekPoints,chunks,metadata:{...metadataPlan.metadata,sampleCount:chunks.length,rangeIndexed:true,clusterCount:clusters.length}};}
export async function readWebmFrameFromSource(source,chunk,{signal}={}){return readRange(source,Number(chunk.offset),Number(chunk.byteLength),{signal});}
