function bytesOf(value){if(value instanceof Uint8Array)return value;if(value instanceof ArrayBuffer)return new Uint8Array(value);if(ArrayBuffer.isView(value))return new Uint8Array(value.buffer,value.byteOffset,value.byteLength);throw new Error('WebM sample payload must be binary');}
function concat(parts){const arrays=parts.filter(Boolean).map(bytesOf);const out=new Uint8Array(arrays.reduce((sum,a)=>sum+a.length,0));let offset=0;for(const array of arrays){out.set(array,offset);offset+=array.length;}return out;}
function idBytes(id){let value=BigInt(id);let length=1;while(value>=(1n<<BigInt(length*8)))length++;const out=new Uint8Array(length);for(let index=length-1;index>=0;index--){out[index]=Number(value&255n);value>>=8n;}return out;}
export function encodeEbmlSize(size){let value=BigInt(size);if(value<0n)throw new Error('EBML size must be non-negative');for(let length=1;length<=8;length++){const max=(1n<<BigInt(7*length))-2n;if(value<=max){const out=new Uint8Array(length);let current=value;for(let index=length-1;index>=0;index--){out[index]=Number(current&255n);current>>=8n;}out[0]|=1<<(8-length);return out;}}throw new Error('EBML size is too large');}
export function encodeEbmlVintValue(value){const numeric=Number(value);if(!Number.isInteger(numeric)||numeric<=0)throw new Error('EBML vint value must be a positive integer');for(let length=1;length<=8;length++){const max=2**(7*length)-2;if(numeric<=max){let current=BigInt(numeric);const out=new Uint8Array(length);for(let index=length-1;index>=0;index--){out[index]=Number(current&255n);current>>=8n;}out[0]|=1<<(8-length);return out;}}throw new Error('EBML vint value is too large');}
function element(id,payload){const body=bytesOf(payload);return concat([idBytes(id),encodeEbmlSize(body.length),body]);}
function uint(value){let current=BigInt(Math.max(0,Math.round(Number(value)||0))),length=1;while(current>=(1n<<BigInt(length*8)))length++;const out=new Uint8Array(length);for(let index=length-1;index>=0;index--){out[index]=Number(current&255n);current>>=8n;}return out;}
function float64(value){const out=new Uint8Array(8);new DataView(out.buffer).setFloat64(0,Number(value),false);return out;}
function string(value){return new TextEncoder().encode(String(value));}
function int16(value){const out=new Uint8Array(2);new DataView(out.buffer).setInt16(0,value,false);return out;}
function codecId(codec,type){const value=String(codec).toLowerCase();if(type==='video'){if(value.startsWith('vp8'))return'V_VP8';if(value.startsWith('vp09')||value.startsWith('vp9'))return'V_VP9';if(value.startsWith('av01')||value.startsWith('av1'))return'V_AV1';}if(type==='audio'){if(value.startsWith('opus'))return'A_OPUS';if(value.startsWith('vorbis'))return'A_VORBIS';}throw new Error(`Codec ${codec} is not supported by the WebM writer`);}
function trackEntry(track,number){const config=track.config??{};const parts=[element(0xd7,uint(number)),element(0x73c5,uint(number)),element(0x83,uint(track.type==='video'?1:track.type==='audio'?2:0)),element(0x86,string(codecId(track.codec,track.type)))];if(config.description)parts.push(element(0x63a2,bytesOf(config.description)));if(track.type==='video'){const width=config.width??config.codedWidth,height=config.height??config.codedHeight;if(!width||!height)throw new Error(`WebM video track ${track.id} requires width and height`);parts.push(element(0xe0,concat([element(0xb0,uint(width)),element(0xba,uint(height))])));}else if(track.type==='audio'){const sampleRate=config.sampleRate??config.sample_rate,channels=config.channels??config.numberOfChannels;if(!sampleRate||!channels)throw new Error(`WebM audio track ${track.id} requires sampleRate and channels`);parts.push(element(0xe1,concat([element(0xb5,float64(sampleRate)),element(0x9f,uint(channels))])));}return element(0xae,concat(parts));}
function samplePayload(sample){if(sample.payload!=null)return bytesOf(sample.payload);if(sample.bytes!=null)return bytesOf(sample.bytes);throw new Error(`WebM sample ${sample.trackId}:${sample.sequence??0} has no payload`);}
function clusterBytes(cluster,trackNumbers){const parts=[element(0xe7,uint(cluster.timecode))];for(const sample of cluster.samples){const number=trackNumbers.get(sample.trackId);const tick=Math.round(Number(sample.timestamp)/1000);const relative=tick-cluster.timecode;if(relative<-32768||relative>32767)throw new Error('WebM SimpleBlock relative timecode exceeds int16 range');const flags=sample.keyframe||sample.type==='key'?0x80:0;const block=concat([encodeEbmlVintValue(number),int16(relative),new Uint8Array([flags]),samplePayload(sample)]);parts.push(element(0xa3,block));}return element(0x1f43b675,concat(parts));}
function makeClusters(samples,{maxClusterMs=5000}={}){const clusters=[];let current=null;for(const sample of samples){const tick=Math.round(Number(sample.timestamp)/1000);const startsNew=!current||tick-current.timecode>30000||(sample.keyframe||sample.type==='key')&&tick-current.timecode>=maxClusterMs;if(startsNew){current={timecode:tick,samples:[]};clusters.push(current);}current.samples.push(sample);}return clusters;}
function cuesBytes(clusters,clusterOffsets,plan,trackNumbers){const videoIds=new Set(plan.tracks.filter((track)=>track.type==='video').map((track)=>track.id));if(!videoIds.size)return null;const points=[];for(let index=0;index<clusters.length;index++){const cluster=clusters[index];const keySample=cluster.samples.find((sample)=>videoIds.has(sample.trackId)&&(sample.keyframe||sample.type==='key'));if(!keySample)continue;const trackNumber=trackNumbers.get(keySample.trackId);const positions=element(0xb7,concat([element(0xf7,uint(trackNumber)),element(0xf1,uint(clusterOffsets[index]))]));points.push(element(0xbb,concat([element(0xb3,uint(cluster.timecode)),positions])));}return points.length?element(0x1c53bb6b,concat(points)):null;}
export function muxWebm(plan,{timecodeScale=1_000_000,maxClusterMs=5000,muxingApp='Media',writingApp='Media'}={}){if(!plan||plan.container!=='webm')throw new Error('muxWebm requires a WebM mux plan');if(!Array.isArray(plan.tracks)||!plan.tracks.length)throw new Error('WebM mux requires tracks');const trackNumbers=new Map(plan.tracks.map((track,index)=>[track.id,index+1]));const samples=[...(plan.samples??[])].sort((a,b)=>Number(a.timestamp)-Number(b.timestamp)||Number(a.trackOrder??0)-Number(b.trackOrder??0)||Number(a.sequence??0)-Number(b.sequence??0));for(const sample of samples)if(!trackNumbers.has(sample.trackId))throw new Error(`Unknown WebM sample track ${sample.trackId}`);const durationMicros=samples.reduce((max,sample)=>Math.max(max,Number(sample.timestamp)+Number(sample.duration??0)),0);const durationTicks=durationMicros*1000/timecodeScale;const ebmlHeader=element(0x1a45dfa3,concat([element(0x4286,uint(1)),element(0x42f7,uint(1)),element(0x42f2,uint(4)),element(0x42f3,uint(8)),element(0x4282,string('webm')),element(0x4287,uint(4)),element(0x4285,uint(2))]));const info=element(0x1549a966,concat([element(0x2ad7b1,uint(timecodeScale)),element(0x4489,float64(durationTicks)),element(0x4d80,string(muxingApp)),element(0x5741,string(writingApp))]));const tracks=element(0x1654ae6b,concat(plan.tracks.map((track,index)=>trackEntry(track,index+1))));const clusterModels=makeClusters(samples,{maxClusterMs});const clusters=clusterModels.map((cluster)=>clusterBytes(cluster,trackNumbers));const clusterOffsets=[];let offset=info.length+tracks.length;for(const cluster of clusters){clusterOffsets.push(offset);offset+=cluster.length;}const cues=cuesBytes(clusterModels,clusterOffsets,plan,trackNumbers);const segmentPayload=concat([info,tracks,...clusters,cues]);return concat([ebmlHeader,element(0x18538067,segmentPayload)]);}
