import { readRange } from './range-source.js';
const IDS={CLUSTER:0x1f43b675,TIMECODE:0xe7,SIMPLE_BLOCK:0xa3,BLOCK_GROUP:0xa0,BLOCK:0xa1,REFERENCE_BLOCK:0xfb};
function vintInfo(first,max=8){let mask=0x80,length=1;while(length<=max&&!(first&mask)){mask>>=1;length++;}if(length>max||!mask)throw new Error('Invalid EBML vint');return{length,mask};}
function unsigned(bytes){let n=0n;for(const b of bytes)n=(n<<8n)|BigInt(b);if(n>BigInt(Number.MAX_SAFE_INTEGER))throw new Error('EBML value exceeds safe integer range');return Number(n);}
async function headerAt(source,offset,parentEnd,{signal,allowPartial=true}={}){if(offset>=parentEnd||offset>=source.size)return null;let first;try{first=await readRange(source,offset,1,{signal});}catch(error){if(allowPartial&&/exceeds source size/.test(String(error.message)))return null;throw error;}const idInfo=vintInfo(first[0],4);if(offset+idInfo.length+1>source.size)return null;const idBytes=await readRange(source,offset,idInfo.length,{signal}),id=unsigned(idBytes),sizeFirst=await readRange(source,offset+idInfo.length,1,{signal}),sizeInfo=vintInfo(sizeFirst[0],8);if(offset+idInfo.length+sizeInfo.length>source.size)return null;const sizeBytes=await readRange(source,offset+idInfo.length,sizeInfo.length,{signal});let value=BigInt(sizeBytes[0]&(sizeInfo.mask-1));for(let i=1;i<sizeBytes.length;i++)value=(value<<8n)|BigInt(sizeBytes[i]);const max=(1n<<BigInt(7*sizeInfo.length))-1n,unknown=value===max,headerSize=idInfo.length+sizeInfo.length,dataOffset=offset+headerSize,size=unknown?null:Number(value),end=size==null?null:dataOffset+size;if(end!=null&&end>parentEnd){if(!(allowPartial&&parentEnd===source.size))throw new Error('EBML element exceeds parent bounds');}return{id,offset,headerSize,dataOffset,size,end,unknownSize:unknown,complete:end==null?false:end<=source.size};}
function signed16(a,b){const raw=(a<<8)|b;return raw&0x8000?raw-0x10000:raw;}
async function readBlockPrefix(source,element,{signal,maxPrefix=65536}={}){let length=Math.min(element.size??0,64);while(length<=Math.min(element.size??0,maxPrefix)){if(element.dataOffset+length>source.size)return null;const bytes=await readRange(source,element.dataOffset,length,{signal});try{return parseBlockPrefix(bytes,element);}catch(error){if(!/prefix|lace|Truncated/.test(String(error.message))||length===Math.min(element.size,maxPrefix))throw error;length=Math.min(element.size,maxPrefix,length*2);}}return null;}
function readLocalVint(bytes,state){if(state.cursor>=bytes.length)throw new Error('Truncated EBML lace prefix');const info=vintInfo(bytes[state.cursor],8);if(state.cursor+info.length>bytes.length)throw new Error('Truncated EBML lace prefix');let value=BigInt(bytes[state.cursor]&(info.mask-1));for(let i=1;i<info.length;i++)value=(value<<8n)|BigInt(bytes[state.cursor+i]);state.cursor+=info.length;return{value,length:info.length};}
function parseBlockPrefix(bytes,element){const state={cursor:0},track=readLocalVint(bytes,state);if(state.cursor+3>bytes.length)throw new Error('Truncated WebM block prefix');const trackNumber=Number(track.value),relative=signed16(bytes[state.cursor],bytes[state.cursor+1]);state.cursor+=2;const flags=bytes[state.cursor++],lacing=(flags>>1)&3,frameCount=lacing?((state.cursor<bytes.length?bytes[state.cursor++]:(()=>{throw new Error('Truncated lace prefix');})())+1):1;const payloadLength=element.size-state.cursor;let sizes=[];
  if(lacing===0)sizes=[payloadLength];
  else if(lacing===2){if(payloadLength%frameCount)throw new Error('Invalid fixed lacing');sizes=Array(frameCount).fill(payloadLength/frameCount);}
  else if(lacing===1){let used=0;for(let frame=0;frame<frameCount-1;frame++){let size=0;while(true){if(state.cursor>=bytes.length)throw new Error('Xiph lace prefix exceeds available prefix');const value=bytes[state.cursor++];size+=value;if(value!==255)break;}sizes.push(size);used+=size;}sizes.push(element.size-state.cursor-used);}
  else {const first=readLocalVint(bytes,state);sizes=[Number(first.value)];let used=sizes[0];for(let frame=1;frame<frameCount-1;frame++){const delta=readLocalVint(bytes,state),bias=(1n<<BigInt(7*delta.length-1))-1n,next=sizes.at(-1)+Number(delta.value-bias);if(next<0)throw new Error('Negative EBML lace size');sizes.push(next);used+=next;}sizes.push(element.size-state.cursor-used);}
  if(sizes.some((size)=>size<0)||sizes.reduce((a,b)=>a+b,0)!==element.size-state.cursor)throw new Error('Invalid WebM lace sizes');let absolute=element.dataOffset+state.cursor;return{trackNumber,relative,flags,keyframe:Boolean(flags&0x80),sizes,frameOffsets:sizes.map((size)=>{const offset=absolute;absolute+=size;return{offset,size};})};}
async function uintElement(source,element,{signal}={}){if(!element.complete)return null;return unsigned(await readRange(source,element.dataOffset,element.size,{signal}));}
export class LiveWebmClusterIndexer{
  constructor({segmentDataOffset=0,timecodeScale=1_000_000,tracks=[]}={}){this.segmentDataOffset=Number(segmentDataOffset)||0;this.timecodeScale=Number(timecodeScale)||1_000_000;this.trackMap=new Map(tracks.map((track)=>[Number(track.number??track.numericId),{id:String(track.id),type:track.type,defaultDurationNs:Number(track.defaultDurationNs??0)}]));this.cursor=this.segmentDataOffset;this.openCluster=null;this.chunks=[];this.seen=new Set();this.sequence=new Map();this.clusterCount=0;}
  async refresh(source,{signal}={}){const added=[];while(true){if(this.openCluster){const status=await this.#scanOpenCluster(source,added,{signal});if(status==='waiting')break;if(status==='next-cluster'){this.openCluster=null;continue;}if(status==='closed'){this.openCluster=null;continue;}if(status==='continue')continue;}
      const element=await headerAt(source,this.cursor,source.size,{signal});if(!element)break;if(element.id!==IDS.CLUSTER){if(element.end==null||!element.complete)break;this.cursor=element.end;continue;}this.openCluster={offset:element.offset,dataOffset:element.dataOffset,end:element.end,unknown:element.unknownSize,cursor:element.dataOffset,timecode:0};this.clusterCount++;if(!element.unknownSize&&element.end>source.size)break;}
    return{newChunks:added,chunks:[...this.chunks],cursor:this.cursor,openCluster:Boolean(this.openCluster),clusterCount:this.clusterCount};}
  async #scanOpenCluster(source,added,{signal}={}){const cluster=this.openCluster,parentEnd=cluster.end??source.size;if(cluster.cursor>=parentEnd){if(cluster.unknown)return'waiting';this.cursor=cluster.end??cluster.cursor;return'closed';}const child=await headerAt(source,cluster.cursor,parentEnd,{signal});if(!child)return'waiting';if(cluster.unknown&&child.id===IDS.CLUSTER){this.cursor=child.offset;return'next-cluster';}if(child.id===IDS.TIMECODE){if(!child.complete)return'waiting';const value=await uintElement(source,child,{signal});cluster.timecode=value??cluster.timecode;cluster.cursor=child.end;return'continue';}
    if(child.id===IDS.SIMPLE_BLOCK||child.id===IDS.BLOCK){if(!child.complete)return'waiting';const prefix=await readBlockPrefix(source,child,{signal});if(!prefix)return'waiting';this.#emit(prefix,cluster.timecode,child.id===IDS.SIMPLE_BLOCK?prefix.keyframe:true,added);cluster.cursor=child.end;return'continue';}
    if(child.id===IDS.BLOCK_GROUP){if(!child.complete)return'waiting';let cursor=child.dataOffset,block=null,reference=false;while(cursor<child.end){const part=await headerAt(source,cursor,child.end,{signal});if(!part||!part.complete)return'waiting';if(part.id===IDS.BLOCK)block=part;if(part.id===IDS.REFERENCE_BLOCK)reference=true;cursor=part.end;}if(block){const prefix=await readBlockPrefix(source,block,{signal});if(!prefix)return'waiting';this.#emit(prefix,cluster.timecode,!reference,added);}cluster.cursor=child.end;return'continue';}
    if(child.end==null||!child.complete)return'waiting';cluster.cursor=child.end;return'continue';}
  #emit(prefix,clusterTimecode,keyframe,added){const track=this.trackMap.get(prefix.trackNumber);if(!track)return;const baseMicros=Math.max(0,Math.round((clusterTimecode+prefix.relative)*this.timecodeScale/1000)),duration=track.defaultDurationNs?Math.round(track.defaultDurationNs/1000):0;for(let i=0;i<prefix.frameOffsets.length;i++){const frame=prefix.frameOffsets[i],key=`${frame.offset}:${frame.size}`;if(this.seen.has(key))continue;this.seen.add(key);const seq=this.sequence.get(track.id)??0;this.sequence.set(track.id,seq+1);const chunk={trackId:track.id,type:keyframe?'key':'delta',keyframe,timestamp:baseMicros+i*duration,presentationTimestamp:baseMicros+i*duration,decodeTimestamp:baseMicros+i*duration,duration,offset:frame.offset,byteLength:frame.size,sequence:seq,live:true};this.chunks.push(chunk);added.push(chunk);}}
}
export function createLiveWebmClusterIndexer(options){return new LiveWebmClusterIndexer(options);}
