import { createAudioMixPlan } from '../../packages/core/src/audio.js';
import { writableStreamByteSink } from '../../packages/core/src/byte-sink.js';
import { createRenderManifest } from '../../packages/core/src/deliver.js';
import { evaluateComposition } from '../../packages/core/src/evaluation.js';
import { analyzeLoudness, normalizeLoudness } from '../../packages/core/src/loudness.js';
import { renderAutomatedMix } from '../../packages/core/src/offline-audio.js';
import { demuxIsoBmff } from '../../packages/core/src/isobmff-demux.js';
import { demuxWebm } from '../../packages/core/src/webm-demux.js';
import { sniffContainer } from '../../packages/core/src/media-kernel.js';
import { BrowserFrameProvider, renderPlanToCanvas2D } from './render-engine.js';
import { generateVideoProxyArtifact } from './derivative-engine.js';
import { loadOrCreateDerivativeJob, runSegmentedDerivative } from './derivative-job-runner.js';
import { renderProgressiveTimelineExport, renderTimelineExport } from './deliver-runtime.js';
import { loadAssetBlob, loadDerivedArtifact, loadStoredGraph, saveDerivedArtifact } from './storage.js';

function toast(message,kind='info'){let node=document.querySelector('#advanced-runtime-toast');if(!node){node=document.createElement('div');node.id='advanced-runtime-toast';Object.assign(node.style,{position:'fixed',right:'18px',bottom:'18px',zIndex:10000,maxWidth:'380px',padding:'10px 14px',borderRadius:'8px',background:'#17191f',color:'#fff',font:'12px system-ui',boxShadow:'0 10px 30px #0008'});document.body.appendChild(node);}node.textContent=message;node.dataset.kind=kind;clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.remove(),5000);}
function safeName(value){return String(value||'media').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'media';}
function download(bytes,name,type){const blob=bytes instanceof Blob?bytes:new Blob([bytes],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function blobResolver(assetId){return loadAssetBlob(assetId).catch(()=>null);}
async function decodeBlobPcm(blob){const Ctor=globalThis.AudioContext??globalThis.webkitAudioContext;if(!Ctor)throw new Error('AudioContext is unavailable for offline decode');const context=new Ctor();try{const decoded=await context.decodeAudioData(await blob.arrayBuffer());return{sampleRate:decoded.sampleRate,length:decoded.length,channels:Array.from({length:decoded.numberOfChannels},(_,i)=>new Float32Array(decoded.getChannelData(i)))}}finally{await context.close().catch(()=>{});}}
async function renderOfflineAudio(graph,output,{start,end,sampleRate=48000}={}){const plan=createAudioMixPlan(graph,{start,end,sampleRate,blockSize:1024});if(!plan.sources.length)return null;const sources=new Map();for(const item of plan.sources){if(sources.has(item.assetId))continue;const blob=await blobResolver(item.assetId);if(blob)sources.set(item.assetId,await decodeBlobPcm(blob));}const clipAutomation={};for(const item of plan.sources){const clip=graph.nodes[item.clipId];if(clip?.props?.audioAutomation)clipAutomation[item.clipId]=clip.props.audioAutomation;}let pcm=renderAutomatedMix(plan,sources,{channels:2,clipAutomation,masterAutomation:output.props?.audioAutomation??{}});const before=analyzeLoudness(pcm);if(Number.isFinite(Number(output.props?.loudnessTargetLufs))){const normalized=normalizeLoudness(pcm,{targetLufs:Number(output.props.loudnessTargetLufs),maxTruePeakDbfs:Number(output.props.maxTruePeakDbfs??-1)});pcm=normalized.buffer;pcm.loudness={before,after:normalized.after,gainDb:normalized.gainDb};}else pcm.loudness={before};return pcm;}
async function createFileSink(name,mimeType){if(typeof globalThis.showSaveFilePicker!=='function')throw new Error('Streaming file output requires the File System Access API');const handle=await showSaveFilePicker({suggestedName:name,types:[{description:mimeType,accept:{[mimeType]:[name.endsWith('.webm')?'.webm':'.mp4']}}]});return writableStreamByteSink(await handle.createWritable());}
async function renderOutput(outputId,container,{stream=false}={}){const graph=await loadStoredGraph();const output=graph?.nodes?.[outputId];if(!output)throw new Error('Output is unavailable');const manifest=createRenderManifest(graph,outputId),provider=new BrowserFrameProvider({blobResolver});const width=Number(output.props.width),height=Number(output.props.height);const renderFrame=async(time)=>{const plan=evaluateComposition(graph,{compositionId:output.props.compositionId,time});const source=document.createElement('canvas');await renderPlanToCanvas2D(source,plan,{assetResolver:(id)=>graph.nodes[id],frameProvider:provider});const target=document.createElement('canvas');target.width=width;target.height=height;target.getContext('2d').drawImage(source,0,0,width,height);return target;};const audioPlan=createAudioMixPlan(graph,{start:Number(output.props.rangeStart??0),end:Number(output.props.rangeEnd),sampleRate:48000});const hasAudio=audioPlan.sources.length>0;const mp4=container==='mp4';const filename=`${safeName(output.name)}.${mp4?'mp4':'webm'}`;const mimeType=mp4?'video/mp4':'video/webm';const sink=stream?await createFileSink(filename,mimeType):null;const renderOptions={manifest,container,renderFrame,renderAudioPcm:hasAudio?({start,end,sampleRate})=>renderOfflineAudio(graph,output,{start,end,sampleRate}):null,videoConfig:mp4?{codec:'avc1.640028',bitrate:Math.max(1_000_000,width*height*4),avc:{format:'avc'}}:{codec:'vp09.00.10.08',bitrate:Math.max(800_000,width*height*3)},audioConfig:hasAudio?(mp4?{codec:'mp4a.40.2',sampleRate:48000,numberOfChannels:2,bitrate:192000}:{codec:'opus',sampleRate:48000,numberOfChannels:2,bitrate:160000}):null,sink,fragmented:stream&&mp4,segmentDuration:2,onProgress:({stage,ratio})=>toast(`${output.name}: ${stage} ${Math.round(ratio*100)}%`)};const result=stream?await renderProgressiveTimelineExport(renderOptions):await renderTimelineExport(renderOptions);provider.clear?.();if(!stream)download(result.bytes,filename,mimeType);toast(stream?`${output.name} streamed to ${mp4?'fragmented MP4':'WebM'}`:`${output.name} rendered to ${mp4?'MP4':'WebM'} (${Math.round(result.bytes.byteLength/1024)} KB)`);return result;}
async function analyzeOutput(outputId){const graph=await loadStoredGraph();const output=graph?.nodes?.[outputId];if(!output)throw new Error('Output is unavailable');const pcm=await renderOfflineAudio(graph,output,{start:Number(output.props.rangeStart??0),end:Number(output.props.rangeEnd),sampleRate:48000});if(!pcm){toast('Output has no audible timeline sources');return;}const result=pcm.loudness?.after??pcm.loudness?.before??analyzeLoudness(pcm);toast(`Integrated ${result.integratedLufs.toFixed(1)} LUFS · true peak ${result.truePeakDbfs.toFixed(1)} dBFS`);}
function selectedAssetId(){return document.querySelector('.library-item.selected[data-select], [data-select].selected')?.dataset.select??null;}
async function buildSelectedProxy(){const graph=await loadStoredGraph(),id=selectedAssetId(),asset=graph?.nodes?.[id];if(!asset||asset.kind!=='asset'||asset.props.mediaKind!=='video')throw new Error('Select a video asset first');const blob=await loadAssetBlob(id);if(!blob)throw new Error('Selected source is offline');const bytes=new Uint8Array(await blob.arrayBuffer()),container=sniffContainer({mimeType:asset.props.mimeType,name:asset.name,bytes:bytes.subarray(0,32)}),plan=container==='webm'?demuxWebm(bytes):demuxIsoBmff(bytes,{container});const track=plan.tracks.find((t)=>t.type==='video'),audioTrack=plan.tracks.find((t)=>t.type==='audio');if(!track)throw new Error('No video track found');const videoChunks=plan.chunks.filter((c)=>c.trackId===track.id),audioChunks=audioTrack?plan.chunks.filter((c)=>c.trackId===audioTrack.id):[];const source={id:asset.id,hash:asset.props.hash,duration:plan.duration,width:track.width,height:track.height};const storage={load:async(key)=>(await loadDerivedArtifact(key))?.value??null,save:(key,value,metadata={})=>saveDerivedArtifact(key,value,metadata)};const job=await loadOrCreateDerivativeJob({source,type:'proxy-video',spec:{width:Math.min(1280,track.width),height:Math.round(track.height*Math.min(1,1280/track.width)/2)*2,codec:'vp9',maxDecodedFrames:480},keyframes:plan.seekPoints,segmentDuration:4,storage});toast(`Proxy: ${job.segments.filter((s)=>s.status==='complete').length}/${job.segments.length} segments complete`);const complete=await runSegmentedDerivative({job,track,chunks:videoChunks,sourceBytes:bytes,storage,onProgress:({completedSegments,totalSegments})=>toast(`Proxy: ${completedSegments}/${totalSegments} segments`),generateSegment:async({segment,chunks,sourceBytes:segmentBytes,signal})=>{const audioForSegment=audioChunks.filter((c)=>{const t=Number(c.presentationTimestamp??c.timestamp??0)/1_000_000,e=t+Number(c.duration??0)/1_000_000;return t<segment.end&&e>segment.start;});return generateVideoProxyArtifact({track,chunks,source:segmentBytes,spec:{...job.spec,maxDecodedFrames:480,maxDecodedAudioFrames:4096},audioTrack,audioChunks:audioForSegment,audioSource:bytes,signal});}});await storage.save(`proxy-manifest:${asset.id}`,{job:complete});toast(`Proxy complete: ${complete.segments.length} resumable WebM segments`);}
function inject(){for(const still of document.querySelectorAll('[data-render-action="still"][data-output-id]')){const parent=still.parentElement;if(!parent||parent.querySelector('[data-advanced-render]'))continue;for(const container of ['mp4','webm']){const button=document.createElement('button');button.textContent=`Render ${container.toUpperCase()}`;button.dataset.advancedRender=container;button.dataset.outputId=still.dataset.outputId;button.addEventListener('click',async(event)=>{event.stopPropagation();button.disabled=true;try{await renderOutput(button.dataset.outputId,container);}catch(error){toast(`Render failed: ${error.message}`,'error');}finally{button.disabled=false;}});parent.appendChild(button);}if(typeof globalThis.showSaveFilePicker==='function'){for(const container of ['mp4','webm']){const button=document.createElement('button');button.textContent=container==='mp4'?'Stream fMP4':'Stream WebM';button.dataset.advancedStream=container;button.dataset.outputId=still.dataset.outputId;button.addEventListener('click',async(event)=>{event.stopPropagation();button.disabled=true;try{await renderOutput(button.dataset.outputId,container,{stream:true});}catch(error){toast(`Stream failed: ${error.message}`,'error');}finally{button.disabled=false;}});parent.appendChild(button);}}const loud=document.createElement('button');loud.textContent='Analyze loudness';loud.addEventListener('click',async(e)=>{e.stopPropagation();try{await analyzeOutput(still.dataset.outputId);}catch(error){toast(error.message,'error');}});parent.appendChild(loud);}const relink=document.querySelector('#relink-input');const host=relink?.parentElement?.parentElement??relink?.parentElement;if(host&&!host.querySelector('[data-build-proxy]')){const button=document.createElement('button');button.textContent='Build/resume proxy';button.dataset.buildProxy='';button.addEventListener('click',async()=>{button.disabled=true;try{await buildSelectedProxy();}catch(error){toast(`Proxy failed: ${error.message}`,'error');}finally{button.disabled=false;}});host.appendChild(button);}}
new MutationObserver(inject).observe(document.documentElement,{subtree:true,childList:true});inject();
