import { createMuxPlanFromEncoded, muxSamplesFromEncodedStream } from '../../packages/core/src/encoded-export.js';
import { segmentMuxPlan } from '../../packages/core/src/mux.js';
import { FragmentedMp4StreamWriter, StreamingWebmWriter } from '../../packages/core/src/stream-mux.js';
import { muxMp4 } from '../../packages/core/src/isobmff-mux.js';
import { muxWebm } from '../../packages/core/src/webm-mux.js';
import { pcmBlocks } from '../../packages/core/src/offline-audio.js';
import { StreamingAudioEncoder, StreamingVideoEncoder } from './streaming-codecs.js';

function defaultVideoFrameFactory(source,{timestamp,duration}){if(typeof VideoFrame!=='function')throw new Error('VideoFrame is unavailable');return source instanceof VideoFrame?source:new VideoFrame(source,{timestamp,duration});}
function pcmBlockAudioData(block,timestamp,{AudioDataCtor=globalThis.AudioData}={}){if(typeof AudioDataCtor!=='function')throw new Error('AudioData is unavailable');const channels=block.channels.length,frames=block.length,data=new Float32Array(channels*frames);for(let c=0;c<channels;c++)data.set(block.channels[c],c*frames);return new AudioDataCtor({format:'f32-planar',sampleRate:block.sampleRate,numberOfFrames:frames,numberOfChannels:channels,timestamp,data});}
function closeMedia(value){try{value?.close?.();}catch{}}
function progressCall(callback,stage,ratio,detail={}){callback?.({stage,ratio:Math.max(0,Math.min(1,Number(ratio)||0)),...detail});}
export async function renderTimelineExport({manifest,renderFrame,renderAudioPcm=null,container='mp4',videoConfig,audioConfig=null,signal,onProgress,frameFactory=defaultVideoFrameFactory,audioDataFactory=pcmBlockAudioData,VideoEncoderClass=StreamingVideoEncoder,AudioEncoderClass=StreamingAudioEncoder,muxMp4Fn=muxMp4,muxWebmFn=muxWebm,sink=null,fragmented=false,segmentDuration=2}={}){
  if(!manifest?.settings)throw new Error('Timeline export requires a render manifest');if(typeof renderFrame!=='function')throw new Error('Timeline export requires renderFrame');const fps=Number(manifest.settings.fps)||30,start=Number(manifest.settings.rangeStart)||0,end=Number(manifest.settings.rangeEnd);if(!(end>start))throw new Error('Render manifest range is empty');const frameDuration=Math.round(1_000_000/fps),frameCount=Math.max(1,Math.ceil((end-start)*fps));const resolvedVideoConfig={width:Number(manifest.settings.width),height:Number(manifest.settings.height),framerate:fps,...videoConfig};const videoEncoder=new VideoEncoderClass(resolvedVideoConfig,{trackId:'video:deliver',signal,keyFrameInterval:Math.max(1,Math.round(fps*2))});try{for(let index=0;index<frameCount;index++){if(signal?.aborted)throw new DOMException('Export aborted','AbortError');const time=start+index/fps;const rendered=await renderFrame(time,index);const frame=frameFactory(rendered,{timestamp:Math.round((time-start)*1_000_000),duration:frameDuration,index});try{await videoEncoder.encode(frame);}finally{closeMedia(frame);if(rendered!==frame)closeMedia(rendered);}progressCall(onProgress,'video',((index+1)/frameCount)*.7,{frame:index+1,frameCount});}await videoEncoder.flush();const streams=[videoEncoder.result()];if(renderAudioPcm&&audioConfig){const pcm=await renderAudioPcm({start,end,sampleRate:Number(audioConfig.sampleRate)||48000,signal});const audioEncoder=new AudioEncoderClass(audioConfig,{trackId:'audio:deliver',signal});try{const blocks=pcmBlocks(pcm,{blockFrames:audioConfig.blockFrames??1024});for(let index=0;index<blocks.length;index++){const block=blocks[index],timestamp=Math.round((index*(audioConfig.blockFrames??1024)/pcm.sampleRate)*1_000_000);const data=audioDataFactory(block,timestamp);try{await audioEncoder.encode(data);}finally{closeMedia(data);}progressCall(onProgress,'audio',.7+((index+1)/Math.max(1,blocks.length))*.15,{block:index+1,blocks:blocks.length});}await audioEncoder.flush();streams.push(audioEncoder.result());}finally{audioEncoder.close();}}
    const plan=createMuxPlanFromEncoded({container:container==='mov'?'mp4':container,streams,metadata:{manifestSignature:manifest.signature??null,deliver:true}});let bytes=null;
    if(sink&&fragmented&&container==='mp4'){const writer=new FragmentedMp4StreamWriter(plan,sink);for(const segment of segmentMuxPlan(plan,{segmentDuration})){const segmentPlan={...plan,samples:segment.samples};await writer.writeSegment(segmentPlan);}await writer.close();progressCall(onProgress,'mux',1,{streamed:true});return{container:'mp4',fragmented:true,streamed:true,plan,streams};}
    if(sink&&container==='webm'){const writer=new StreamingWebmWriter(plan.tracks,sink);for(const sample of plan.samples)await writer.addSample(sample);await writer.close();progressCall(onProgress,'mux',1,{streamed:true});return{container:'webm',streamed:true,plan,streams};}
    bytes=container==='webm'?muxWebmFn(plan):muxMp4Fn({...plan,container:container==='mov'?'mov':'mp4'});progressCall(onProgress,'mux',1,{byteLength:bytes.byteLength});return{container,fragmented:false,streamed:false,bytes,plan,streams};
  }finally{videoEncoder.close();}
}


async function encodeOfflineAudioStream({renderAudioPcm,audioConfig,start,end,signal,onProgress,AudioEncoderClass,audioDataFactory}){
  if(!renderAudioPcm||!audioConfig)return null;const pcm=await renderAudioPcm({start,end,sampleRate:Number(audioConfig.sampleRate)||48000,signal});const audioEncoder=new AudioEncoderClass(audioConfig,{trackId:'audio:deliver',signal});try{const blocks=pcmBlocks(pcm,{blockFrames:audioConfig.blockFrames??1024});for(let index=0;index<blocks.length;index++){if(signal?.aborted)throw new DOMException('Export aborted','AbortError');const block=blocks[index],timestamp=Math.round((block.start/pcm.sampleRate)*1_000_000),data=audioDataFactory(block,timestamp);try{await audioEncoder.encode(data);}finally{closeMedia(data);}progressCall(onProgress,'audio',((index+1)/Math.max(1,blocks.length))*.12,{block:index+1,blocks:blocks.length});}await audioEncoder.flush();return audioEncoder.result();}finally{audioEncoder.close();}}
function streamWithChunks(base,chunks){return{...base,chunks};}
export async function renderProgressiveTimelineExport({manifest,renderFrame,renderAudioPcm=null,container='mp4',videoConfig,audioConfig=null,signal,onProgress,frameFactory=defaultVideoFrameFactory,audioDataFactory=pcmBlockAudioData,VideoEncoderClass=StreamingVideoEncoder,AudioEncoderClass=StreamingAudioEncoder,sink,segmentDuration=2}={}){
  if(!sink)throw new Error('Progressive timeline export requires a byte sink');if(!['mp4','webm'].includes(container))throw new Error(`Progressive export does not support ${container}`);if(!manifest?.settings||typeof renderFrame!=='function')throw new Error('Progressive timeline export requires manifest and renderFrame');const fps=Number(manifest.settings.fps)||30,start=Number(manifest.settings.rangeStart)||0,end=Number(manifest.settings.rangeEnd);if(!(end>start))throw new Error('Render manifest range is empty');const frameDuration=Math.round(1_000_000/fps),frameCount=Math.max(1,Math.ceil((end-start)*fps)),resolvedVideoConfig={width:Number(manifest.settings.width),height:Number(manifest.settings.height),framerate:fps,...videoConfig};
  const audioStream=await encodeOfflineAudioStream({renderAudioPcm,audioConfig,start,end,signal,onProgress,AudioEncoderClass,audioDataFactory});const pendingVideo=[];const videoEncoder=new VideoEncoderClass(resolvedVideoConfig,{trackId:'video:deliver',signal,keyFrameInterval:Math.max(1,Math.round(fps*segmentDuration)),retainChunks:false,onChunk:(chunk)=>pendingVideo.push(chunk)});let writer=null,videoBase=null,audioPending=audioStream?[...audioStream.chunks]:[],videoCount=0,audioCount=0,segmentCount=0,segmentVideo=[],segmentAudio=[],nextBoundary=Math.max(.25,Number(segmentDuration)||2)*1_000_000;
  const makeBasePlan=()=>createMuxPlanFromEncoded({container,streams:[streamWithChunks(videoBase,[]),...(audioStream?[streamWithChunks(audioStream,[])]:[])],metadata:{manifestSignature:manifest.signature??null,deliver:true,progressive:true}});
  const flushMp4Segment=async()=>{if(!segmentVideo.length&&!segmentAudio.length)return;const streams=[streamWithChunks(videoBase,segmentVideo),...(audioStream?[streamWithChunks(audioStream,segmentAudio)]:[])];const plan=createMuxPlanFromEncoded({container:'mp4',streams,metadata:{manifestSignature:manifest.signature??null,segment:segmentCount}});await writer.writeSegment(plan);videoCount+=segmentVideo.length;audioCount+=segmentAudio.length;segmentCount++;segmentVideo=[];segmentAudio=[];};
  const drain=async(final=false)=>{while(pendingVideo.length){const chunk=pendingVideo.shift();if(container==='webm'){while(audioPending.length&&Number(audioPending[0].timestamp??0)<=Number(chunk.timestamp??0)){await writer.addSample(muxSamplesFromEncodedStream(streamWithChunks(audioStream,[audioPending.shift()]),audioStream.id)[0]);audioCount++;}await writer.addSample(muxSamplesFromEncodedStream(streamWithChunks(videoBase,[chunk]),videoBase.id)[0]);videoCount++;continue;}const timestamp=Number(chunk.timestamp??0);if(segmentVideo.length&&chunk.keyframe&&timestamp>=nextBoundary){while(audioPending.length&&Number(audioPending[0].timestamp??0)<timestamp)segmentAudio.push(audioPending.shift());await flushMp4Segment();nextBoundary=timestamp+Math.max(.25,Number(segmentDuration)||2)*1_000_000;}segmentVideo.push(chunk);}if(final){if(container==='webm'){while(audioPending.length){await writer.addSample(muxSamplesFromEncodedStream(streamWithChunks(audioStream,[audioPending.shift()]),audioStream.id)[0]);audioCount++;}}else{segmentAudio.push(...audioPending.splice(0));await flushMp4Segment();}}};
  try{
    for(let index=0;index<frameCount;index++){if(signal?.aborted)throw new DOMException('Export aborted','AbortError');const time=start+index/fps,rendered=await renderFrame(time,index),frame=frameFactory(rendered,{timestamp:Math.round((time-start)*1_000_000),duration:frameDuration,index});try{await videoEncoder.encode(frame);}finally{closeMedia(frame);if(rendered!==frame)closeMedia(rendered);}if(index===0){await videoEncoder.flush();videoBase=videoEncoder.result();const basePlan=makeBasePlan();writer=container==='mp4'?new FragmentedMp4StreamWriter(basePlan,sink):new StreamingWebmWriter(basePlan.tracks,sink);await writer.start();}await drain();progressCall(onProgress,'video',.12+((index+1)/frameCount)*.83,{frame:index+1,frameCount});}
    await videoEncoder.flush();if(!videoBase)videoBase=videoEncoder.result();if(!writer){const basePlan=makeBasePlan();writer=container==='mp4'?new FragmentedMp4StreamWriter(basePlan,sink):new StreamingWebmWriter(basePlan.tracks,sink);await writer.start();}await drain(true);const summary=await writer.close();progressCall(onProgress,'mux',1,{streamed:true,...summary});return{container,fragmented:container==='mp4',streamed:true,progressive:true,videoChunks:videoCount,audioChunks:audioCount,segments:container==='mp4'?segmentCount:summary.clusters,summary};
  }finally{videoEncoder.close();}
}
