export const MEDIA_EFFECT_WGSL = `
struct Params { brightness:f32, contrast:f32, saturation:f32, hue:f32, blur:f32, texelX:f32, texelY:f32, opacity:f32 };
@group(0) @binding(0) var sourceTex: texture_2d<f32>;
@group(0) @binding(1) var sourceSampler: sampler;
@group(0) @binding(2) var<uniform> p: Params;
struct Out { @builtin(position) position:vec4<f32>, @location(0) uv:vec2<f32> };
@vertex fn vs(@builtin(vertex_index) index:u32)->Out { var pos=array<vec2<f32>,3>(vec2(-1.,-1.),vec2(3.,-1.),vec2(-1.,3.)); var uv=array<vec2<f32>,3>(vec2(0.,1.),vec2(2.,1.),vec2(0.,-1.)); var o:Out;o.position=vec4(pos[index],0.,1.);o.uv=uv[index];return o; }
fn hueRotate(c:vec3<f32>,a:f32)->vec3<f32>{let s=sin(a);let co=cos(a);let m=mat3x3<f32>(vec3(.213+.787*co-.213*s,.715-.715*co-.715*s,.072-.072*co+.928*s),vec3(.213-.213*co+.143*s,.715+.285*co+.140*s,.072-.072*co-.283*s),vec3(.213-.213*co-.787*s,.715-.715*co+.715*s,.072+.928*co+.072*s));return m*c;}
fn fetch(uv:vec2<f32>)->vec4<f32>{if(p.blur<=0.01){return textureSample(sourceTex,sourceSampler,uv);}let d=vec2(p.texelX,p.texelY)*min(p.blur,8.);var c=textureSample(sourceTex,sourceSampler,uv)*.2;c+=textureSample(sourceTex,sourceSampler,uv+vec2(d.x,0.))*.1;c+=textureSample(sourceTex,sourceSampler,uv-vec2(d.x,0.))*.1;c+=textureSample(sourceTex,sourceSampler,uv+vec2(0.,d.y))*.1;c+=textureSample(sourceTex,sourceSampler,uv-vec2(0.,d.y))*.1;c+=textureSample(sourceTex,sourceSampler,uv+d)*.1;c+=textureSample(sourceTex,sourceSampler,uv-d)*.1;c+=textureSample(sourceTex,sourceSampler,uv+vec2(d.x,-d.y))*.1;c+=textureSample(sourceTex,sourceSampler,uv+vec2(-d.x,d.y))*.1;return c;}
@fragment fn fs(input:Out)->@location(0) vec4<f32>{var c=fetch(input.uv);c.rgb*=p.brightness;c.rgb=(c.rgb-.5)*p.contrast+.5;let l=dot(c.rgb,vec3(.2126,.7152,.0722));c.rgb=mix(vec3(l),c.rgb,p.saturation);c.rgb=hueRotate(c.rgb,p.hue);c.a*=p.opacity;return c;}`;
function paramsArray(params,width,height){return new Float32Array([Number(params.brightness??1),Number(params.contrast??1),Number(params.saturation??1),Number(params.hueRadians??((Number(params.hueDegrees??0)*Math.PI)/180)),Math.max(0,Number(params.blur??params.blurRadius??0)),1/Math.max(1,width),1/Math.max(1,height),Number(params.opacity??1)]);}
export class GpuEffectPipeline {
  constructor(device,{format='bgra8unorm'}={}){this.device=device;this.format=format;const module=device.createShaderModule({code:MEDIA_EFFECT_WGSL});this.pipeline=device.createRenderPipeline({layout:'auto',vertex:{module,entryPoint:'vs'},fragment:{module,entryPoint:'fs',targets:[{format}]},primitive:{topology:'triangle-list'}});this.sampler=device.createSampler({magFilter:'linear',minFilter:'linear'});this.uniform=device.createBuffer({size:32,usage:(globalThis.GPUBufferUsage?.UNIFORM??64)|(globalThis.GPUBufferUsage?.COPY_DST??8)});}
  render(encoder,sourceTexture,targetView,{width,height,...params}={}){this.device.queue.writeBuffer(this.uniform,0,paramsArray(params,width,height));const bindGroup=this.device.createBindGroup({layout:this.pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:sourceTexture.createView()},{binding:1,resource:this.sampler},{binding:2,resource:{buffer:this.uniform}}]});const pass=encoder.beginRenderPass({colorAttachments:[{view:targetView,loadOp:'clear',storeOp:'store',clearValue:{r:0,g:0,b:0,a:0}}]});pass.setPipeline(this.pipeline);pass.setBindGroup(0,bindGroup);pass.draw(3);pass.end();}
  destroy(){try{this.uniform.destroy?.();}catch{}}
}
