import { prefetchWindows } from '../../packages/core/src/seek-index.js';

function abortError(message='Kernel task cancelled'){const error=new Error(message);error.name='AbortError';return error;}
export class KernelWorkerPool {
  constructor({size=2,clientFactory}={}){if(typeof clientFactory!=='function')throw new Error('KernelWorkerPool requires clientFactory');this.size=Math.max(1,Math.round(Number(size)||1));this.clients=Array.from({length:this.size},(_,index)=>({index,client:clientFactory(index),busy:null}));this.queue=[];this.byKey=new Map();this.sequence=0;this.closed=false;}
  schedule(kind,payload,{priority=0,key,transfer=[],onProgress}={}){if(this.closed)throw new Error('KernelWorkerPool is closed');if(key&&this.byKey.has(key))return this.byKey.get(key).handle;let resolve,reject;const promise=new Promise((res,rej)=>{resolve=res;reject=rej;});const task={id:`pool:${++this.sequence}`,kind,payload,priority:Number(priority)||0,key,transfer,onProgress,resolve,reject,state:'queued',underlying:null,settled:false};const handle={id:task.id,promise,cancel:()=>this.cancel(task.id)};task.handle=handle;if(key)this.byKey.set(key,task);this.queue.push(task);this.#sort();this.#pump();return handle;}
  #sort(){this.queue.sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id,undefined,{numeric:true}));}
  #pump(){if(this.closed)return;for(const slot of this.clients){if(slot.busy)continue;const task=this.queue.shift();if(!task)break;if(task.state!=='queued')continue;slot.busy=task;task.state='running';try{task.underlying=slot.client.run(task.kind,task.payload,{priority:task.priority,transfer:task.transfer,onProgress:task.onProgress});Promise.resolve(task.underlying.promise).then((value)=>this.#finish(slot,task,null,value),(error)=>this.#finish(slot,task,error));}catch(error){this.#finish(slot,task,error);}}}
  #finish(slot,task,error,value){if(slot.busy===task)slot.busy=null;if(task.key&&this.byKey.get(task.key)===task)this.byKey.delete(task.key);if(!task.settled){task.settled=true;if(task.state==='cancelled')task.reject(abortError());else if(error){task.state='failed';task.reject(error);}else{task.state='done';task.resolve(value);}}this.#pump();}
  cancel(id){const queued=this.queue.find((task)=>task.id===id);if(queued){queued.state='cancelled';this.queue=this.queue.filter((task)=>task!==queued);if(queued.key&&this.byKey.get(queued.key)===queued)this.byKey.delete(queued.key);if(!queued.settled){queued.settled=true;queued.reject(abortError());}return true;}for(const slot of this.clients){const task=slot.busy;if(task?.id===id){task.state='cancelled';if(task.key&&this.byKey.get(task.key)===task)this.byKey.delete(task.key);try{task.underlying?.cancel?.();}catch{}if(!task.settled){task.settled=true;task.reject(abortError());}return true;}}return false;}
  stats(){return{size:this.size,active:this.clients.filter((slot)=>slot.busy).length,queued:this.queue.length,deduplicated:this.byKey.size};}
  async idle(){while(this.queue.length||this.clients.some((slot)=>slot.busy))await new Promise((resolve)=>setTimeout(resolve,0));}
  close(){if(this.closed)return;this.closed=true;for(const task of [...this.queue]){task.state='cancelled';if(!task.settled){task.settled=true;task.reject(abortError('Kernel pool closed'));}}this.queue=[];for(const slot of this.clients){if(slot.busy){slot.busy.state='cancelled';try{slot.busy.underlying?.cancel?.();}catch{}if(!slot.busy.settled){slot.busy.settled=true;slot.busy.reject(abortError('Kernel pool closed'));}}try{slot.client.close?.();}catch{}}this.byKey.clear();}
}
export class PlaybackPrefetchController {
  constructor({pool,index,trackIds,payloadForWindow,taskKind='decode-video'}={}){if(!pool||!index||typeof payloadForWindow!=='function')throw new Error('PlaybackPrefetchController requires pool, index and payloadForWindow');this.pool=pool;this.index=index;this.trackIds=[...(trackIds??[])];this.payloadForWindow=payloadForWindow;this.taskKind=taskKind;this.handles=[];this.generation=0;}
  update({time=0,direction=1,horizon=4,behind=.25}={}){this.cancel();const generation=++this.generation;const windows=prefetchWindows(this.index,this.trackIds,{time,direction,horizon,behind});this.handles=windows.map((window,index)=>this.pool.schedule(this.taskKind,this.payloadForWindow(window),{priority:100-index,key:`prefetch:${window.trackId}:${window.start.toFixed(3)}:${window.end.toFixed(3)}`}));return{generation,windows,handles:this.handles};}
  cancel(){for(const handle of this.handles)handle.cancel();this.handles=[];}
}
