import { createPagedRangeSource, normalizeByteRange } from '../../packages/core/src/range-source.js';

function abortIfNeeded(signal){if(!signal?.aborted)return;const error=new Error('Media source read aborted');error.name='AbortError';throw error;}
function contentRangeSize(value){const match=String(value??'').match(/bytes\s+\d+-\d+\/(\d+|\*)/i);return match&&match[1]!=='*'?Number(match[1]):null;}
export class BlobRangeSource {
  constructor(blob,{id='blob'}={}){if(!(blob instanceof Blob)&&typeof blob?.slice!=='function')throw new Error('BlobRangeSource requires a Blob-like object');this.blob=blob;this.size=Number(blob.size);this.id=id;this.reads=0;this.bytesRead=0;}
  async read(offset,length,{signal}={}){abortIfNeeded(signal);const range=normalizeByteRange({offset,length},this.size);const buffer=await this.blob.slice(range.offset,range.end).arrayBuffer();abortIfNeeded(signal);const bytes=new Uint8Array(buffer);if(bytes.byteLength!==range.length)throw new Error('Blob range read returned unexpected length');this.reads++;this.bytesRead+=bytes.byteLength;return bytes;}
  stats(){return{id:this.id,size:this.size,reads:this.reads,bytesRead:this.bytesRead};}
}
export class HttpRangeSource {
  constructor(url,{size,fetchImpl=globalThis.fetch,id=url}={}){if(!url)throw new Error('HttpRangeSource requires a URL');if(typeof fetchImpl!=='function')throw new Error('HttpRangeSource requires fetch');this.url=String(url);this.size=Number(size);this.fetchImpl=fetchImpl;this.id=id;this.full=null;this.reads=0;this.bytesRead=0;}
  static async create(url,{size,fetchImpl=globalThis.fetch,signal,id}={}){if(Number.isFinite(Number(size)))return new HttpRangeSource(url,{size:Number(size),fetchImpl,id});const response=await fetchImpl(url,{headers:{Range:'bytes=0-0'},signal});if(!response.ok)throw new Error(`Unable to probe remote media source (${response.status})`);const detected=contentRangeSize(response.headers.get('content-range'))??Number(response.headers.get('content-length'));if(!(detected>=0))throw new Error('Remote media source did not expose a usable size');const source=new HttpRangeSource(url,{size:detected,fetchImpl,id});if(response.status===200){source.full=new Uint8Array(await response.arrayBuffer());source.size=source.full.byteLength;}return source;}
  async read(offset,length,{signal}={}){abortIfNeeded(signal);const range=normalizeByteRange({offset,length},this.size);if(this.full){this.reads++;this.bytesRead+=range.length;return this.full.slice(range.offset,range.end);}const response=await this.fetchImpl(this.url,{headers:{Range:`bytes=${range.offset}-${range.end-1}`},signal});if(!response.ok)throw new Error(`Remote range request failed (${response.status})`);const bytes=new Uint8Array(await response.arrayBuffer());if(response.status===200){this.full=bytes;this.size=bytes.byteLength;const normalized=normalizeByteRange(range,this.size);this.reads++;this.bytesRead+=normalized.length;return this.full.slice(normalized.offset,normalized.end);}if(bytes.byteLength!==range.length)throw new Error(`Remote range returned ${bytes.byteLength} bytes for ${range.length}`);this.reads++;this.bytesRead+=bytes.byteLength;return bytes;}
  stats(){return{id:this.id,size:this.size,reads:this.reads,bytesRead:this.bytesRead,fullFallback:Boolean(this.full)};}
}
export async function createAssetRangeSource(asset,{blobResolver,fetchImpl=globalThis.fetch,pageSize=1024*1024,maxCacheBytes=64*1024*1024,signal}={}){if(!asset?.id)throw new Error('Asset range source requires an asset');let base=null;if(typeof blobResolver==='function'){const blob=await blobResolver(asset.id,asset);if(blob)base=new BlobRangeSource(blob,{id:`asset:${asset.id}`});}if(!base){const uri=String(asset.props?.uri??'');if(/^https?:\/\//i.test(uri))base=await HttpRangeSource.create(uri,{size:asset.props?.size,fetchImpl,signal,id:`asset:${asset.id}`});else throw new Error(`Media source is offline: ${asset.name??asset.id}`);}return createPagedRangeSource(base,{pageSize,maxBytes:maxCacheBytes});}
