import { createMuxPlanFromEncoded } from '../../packages/core/src/encoded-export.js';
import { createFragmentedMp4Init, createFragmentedMp4Segment } from '../../packages/core/src/isobmff-mux.js';
import { pcmBlocks } from '../../packages/core/src/offline-audio.js';
import { StreamingAudioEncoder, StreamingVideoEncoder } from './streaming-codecs.js';
function closeMedia(value){try{value?.close?.();}catch{}}
function abortIfNeeded(signal){if(!signal?.aborted)return;const error=new Error('Render chunk aborted');error.name='AbortError';throw error;}
function defaultFrameFactory(source,{timestamp,duration}){if(typeof VideoFrame!=='function')throw new Error('VideoFrame is unavailable');return source instanceof VideoFrame?source:new VideoFrame(source,{timestamp,duration});}
function defaultAudioDataFactory(block,timestamp,{AudioDataCtor=globalThis.AudioData}={}){if(typeof AudioDataCtor!=='function')throw new Error('AudioData is unavailable');const channels=block.channels.length,frames=block.length,data=new Float32Array(channels*frames);for(let channel=0;channel<channels;channel++)data.set(block.channels[channel],channel*frames);return new AudioDataCtor({format:'f32-planar',sampleRate:block.sampleRate,numberOfFrames:frames,numberOfChannels:channels,timestamp,data});}
function bytesOf(value){if(value instanceof Uint8Array)return value;if(value instanceof ArrayBuffer)return new Uint8Array(value);if(ArrayBuffer.isView(value))return new Uint8Array(value.buffer,value.byteOffset,value.byteLength);return new Uint8Array();}
function hashBytes(value){let hash=2166136261;for(const byte of bytesOf(value)){hash^=byte;hash=Math.imul(hash,16777619);}return(hash>>>0).toString(16).padStart(8,'0');}
export function encodedStreamsSignature(streams){return streams.map((stream)=>{const config=stream.decoderConfig??stream.config??{};return[stream.type,stream.codec,stream.width??config.codedWidth??config.width??'',stream.height??config.codedHeight??config.height??'',stream.sampleRate??config.sampleRate??'',stream.channels??config.numberOfChannels??config.channels??'',config.description?hashBytes(config.description):''].join(':');}).join('|');}
export function outputTimestampMicros(manifest,time){return Math.max(0,Math.round((Number(time)-Number(manifest.settings.rangeStart??0))*1_000_000));}
async function encodeVideo({manifest,chunk,renderFrame,videoConfig,signal,onProgress,frameFactory,VideoEncoderClass}){const fps=Number(manifest.settings.fps)||30,frameDuration=Math.round(1_000_000/fps),width=Number(manifest.settings.width),height=Number(manifest.settings.height),resolvedVideo={width,height,framerate:fps,...videoConfig},video=new VideoEncoderClass(resolvedVideo,{trackId:'video:deliver',signal,keyFrameInterval:Math.max(1,chunk.frameCount)});try{for(let frameIndex=chunk.frameStart;frameIndex<chunk.frameEnd;frameIndex++){abortIfNeeded(signal);const time=frameIndex/fps,rendered=await renderFrame(time,frameIndex-chunk.frameStart),frame=frameFactory(rendered,{timestamp:outputTimestampMicros(manifest,time),duration:frameDuration,index:frameIndex});try{await video.encode(frame);}finally{closeMedia(frame);if(rendered!==frame)closeMedia(rendered);}onProgress({stage:'video',ratio:(frameIndex-chunk.frameStart+1)/Math.max(1,chunk.frameCount)});}await video.flush();return video.result();}finally{video.close?.();}}
async function encodeAudio({manifest,chunk,renderAudioPcm,audioConfig,signal,onProgress,audioDataFactory,AudioEncoderClass}){if(!renderAudioPcm||!audioConfig)return null;const pcm=await renderAudioPcm({start:chunk.timeStart,end:chunk.timeEnd,sampleRate:Number(audioConfig.sampleRate)||48000,signal});if(!pcm)return null;const audio=new AudioEncoderClass(audioConfig,{trackId:'audio:deliver',signal});try{const blocks=pcmBlocks(pcm,{blockFrames:audioConfig.blockFrames??1024});for(let index=0;index<blocks.length;index++){abortIfNeeded(signal);const block=blocks[index],time=chunk.timeStart+Number(block.start??index*(audioConfig.blockFrames??1024))/pcm.sampleRate,data=audioDataFactory(block,outputTimestampMicros(manifest,time));try{await audio.encode(data);}finally{closeMedia(data);}onProgress({stage:'audio',ratio:(index+1)/Math.max(1,blocks.length)});}await audio.flush();return audio.result();}finally{audio.close?.();}}
export async function renderFragmentedMp4Chunk({manifest,chunk,renderFrame,renderAudioPcm=null,videoConfig,audioConfig=null,sequenceNumber=1,signal,onProgress=()=>{},frameFactory=defaultFrameFactory,audioDataFactory=defaultAudioDataFactory,VideoEncoderClass=StreamingVideoEncoder,AudioEncoderClass=StreamingAudioEncoder,initWriter=createFragmentedMp4Init,segmentWriter=createFragmentedMp4Segment}={}){if(!manifest?.settings||!chunk||typeof renderFrame!=='function')throw new Error('Fragmented render chunk requires manifest, chunk and renderFrame');const [video,audio]=await Promise.all([encodeVideo({manifest,chunk,renderFrame,videoConfig,signal,onProgress,frameFactory,VideoEncoderClass}),encodeAudio({manifest,chunk,renderAudioPcm,audioConfig,signal,onProgress,audioDataFactory,AudioEncoderClass})]);const streams=[video,...(audio?[audio]:[])],plan=createMuxPlanFromEncoded({container:'mp4',streams,metadata:{manifestSignature:manifest.signature,renderChunk:chunk.index}}),codecSignature=encodedStreamsSignature(streams),initSegment=initWriter(plan),mediaSegment=segmentWriter(plan,{sequenceNumber});return{initSegment:initSegment.buffer.slice(initSegment.byteOffset,initSegment.byteOffset+initSegment.byteLength),mediaSegment:mediaSegment.buffer.slice(mediaSegment.byteOffset,mediaSegment.byteOffset+mediaSegment.byteLength),codecSignature,summary:{frameStart:chunk.frameStart,frameEnd:chunk.frameEnd,timeStart:chunk.timeStart,timeEnd:chunk.timeEnd,videoChunks:video.chunks.length,audioChunks:audio?.chunks.length??0,parallelAv:Boolean(audio)}};}
