import { normalizeBoundedModelJsonObject } from '../../packages/core/src/model-input.js';
import { OPERATION_LOG_SCHEMA, canonicalOperationLogJson, operationLogChecksum, validateOperationLog } from '../../packages/core/src/operation-log.js';
import { normalizeStudioAssetWrites } from './persistence-context.js';
const DB_NAME = "media-studio";
const DB_VERSION = 4;
const MAX_DERIVED_LIST_RECORDS = 4096;
const MAX_DERIVED_KEY_CHARS = 1024;
const MAX_DERIVED_METADATA_BYTES = 64 * 1024;
const MAX_ASSET_IDENTITY_CHARS = 1024;
const WORKSPACE_KEY = "current";
let databasePromise = null;
let currentGraphCache = null;

function requestResult(request) { return new Promise((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("IndexedDB request failed")); }); }
function transactionDone(transaction) { return new Promise((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error ?? new Error("IndexedDB transaction failed")); transaction.onabort = () => reject(transaction.error ?? new Error("IndexedDB transaction aborted")); }); }
function assetIdentity(value,label="Asset id"){if(typeof value!=="string"||!value)throw new Error(`${label} must be a non-empty string`);if(value.length>MAX_ASSET_IDENTITY_CHARS)throw new Error(`${label} exceeds ${MAX_ASSET_IDENTITY_CHARS} characters`);return value;}
function storedAssetId(record,index){if(!record||typeof record!=="object")throw new Error(`Stored asset ${index} must be an object`);const descriptor=Object.getOwnPropertyDescriptor(record,"id");if(!descriptor||!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error(`Stored asset ${index} id must be an enumerable data field`);return assetIdentity(descriptor.value,`Stored asset ${index} id`);}
function storedAssetBlob(record){if(record==null)return null;if(typeof record!=="object")throw new Error("Stored asset record must be an object");const descriptor=Object.getOwnPropertyDescriptor(record,"blob");if(!descriptor)return null;if(!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error("Stored asset blob must be an enumerable data field");return descriptor.value??null;}
function storageEstimateNumber(result,key){if(!result||typeof result!=="object")throw new Error("Storage estimate must be an object");const descriptor=Object.getOwnPropertyDescriptor(result,key);if(!descriptor)return 0;if(!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error(`Storage estimate ${key} must be an enumerable data field`);const value=descriptor.value;if(typeof value!=="number"||!Number.isFinite(value)||value<0)throw new Error(`Storage estimate ${key} must be a finite non-negative number`);return value;}
export function localAssetUri(assetId) { return `media://asset/${assetIdentity(assetId)}`; }
export function getCachedStoredGraph(){return currentGraphCache;}
export async function openMediaDatabase() {
  if (!("indexedDB" in globalThis)) return null;
  if (databasePromise) return databasePromise;
  databasePromise = new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onupgradeneeded = (event) => {
      const database = request.result;
      if (!database.objectStoreNames.contains("workspace")) database.createObjectStore("workspace", { keyPath: "key" });
      let assets;
      if (!database.objectStoreNames.contains("assets")) assets = database.createObjectStore("assets", { keyPath: "id" }); else assets = request.transaction.objectStore("assets");
      if (!assets.indexNames.contains("hash")) assets.createIndex("hash", "hash", { unique: false });
      if (!assets.indexNames.contains("name")) assets.createIndex("name", "name", { unique: false });
      let derived;
      if (!database.objectStoreNames.contains("derived")) derived = database.createObjectStore("derived", { keyPath: "key" }); else derived = request.transaction.objectStore("derived");
      if (!database.objectStoreNames.contains("derivedMeta")) database.createObjectStore("derivedMeta", { keyPath: "key" });
      if ((event?.oldVersion ?? 0) < 4) derived.clear();
      let journal;
      if (!database.objectStoreNames.contains("journal")) journal = database.createObjectStore("journal", { keyPath: "sequence" }); else journal = request.transaction.objectStore("journal");
      if (!journal.indexNames.contains("transactionId")) journal.createIndex("transactionId", "transactionId", { unique: true });
    };
    request.onerror = () => { databasePromise = null; reject(request.error ?? new Error("IndexedDB open failed")); };
    request.onblocked = () => { /* versionchange listeners on existing tabs should release the DB */ };
    request.onsuccess = () => { const database = request.result; database.onversionchange = () => { try { database.close(); } finally { databasePromise = null; } }; resolve(database); };
  });
  return databasePromise;
}
export async function closeMediaDatabase(){if(!databasePromise)return;try{const database=await databasePromise;database?.close?.();}finally{databasePromise=null;}}
async function databaseTransaction(storeNames,mode,run){const database=await openMediaDatabase();if(!database)return null;const names=Array.isArray(storeNames)?storeNames:[storeNames],tx=database.transaction(names,mode),stores=Object.fromEntries(names.map((name)=>[name,tx.objectStore(name)])),result=await run(stores,tx);await transactionDone(tx);return result;}
async function transaction(storeName,mode,run){return databaseTransaction(storeName,mode,async(stores,tx)=>run(stores[storeName],tx));}
export async function saveStoredGraph(graph) { const result=await databaseTransaction(["workspace","journal"],"readwrite",async({workspace,journal})=>{journal.clear();workspace.put({ key: WORKSPACE_KEY, graph, journalBaseGraph: graph, journalSequence: 0, journalChecksum: null, savedAt: new Date().toISOString() });return true;});currentGraphCache=graph;return Boolean(result); }
export async function loadStoredGraphCheckpoint(){const record=await transaction("workspace","readonly",async(store)=>requestResult(store.get(WORKSPACE_KEY)));if(!record)return null;currentGraphCache=record.graph??null;return{graph:record.graph??null,journalBaseGraph:record.journalBaseGraph??record.graph??null,journalSequence:Number(record.journalSequence??0),journalChecksum:record.journalChecksum??null,savedAt:record.savedAt??null,lastCompactedAt:record.lastCompactedAt??null,compactedFromSequence:Number(record.compactedFromSequence??0),compactedFromChecksum:record.compactedFromChecksum??null};}
export async function loadStoredGraph() { return currentGraphCache??(await loadStoredGraphCheckpoint())?.graph??null; }
function assertJournalEntry(entry){const clean=JSON.parse(canonicalOperationLogJson(entry));if(!clean||typeof clean!=="object"||Array.isArray(clean))throw new Error("Stored operation entry must be an object");if(clean.schema!==OPERATION_LOG_SCHEMA)throw new Error(`Stored operation entry schema must be ${OPERATION_LOG_SCHEMA}`);if(!Number.isSafeInteger(clean.sequence)||clean.sequence<1)throw new Error("Stored operation entry sequence must be a positive safe integer");if(typeof clean.checksum!=="string"||!clean.checksum)throw new Error("Stored operation entry checksum is required");if(typeof clean.transaction?.id!=="string"||!clean.transaction.id)throw new Error("Stored operation entry transaction id is required");const expected=operationLogChecksum({schema:OPERATION_LOG_SCHEMA,sequence:clean.sequence,transaction:clean.transaction,previousChecksum:clean.previousChecksum??null});if(clean.checksum!==expected)throw new Error(`Stored operation entry ${clean.sequence} checksum mismatch`);return clean;}
function opaqueBlobField(blob,key,fallback){const descriptor=Object.getOwnPropertyDescriptor(blob,key);if(descriptor?.enumerable&&Object.hasOwn(descriptor,"value"))return descriptor.value;const BlobCtor=globalThis.Blob,FileCtor=globalThis.File;if(typeof BlobCtor==="function"&&blob instanceof BlobCtor){if(key==="size"||key==="type")return blob[key];if(key==="name"&&typeof FileCtor==="function"&&blob instanceof FileCtor)return blob.name;}return fallback;}
function assetRecord(assetId,blob,metadata={},savedAt=new Date().toISOString()){if(typeof assetId!=="string"||!assetId)throw new Error("Asset write requires assetId");const BlobCtor=globalThis.Blob;if(typeof BlobCtor!=="function"||!(blob instanceof BlobCtor))throw new Error(`Asset write ${assetId} requires Blob data`);return{id:assetId,blob,hash:metadata.hash??null,name:metadata.name??opaqueBlobField(blob,"name",""),mediaKind:metadata.mediaKind??null,mimeType:metadata.mimeType??opaqueBlobField(blob,"type",""),size:metadata.size??opaqueBlobField(blob,"size",0),duration:metadata.duration??null,width:metadata.width??null,height:metadata.height??null,savedAt};}
function normalizeAssetWrites(assetWrites=[]){return normalizeStudioAssetWrites(assetWrites);}
async function saveGraphJournalTransaction(graph,entry,{assetWrites=[]}={}){const safeEntry=assertJournalEntry(entry),writes=normalizeAssetWrites(assetWrites),storeNames=writes.length?["workspace","journal","assets"]:["workspace","journal"],result=await databaseTransaction(storeNames,"readwrite",async(stores)=>{const {workspace,journal}=stores,current=await requestResult(workspace.get(WORKSPACE_KEY)),expected=Number(current?.journalSequence??0)+1,previousChecksum=current?.journalChecksum??null;if(safeEntry.sequence!==expected)throw new Error(`Operation journal sequence ${safeEntry.sequence} does not follow checkpoint ${expected-1}`);if((safeEntry.previousChecksum??null)!==previousChecksum)throw new Error(`Operation journal entry ${safeEntry.sequence} does not extend checkpoint checksum`);const savedAt=new Date().toISOString(),transactionId=safeEntry.transaction.id;if(writes.length){for(const write of writes)stores.assets.put(assetRecord(write.assetId,write.blob,write.metadata,savedAt));}journal.add({...safeEntry,transactionId,savedAt});workspace.put({...current,key:WORKSPACE_KEY,graph,journalBaseGraph:current?.journalBaseGraph??current?.graph??graph,journalSequence:safeEntry.sequence,journalChecksum:safeEntry.checksum,savedAt});return true;});currentGraphCache=graph;return Boolean(result);}
export async function saveStoredGraphWithOperation(graph,entry){return saveGraphJournalTransaction(graph,entry);}
export async function saveStoredGraphWithOperationAndAssets(graph,entry,assetWrites=[]){return saveGraphJournalTransaction(graph,entry,{assetWrites});}
export async function compactStoredOperationJournal({expectedSequence,expectedChecksum}={}){const result=await databaseTransaction(["workspace","journal"],"readwrite",async({workspace,journal})=>{const current=await requestResult(workspace.get(WORKSPACE_KEY));if(!current?.graph)throw new Error("Operation journal compaction requires a stored graph checkpoint");const sequence=Number(current.journalSequence??0),checksum=current.journalChecksum??null;if(expectedSequence!==undefined&&Number(expectedSequence)!==sequence)throw new Error(`Operation journal compaction expected sequence ${expectedSequence} but found ${sequence}`);if(expectedChecksum!==undefined&&(expectedChecksum??null)!==checksum)throw new Error("Operation journal compaction checksum does not match checkpoint head");if(sequence===0)return{compacted:false,graph:current.graph,previousSequence:0,previousChecksum:checksum,sequence:0,checksum:null,savedAt:current.savedAt??null};const savedAt=new Date().toISOString();journal.clear();workspace.put({...current,graph:current.graph,journalBaseGraph:current.graph,journalSequence:0,journalChecksum:null,savedAt,lastCompactedAt:savedAt,compactedFromSequence:sequence,compactedFromChecksum:checksum});return{compacted:true,graph:current.graph,previousSequence:sequence,previousChecksum:checksum,sequence:0,checksum:null,savedAt};});return result??{compacted:false,graph:null,previousSequence:0,previousChecksum:null,sequence:0,checksum:null,savedAt:null};}
export async function listStoredOperationEntries({afterSequence=0,limit=Infinity}={}){const records=await transaction("journal","readonly",async(store)=>requestResult(store.getAll()))??[],after=Math.max(0,Number(afterSequence)||0),max=Number.isFinite(Number(limit))?Math.max(0,Number(limit)):records.length;return records.filter((record)=>Number(record.sequence)>after).sort((a,b)=>Number(a.sequence)-Number(b.sequence)).slice(0,max);}
export async function findStoredOperationEntryByTransactionId(transactionId){if(!transactionId)return null;return transaction("journal","readonly",async(store)=>store.indexNames.contains("transactionId")?requestResult(store.index("transactionId").get(String(transactionId))):null);}
export async function loadStoredOperationRecovery(){const checkpoint=await loadStoredGraphCheckpoint();if(!checkpoint)return null;const entries=await listStoredOperationEntries(),projectId=String(checkpoint.journalBaseGraph?.projectId??checkpoint.graph?.projectId??"workspace"),log={schema:OPERATION_LOG_SCHEMA,projectId,baseRevision:0,metadata:{},entries};validateOperationLog(log);const head=entries.at(-1)??null,sequence=head?.sequence??0,checksum=head?.checksum??null;if(sequence!==checkpoint.journalSequence||checksum!==checkpoint.journalChecksum)throw new Error("Operation journal head does not match stored graph checkpoint");return{baseGraph:checkpoint.journalBaseGraph,graph:checkpoint.graph,sequence,checksum,entries,log};}
export async function saveAssetBlob(assetId, blob, metadata = {}) { const [write]=normalizeAssetWrites([{assetId,blob,metadata}]),result=await transaction("assets","readwrite",async(store)=>{store.put(assetRecord(write.assetId,write.blob,write.metadata));return true;});return Boolean(result); }
export async function loadAssetBlob(assetId) { const record=await loadStoredAsset(assetId);return storedAssetBlob(record); }
export async function loadStoredAsset(assetId) { const safeId=assetIdentity(assetId);return transaction("assets","readonly",async(store)=>requestResult(store.get(safeId))); }
export async function findStoredAssetByHash(hash) { if(hash==null||hash==="")return null;const safeHash=assetIdentity(hash,"Asset hash");return transaction("assets","readonly",async(store)=>store.indexNames.contains("hash")?requestResult(store.index("hash").get(safeHash)):null); }
export async function listStoredAssets() { const records=await transaction("assets","readonly",async(store)=>requestResult(store.getAll()))??[];return records.map(({blob,...metadata})=>({...metadata,hasBlob:Boolean(blob)})); }
export function planAssetGarbageCollection(graph,records,{now=Date.now(),olderThanMs=30*24*60*60*1000,maxDeleteBytes=Infinity,retainAssetIds=[],retainAssetHashes=[]}={}){const nodes=Object.values(graph?.nodes??{}),referencedIds=new Set([...nodes.filter((node)=>node?.kind==="asset").map((node)=>String(node.id)),...(retainAssetIds??[]).map((id)=>String(id))]),referencedHashes=new Set([...nodes.filter((node)=>node?.kind==="asset"&&node.props?.hash).map((node)=>String(node.props.hash)),...(retainAssetHashes??[]).filter(Boolean).map((hash)=>String(hash))]),cutoff=Math.max(0,Number(olderThanMs)||0),budget=Number.isFinite(Number(maxDeleteBytes))?Math.max(0,Number(maxDeleteBytes)):Infinity,candidates=[],retained=[];let deleteBytes=0;for(const record of records??[]){const id=String(record?.id??""),hash=record?.hash?String(record.hash):null,size=Math.max(0,Number(record?.size??record?.blob?.size??0)||0),savedAtMs=Date.parse(record?.savedAt??"");let reason=null;if(referencedIds.has(id))reason="referenced-id";else if(hash&&referencedHashes.has(hash))reason="referenced-hash";else if(!Number.isFinite(savedAtMs))reason="unknown-age";else if(Number(now)-savedAtMs<cutoff)reason="recent";if(reason){retained.push({id,hash,size,savedAt:record?.savedAt??null,reason});continue;}if(deleteBytes+size>budget){retained.push({id,hash,size,savedAt:record?.savedAt??null,reason:"budget"});continue;}candidates.push({id,hash,size,savedAt:record?.savedAt??null,ageMs:Math.max(0,Number(now)-savedAtMs)});deleteBytes+=size;}return{candidates,retained,deleteBytes,referencedIds:[...referencedIds],referencedHashes:[...referencedHashes]};}
export async function garbageCollectStoredAssets(options={}){const result=await databaseTransaction(["workspace","assets"],"readwrite",async({workspace,assets})=>{const current=await requestResult(workspace.get(WORKSPACE_KEY));if(!current?.graph)return{deletedIds:[],deleteBytes:0,candidates:[],retained:[],referencedIds:[],referencedHashes:[]};const records=await requestResult(assets.getAll()),plan=planAssetGarbageCollection(current.graph,records,options);for(const candidate of plan.candidates)assets.delete(candidate.id);return{...plan,deletedIds:plan.candidates.map((candidate)=>candidate.id)};});return result??{deletedIds:[],deleteBytes:0,candidates:[],retained:[],referencedIds:[],referencedHashes:[]};}
export async function deleteAssetBlob(assetId) { const safeId=assetIdentity(assetId),result=await transaction("assets","readwrite",async(store)=>{store.delete(safeId);return true;});return Boolean(result); }
export async function listStoredAssetIds() { const records=await transaction("assets","readonly",async(store)=>requestResult(store.getAll()))??[];if(!Array.isArray(records))throw new Error("Stored assets must be an array");return records.map((record,index)=>storedAssetId(record,index)); }
export async function hasAssetBlob(assetId) { return (await loadAssetBlob(assetId)) !== null; }
function boundedDerivedListLimit(limit=MAX_DERIVED_LIST_RECORDS){if(!Number.isInteger(limit)||limit<1||limit>MAX_DERIVED_LIST_RECORDS)throw new Error(`Derived artifact list limit must be an integer between 1 and ${MAX_DERIVED_LIST_RECORDS}`);return limit;}
function derivedKey(key,label="Derived artifact key",{allowEmpty=false}={}){if(typeof key!=="string"||(!allowEmpty&&!key))throw new Error(`${label} must be ${allowEmpty?'a string':'a non-empty string'}`);if(key.length>MAX_DERIVED_KEY_CHARS)throw new Error(`${label} exceeds ${MAX_DERIVED_KEY_CHARS} characters`);return key;}
function derivedListPrefix(prefix=""){return derivedKey(prefix,"Derived artifact list prefix",{allowEmpty:true});}
function derivedListOptions(options={}){if(!options||typeof options!=="object"||Array.isArray(options))throw new Error("Derived artifact list options must be a plain data object");const prototype=Object.getPrototypeOf(options);if(prototype!==Object.prototype&&prototype!==null)throw new Error("Derived artifact list options must be a plain data object");const descriptors=Object.getOwnPropertyDescriptors(options),clean={};for(const key of Reflect.ownKeys(descriptors)){if(typeof key!=="string"||(key!=="prefix"&&key!=="limit"))throw new Error(`Unsupported derived artifact list option: ${String(key)}`);const descriptor=descriptors[key];if(!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error("Derived artifact list options must contain enumerable data fields only");clean[key]=descriptor.value;}return{prefix:derivedListPrefix(clean.prefix??""),limit:boundedDerivedListLimit(clean.limit??MAX_DERIVED_LIST_RECORDS)};}
async function boundedStoreRecords(store,prefix,limit){if(typeof store.openCursor!=="function"){const records=await requestResult(store.getAll())??[];return records.filter((record)=>typeof record?.key==="string"&&record.key.startsWith(prefix)).sort((a,b)=>a.key.localeCompare(b.key)).slice(0,limit);}return new Promise((resolve,reject)=>{const records=[],request=store.openCursor();request.onerror=()=>reject(request.error??new Error("IndexedDB cursor failed"));request.onsuccess=()=>{const cursor=request.result;if(!cursor){resolve(records);return;}const key=typeof cursor.key==="string"?cursor.key:String(cursor.key??"");if((!prefix||key.startsWith(prefix))&&records.length<limit)records.push(cursor.value);if(records.length>=limit){resolve(records);return;}cursor.continue();};});}
export async function saveDerivedArtifact(key, value, metadata = {}) { const safeKey=derivedKey(key),savedAt=new Date().toISOString(),recordMetadata=normalizeBoundedModelJsonObject(metadata,"Derived artifact metadata",{maxBytes:MAX_DERIVED_METADATA_BYTES});const result=await databaseTransaction(["derived","derivedMeta"],"readwrite",async({derived,derivedMeta})=>{derived.put({key:safeKey,value,metadata:recordMetadata,savedAt});derivedMeta.put({key:safeKey,metadata:recordMetadata,savedAt});return true;});return Boolean(result); }
export async function loadDerivedArtifact(key) { const safeKey=derivedKey(key);return transaction("derived","readonly",async(store)=>requestResult(store.get(safeKey))); }
export async function listDerivedArtifacts(options={}){const {prefix,limit}=derivedListOptions(options);return await transaction("derivedMeta","readonly",async(store)=>boundedStoreRecords(store,prefix,limit))??[];}
export async function deleteDerivedArtifact(key) { const safeKey=derivedKey(key);const result=await databaseTransaction(["derived","derivedMeta"],"readwrite",async({derived,derivedMeta})=>{derived.delete(safeKey);derivedMeta.delete(safeKey);return true;});return Boolean(result); }
export async function deleteDerivedArtifactsByPrefix(prefix){const text=derivedListPrefix(prefix);let removed=0;for(;;){const keys=(await listDerivedArtifacts({prefix:text,limit:MAX_DERIVED_LIST_RECORDS})).map((record)=>record.key);if(!keys.length)return removed;await databaseTransaction(["derived","derivedMeta"],"readwrite",async({derived,derivedMeta})=>{for(const key of keys){derived.delete(key);derivedMeta.delete(key);}return true;});removed+=keys.length;if(keys.length<MAX_DERIVED_LIST_RECORDS)return removed;}}
export async function clearDerivedArtifacts() { const result=await databaseTransaction(["derived","derivedMeta"],"readwrite",async({derived,derivedMeta})=>{derived.clear();derivedMeta.clear();return true;});return Boolean(result); }
export async function estimateStorageQuota(){if(typeof globalThis.navigator?.storage?.estimate!=="function")return null;const result=await globalThis.navigator.storage.estimate(),usage=storageEstimateNumber(result,"usage"),quota=storageEstimateNumber(result,"quota");return{usage,quota,available:Math.max(0,quota-usage),ratio:quota>0?usage/quota:0};}
