import { normalizeBoundedModelJsonObject } from '../../packages/core/src/model-input.js';
import { OPERATION_LOG_SCHEMA, canonicalOperationLogJson, operationLogChecksum, validateOperationLog } from '../../packages/core/src/operation-log.js';
import { normalizeStudioAssetWrites } from './persistence-context.js';
const DB_NAME = "media-studio";
const DB_VERSION = 4;
const MAX_DERIVED_LIST_RECORDS = 4096;
const MAX_DERIVED_KEY_CHARS = 1024;
const MAX_DERIVED_METADATA_BYTES = 64 * 1024;
const MAX_ASSET_IDENTITY_CHARS = 1024;
const MAX_STORED_ASSET_METADATA_BYTES = 64 * 1024;
const MAX_ASSET_LIST_RECORDS = 65536;
const MAX_ASSET_GC_RECORDS = 65536;
const MAX_ASSET_GC_REFERENCES = 65536;
const MAX_STORED_OPERATION_ENTRIES = 65536;
const MAX_JOURNAL_IDENTITY_CHARS = 1024;
const WORKSPACE_KEY = "current";
let databasePromise = null;
let currentGraphCache = null;

function requestResult(request) { return new Promise((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("IndexedDB request failed")); }); }
function transactionDone(transaction) { return new Promise((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error ?? new Error("IndexedDB transaction failed")); transaction.onabort = () => reject(transaction.error ?? new Error("IndexedDB transaction aborted")); }); }
function assetIdentity(value,label="Asset id"){if(typeof value!=="string"||!value)throw new Error(`${label} must be a non-empty string`);if(value.length>MAX_ASSET_IDENTITY_CHARS)throw new Error(`${label} exceeds ${MAX_ASSET_IDENTITY_CHARS} characters`);return value;}
function storedAssetId(record,index){if(!record||typeof record!=="object")throw new Error(`Stored asset ${index} must be an object`);const descriptor=Object.getOwnPropertyDescriptor(record,"id");if(!descriptor||!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error(`Stored asset ${index} id must be an enumerable data field`);return assetIdentity(descriptor.value,`Stored asset ${index} id`);}
function storedAssetBlob(record){if(record==null)return null;if(typeof record!=="object")throw new Error("Stored asset record must be an object");const descriptor=Object.getOwnPropertyDescriptor(record,"blob");if(!descriptor)return null;if(!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error("Stored asset blob must be an enumerable data field");return descriptor.value??null;}
function storageEstimateNumber(result,key){if(!result||typeof result!=="object")throw new Error("Storage estimate must be an object");const descriptor=Object.getOwnPropertyDescriptor(result,key);if(!descriptor)return 0;if(!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error(`Storage estimate ${key} must be an enumerable data field`);const value=descriptor.value;if(typeof value!=="number"||!Number.isFinite(value)||value<0)throw new Error(`Storage estimate ${key} must be a finite non-negative number`);return value;}
function optionalDataField(value,key,label){if(!value||typeof value!=="object")throw new Error(`${label} must be an object`);const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor)return undefined;if(!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error(`${label} ${key} must be an enumerable data field`);return descriptor.value;}
function plainDataOptions(value,label,allowedKeys){if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(`${label} must be a plain data object`);const prototype=Object.getPrototypeOf(value);if(prototype!==Object.prototype&&prototype!==null)throw new Error(`${label} must be a plain data object`);const descriptors=Object.getOwnPropertyDescriptors(value),clean={};for(const key of Reflect.ownKeys(descriptors)){if(typeof key!=="string"||!allowedKeys.has(key))throw new Error(`Unsupported ${label} field: ${String(key)}`);const descriptor=descriptors[key];if(!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error(`${label} must contain enumerable data fields only`);Object.defineProperty(clean,key,{value:descriptor.value,enumerable:true,writable:true,configurable:true});}return clean;}
function boundedAssetList(records,label,max=MAX_ASSET_LIST_RECORDS){if(!Array.isArray(records))throw new Error(`${label} must be an array`);if(records.length>max)throw new Error(`${label} exceeds ${max} records`);for(let index=0;index<records.length;index++){const descriptor=Object.getOwnPropertyDescriptor(records,String(index));if(!descriptor||!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error(`${label} must be a dense data array`);}return records;}
function boundedGcNumber(value,label,{allowInfinity=false}={}){if(allowInfinity&&value===Infinity)return Infinity;if(typeof value!=="number"||!Number.isFinite(value)||value<0)throw new Error(`${label} must be a finite non-negative number${allowInfinity?' or Infinity':''}`);return value;}
function boundedGcIdentityList(value,label){if(value==null)return[];if(!Array.isArray(value))throw new Error(`${label} must be an array`);if(value.length>MAX_ASSET_GC_REFERENCES)throw new Error(`${label} exceeds ${MAX_ASSET_GC_REFERENCES} values`);const result=[];for(let index=0;index<value.length;index++){const descriptor=Object.getOwnPropertyDescriptor(value,String(index));if(!descriptor||!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error(`${label} must be a dense data array`);result.push(assetIdentity(descriptor.value,`${label}[${index}]`));}return result;}
const ASSET_GC_OPTION_KEYS=new Set(["now","olderThanMs","maxDeleteBytes","retainAssetIds","retainAssetHashes"]);
function assetGarbageCollectionOptions(options={}){const clean=plainDataOptions(options,"Asset garbage collection options",ASSET_GC_OPTION_KEYS);return{now:boundedGcNumber(clean.now??Date.now(),"Asset garbage collection now"),olderThanMs:boundedGcNumber(clean.olderThanMs??30*24*60*60*1000,"Asset garbage collection olderThanMs"),maxDeleteBytes:boundedGcNumber(clean.maxDeleteBytes??Infinity,"Asset garbage collection maxDeleteBytes",{allowInfinity:true}),retainAssetIds:boundedGcIdentityList(clean.retainAssetIds??[],"Asset garbage collection retainAssetIds"),retainAssetHashes:boundedGcIdentityList(clean.retainAssetHashes??[],"Asset garbage collection retainAssetHashes")};}
function storedAssetSummary(record,index){if(!record||typeof record!=="object"||Array.isArray(record))throw new Error(`Stored asset ${index} must be an object`);const descriptors=Object.getOwnPropertyDescriptors(record),metadata={};let hasBlob=false;for(const key of Reflect.ownKeys(descriptors)){if(typeof key!=="string")throw new Error(`Stored asset ${index} fields must be strings`);const descriptor=descriptors[key];if(!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error(`Stored asset ${index} must contain enumerable data fields only`);if(key==="blob"){hasBlob=descriptor.value!=null;continue;}Object.defineProperty(metadata,key,{value:descriptor.value,enumerable:true,writable:true,configurable:true});}const clean=normalizeBoundedModelJsonObject(metadata,`Stored asset ${index} metadata`,{maxBytes:MAX_STORED_ASSET_METADATA_BYTES});return{...clean,hasBlob};}
function assetGcGraphReferences(graph,retainAssetIds,retainAssetHashes){const referencedIds=new Set(retainAssetIds),referencedHashes=new Set(retainAssetHashes);if(graph==null)return{referencedIds,referencedHashes};if(typeof graph!=="object"||Array.isArray(graph))throw new Error("Asset garbage collection graph must be an object");const nodes=optionalDataField(graph,"nodes","Asset garbage collection graph")??{};if(!nodes||typeof nodes!=="object"||Array.isArray(nodes))throw new Error("Asset garbage collection graph nodes must be an object");const descriptors=Object.getOwnPropertyDescriptors(nodes),keys=Reflect.ownKeys(descriptors);if(keys.length>MAX_ASSET_GC_REFERENCES)throw new Error(`Asset garbage collection graph exceeds ${MAX_ASSET_GC_REFERENCES} nodes`);for(const key of keys){if(typeof key!=="string")throw new Error("Asset garbage collection graph node keys must be strings");const descriptor=descriptors[key];if(!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error("Asset garbage collection graph nodes must contain enumerable data fields only");const node=descriptor.value;if(!node||typeof node!=="object"||Array.isArray(node))throw new Error(`Asset garbage collection node ${key} must be an object`);if(optionalDataField(node,"kind",`Asset garbage collection node ${key}`)!=="asset")continue;referencedIds.add(assetIdentity(optionalDataField(node,"id",`Asset garbage collection node ${key}`),`Asset garbage collection node ${key} id`));const props=optionalDataField(node,"props",`Asset garbage collection node ${key}`);if(props!=null){if(!props||typeof props!=="object"||Array.isArray(props))throw new Error(`Asset garbage collection node ${key} props must be an object`);const hash=optionalDataField(props,"hash",`Asset garbage collection node ${key} props`);if(hash!=null&&hash!=="")referencedHashes.add(assetIdentity(hash,`Asset garbage collection node ${key} hash`));}}return{referencedIds,referencedHashes};}
function assetGcRecord(record,index){if(!record||typeof record!=="object"||Array.isArray(record))throw new Error(`Asset garbage collection record ${index} must be an object`);const id=assetIdentity(optionalDataField(record,"id",`Asset garbage collection record ${index}`),`Asset garbage collection record ${index} id`),rawHash=optionalDataField(record,"hash",`Asset garbage collection record ${index}`),hash=rawHash==null||rawHash===""?null:assetIdentity(rawHash,`Asset garbage collection record ${index} hash`),rawSize=optionalDataField(record,"size",`Asset garbage collection record ${index}`),blob=rawSize==null?optionalDataField(record,"blob",`Asset garbage collection record ${index}`):null,size=boundedGcNumber(rawSize??opaqueBlobField(blob,"size",0),`Asset garbage collection record ${index} size`),rawSavedAt=optionalDataField(record,"savedAt",`Asset garbage collection record ${index}`);if(rawSavedAt!=null&&typeof rawSavedAt!=="string")throw new Error(`Asset garbage collection record ${index} savedAt must be a string or null`);if(typeof rawSavedAt==="string"&&rawSavedAt.length>1024)throw new Error(`Asset garbage collection record ${index} savedAt exceeds 1024 characters`);return{id,hash,size,savedAt:rawSavedAt??null};}
function storedJsonObject(value,label){let clean;try{clean=JSON.parse(canonicalOperationLogJson(value));}catch(error){throw new Error(`${label} must be inert JSON: ${error.message}`);}if(!clean||typeof clean!=="object"||Array.isArray(clean))throw new Error(`${label} must be an object`);return clean;}
function journalSequence(value,label,{positive=false}={}){if(typeof value!=="number"||!Number.isSafeInteger(value)||value<(positive?1:0))throw new Error(`${label} must be a ${positive?'positive':'non-negative'} safe integer`);return value;}
function journalIdentity(value,label){if(typeof value!=="string"||!value)throw new Error(`${label} must be a non-empty string`);if(value.length>MAX_JOURNAL_IDENTITY_CHARS)throw new Error(`${label} exceeds ${MAX_JOURNAL_IDENTITY_CHARS} characters`);return value;}
function optionalJournalText(value,label,{allowEmpty=false}={}){if(value==null)return null;if(typeof value!=="string"||(!allowEmpty&&!value))throw new Error(`${label} must be ${allowEmpty?'a string':'a non-empty string'} or null`);if(value.length>MAX_JOURNAL_IDENTITY_CHARS)throw new Error(`${label} exceeds ${MAX_JOURNAL_IDENTITY_CHARS} characters`);return value;}
function storedWorkspaceCheckpoint(value,{fallbackGraph=null}={}){if(value==null)return{graph:null,journalBaseGraph:fallbackGraph,journalSequence:0,journalChecksum:null,savedAt:null,lastCompactedAt:null,compactedFromSequence:0,compactedFromChecksum:null};if(typeof value!=="object"||Array.isArray(value))throw new Error("Stored workspace checkpoint must be an object");const rawGraph=optionalDataField(value,"graph","Stored workspace checkpoint"),graph=rawGraph==null?null:storedJsonObject(rawGraph,"Stored workspace graph"),rawBase=optionalDataField(value,"journalBaseGraph","Stored workspace checkpoint"),journalBaseGraph=rawBase==null?(graph??fallbackGraph):storedJsonObject(rawBase,"Stored journal base graph"),journalSequenceValue=optionalDataField(value,"journalSequence","Stored workspace checkpoint"),journalSequenceNumber=journalSequence(journalSequenceValue??0,"Stored journal sequence"),journalChecksum=optionalJournalText(optionalDataField(value,"journalChecksum","Stored workspace checkpoint")??null,"Stored journal checksum"),savedAt=optionalJournalText(optionalDataField(value,"savedAt","Stored workspace checkpoint")??null,"Stored workspace savedAt",{allowEmpty:false}),lastCompactedAt=optionalJournalText(optionalDataField(value,"lastCompactedAt","Stored workspace checkpoint")??null,"Stored workspace lastCompactedAt",{allowEmpty:false}),compactedFromSequenceValue=optionalDataField(value,"compactedFromSequence","Stored workspace checkpoint"),compactedFromSequence=journalSequence(compactedFromSequenceValue??0,"Stored compacted sequence"),compactedFromChecksum=optionalJournalText(optionalDataField(value,"compactedFromChecksum","Stored workspace checkpoint")??null,"Stored compacted checksum");if(journalSequenceNumber>0&&journalChecksum==null)throw new Error("Stored journal checksum is required for a non-empty journal");if(journalSequenceNumber===0&&journalChecksum!=null)throw new Error("Stored journal checksum must be null for an empty journal");return{graph,journalBaseGraph,journalSequence:journalSequenceNumber,journalChecksum,savedAt,lastCompactedAt,compactedFromSequence,compactedFromChecksum};}
function journalProjectId(graph,label){if(graph==null)return null;const value=optionalDataField(graph,"projectId",label);return value==null?null:journalIdentity(value,`${label} projectId`);}
const JOURNAL_WRITE_OPTION_KEYS=new Set(["assetWrites"]),JOURNAL_COMPACT_OPTION_KEYS=new Set(["expectedSequence","expectedChecksum"]),JOURNAL_LIST_OPTION_KEYS=new Set(["afterSequence","limit"]);
function journalWriteOptions(options={}){const clean=plainDataOptions(options,"Graph journal transaction options",JOURNAL_WRITE_OPTION_KEYS);return{assetWrites:clean.assetWrites??[]};}
function journalCompactOptions(options={}){const clean=plainDataOptions(options,"Operation journal compaction options",JOURNAL_COMPACT_OPTION_KEYS);return{expectedSequence:clean.expectedSequence===undefined?undefined:journalSequence(clean.expectedSequence,"Operation journal expectedSequence"),expectedChecksum:clean.expectedChecksum===undefined?undefined:optionalJournalText(clean.expectedChecksum,"Operation journal expectedChecksum")};}
function journalListOptions(options={}){const clean=plainDataOptions(options,"Stored operation list options",JOURNAL_LIST_OPTION_KEYS),afterSequence=journalSequence(clean.afterSequence??0,"Stored operation afterSequence"),limit=clean.limit??Infinity;if(limit!==Infinity&&(!Number.isSafeInteger(limit)||limit<0))throw new Error("Stored operation list limit must be a non-negative safe integer or Infinity");return{afterSequence,limit};}
export function localAssetUri(assetId) { return `media://asset/${assetIdentity(assetId)}`; }
export function getCachedStoredGraph(){return currentGraphCache;}
export async function openMediaDatabase() {
  if (!("indexedDB" in globalThis)) return null;
  if (databasePromise) return databasePromise;
  databasePromise = new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onupgradeneeded = (event) => {
      const database = request.result;
      if (!database.objectStoreNames.contains("workspace")) database.createObjectStore("workspace", { keyPath: "key" });
      let assets;
      if (!database.objectStoreNames.contains("assets")) assets = database.createObjectStore("assets", { keyPath: "id" }); else assets = request.transaction.objectStore("assets");
      if (!assets.indexNames.contains("hash")) assets.createIndex("hash", "hash", { unique: false });
      if (!assets.indexNames.contains("name")) assets.createIndex("name", "name", { unique: false });
      let derived;
      if (!database.objectStoreNames.contains("derived")) derived = database.createObjectStore("derived", { keyPath: "key" }); else derived = request.transaction.objectStore("derived");
      if (!database.objectStoreNames.contains("derivedMeta")) database.createObjectStore("derivedMeta", { keyPath: "key" });
      if ((event?.oldVersion ?? 0) < 4) derived.clear();
      let journal;
      if (!database.objectStoreNames.contains("journal")) journal = database.createObjectStore("journal", { keyPath: "sequence" }); else journal = request.transaction.objectStore("journal");
      if (!journal.indexNames.contains("transactionId")) journal.createIndex("transactionId", "transactionId", { unique: true });
    };
    request.onerror = () => { databasePromise = null; reject(request.error ?? new Error("IndexedDB open failed")); };
    request.onblocked = () => { /* versionchange listeners on existing tabs should release the DB */ };
    request.onsuccess = () => { const database = request.result; database.onversionchange = () => { try { database.close(); } finally { databasePromise = null; } }; resolve(database); };
  });
  return databasePromise;
}
export async function closeMediaDatabase(){if(!databasePromise)return;try{const database=await databasePromise;database?.close?.();}finally{databasePromise=null;}}
async function databaseTransaction(storeNames,mode,run){const database=await openMediaDatabase();if(!database)return null;const names=Array.isArray(storeNames)?storeNames:[storeNames],tx=database.transaction(names,mode),stores=Object.fromEntries(names.map((name)=>[name,tx.objectStore(name)])),result=await run(stores,tx);await transactionDone(tx);return result;}
async function transaction(storeName,mode,run){return databaseTransaction(storeName,mode,async(stores,tx)=>run(stores[storeName],tx));}
export async function saveStoredGraph(graph) { const safeGraph=storedJsonObject(graph,"Stored graph"),result=await databaseTransaction(["workspace","journal"],"readwrite",async({workspace,journal})=>{journal.clear();workspace.put({ key: WORKSPACE_KEY, graph:safeGraph, journalBaseGraph:safeGraph, journalSequence: 0, journalChecksum: null, savedAt: new Date().toISOString() });return true;});currentGraphCache=graph;return Boolean(result); }
export async function loadStoredGraphCheckpoint(){const raw=await transaction("workspace","readonly",async(store)=>requestResult(store.get(WORKSPACE_KEY)));if(!raw)return null;const record=storedWorkspaceCheckpoint(raw);currentGraphCache=record.graph??null;return record;}
export async function loadStoredGraph() { return currentGraphCache??(await loadStoredGraphCheckpoint())?.graph??null; }
function assertJournalEntry(entry){const clean=JSON.parse(canonicalOperationLogJson(entry));if(!clean||typeof clean!=="object"||Array.isArray(clean))throw new Error("Stored operation entry must be an object");if(clean.schema!==OPERATION_LOG_SCHEMA)throw new Error(`Stored operation entry schema must be ${OPERATION_LOG_SCHEMA}`);if(!Number.isSafeInteger(clean.sequence)||clean.sequence<1)throw new Error("Stored operation entry sequence must be a positive safe integer");if(typeof clean.checksum!=="string"||!clean.checksum)throw new Error("Stored operation entry checksum is required");if(typeof clean.transaction?.id!=="string"||!clean.transaction.id)throw new Error("Stored operation entry transaction id is required");const expected=operationLogChecksum({schema:OPERATION_LOG_SCHEMA,sequence:clean.sequence,transaction:clean.transaction,previousChecksum:clean.previousChecksum??null});if(clean.checksum!==expected)throw new Error(`Stored operation entry ${clean.sequence} checksum mismatch`);return clean;}
function opaqueBlobField(blob,key,fallback){const descriptor=Object.getOwnPropertyDescriptor(blob,key);if(descriptor?.enumerable&&Object.hasOwn(descriptor,"value"))return descriptor.value;const BlobCtor=globalThis.Blob,FileCtor=globalThis.File;if(typeof BlobCtor==="function"&&blob instanceof BlobCtor){if(key==="size"||key==="type")return blob[key];if(key==="name"&&typeof FileCtor==="function"&&blob instanceof FileCtor)return blob.name;}return fallback;}
function assetRecord(assetId,blob,metadata={},savedAt=new Date().toISOString()){if(typeof assetId!=="string"||!assetId)throw new Error("Asset write requires assetId");const BlobCtor=globalThis.Blob;if(typeof BlobCtor!=="function"||!(blob instanceof BlobCtor))throw new Error(`Asset write ${assetId} requires Blob data`);return{id:assetId,blob,hash:metadata.hash??null,name:metadata.name??opaqueBlobField(blob,"name",""),mediaKind:metadata.mediaKind??null,mimeType:metadata.mimeType??opaqueBlobField(blob,"type",""),size:metadata.size??opaqueBlobField(blob,"size",0),duration:metadata.duration??null,width:metadata.width??null,height:metadata.height??null,savedAt};}
function normalizeAssetWrites(assetWrites=[]){return normalizeStudioAssetWrites(assetWrites);}
async function saveGraphJournalTransaction(graph,entry,options={}){const safeGraph=storedJsonObject(graph,"Stored journal graph"),safeEntry=assertJournalEntry(entry),{assetWrites}=journalWriteOptions(options),writes=normalizeAssetWrites(assetWrites),storeNames=writes.length?["workspace","journal","assets"]:["workspace","journal"],result=await databaseTransaction(storeNames,"readwrite",async(stores)=>{const {workspace,journal}=stores,current=storedWorkspaceCheckpoint(await requestResult(workspace.get(WORKSPACE_KEY)),{fallbackGraph:safeGraph}),expected=current.journalSequence+1,previousChecksum=current.journalChecksum;if(safeEntry.sequence!==expected)throw new Error(`Operation journal sequence ${safeEntry.sequence} does not follow checkpoint ${expected-1}`);if((safeEntry.previousChecksum??null)!==previousChecksum)throw new Error(`Operation journal entry ${safeEntry.sequence} does not extend checkpoint checksum`);const savedAt=new Date().toISOString(),transactionId=safeEntry.transaction.id;if(writes.length){for(const write of writes)stores.assets.put(assetRecord(write.assetId,write.blob,write.metadata,savedAt));}journal.add({...safeEntry,transactionId,savedAt});workspace.put({key:WORKSPACE_KEY,graph:safeGraph,journalBaseGraph:current.journalBaseGraph??current.graph??safeGraph,journalSequence:safeEntry.sequence,journalChecksum:safeEntry.checksum,savedAt,lastCompactedAt:current.lastCompactedAt,compactedFromSequence:current.compactedFromSequence,compactedFromChecksum:current.compactedFromChecksum});return true;});currentGraphCache=graph;return Boolean(result);}
export async function saveStoredGraphWithOperation(graph,entry){return saveGraphJournalTransaction(graph,entry);}
export async function saveStoredGraphWithOperationAndAssets(graph,entry,assetWrites=[]){return saveGraphJournalTransaction(graph,entry,{assetWrites});}
export async function compactStoredOperationJournal(options={}){const {expectedSequence,expectedChecksum}=journalCompactOptions(options),result=await databaseTransaction(["workspace","journal"],"readwrite",async({workspace,journal})=>{const current=storedWorkspaceCheckpoint(await requestResult(workspace.get(WORKSPACE_KEY)));if(!current.graph)throw new Error("Operation journal compaction requires a stored graph checkpoint");const sequence=current.journalSequence,checksum=current.journalChecksum;if(expectedSequence!==undefined&&expectedSequence!==sequence)throw new Error(`Operation journal compaction expected sequence ${expectedSequence} but found ${sequence}`);if(expectedChecksum!==undefined&&expectedChecksum!==checksum)throw new Error("Operation journal compaction checksum does not match checkpoint head");if(sequence===0)return{compacted:false,graph:current.graph,previousSequence:0,previousChecksum:checksum,sequence:0,checksum:null,savedAt:current.savedAt};const savedAt=new Date().toISOString();journal.clear();workspace.put({key:WORKSPACE_KEY,graph:current.graph,journalBaseGraph:current.graph,journalSequence:0,journalChecksum:null,savedAt,lastCompactedAt:savedAt,compactedFromSequence:sequence,compactedFromChecksum:checksum});return{compacted:true,graph:current.graph,previousSequence:sequence,previousChecksum:checksum,sequence:0,checksum:null,savedAt};});return result??{compacted:false,graph:null,previousSequence:0,previousChecksum:null,sequence:0,checksum:null,savedAt:null};}
export async function listStoredOperationEntries(options={}){const {afterSequence,limit}=journalListOptions(options),records=boundedAssetList(await transaction("journal","readonly",async(store)=>requestResult(store.getAll()))??[],"Stored operation entries",MAX_STORED_OPERATION_ENTRIES),entries=records.map((record)=>assertJournalEntry(record)).filter((record)=>record.sequence>afterSequence).sort((a,b)=>a.sequence-b.sequence);return entries.slice(0,limit===Infinity?entries.length:limit);}
export async function findStoredOperationEntryByTransactionId(transactionId){if(transactionId==null||transactionId==="")return null;const safeId=journalIdentity(transactionId,"Stored operation transaction id"),record=await transaction("journal","readonly",async(store)=>store.indexNames.contains("transactionId")?requestResult(store.index("transactionId").get(safeId)):null);return record==null?null:assertJournalEntry(record);}
export async function loadStoredOperationRecovery(){const checkpoint=await loadStoredGraphCheckpoint();if(!checkpoint)return null;const entries=await listStoredOperationEntries(),projectId=journalProjectId(checkpoint.journalBaseGraph,"Stored journal base graph")??journalProjectId(checkpoint.graph,"Stored graph")??"workspace",log={schema:OPERATION_LOG_SCHEMA,projectId,baseRevision:0,metadata:{},entries};validateOperationLog(log);const head=entries.at(-1)??null,sequence=head?.sequence??0,checksum=head?.checksum??null;if(sequence!==checkpoint.journalSequence||checksum!==checkpoint.journalChecksum)throw new Error("Operation journal head does not match stored graph checkpoint");return{baseGraph:checkpoint.journalBaseGraph,graph:checkpoint.graph,sequence,checksum,entries,log};}
export async function saveAssetBlob(assetId, blob, metadata = {}) { const [write]=normalizeAssetWrites([{assetId,blob,metadata}]),result=await transaction("assets","readwrite",async(store)=>{store.put(assetRecord(write.assetId,write.blob,write.metadata));return true;});return Boolean(result); }
export async function loadAssetBlob(assetId) { const record=await loadStoredAsset(assetId);return storedAssetBlob(record); }
export async function loadStoredAsset(assetId) { const safeId=assetIdentity(assetId);return transaction("assets","readonly",async(store)=>requestResult(store.get(safeId))); }
export async function findStoredAssetByHash(hash) { if(hash==null||hash==="")return null;const safeHash=assetIdentity(hash,"Asset hash");return transaction("assets","readonly",async(store)=>store.indexNames.contains("hash")?requestResult(store.index("hash").get(safeHash)):null); }
export async function listStoredAssets() { const records=boundedAssetList(await transaction("assets","readonly",async(store)=>requestResult(store.getAll()))??[],"Stored assets");return records.map((record,index)=>storedAssetSummary(record,index)); }
export function planAssetGarbageCollection(graph,records,options={}){const {now,olderThanMs,maxDeleteBytes,retainAssetIds,retainAssetHashes}=assetGarbageCollectionOptions(options),safeRecords=boundedAssetList(records??[],"Asset garbage collection records",MAX_ASSET_GC_RECORDS),{referencedIds,referencedHashes}=assetGcGraphReferences(graph,retainAssetIds,retainAssetHashes),candidates=[],retained=[];let deleteBytes=0;for(let index=0;index<safeRecords.length;index++){const descriptor=Object.getOwnPropertyDescriptor(safeRecords,String(index)),record=assetGcRecord(descriptor.value,index),savedAtMs=record.savedAt==null?NaN:Date.parse(record.savedAt);let reason=null;if(referencedIds.has(record.id))reason="referenced-id";else if(record.hash&&referencedHashes.has(record.hash))reason="referenced-hash";else if(!Number.isFinite(savedAtMs))reason="unknown-age";else if(now-savedAtMs<olderThanMs)reason="recent";if(reason){retained.push({...record,reason});continue;}if(deleteBytes+record.size>maxDeleteBytes){retained.push({...record,reason:"budget"});continue;}candidates.push({...record,ageMs:Math.max(0,now-savedAtMs)});deleteBytes+=record.size;}return{candidates,retained,deleteBytes,referencedIds:[...referencedIds],referencedHashes:[...referencedHashes]};}
export async function garbageCollectStoredAssets(options={}){const safeOptions=assetGarbageCollectionOptions(options),result=await databaseTransaction(["workspace","assets"],"readwrite",async({workspace,assets})=>{const current=await requestResult(workspace.get(WORKSPACE_KEY));if(!current)return{deletedIds:[],deleteBytes:0,candidates:[],retained:[],referencedIds:[],referencedHashes:[]};const graph=optionalDataField(current,"graph","Stored workspace");if(!graph)return{deletedIds:[],deleteBytes:0,candidates:[],retained:[],referencedIds:[],referencedHashes:[]};const records=await requestResult(assets.getAll()),plan=planAssetGarbageCollection(graph,records,safeOptions);for(const candidate of plan.candidates)assets.delete(candidate.id);return{...plan,deletedIds:plan.candidates.map((candidate)=>candidate.id)};});return result??{deletedIds:[],deleteBytes:0,candidates:[],retained:[],referencedIds:[],referencedHashes:[]};}
export async function deleteAssetBlob(assetId) { const safeId=assetIdentity(assetId),result=await transaction("assets","readwrite",async(store)=>{store.delete(safeId);return true;});return Boolean(result); }
export async function listStoredAssetIds() { const records=await transaction("assets","readonly",async(store)=>requestResult(store.getAll()))??[];if(!Array.isArray(records))throw new Error("Stored assets must be an array");return records.map((record,index)=>storedAssetId(record,index)); }
export async function hasAssetBlob(assetId) { return (await loadAssetBlob(assetId)) !== null; }
function boundedDerivedListLimit(limit=MAX_DERIVED_LIST_RECORDS){if(!Number.isInteger(limit)||limit<1||limit>MAX_DERIVED_LIST_RECORDS)throw new Error(`Derived artifact list limit must be an integer between 1 and ${MAX_DERIVED_LIST_RECORDS}`);return limit;}
function derivedKey(key,label="Derived artifact key",{allowEmpty=false}={}){if(typeof key!=="string"||(!allowEmpty&&!key))throw new Error(`${label} must be ${allowEmpty?'a string':'a non-empty string'}`);if(key.length>MAX_DERIVED_KEY_CHARS)throw new Error(`${label} exceeds ${MAX_DERIVED_KEY_CHARS} characters`);return key;}
function derivedListPrefix(prefix=""){return derivedKey(prefix,"Derived artifact list prefix",{allowEmpty:true});}
function derivedListOptions(options={}){if(!options||typeof options!=="object"||Array.isArray(options))throw new Error("Derived artifact list options must be a plain data object");const prototype=Object.getPrototypeOf(options);if(prototype!==Object.prototype&&prototype!==null)throw new Error("Derived artifact list options must be a plain data object");const descriptors=Object.getOwnPropertyDescriptors(options),clean={};for(const key of Reflect.ownKeys(descriptors)){if(typeof key!=="string"||(key!=="prefix"&&key!=="limit"))throw new Error(`Unsupported derived artifact list option: ${String(key)}`);const descriptor=descriptors[key];if(!descriptor.enumerable||!Object.hasOwn(descriptor,"value"))throw new Error("Derived artifact list options must contain enumerable data fields only");clean[key]=descriptor.value;}return{prefix:derivedListPrefix(clean.prefix??""),limit:boundedDerivedListLimit(clean.limit??MAX_DERIVED_LIST_RECORDS)};}
async function boundedStoreRecords(store,prefix,limit){if(typeof store.openCursor!=="function"){const records=await requestResult(store.getAll())??[];return records.filter((record)=>typeof record?.key==="string"&&record.key.startsWith(prefix)).sort((a,b)=>a.key.localeCompare(b.key)).slice(0,limit);}return new Promise((resolve,reject)=>{const records=[],request=store.openCursor();request.onerror=()=>reject(request.error??new Error("IndexedDB cursor failed"));request.onsuccess=()=>{const cursor=request.result;if(!cursor){resolve(records);return;}const key=typeof cursor.key==="string"?cursor.key:String(cursor.key??"");if((!prefix||key.startsWith(prefix))&&records.length<limit)records.push(cursor.value);if(records.length>=limit){resolve(records);return;}cursor.continue();};});}
export async function saveDerivedArtifact(key, value, metadata = {}) { const safeKey=derivedKey(key),savedAt=new Date().toISOString(),recordMetadata=normalizeBoundedModelJsonObject(metadata,"Derived artifact metadata",{maxBytes:MAX_DERIVED_METADATA_BYTES});const result=await databaseTransaction(["derived","derivedMeta"],"readwrite",async({derived,derivedMeta})=>{derived.put({key:safeKey,value,metadata:recordMetadata,savedAt});derivedMeta.put({key:safeKey,metadata:recordMetadata,savedAt});return true;});return Boolean(result); }
export async function loadDerivedArtifact(key) { const safeKey=derivedKey(key);return transaction("derived","readonly",async(store)=>requestResult(store.get(safeKey))); }
export async function listDerivedArtifacts(options={}){const {prefix,limit}=derivedListOptions(options);return await transaction("derivedMeta","readonly",async(store)=>boundedStoreRecords(store,prefix,limit))??[];}
export async function deleteDerivedArtifact(key) { const safeKey=derivedKey(key);const result=await databaseTransaction(["derived","derivedMeta"],"readwrite",async({derived,derivedMeta})=>{derived.delete(safeKey);derivedMeta.delete(safeKey);return true;});return Boolean(result); }
export async function deleteDerivedArtifactsByPrefix(prefix){const text=derivedListPrefix(prefix);let removed=0;for(;;){const keys=(await listDerivedArtifacts({prefix:text,limit:MAX_DERIVED_LIST_RECORDS})).map((record)=>record.key);if(!keys.length)return removed;await databaseTransaction(["derived","derivedMeta"],"readwrite",async({derived,derivedMeta})=>{for(const key of keys){derived.delete(key);derivedMeta.delete(key);}return true;});removed+=keys.length;if(keys.length<MAX_DERIVED_LIST_RECORDS)return removed;}}
export async function clearDerivedArtifacts() { const result=await databaseTransaction(["derived","derivedMeta"],"readwrite",async({derived,derivedMeta})=>{derived.clear();derivedMeta.clear();return true;});return Boolean(result); }
export async function estimateStorageQuota(){if(typeof globalThis.navigator?.storage?.estimate!=="function")return null;const result=await globalThis.navigator.storage.estimate(),usage=storageEstimateNumber(result,"usage"),quota=storageEstimateNumber(result,"quota");return{usage,quota,available:Math.max(0,quota-usage),ratio:quota>0?usage/quota:0};}
