import { decoderConfigForTrack } from '../../packages/core/src/media-kernel.js';
import { createMuxPlanFromEncoded } from '../../packages/core/src/encoded-export.js';
import { muxWebm } from '../../packages/core/src/webm-mux.js';
import { checkDecoderSupport, checkEncoderSupport, createWebCodecsChunk } from './webcodecs.js';

function positive(value,fallback){const n=Number(value);return Number.isFinite(n)&&n>0?n:fallback;}
function abortError(){const error=new Error('Proxy transcode aborted');error.name='AbortError';return error;}
function closeMedia(value){try{value?.close?.();}catch{}}
function proxyCodec(codec){const value=String(codec??'vp9').toLowerCase();if(value==='vp9'||value.startsWith('vp09'))return'vp09.00.10.08';if(value==='av1'||value.startsWith('av01'))return'av01.0.05M.08';throw new Error(`Unsupported browser proxy codec: ${codec}`);}
function defaultCanvasFactory(width,height){if(typeof OffscreenCanvas==='function')return new OffscreenCanvas(width,height);if(globalThis.document?.createElement){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;return canvas;}throw new Error('Proxy scaling requires a canvas implementation');}
function defaultScaleFrame(frame,{width,height,canvasFactory=defaultCanvasFactory,VideoFrameCtor=globalThis.VideoFrame}={}){if(typeof VideoFrameCtor!=='function')throw new Error('Proxy scaling requires VideoFrame');const canvas=canvasFactory(width,height),context=canvas.getContext?.('2d');if(!context)throw new Error('Proxy scaling requires Canvas2D');context.drawImage(frame,0,0,width,height);return new VideoFrameCtor(canvas,{timestamp:Number(frame.timestamp??0),duration:Number(frame.duration??0)||undefined});}
function encodedRecord(chunk,metadata,sequence,trackId){const bytes=new Uint8Array(Number(chunk.byteLength)||0);chunk.copyTo(bytes);const payload=bytes.buffer;return{trackId,type:chunk.type==='key'?'key':'delta',keyframe:chunk.type==='key',timestamp:Number(chunk.timestamp)||0,dts:Number(chunk.timestamp)||0,duration:Number(chunk.duration)||0,sequence,byteLength:bytes.byteLength,payload,bytes:payload,decoderConfig:metadata?.decoderConfig??null};}
async function pressure(decoder,encoder,{decodeQueue=6,encodeQueue=6}={}){if(Number(decoder.decodeQueueSize??0)>=decodeQueue)await decoder.flush?.();if(Number(encoder.encodeQueueSize??0)>=encodeQueue)await encoder.flush?.();}
export async function transcodeVideoStreaming({track,chunks,source,spec={},signal,VideoDecoderCtor=globalThis.VideoDecoder,VideoEncoderCtor=globalThis.VideoEncoder,VideoChunk=globalThis.EncodedVideoChunk,frameScaler=defaultScaleFrame,probeSupport=true,onProgress=()=>{}}={}){
  if(!track||track.type!=='video')throw new Error('Streaming proxy requires a video track');if(!Array.isArray(chunks)||!chunks.length)throw new Error('Streaming proxy requires encoded video chunks');if(typeof VideoDecoderCtor!=='function'||typeof VideoEncoderCtor!=='function')throw new Error('Streaming proxy requires WebCodecs video decode and encode');
  const width=Math.max(2,Math.round(positive(spec.width,track.width??track.codedWidth??1280)/2)*2),height=Math.max(2,Math.round(positive(spec.height,track.height??track.codedHeight??720)/2)*2),framerate=positive(spec.framerate??spec.frameRate??track.frameRate,30),codec=proxyCodec(spec.codec);const videoConfig={codec,width,height,bitrate:Math.max(250_000,Math.round(Number(spec.bitrate)||width*height*framerate*.08)),framerate};
  if(probeSupport){const [decodeSupport,encodeSupport]=await Promise.all([checkDecoderSupport(track,{VideoDecoderCtor}),checkEncoderSupport('video',videoConfig,{VideoEncoderCtor})]);if(!decodeSupport.supported)throw new Error(`Unsupported proxy decoder config: ${decodeSupport.reason}`);if(!encodeSupport.supported)throw new Error(`Unsupported proxy encoder config: ${encodeSupport.reason}`);}
  const records=[];let decoderFailure=null,encoderFailure=null,decoded=0,submitted=0,liveFrames=0,peakLiveFrames=0;const interval=Math.max(1,Math.round(framerate*positive(spec.keyframeIntervalSeconds,2)));
  const encoder=new VideoEncoderCtor({output:(chunk,metadata)=>records.push(encodedRecord(chunk,metadata,records.length,'proxy-video')),error:(error)=>{encoderFailure=error;}});encoder.configure(videoConfig);
  const decoder=new VideoDecoderCtor({output:(frame)=>{liveFrames++;peakLiveFrames=Math.max(peakLiveFrames,liveFrames);let scaled=null;try{scaled=frameScaler(frame,{width,height,VideoFrameCtor:globalThis.VideoFrame});encoder.encode(scaled,{keyFrame:submitted%interval===0});submitted++;decoded++;onProgress(decoded/Math.max(1,chunks.length),{decoded,submitted});}catch(error){decoderFailure=decoderFailure??error;}finally{if(scaled&&scaled!==frame)closeMedia(scaled);closeMedia(frame);liveFrames--;}} ,error:(error)=>{decoderFailure=error;}});decoder.configure(decoderConfigForTrack(track));
  try{for(const descriptor of chunks){if(signal?.aborted)throw abortError();await pressure(decoder,encoder,{decodeQueue:Math.max(1,Number(spec.decodeQueue)||6),encodeQueue:Math.max(1,Number(spec.encodeQueue)||6)});if(decoderFailure)throw decoderFailure;if(encoderFailure)throw encoderFailure;decoder.decode(createWebCodecsChunk(track,descriptor,source,{VideoChunk}));}await decoder.flush?.();if(decoderFailure)throw decoderFailure;await encoder.flush?.();if(encoderFailure)throw encoderFailure;if(!records.length)throw new Error('Proxy encoder produced no chunks');const decoderConfig=records.find((record)=>record.decoderConfig)?.decoderConfig??null;return{id:'proxy-video',type:'video',codec,config:videoConfig,decoderConfig,chunks:records,width,height,metrics:{decodedFrames:decoded,encodedFrames:records.length,peakLiveDecodedFrames:peakLiveFrames}};}finally{try{decoder.close?.();}catch{}try{encoder.close?.();}catch{}}
}
export async function transcodeAudioStreaming({track,chunks,source,spec={},signal,AudioDecoderCtor=globalThis.AudioDecoder,AudioEncoderCtor=globalThis.AudioEncoder,AudioChunk=globalThis.EncodedAudioChunk,probeSupport=true}={}){
  if(!track||track.type!=='audio'||!chunks?.length)return null;if(typeof AudioDecoderCtor!=='function'||typeof AudioEncoderCtor!=='function')throw new Error('Streaming proxy audio requires WebCodecs audio decode and encode');const sampleRate=positive(track.sampleRate??track.config?.sampleRate,48000),channels=Math.max(1,Math.round(positive(track.channels??track.config?.numberOfChannels,2))),config={codec:'opus',sampleRate,numberOfChannels:channels,bitrate:Math.max(32_000,Math.round(Number(spec.audioBitrate)||128_000))};if(probeSupport){const [decodeSupport,encodeSupport]=await Promise.all([checkDecoderSupport(track,{AudioDecoderCtor}),checkEncoderSupport('audio',config,{AudioEncoderCtor})]);if(!decodeSupport.supported)throw new Error(`Unsupported proxy audio decoder: ${decodeSupport.reason}`);if(!encodeSupport.supported)throw new Error(`Unsupported proxy audio encoder: ${encodeSupport.reason}`);}const records=[];let decoderFailure=null,encoderFailure=null,decoded=0,live=0,peak=0;const encoder=new AudioEncoderCtor({output:(chunk,metadata)=>records.push(encodedRecord(chunk,metadata,records.length,'proxy-audio')),error:(error)=>{encoderFailure=error;}});encoder.configure(config);const decoder=new AudioDecoderCtor({output:(frame)=>{live++;peak=Math.max(peak,live);try{encoder.encode(frame);decoded++;}catch(error){decoderFailure=decoderFailure??error;}finally{closeMedia(frame);live--;}} ,error:(error)=>{decoderFailure=error;}});decoder.configure(decoderConfigForTrack(track));try{for(const descriptor of chunks){if(signal?.aborted)throw abortError();await pressure(decoder,encoder,{decodeQueue:Math.max(1,Number(spec.audioDecodeQueue)||12),encodeQueue:Math.max(1,Number(spec.audioEncodeQueue)||12)});if(decoderFailure)throw decoderFailure;if(encoderFailure)throw encoderFailure;decoder.decode(createWebCodecsChunk(track,descriptor,source,{AudioChunk}));}await decoder.flush?.();if(decoderFailure)throw decoderFailure;await encoder.flush?.();if(encoderFailure)throw encoderFailure;return{id:'proxy-audio',type:'audio',codec:'opus',config,decoderConfig:records.find((record)=>record.decoderConfig)?.decoderConfig??null,chunks:records,sampleRate,channels,metrics:{decodedFrames:decoded,encodedFrames:records.length,peakLiveDecodedFrames:peak}};}finally{try{decoder.close?.();}catch{}try{encoder.close?.();}catch{}}
}
export async function generateStreamingVideoProxyArtifact({track,chunks,source,spec={},audioTrack=null,audioChunks=[],audioSource=source,signal,muxer=muxWebm,...codecOptions}={}){const video=await transcodeVideoStreaming({track,chunks,source,spec,signal,...codecOptions});const audio=audioTrack&&audioChunks?.length?await transcodeAudioStreaming({track:audioTrack,chunks:audioChunks,source:audioSource,spec,signal,...codecOptions}):null;const streams=[video,...(audio?[audio]:[])],plan=createMuxPlanFromEncoded({container:'webm',streams,metadata:{derived:true,streamingTranscode:true,sourceTrackId:track.id,audioSourceTrackId:audio?.id?audioTrack.id:null}}),bytes=muxer(plan,{maxClusterMs:Math.max(1000,Math.round(positive(spec.keyframeIntervalSeconds,2)*1000))});return{bytes:bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),byteLength:bytes.byteLength,mimeType:'video/webm',width:video.width,height:video.height,codec:video.codec,frameCount:video.chunks.length,audioIncluded:Boolean(audio),videoOnly:!audio,metrics:{video:video.metrics,audio:audio?.metrics??null}};}
