import {createTrustRegistry,TrustRegistrySession,validateTrustRegistry} from '../../packages/core/src/trust-registry.js';

const DB_NAME='media-studio-trust';
const DB_VERSION=1;
const STORE='registry';
const REGISTRY_KEY='current';
let databasePromise=null;
function requestResult(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error??new Error('Trust IndexedDB request failed'));});}
function transactionDone(transaction){return new Promise((resolve,reject)=>{transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error??new Error('Trust IndexedDB transaction failed'));transaction.onabort=()=>reject(transaction.error??new Error('Trust IndexedDB transaction aborted'));});}
export async function openTrustDatabase(){if(!('indexedDB' in globalThis))return null;if(databasePromise)return databasePromise;databasePromise=new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const database=request.result;if(!database.objectStoreNames.contains(STORE))database.createObjectStore(STORE,{keyPath:'key'});};request.onerror=()=>{databasePromise=null;reject(request.error??new Error('Trust IndexedDB open failed'));};request.onblocked=()=>{};request.onsuccess=()=>{const database=request.result;database.onversionchange=()=>{try{database.close();}finally{databasePromise=null;}};resolve(database);};});return databasePromise;}
export async function closeTrustDatabase(){if(!databasePromise)return;try{const database=await databasePromise;database?.close?.();}finally{databasePromise=null;}}
async function withRegistryTransaction(mode,run){const database=await openTrustDatabase();if(!database)return null;const tx=database.transaction(STORE,mode),store=tx.objectStore(STORE),result=await run(store,tx);await transactionDone(tx);return result;}
export async function loadStoredTrustRegistry(){const record=await withRegistryTransaction('readonly',async(store)=>requestResult(store.get(REGISTRY_KEY)));if(!record?.registry)return createTrustRegistry();validateTrustRegistry(record.registry);return structuredClone(record.registry);}
export async function saveStoredTrustRegistry(registry,{expectedRevision=registry?.revision-1}={}){validateTrustRegistry(registry);if(!Number.isSafeInteger(expectedRevision)||expectedRevision<0)throw new Error('Trust registry expectedRevision must be a non-negative safe integer');if(registry.revision!==expectedRevision+1)throw new Error(`Trust registry revision ${registry.revision} must advance exactly from ${expectedRevision}`);const result=await withRegistryTransaction('readwrite',async(store)=>{const currentRecord=await requestResult(store.get(REGISTRY_KEY)),current=currentRecord?.registry??createTrustRegistry();validateTrustRegistry(current);if(current.revision!==expectedRevision)throw new Error(`Trust registry compare-and-swap expected revision ${expectedRevision} but found ${current.revision}`);store.put({key:REGISTRY_KEY,registry:structuredClone(registry),savedAt:new Date().toISOString()});return true;});if(result===null)throw new Error('Trust registry durable storage is unavailable');return true;}
export async function createStoredTrustRegistrySession({registry=null,verifySignature,...options}={}){const initial=registry??await loadStoredTrustRegistry();return new TrustRegistrySession({registry:initial,verifySignature,...options,persist:async(next)=>saveStoredTrustRegistry(next,{expectedRevision:next.revision-1})});}
