import { decoderConfigForTrack } from '../../packages/core/src/media-kernel.js';

function bytesOf(source){if(source instanceof Uint8Array)return source;if(source instanceof ArrayBuffer)return new Uint8Array(source);if(ArrayBuffer.isView(source))return new Uint8Array(source.buffer,source.byteOffset,source.byteLength);throw new Error('Encoded source must be binary');}
function abortError(){const error=new Error('Decode aborted');error.name='AbortError';return error;}
export function webCodecsCapabilities(scope=globalThis){return{videoDecoder:typeof scope.VideoDecoder==='function',audioDecoder:typeof scope.AudioDecoder==='function',encodedVideoChunk:typeof scope.EncodedVideoChunk==='function',encodedAudioChunk:typeof scope.EncodedAudioChunk==='function',videoEncoder:typeof scope.VideoEncoder==='function',audioEncoder:typeof scope.AudioEncoder==='function'};}
export function chunkBytes(source,descriptor,{copy=false}={}){const bytes=bytesOf(source);if(descriptor?.offset==null||descriptor?.byteLength==null)throw new Error('Encoded chunk requires offset and byteLength');const start=Number(descriptor.offset),end=start+Number(descriptor.byteLength);if(start<0||end>bytes.length)throw new Error('Encoded chunk range exceeds source');const slice=bytes.subarray(start,end);return copy?slice.slice():slice;}
export function encodedChunkInit(descriptor,source){return{type:descriptor.type==='key'?'key':'delta',timestamp:Number(descriptor.presentationTimestamp??descriptor.timestamp),duration:Number(descriptor.duration??0)||undefined,data:chunkBytes(source,descriptor)};}
export function createWebCodecsChunk(track,descriptor,source,{VideoChunk=globalThis.EncodedVideoChunk,AudioChunk=globalThis.EncodedAudioChunk}={}){const init=encodedChunkInit(descriptor,source);if(track.type==='video'){if(typeof VideoChunk!=='function')throw new Error('EncodedVideoChunk is unavailable');return new VideoChunk(init);}if(track.type==='audio'){if(typeof AudioChunk!=='function')throw new Error('EncodedAudioChunk is unavailable');return new AudioChunk(init);}throw new Error(`Unsupported WebCodecs track type: ${track.type}`);}
export async function checkDecoderSupport(track,{VideoDecoderCtor=globalThis.VideoDecoder,AudioDecoderCtor=globalThis.AudioDecoder}={}){const config=decoderConfigForTrack(track);const ctor=track.type==='video'?VideoDecoderCtor:track.type==='audio'?AudioDecoderCtor:null;if(!ctor) return{supported:false,config,reason:'decoder-unavailable'};if(typeof ctor.isConfigSupported!=='function')return{supported:true,config,reason:'support-probe-unavailable'};try{const result=await ctor.isConfigSupported(config);return{supported:Boolean(result?.supported),config:result?.config??config,reason:result?.supported?'supported':'unsupported-config'};}catch(error){return{supported:false,config,reason:error.message};}}
async function waitForQueue(decoder,maxQueue){if(Number(decoder.decodeQueueSize??0)<maxQueue)return;if(typeof decoder.flush==='function')await decoder.flush();}
export async function decodeChunkDescriptors(track,chunks,source,{onOutput=()=>{},onError,signal,maxQueue=8,VideoDecoderCtor=globalThis.VideoDecoder,AudioDecoderCtor=globalThis.AudioDecoder,VideoChunk=globalThis.EncodedVideoChunk,AudioChunk=globalThis.EncodedAudioChunk,probeSupport=true}={}){
  if(!Array.isArray(chunks))throw new Error('chunks must be an array');if(signal?.aborted)throw abortError();const ctor=track.type==='video'?VideoDecoderCtor:track.type==='audio'?AudioDecoderCtor:null;if(typeof ctor!=='function')throw new Error(`${track.type} decoder is unavailable`);if(probeSupport){const support=await checkDecoderSupport(track,{VideoDecoderCtor,AudioDecoderCtor});if(!support.supported)throw new Error(`Unsupported ${track.type} decoder config: ${support.reason}`);}
  let decoderError=null;const decoder=new ctor({output:onOutput,error:(error)=>{decoderError=error;onError?.(error);}});const config=decoderConfigForTrack(track);decoder.configure(config);let submitted=0;try{for(const descriptor of chunks){if(signal?.aborted)throw abortError();await waitForQueue(decoder,Math.max(1,Number(maxQueue)||1));if(decoderError)throw decoderError;const chunk=createWebCodecsChunk(track,descriptor,source,{VideoChunk,AudioChunk});decoder.decode(chunk);submitted++;}if(typeof decoder.flush==='function')await decoder.flush();if(decoderError)throw decoderError;return{submitted,config};}finally{try{decoder.close?.();}catch{}}}

export async function checkEncoderSupport(type,config,{VideoEncoderCtor=globalThis.VideoEncoder,AudioEncoderCtor=globalThis.AudioEncoder}={}){const ctor=type==='video'?VideoEncoderCtor:type==='audio'?AudioEncoderCtor:null;if(!ctor)return{supported:false,config,reason:'encoder-unavailable'};if(typeof ctor.isConfigSupported!=='function')return{supported:true,config,reason:'support-probe-unavailable'};try{const result=await ctor.isConfigSupported(config);return{supported:Boolean(result?.supported),config:result?.config??config,reason:result?.supported?'supported':'unsupported-config'};}catch(error){return{supported:false,config,reason:error.message};}}
function encodedRecord(chunk,metadata,sequence,trackId){const bytes=new Uint8Array(Number(chunk.byteLength)||0);chunk.copyTo(bytes);const payload=bytes.buffer;const type=chunk.type==='key'?'key':'delta',timestamp=Number(chunk.timestamp)||0;return{trackId:String(trackId),type,keyframe:type==='key',timestamp,dts:timestamp,duration:Number(chunk.duration)||0,sequence,byteLength:bytes.byteLength,bytes:payload,payload,decoderConfig:metadata?.decoderConfig??null};}
async function waitForEncodeQueue(encoder,maxQueue){if(Number(encoder.encodeQueueSize??0)<maxQueue)return;if(typeof encoder.flush==='function')await encoder.flush();}
export async function encodeVideoFrames(frames,config,{trackId='video:encoded',signal,maxQueue=8,keyFrameInterval=60,onChunk=()=>{},VideoEncoderCtor=globalThis.VideoEncoder,probeSupport=true}={}){if(typeof VideoEncoderCtor!=='function')throw new Error('video encoder is unavailable');if(probeSupport){const support=await checkEncoderSupport('video',config,{VideoEncoderCtor});if(!support.supported)throw new Error(`Unsupported video encoder config: ${support.reason}`);}const records=[];let failure=null;const encoder=new VideoEncoderCtor({output:(chunk,metadata)=>{const record=encodedRecord(chunk,metadata,records.length,trackId);records.push(record);onChunk(record);},error:(error)=>{failure=error;}});encoder.configure(config);let submitted=0;try{for(const frame of frames){if(signal?.aborted)throw abortError();await waitForEncodeQueue(encoder,Math.max(1,Number(maxQueue)||1));if(failure)throw failure;encoder.encode(frame,{keyFrame:submitted%Math.max(1,Math.round(Number(keyFrameInterval)||1))===0});submitted++;}await encoder.flush?.();if(failure)throw failure;return{submitted,chunks:records,config};}finally{try{encoder.close?.();}catch{}}}
export async function encodeAudioData(frames,config,{trackId='audio:encoded',signal,maxQueue=16,onChunk=()=>{},AudioEncoderCtor=globalThis.AudioEncoder,probeSupport=true}={}){if(typeof AudioEncoderCtor!=='function')throw new Error('audio encoder is unavailable');if(probeSupport){const support=await checkEncoderSupport('audio',config,{AudioEncoderCtor});if(!support.supported)throw new Error(`Unsupported audio encoder config: ${support.reason}`);}const records=[];let failure=null;const encoder=new AudioEncoderCtor({output:(chunk,metadata)=>{const record=encodedRecord(chunk,metadata,records.length,trackId);records.push(record);onChunk(record);},error:(error)=>{failure=error;}});encoder.configure(config);let submitted=0;try{for(const frame of frames){if(signal?.aborted)throw abortError();await waitForEncodeQueue(encoder,Math.max(1,Number(maxQueue)||1));if(failure)throw failure;encoder.encode(frame);submitted++;}await encoder.flush?.();if(failure)throw failure;return{submitted,chunks:records,config};}finally{try{encoder.close?.();}catch{}}}
